### ISSUE TITLE
Copy Address to Clipboard

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#1000]
https://www.npmjs.com/package/react-copy-to-clipboard

- [ ] Document / copy icon next to account address that copies it to the clipboard

**Comment by KanteLabs** [comment]
I can work on this.

**Comment by dternyak** [comment]
@KanteLabs Please do! We welcome open-source contributions. Happy to merge a PR if you open one :)

**Comment by KanteLabs** [comment]
https://github.com/KanteLabs/MyCrypto/tree/copy-to-clipboard

Submitting a pull request for the feature
