### ISSUE TITLE
Display 'ETH' instead of 'ether' 

### ISSUE THREAD

**Issue by james-prado** [MyCryptoHQ/MyCrypto#1016]
We should remain consistent and use 'ETH' instead of 'ether'. I think the error occurs because the amount field dropdown has the 'ETH' option set to a value of 'ether', which is causing this inconsistency in the tx confirmation modal.

<img width="549" alt="screen shot 2018-02-07 at 11 35 28 am" src="https://user-images.githubusercontent.com/13836920/35928520-5e4a1efc-0bfb-11e8-9b9d-96cfb970c4ce.png">

**Comment by wbobeirne** [comment]
In most places in the code, we do
```
unit === 'ether' ? network.unit : unit
```
so we should either move this into a common use formatter, make it a part of UnitDisplay, or make it a less user-displayable string like `default` or something like that. The reason we do this is because it's still `'ether'` on non-ETH networks, like ETC or UBIQ.
