### ISSUE TITLE
Integrate GasExpress

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#1046]
https://dev.blockscale.net/api/gasexpress.json

- [ ] Show marks on slider based on speed data retrieved from `gasexpress`. Default to `fast`
- [ ] Gracefully fail on gasexpress service being down / unavailable, and use hardcoded default gas price

**Comment by wbobeirne** [comment]
_Hell yeah_. In the future, time estimates would be nice, but this is excellent.
