### ISSUE TITLE
Integrate Parity Signer

### ISSUE THREAD

**Issue by maciejhirsz** [MyCryptoHQ/MyCrypto#1056]
### Disclaimer

This is kind of an extension of: https://github.com/kvhnuke/etherwallet/issues/551

Also I'm actually happy to sit down and implement it myself, but I'd like to hear if it's something you'd be willing to include in the first place.

### Description of the Feature

Parity has developed a Parity Signer mobile app a while ago, it's available both on [iOS](https://itunes.apple.com/de/app/parity-signer/id1218174838?l=en&mt=8) and [Android](https://play.google.com/store/apps/details?id=com.nativesigner). The app can be a low entry barrier alternative to hardware wallets (especially if you have an old phone that you can turn completely offline and run the app on it).

The app in combination with the Parity client UI allows you to store the private key on your phone, recover wallet from Parity phrases (which solves the MEW issue linked above for us), and sign transactions done in the browser via QR codes - the raw transaction is presented as a QR code, scanned by the app, signed in the app, and then a QR code with the signed transaction can be scanned by the browser via webcam.

I reckon it should be reasonably easy to port the QR scanning code to MyCrypto, which would offer the users a more secure way of handling their private keys than using keystore files / phrases in the browser directly. It can also help with phishing since the app displays the transaction details from the QR code to the user (how much ether and to whom is going to be transferred, regardless of what the web UI displays).

Yay/nay?

**Comment by dternyak** [comment]
Thanks for opening this issue @maciejhirsz!

A big `yay` from me.

We've brainstormed a similar proposal that you can find at https://github.com/MyCryptoHQ/MyCrypto/issues/921, however these are distinct enough that they will need to be implemented independently.

I would certainly be in favor of merging a PR if you do submit one that includes your described functionality.

Let me know if there's anything further I can help with, and feel free to ask any questions you might have while getting acclimated to the codebase here.

**Comment by 5chdn** [comment]
Btw, the signer apps are open-source if you have use for them https://github.com/paritytech/parity-signer

**Comment by maciejhirsz** [comment]
@dternyak sure, slack me up - maciej@parity.io. I'll start working on this as soon as I'm done with some other more pressing issues. My general idea is to make a React component library for that, to make the integration easier (plus there might be other projects that could benefit from it).

**Comment by dternyak** [comment]
@maciejhirsz Done! I like the idea of making a general purpose react component library to more fully modularize the implementation.
