### ISSUE TITLE
Mnemonic Phrase Unlock Feature: Show more addresses per page

### ISSUE THREAD

**Issue by tayvano** [MyCryptoHQ/MyCrypto#1071]
From Dino via Skype

> "Suggestion:  Show more than 5 addresses ‘per page’ on the ledger nano — everyone uses tons of addresses and its annoying to scroll back and forth pages….  would be big improvement"

I personally have run into this as well, but doing this may have wider implications on new users, etc. 

(could also be good for bounties)

**Comment by dternyak** [comment]
This is a simple config tweak: https://github.com/MyCryptoHQ/MyCrypto/blob/01fc5f1a89251bd2799f0928901b7a998d8da8c4/common/components/WalletDecrypt/components/DeterministicWalletsModal.tsx#L21

I'll bump it up to 10 and see how user feedback is on the beta.

**Comment by dternyak** [comment]
![2018-02-12 15 45 31](https://user-images.githubusercontent.com/7861465/36121472-e5d728e2-100b-11e8-9648-dd8375956742.gif)

On my 2560 x 1600 machine, you now have to scroll to see the `more` button with the higher number of items per page.

I'm not sure if it's worth the tradeoff of additional addresses per page, but maybe @wbobeirne or @james-prado can cook up some CSS that would address both issues.

**Comment by tayvano** [comment]
perhaps have just the table itself (1-10) overflow / scroll so you can always see the labels and the top and more/prev address? Just a thought

**Comment by wbobeirne** [comment]
Unfortunately making a `tbody` scroll while keeping the `thead` is a bit of a nightmare, but we could work that out with flexbox. However, I think the UX of doing a ton of scrolling isn't _much_ better than clicking next a bunch of times. I'd like to learn more about how people keep track of their dozens of addresses, that might lead to a better solution. A few I can think of:

1. A search bar for the address
2. Select address by number alone
3. Recent addresses / favorite addresses
4. Optionally input the desired address or index along with mnemonic / password, instantly unlock that address, bypassing the modal
5. (In the future) instantly get access by address, only input mnemonic when needed

Would be great to get some more feedback about how to best solve this before we just bump the number.

**Comment by aghamir** [comment]
The search bar for the address is the best solution to find desire address in Mnemonic addresses. It's too time consuming to search address by paging.
