### ISSUE TITLE
General improvements of the onboarding modal

### ISSUE THREAD

**Issue by MrLuit** [MyCryptoHQ/MyCrypto#1081]
### Description of the Feature

While the current onboarding modal is really, really good, it might use some improvements:

- [ ] A fade in / fade out for all the individual pages. This way people will take some time clicking through all of them which might encourage some people to actually read the pages. Any other animation can also be used if it fits better.
- [ ] Make the images on the pages load in the background before they are shown. The current behavior can be a little bit annoying on slower internet connections (can be reproduced by using Chrome Dev Tools and setting the network speed to Slow 3G)

![](https://i.imgur.com/tRU7iNs.gif)

### Example(s) of Feature

I really like this animation but really anything can be used: https://codepen.io/jebbles/pen/MKoYya

**Comment by dternyak** [comment]
The mobile styling could use some improvements as well

![mobile](https://user-images.githubusercontent.com/7861465/36233248-9ef85518-11aa-11e8-9090-9a1528bf8e36.jpg)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837127)
