### ISSUE TITLE
Transaction History Component

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#1083]
### Description of the Feature

As part of the on-going work in https://github.com/MyCryptoHQ/MyCrypto/issues/774, @wbobeirne has mocked up a TX history component that will show progress as confirmations are broadcast during `sweeper` sweeps.

This TX history component should be generic enough to also apply to our Send view, so that we can display the transaction history for the unlocked account.

### Example(s) of Feature

Currently, we link out to [etherscan](https://etherscan.io/address/0xcfceab0b7380befc8952a674df2fcff0398bd2a7) so that users can view their transaction history.

**Comment by wbobeirne** [comment]
So the mockups in #774 don't actually show what a history would look like, so design wise we'd have to start fresh.

Full history for an address is actually a tricky subject. Nodes don't offer a way of requesting all of the transactions for an address, only the information of individual transactions. This means that given a user's address, we don't have an easy, node-agnostic way of collecting all of this information. This leaves us with a few choices:

1. Leverage etherscan or some other explorer for getting this information. All we would need to grab is all the tx hashes for a given address, and we could let the node do the rest of the work.
2. Set up our own infrastructure for tracking all of these transactions. I think this could be pretty lightweight as a redis set, but it would definitely be a non-trivial amount of dev work.
3. Only track transactions sent through MEW, and store tx hashes in local storage. This is something I think I want to do as a part of #775 as-is, have a pre-filled dropdown of recent transactions for you to check, and we could extend that. However this may cause major user confusion, not seeing the same transactions that they see on Etherscan, if they've done some in a different browser / different client. Not very in favor of this one.

Let me know what you think. I think for our current use-cases, we can do the short-term same session transaction tracking for sweeper and check tx. But if we want a proper full history, we'll have to figure this out.

**Comment by dternyak** [comment]
Session specific transaction history would be 👍 with me as an MVP.

I'm not sure that Etherscan could / would want to handle the additional load for retrieving the tx hashes for a given address, so we may have to hold off until geth / parity have that functionality natively.

I'd definitely like to stay away from (3), as I agree with you that users are likely to experience confusion.
