### ISSUE TITLE
Placeholder on ENS page still references MEW

### ISSUE THREAD

**Issue by wschwab** [MyCryptoHQ/MyCrypto#1095]
### Description of the Issue

Hey all, I'm sure you've all got tons to do, but I figured you'd want someone to point this out. The placeholder on the ENS page (accessed from the top bar) still references MEW (it's 'mewtopia').

EDIT: This is also true for the 'Contracts' and 'DomainSale' pages

### Steps to Reproduce

Go to https://mycrypto.com/#ens. Observe.

PS - I dug around in the repo looking for the page myself, but I couldn't find it. Making a PR on this would've taken me less time than opening the issue, I know. But once I couldn't find it, I figured you'd want to catch it anyway.  Cheers, and thanks for the wallet.

**Comment by MrLuit** [comment]
Hey there! This is the repository for MyCrypto v4 (so not the live version). I'll create a PR for you on the correct repository (which is https://github.com/MyCryptoHQ/MyCrypto.com)

**Comment by wschwab** [comment]
Thanks! (I had thought the beta would be the right place.)
