### ISSUE TITLE
Suggestion: use Crowdin for translations

### ISSUE THREAD

**Issue by rajivshah3** [MyCryptoHQ/MyCrypto#1119]
I noticed that the translations require translators to edit the raw JSON, which might not be easy for some users. I use Crowdin in one of my projects and it couldn't be easier. Instead of translators trying to figure out GitHub, they can simply enter translations on a website. With GitHub integrations, it allows you to simply update the `en.json` in your repository, and it will automatically update the strings on Crowdin. When users make translations on Crowdin, the translations are automatically pushed to a branch of your repository and a pull request is open so you can merge them in. You can check it out at http://crowdin.com

**Comment by wbobeirne** [comment]
This is a very cool idea, we'll definitely look into what a solution like this would take to implement. Thanks for the suggestion!

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837174)
