### ISSUE TITLE
Issue Adding Custom Nodes (OPTIONS vs POST) (Parity vs Geth)

### ISSUE THREAD

**Issue by MysticRyuujin** [MyCryptoHQ/MyCrypto#1120]
When trying to add custom Parity nodes sometimes my browser seems to sends "OPTIONS" w/o any data instead of  a "POST" asking for the eth_blockNumber which results in a 403... Here's an example from FireFox Developer Tools:

![image](https://user-images.githubusercontent.com/8877131/36330549-b03e0850-132f-11e8-8544-c902600b0489.png)

I click Add Custom Node, and I enter my node information, it's exactly the same config for both nodes...

Using the developer tools to "Copy as cURL" results in this:

```
curl "https://paritynodes.mydomain.lan/" -X OPTIONS -H "Host: paritynodes.mydomain.lan" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" -H "Accept-Language: en-US,en;q=0.5" --compressed -H "Access-Control-Request-Method: POST" -H "Access-Control-Request-Headers: content-type" -H "Origin: https://mycrypto.com" -H "DNT: 1" -H "Connection: keep-alive"
```

and this:

```
curl "https://gethnodes.mydomain.lan/" -H "Host: gethnodes.mydomain.lan" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0" -H "Accept: application/json, text/plain, */*" -H "Accept-Language: en-US,en;q=0.5" --compressed -H "Referer: https://mycrypto.com/" -H "Content-Type: application/json; charset=UTF-8" -H "Origin: https://mycrypto.com" -H "DNT: 1" -H "Connection: keep-alive" --data "{""method"":""eth_blockNumber"",""id"":""735664f04248b13270b0baf996e4a2f2"",""jsonrpc"":""2.0""}"
```

I have no idea why the first one is of method "OPTIONS" nor does it contain any data being sent to the node. And this isn't a FireFox issue because Chrome seems to do the same thing...

These nodes work perfectly fine using HTTPS if I query them manually...

Here is in in Chrome Developer Tools too:
![image](https://user-images.githubusercontent.com/8877131/36330895-62048644-1331-11e8-937f-86306dbd2ef3.png)

![image](https://user-images.githubusercontent.com/8877131/36331485-99e13d08-1333-11e8-8538-17336df38c71.png)

In case there's a question about NGINX, the configs for the nodes are identical...

Literally the only difference is that one is Parity and the other is Geth (and their FQDNs).

**Comment by wbobeirne** [comment]
This is what's known as a CORS preflight request, an innocuous request to make sure that the cross-origin receiver will be OK with our request https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request.

Does this look similar to your issue? https://github.com/paritytech/jsonrpc/issues/114 Either way, this is browser behavior that we can't override, so unfortunately I think Parity will have to work this one out for their RPC servers.
