### ISSUE TITLE
Adding Long FQDN Custom Node Freezes GUI

### ISSUE THREAD

**Issue by MysticRyuujin** [MyCryptoHQ/MyCrypto#1122]
I previously opened this issue under MEW but it was never fixed and still persists.

If you attempt to add a custom node with a decently long FQDN by typing it, the GUI and the entire tab will completely freeze. This happens in FireFox and Chrome.

The longer the FQDN the longer it freezes once you press the dot/period key.

How to Reproduce:
1. Enter the following into the Custom Node URL:
`https://00112233445566778899`

2. Affix your cursor at the end of the url and manually type ".com"

As soon as you press the period/dot key you'll notice the lag.

That length of an FQDN is just enough to be annoying w/o totally locking up my browser 😄 but an even longer one locks up even longer...exponentially.

**Comment by wbobeirne** [comment]
I'm definitely noticing an abnormal amount of work going on here, but at 6x cpu slowdown on the development build I'm only looking at ~120ms per keystroke for the `.com` portion for a 50+ char domain. Can you provide some browser information?

![screen shot 2018-02-16 at 5 53 00 pm](https://user-images.githubusercontent.com/649992/36332991-7cc96f42-1342-11e8-9201-372e41739a63.png)

**Comment by MysticRyuujin** [comment]
Ok so I tested this with both FireFox, Chrome, and Edge same behavior in all three. I even disabled all extensions in chrome in Incognito Mode and tested just to rule out any of that stuff. I never use Edge so that's for sure clean 😄 

I'm not sure what type of data you'd need to reproduce?
Windows 10 x64
Edge: `Microsoft Edge 41.16299.15.0`
Chrome: `Version 64.0.3282.167 (Official Build) (64-bit)`
FireFox: `58.0.2 (64-bit)`

With a URL of `http://abcdefghijklmnopqrstuvwxyz` pressing the dot after that causes a lockup of probably 10 minutes on my machine. It's an Intel Core i7-4770k, the CPU usage on the browsers skyrockets.

**Comment by MysticRyuujin** [comment]
@wbobeirne I think I opened this in the wrong repo as this is happening on the main website?

**Comment by wbobeirne** [comment]
Oh, yep, different repos. Looks like this isn't a problem in the beta version. Thanks for letting me know!
