### ISSUE TITLE
Custom Node URL Parsing and Port Appending

### ISSUE THREAD

**Issue by MysticRyuujin** [MyCryptoHQ/MyCrypto#1123]
Ethereum-Harmony exposes their RPC port on the same port that they expose their GUI on with the directory /rpc/

E.G. http://harmony:8080/rpc/

It is impossible to add these nodes due to the current method that MyCrypto adds custom nodes (by appending the port number to the URI).

If the port number was optional, or just removed and specified in the URL this would allow the adding of Ethereum-Harmony nodes.

I should be able to just put `http://harmony:8080/rpc/` into the URL field. I'm don't think having a separate port field is better than just asking users to add nodes with the URL format of `http://hostname:8545'

**Comment by wbobeirne** [comment]
Yup, this was a really naive first pass for custom nodes. I'd had a note to replace this with a more robust URL creator, but it hadn't come up yet. Thanks for reminding me of the demand, I can take a crack at this shortly.

I think you're right that a straight-forward URL input will probably do the job, as long as helpful messages are added when users make mistakes or do unintuitive things, e.g. remind them to add http/s protocol, or inform them that it will default to 80 / 443 if they don't specify a port.
