### ISSUE TITLE
Display Checksummed Addresses

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#1137]
- [ ] Create component that ensures the address that is passed by prop is checksummed and then renders it.
- [ ] Convert all instances of address being shown in ^ component for display

**Comment by wbobeirne** [comment]
We should probably checksum everywhere we display an address, for consistency.

**Comment by dternyak** [comment]
@wbobeirne Definitely, we should make a component that accepts the address and enforces that it's checksummed.
