### ISSUE TITLE
Switch from Electron to Muon

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#1151]
Based on some discussions and feedback, we're going to transition from Electron to Brave's fork, [Muon](https://github.com/brave/muon). It looks like our build dependencies (`electron-builder` and `electron-updater`) should support the switch.

**Comment by wbobeirne** [comment]
Spent the last couple hours at this, here are my initial findings:

* Muon has no dedicated npm package, instead they rely on a [fork of `electron-prebuilt`](https://github.com/brave/electron-prebuilt) that just has you download binaries, rather than compile them yourself.
* It doesn't look like there's any typescript support here. Despite removing the package `electron`, you still use it ala `import electron from "electron";`. However, typescript has no idea what's going on with this and complains. I've found no reference implementations of Muon + Typescript.
* The documentation for switching is _really_ sparse, fortunately someone has a PR up with some guidance: https://github.com/brave/muon/pull/444

It's looking like there might be some fighting to do with this transition.

**Comment by kewde** [comment]
@wbobeirne 

Muon works with the default electron-builder, you might find some interesting bits here:
https://github.com/particl/particl-desktop/pull/807

**Comment by wbobeirne** [comment]
After some further investigating, we're going to put this on hold until Muon development is further along. For now our Electron build is pretty locked down and vetted, but we'll definitely keep an eye on Muon's progress and revisit this in the future.

**Comment by wbobeirne** [comment]
Swapy's recent [blog post](https://medium.com/swapynetwork/integrating-metamask-with-electron-a-simple-secure-and-non-intrusive-approach-517a04da1656) and [boilerplate repo](https://github.com/SwapyNetwork/electron-metamask-boilerplate) for running a muon app and incorporating MetaMask is very promising, should be a good resource when we return to this.
