### ISSUE TITLE
No popup warning when nav to TX Status

### ISSUE THREAD

**Issue by p-s-dev** [MyCryptoHQ/MyCrypto#1158]
### Description of the Feature

After sending a transaction, the "TX Status" button-link is shown.  After clicking this, the "not a bank" popup warning is shown.  Maybe the popup doesn't need to be shown again in this flow, after sending a transaction.

**Comment by wbobeirne** [comment]
The beta actually doesn't have a TX Status button right now (Thanks for the reminder to fix that though, should be added here: https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/components/ExtendedNotifications/TransactionSucceeded.tsx)

I think this is feedback for the current production site, which has a separate issue queue / repo over here: https://github.com/MyCryptoHQ/mycrypto.com/issues Let me know if I had that mistaken, and I'll reopen this issue.
