### ISSUE TITLE
[LEGACY] Have default decimals for networks

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1185]
For networks such as `EXP, UBQ, ETC, ETH` we should have default decimals hard coded in, and allow users to add the number of decimals for custom networks.

**Comment by wbobeirne** [comment]
Are there any networks right now not using 18? Would be nice to have something to test with.

**Comment by HenryNguyen5** [comment]
I looked into UBIQ and EXP, but didnt find any documentation that says they're different from 18 decimals

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837109)
