### ISSUE TITLE
Upgrade to Webpack 4

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#1191]
Webpack 4 was [just released](https://medium.com/webpack/webpack-4-released-today-6cdb994702d4), and will require some config migration. This issue should contain most discussion of any problems that come up with doing so.

I think it would be ideal to work out any of the kinks here _before_ launch, as build bugs can be pretty hard to pin down, and this'll be a pain to do when we have considerably more users and devs.

**Comment by wbobeirne** [comment]
So far I've found the following aren't up to date:

* [autodll-webpack-plugin](https://github.com/asfktz/autodll-webpack-plugin/issues/105)
* [hard-source-webpack-plugin](https://github.com/mzgoddard/hard-source-webpack-plugin/issues/276) claims to be compatible, but updating it killed the build (See link for issue)
* [webpack-subresource-integrity](https://github.com/waysact/webpack-subresource-integrity/issues/63)

I'll commit my work so far and push to a `webpack-4` branch, but I think we should try to wait until these modules get resolved, or lend a hand in upgrading them before we try to upgrade our build.

**Comment by wbobeirne** [comment]
Also going to keep a comment of packages we need to update, and close greenkeeper issues related to those:

* [ ] `hard-source-webpack-plugin`
* [ ] `html-webpack-plugin`
* [ ] `webpack-subresource-integrity`
* [ ] `autodll-webpack-plugin`

**Comment by wbobeirne** [comment]
Just circled back around to this, but `autodll-webpack-plugin` and `favicons-webpack-plugin` are both not up to date yet. Neither of these are mission critical, so if push comes to shove, we could just remove them from the build. I've got it running in dev by removing the autodll code, progress is pushed to `webpack-4`.

**Comment by anuraaga** [comment]
Sorry to jump in, found this when looking at `autodll-webpack-plugin` webpack 4 support. FYI for `favicons-webpack-plugin`, I was able to use `webapp-webpack-plugin` instead, which seems to primarily be a fork of favicons that also supports webpack 4.

**Comment by wbobeirne** [comment]
Alright, latest update on this: All of the necessary modules have come around to Webpack 4, so we've got builds completing. However, as far as I can tell, Webpack 4 might have changed the way cyclic dependencies resolve, because some of the imports are resulting in empty objects. However, this only happens in production builds, so I can't be sure if it's that or some minification issue. I've tried both babel minify, and uglifyjs, both have thier share of problems. I'll keep working on this.

Speaking of minification, I went ahead and measured build times and sizes, here are the results:

### Build Times

| Build                       | Old     | New     |
|-------------------------------|---------|---------|
| Initial dev run (no .cache)   | 33.043s | 28.852s |
| Initial dev run (with .cache) | 8.530s  | 5.049s  |
| First watch save              | 2.080s  | 5.164s  |
| Subsequent watch saves        | 1.972s  | 1.577s  |

^ New build doesn't yet use DLLs due to un-upgraded plugin.

### Build Sizes

| File   | Old    | New    |
|--------|--------|--------|
| Client | 6.79mb | 4.55mb |
| Vendor | 2.28mb | 1.47mb |

This definitely shows that there are some decent savings with Webpack 4. Hopefully the build can get sorted soon.

**Comment by dternyak** [comment]
Thanks for the update! The build size savings are pretty massive, so it will indeed be good to get the build sorted and get these savings in!

**Comment by wbobeirne** [comment]
After more tinkering, it looks like this is a result of the aggressive tree-shaking / export dependency graph in Webpack 4. I think all of our cyclic dependencies have exposed some kind of a bug. This is fixed by disabled `optimization.concatenateModules`, which uses `optimization.providedExports` and `optimization.usedExports` to determine which modules share sets of imported modules that aren't dependent on each other.

The problem is that some of the code (e.g. `common/store/configAndTokens.ts`) use other modules (e.g. `common/selectors/config/nodes.ts`), but for whatever reason Webpack is running the initial code before its required modules have resolved. I think this is because our dependency graph is totally fucked right now.

So I think we've got a couple of options:

1) Switch to webpack 4 with these optimizations disabled. There' still savings in here (5.81mb client, 1.9mb vendor) but it's not quite as much as before. We can fix the dependency graph later.
2) Fix the dependency graph by ducks-ifying a lot of our code (cc @HenryNguyen5) and revisit Webpack 4 then.
