### ISSUE TITLE
Refactor template to retain state / not re-render

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#1192]
### Description of the Issue

Right now when you navigate pages, the entire template re-renders. This is because each container renders <TabSection> independently. This causes certain issues with losing state. For instance, if you're on mobile, scroll navigation, and click a link, you'll have the navigation reset to a scrollLeft of 0. This re-rendering is both needless from a performance perspective, and potentially confusing if anything else in the header or footer's state gets reset.

We should probably move `<TabSection>` into Root.tsx, and have it wrap the router. We may need to come up with a way to have routes define behavior of TabSection via props, possibly in some kind of master routes config.

### Steps to Reproduce

1. Open a page on a mobile device
2. Slide navigation
3. Click a link
4. See navigation reset to the left

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837107)
