### ISSUE TITLE
Transaction value sometimes sets itself to '0'

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#1201]
### Description of the Issue

Sometimes when entering the value on send transaction, after entering it, it will be reset to zero. This only happens once, after you fix the set to zero, it won't happen again.

### Steps to Reproduce

This has been inconsistent, but:

1. Unlock a wallet on send
2. Set the address
3. Set the value to `1`
4. Unfocus the field
5. Value is set back to `0`

#### Setting to 1 action

<img width="938" alt="screen shot 2018-02-28 at 3 18 21 pm" src="https://user-images.githubusercontent.com/649992/36811175-e44ba19c-1c9a-11e8-801b-d0e63c9e4686.png">

#### Followed soon after by being set to 0 action (That I didn't trigger)

<img width="912" alt="screen shot 2018-02-28 at 3 18 27 pm" src="https://user-images.githubusercontent.com/649992/36811188-ecf65760-1c9a-11e8-9aad-04dd5ddd09d8.png">

**Comment by wbobeirne** [comment]
I'm also seeing `-1` on occasion as well.

**Comment by dternyak** [comment]
I have feeling this might be due to scrolling down on the touchpad without
realizing it -- I've definitely done it myself a few times.

**Comment by dternyak** [comment]
![2018-03-01 15 37 27](https://user-images.githubusercontent.com/7861465/36871042-795cedd8-1d66-11e8-9cb0-d2eaeae76aea.gif)

**Comment by wbobeirne** [comment]
This is very embarrassing. I'll fix this behavior and we'll never speak of it again.

**Comment by dternyak** [comment]
😁 It may actually be worth figuring out if we can disable it, as I think it's very common behavior that users will scroll down after finalizing the amount value.

We could turn it off with a simple event listener, but I'm not sure how much an anti-pattern that is.

**Comment by wbobeirne** [comment]
Yeah, that's what I mean. I'll add an event listener, or see if it's some attribute that disables this. I'm pretty sure this is a side effect of being `type="number"`

**Comment by dternyak** [comment]
Awesome -- yup, I think so too.
