### ISSUE TITLE
Improve redux state storage & hydration

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#1205]
Right now our code for saving and restoring redux state in local storage is tenuous at best. It's all in store.ts in a very ad-hoc way, there's a good amount of repetition between the saving and loading portions, and there's no good way to alter redux state without blowing away local storage, which will no longer be an option once we hit production. Here's are my proposals, which are largely inspired by most databases that have the same kinds of persistence issues:

#### 1) Have a manifest object & type for saving & loading state

If you want to save a key, you should just mark it off in one manifest. That manifest should be typed, so that we're sure that if something's supposed to be in it, it's there. I'm not sure how this should look though, so feedback is welcome.

#### 2) Provide "hooks" for custom behavior

Swap doesn't reload state unless you're on step 3. Transactions need to re-BN gas price. There should be a pre-load step that allows us to do these checks, and manipulate the stored state.

#### 3) Version state, run through "upgrade" functions

An additional key should be saved in `REDUX_STATE` called `VERSION`, which maps to a constant in code. This should be an integer that's incremented by one every time there's a breaking change. Upon loading a store, we should check if the version number is below the current one, and if so, increment it by one and run the relevant update function on the store. Repeat until they're up to the current version, and save that to local storage again.

cc @dternyak @HenryNguyen5 @skubakdj @james-prado @aitrean for discussion.

**Comment by HenryNguyen5** [comment]
I ran into the same issue before during the `nodes-networks-redux` refactor, and while thinking of a future solution, 3) seemed most natural. During some research after, something like `redux-persist` package would really help here as we can have per-reducer state hydration, including sub-reducers. This would definitely increase maintainability as we would only have to worry about rehydrating small slices of state per file, just like how reducers are coded in. The package also provides migration hooks to move between versions of state.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837105)
