### ISSUE TITLE
Slightly offset promos

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#1227]
<img width="414" alt="screen shot 2018-03-02 at 12 44 45 am" src="https://user-images.githubusercontent.com/7861465/36886619-eb396232-1db2-11e8-956d-fb3f10a8fcd8.png">

**Comment by james-prado** [comment]
Closing stale issue, the alignment is sligntly offset due to how the text wraps. Unfortunately there is no way to fix this issue consistently across multiple promos, or at multiple screen sizes.
