### ISSUE TITLE
Center / Adjust Token Scanner Buttons

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#1230]
<img width="432" alt="screen shot 2018-03-02 at 1 58 50 am" src="https://user-images.githubusercontent.com/7861465/36888934-4ec90f32-1dbd-11e8-8a7a-1dff03c2985c.png">

**Comment by Adexbafo** [comment]
I think this needs to be reviewed as the button meant for scanning tokens which I believe has to be automatic, didn't perform that functions at all. So please kindly check this and work on it, as adding manually is strenuous and time consuming.

**Comment by james-prado** [comment]
Closed by https://github.com/MyCryptoHQ/MyCrypto/pull/1276
