### ISSUE TITLE
Update Keystore Password UI Behaviour

### ISSUE THREAD

**Issue by aitrean** [MyCryptoHQ/MyCrypto#1260]
Right now on beta, the keystore field looks unresponsive because we're not giving any visual queues when the user picks a keystore. In an old build, the password box would appear after we attempted to unlock a keystore with a blank password (which that a password was necessary). I'm not sure why we removed that, but I think it would be ideal, or at least some other visual queue.

**Comment by wbobeirne** [comment]
I wasn't a fan of how much the UI "jumped" in the old version, introducing new fields. I do think it would help to make it look more interactive though. Maybe we should disable the password field, until there's a file uploaded, then make it editable?

**Comment by aitrean** [comment]
That sounds like a good solution. I just want a visual indicator that the keystore is uploaded, and I don't think the password field should be open while there's no corresponding keystore to unlock.
