### ISSUE TITLE
Back button doesn't work as expected on WalletDecrypt

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#1262]
### Description of the Issue

From a user in Discord: After selecting a wallet on /account, or any page with wallet decrypt, the user expected to be able to use their browser back button to select a different wallet. Instead, they were navigated away from the page. We should probably push a navigation to the stack when a user selects a wallet, and handle when it's popped.

### Steps to Reproduce

1. Navigate to `/account`
2. Select "Ledger" as your wallet
3. Press back button
4. Confirm you get navigated to the previous page

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837103)
