### ISSUE TITLE
Copy & Share QR Code

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#1278]
"Send QR codes on the request payment tab via email, MMS, etc. or even just copy and paste function so we can use any service."

https://medium.com/@RaymondDurk/mycrypto-beta-is-a-great-sign-for-things-to-come-6e1f756b28d2

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837101)
