### ISSUE TITLE
Add preferred fiat setting

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#1281]
### Description of the Feature

Most things around the site use USD, except the Equivalent Values sidebar component which uses multiple fiat options. Since those are available, we could presumably use any fiat currency where we currently have USD hard coded. This might be a nice setting for better internationalization.

Not sure if we should auto-configure it based on locale, or have it be always default to USD though.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837099)
