### ISSUE TITLE
Bulk token balance fetch failures aren't handled

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#1293]
### Description of the Issue

Discovered in #1270, if a token balance fetch comes back with failures, it's not getting handled right now:

#### Request
```
[{
  "method": "eth_call",
  "params": [
    {
      "to": "0x983f6d60db79ea8ca4eb9968c6aff8cfa04b3c63",
      "data": "0x70a0823100000000000000000000000030cf8aa72c4e69e35e0e48e785176704d6d70c7d"
    },
    "pending"
  ],
  "id": "ccd3f8a83671b8c23dc33a7085eaf5e3",
  "jsonrpc": "2.0"
}]
```
#### Response
```
[{
  "jsonrpc": "2.0",
  "error": {
    "code": -32015,
    "message": "Transaction execution error.",
    "data": "Internal(\"Database missing expected key: e1b9…75a7\")"
  },
  "id": "ccd3f8a83671b8c23dc33a7085eaf5e3"
}]
```

Results in

```
client.1be3dddc.js:11 Failed to scan for tokens Error: unsupported value conversion
  at handleValues (client.1be3dddc.js:1)
  at TokenValue (client.1be3dddc.js:1)
  at response.map.item (client.1be3dddc.js:1)
  at Array.map ()
  at client.batch.then.response (client.1be3dddc.js:1)
  at scanWalletForTokens @ client.1be3dddc.js:11
```

which happens in this function over here: https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/libs/nodes/rpc/index.ts#L80

### Steps to Reproduce

Inconsistent, but I've gotten it a couple of times by checking the balance on a wallet with a lot of tokens.

**Comment by dternyak** [comment]
Shepherd is the current approach to fixing this. We will split batched requests and fire against multiple (and potentially against the same) node infrastructure to prevent the backend from choking on larger non-0 token balance requests)
