### ISSUE TITLE
Token Scanner Fails to find popular tokens

### ISSUE THREAD

**Issue by ChosunOne** [MyCryptoHQ/MyCrypto#1298]
### Description of the Issue

The token scanner does not report the balances of Augur (REP) or Cindicator (CND).  

### Steps to Reproduce

Use a ledger to unlock an account with both REP and CND

### Description of Your Machine

Windows 10
Google Chrome Version 64.0.3282.186 (Official Build) (64-bit)

### Console Logs / Screenshots

[Screenshot of the results of the token scanner on an address with tokens](https://imgur.com/a/1IQ0q)
[Screenshot of the results of etherscan on the same address with tokens](https://imgur.com/a/4AJ5W)

**Comment by wbobeirne** [comment]
Our token list is currently a little out of date. There's an open PR / discussion about expanding it over here https://github.com/MyCryptoHQ/MyCrypto/pull/1247, so I'm going to close this issue. Thanks for the report though!
