### ISSUE TITLE
ShapeShift logo opens Bity URL

### ISSUE THREAD

**Issue by wtzb** [MyCryptoHQ/MyCrypto#1318]
### Description of the Issue

The ShapeShift logo in the 'Swap' tab opens up the following URL: https://bity.com/af/jshkb37v

### Steps to Reproduce

Open 'Swap' tab, start the Swap process, then the ShapeShift logo will appear in the top-right, click the ShapeShift logo in top-right.

### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/11412480/37352983-b13edb2c-26de-11e8-8612-9904ed52d9db.png)

**Comment by hahnmichaelf** [comment]
I was unable to replicate this when I attempted it using your steps @wtzb 

I did, however, find that link within the codebase with a comment to replace it

**Comment by wtzb** [comment]
I forgot to add that you will have to start the Swap process, then the ShapeShift logo will appear in the top-right corner, with the invalid URL. @hahnmichaelf

**Comment by wbobeirne** [comment]
Yep, this is legit. Thanks for the find, I'll be sure to update.
