### ISSUE TITLE
Merge the 'generate tx' button with the 'send tx' button

### ISSUE THREAD

**Issue by james-prado** [MyCryptoHQ/MyCrypto#1340]
### Description of the Issue

The average user doesn't need to see the transaction parameters, serialized parameters, or the signed transaction. All of those are really for advanced users and should be moved to the 'details' tab in the tx confirmation modal. 

Also the 'generate transaction' button should be replaced with just the 'send transaction' button. Functionally it should behave the same, it'll ask for confirmation on hardware wallets before sending, and still generate the transaction, but it'll simplify the sending process.

**Comment by wbobeirne** [comment]
I'm into this for the online view, but we have to make sure we preserve this behavior for the offline view, since they'll need to copy / paste the signed TX. I think that's the only case affected by this change, but someone else can weigh in if there are more.
