### ISSUE TITLE
Error when setting MyCrypto project on local environment

### ISSUE THREAD

**Issue by wannabit-jayb** [MyCryptoHQ/MyCrypto#1344]
---
### Description of the Issue

> I am trying to run MyCrypto on my local environment. Does anyone know what the problem is ? If I need some additional system dependencies, what do you think those dependencies are?

### Steps to Reproduce

```bash
git clone https://github.com/MyCryptoHQ/MyCrypto.git
```

> Taking quite a long time, but successfully cloned MyCrypto project.

Cloning into 'MyCrypto'...
remote: Counting objects: 17094, done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 17094 (delta 36), reused 33 (delta 15), pack-reused 17000
Receiving objects: 100% (17094/17094), 9.61 MiB | 30.00 KiB/s, done.
Resolving deltas: 100% (10741/10741), done.

```bash
npm install
```

> Success with some WARNINGS

npm WARN ts-jest@22.4.1 requires a peer of jest@^22.4.0 || ^22.5.0-alpha.1 || ^23.0.0-alpha.1 but none is installed. You must install peer dependencies yourself.
npm WARN MyCrypto@0.5.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@1.3.1 (node_modules/7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.3.1: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.2.0 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.2.0: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-linux@1.7.2 (node_modules/app-builder-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-linux@1.7.2: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-win@1.7.2 (node_modules/app-builder-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-win@1.7.2: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})

```bash
npm run dev
```

> set a breakpoint in malloc_error_break to debug ???

> MyCrypto@0.5.1 predev /Users/coincube/dev/MyCrypto
> check-node-version --package

> MyCrypto@0.5.1 dev /Users/coincube/dev/MyCrypto
> node webpack_config/devServer.js

AutoDllPlugin: is valid cache? false
AutoDllPlugin: cleanup
AutoDllPlugin: compile
[hard-source:core] HardSourceWebpackPlugin is writing to a new confighash path for the first time: /Users/coincube/dev/MyCrypto/node_modules/.cache/hard-source/204ccb61186e913f00df8b1fc3779982ea61c5294327b6727e94b62d462d4677
webpack building...
ts-loader: Using typescript@2.6.2 and /Users/coincube/dev/MyCrypto/tsconfig.json
ts-loader: Using typescript@2.6.2 and /Users/coincube/dev/MyCrypto/tsconfig.json
ts-loader: Using typescript@2.6.2 and /Users/coincube/dev/MyCrypto/tsconfig.json
node(12275,0x70000bf42000) malloc: *** error for object 0x107364200: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
[1]    12261 abort      npm run dev

### Description of Your Machine

Chrome Version 64.0.3282.186 (Official Build) (64-bit)
OS : Mac OS High Sierra
node v : 5.6.0
npm v : 8.9.4 

---

**Comment by tommycox** [comment]
Am getting this as well. Blocks #1117

`Node v8.9.4`
`npm v5.6.0`
`Mac OS High Sierra`

**Comment by Bagaric** [comment]
Same error here.

MacOS High Sierra 10.13.3
npm 5.6.0
node 8.9.4

**Comment by wbobeirne** [comment]
Hey y'all, thanks for the reports. It looks like this is a bug in `node-sass`. We should update the version shortly, but in the mean time you can manually bump it yourself in package.json

**Comment by kosecki123** [comment]
Yep. I bumped `node-sass` to 4.8.3 and the error is gone.

**Comment by wannabit-jayb** [comment]
@wbobeirne @kosecki123 
That works well, thank you !
