### ISSUE TITLE
Bytes array are not properly being displayed

### ISSUE THREAD

**Issue by rstormsf** [MyCryptoHQ/MyCrypto#1345]
### Description of the Issue
If I read some information from smart contract that is returning `bytes` 
I cannot properly see the data

### Steps to Reproduce
1. Go to
https://beta.mycrypto.com/contracts/interact
2. Select Kovan network
3. Choose address contract: `0xd6b01b3e0e1bacab84263c93d702f22aee0ee687`
4. ABI: https://gist.github.com/rstormsf/87349e24ace3be7e61476bec9e1d032a
5. Select function message
6. Provide input:
`0xba44fd1f70c3023005117f797a967694ed3e71d110cd3714a28c3cdd77df5b02`

Get something like this:
```
9�.��GU||]�L�mH��cEx]�*�B`�`y�����ю�0��L�ܺ-�{	l;��
```

FYI when I did it on MEW, it works as expected:
```
0x0039f22efb07a647557c7c5d17854cfd6d489ef3000000000000000000000000000000000000000000000000016345785d8a00002aba426015916079a2a10306fa1bb2edd18ed030a1a04cd9dcba2d1bd77b096c000000000000000000000000000000000000000000000000000000003b9aca00
```
response from contract
### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/9360827/37635774-e26f1adc-2bba-11e8-8a03-d63e78f8b96a.png)

How it should be:
![image](https://user-images.githubusercontent.com/9360827/37635818-2c48b73a-2bbb-11e8-8e87-f303f7e6a06a.png)

**Comment by wbobeirne** [comment]
Thanks for the incredibly thorough report. I was able to replicate with your instructions, we'll definitely get this sorted before launching out of beta.

**Comment by HenryNguyen5** [comment]
This is due to the wrong encoding parameter when converting the buffer value to a string, looks like its coming back as `utf8` when it should be `hex`
