### ISSUE TITLE
Keystore File Fields always red

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#1357]
<img width="801" alt="screen shot 2018-03-21 at 2 02 40 pm" src="https://user-images.githubusercontent.com/7861465/37731591-906c7930-2d10-11e8-91e0-6caee8590294.png">

When entering a valid password, the field will show red and give feedback to the user that this password is incorrect, even when it isn't.

- [ ] Show green (valid) borders when a password is valid.

**Comment by wbobeirne** [comment]
This looks to have been fixed, I think as a part of #1323.
