### ISSUE TITLE
Send All Funds UX improvements

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#1360]
## What?
Proposal for enhancements to the "send entire balance" UI.

#### MyCrypto Current 
<img width="500" alt="screen shot 2018-03-21 at 2 23 13 pm" src="https://user-images.githubusercontent.com/7861465/37732565-673cea06-2d13-11e8-8f69-9b4a819615c8.png">

Instead of "Send Entire Balance" shown below the amount field, a more common UI is including an element on the far right of the input (as shown below). 

#### Trezor
<img width="500" alt="screen shot 2018-03-21 at 2 16 34 pm" src="https://user-images.githubusercontent.com/7861465/37732252-7d48b902-2d12-11e8-8aad-94a521cdb019.png">

#### Mockup
<img width="629" alt="screen shot 2018-03-21 at 2 25 49 pm" src="https://user-images.githubusercontent.com/7861465/37732678-c6cc20cc-2d13-11e8-8a17-f23a0f150bb7.png">

- [ ] Enhance the send entire balance UI by providing a clickable element show within the input field.

**Comment by wbobeirne** [comment]
I'm going to take this one and group it with a couple of style fixes for the send form.
