### ISSUE TITLE
highlight required form fields & validate forms onClick

### ISSUE THREAD

**Issue by james-prado** [MyCryptoHQ/MyCrypto#1361]
Currently there's no way to distinguish between an optional or a required field. Adding some kind of visual difference will help users fill out forms and correct mistakes. 

Also in most* cases, I don't think buttons need to be disabled until all inputs are filled and valid. Instead 'submit' buttons at the end of a form should validate the inputs `onClick`, then highlight any skipped or invalid inputs. This provides the same level of validation, but makes it easier to correct mistakes when submitting forms.

**Comment by dternyak** [comment]
Related https://github.com/MyCryptoHQ/MyCrypto/issues/1357

**Comment by wbobeirne** [comment]
I'm not super wild on the validation only on clicking submit, I think telling the user to fix their issues when it's most relevant is ideal. However I definitely agree that a required indication should definitely be done. Might be good to make an InputGroup component that encompasses the whole input group (label & input) and give it a `required` boolean that adds an orange asterisk or something.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837095)
