### ISSUE TITLE
Can't unlock accounts in Safari

### ISSUE THREAD

**Issue by Varunram** [MyCryptoHQ/MyCrypto#1372]
I constantly keep getting "Please Enter a Password" if I try to unlock my account on Safari (macOS 10.13.3). Unlocking works just fine on Chrome, so I guess there's some weird stuff going on only with safari.

**Comment by wbobeirne** [comment]
I'm able to reproduce this on https://beta.mycrypto.com, but unable to reproduce it on the latest development version, so I assume this was fixed somewhere along the way. Hopefully we'll have a new release up shortly that will make this work on the beta site as well.

Sorry for the inconvenience!
