### ISSUE TITLE
Ledger Wallet do not unlock

### ISSUE THREAD

**Issue by gellesrinivas** [MyCryptoHQ/MyCrypto#1403]
If you're having an issue with unlocking your wallet, a transaction, a swap,
or an ENS auction, please email support@mycrypto.com. Github issues are for
development only, and support questions that aren't bugs or feature requests
will not be answered.

---

If you've experienced a bug, please provide the following information:

Unable to unlock the Ledger Wallet after installing the new firmware on Ledger Wallet.

### Steps to Reproduce

1. Open MyCrypto.com
2. Click on Send 
3. Unlock the ledger wallet and open the ether wallet
4. Select the Ledger Wallet option from the options
5. Click on the "Continue on Ledger Wallet"
Nothing happens. Earlier use to get a popup to allow to select the ether to send

### Description of Your Machine

(Your browser, browser version, operating system, device)
Chrome browser / IE

### Console Logs / Screenshots

(Console logs or screenshots go here, if applicable)

---

If you're suggesting a feature, make sure someone hasn't already posted it. If
no one has, please provide the following information:

### Description of the Feature

(Your description goes here)

### Example(s) of Feature

(If another product or app is doing this, please link it)

**Comment by wbobeirne** [comment]
Hey @gellesrinivas, based on your description I think you're using the production site of MyCrypto. You can find the repository and issue queue for that over at https://github.com/MyCryptoHQ/mycrypto.com/issues
