### ISSUE TITLE
gastracker address url is error

### ISSUE THREAD

**Issue by VieYang** [MyCryptoHQ/MyCrypto#1414]
### Description of the Issue

ETC Transaction History Address URL is error.
MyCrypto show me the url https://gastracker.io/address/0x4bbeEB066eD09B7AEd07bF39EEe0460DFa261520,  but https://gastracker.io/addr/0x4bbeEB066eD09B7AEd07bF39EEe0460DFa261520 is correct

**Comment by dternyak** [comment]
Thanks for the report! We'll be sure to get this patched up in the next release.
