### ISSUE TITLE
Cannot sign message with Ledger on beta.mycrypto.com

### ISSUE THREAD

**Issue by phiferd** [MyCryptoHQ/MyCrypto#1441]
### Description of the Issue

Cannot sign messages on https://beta.mycrypto.com/sign-and-verify-message/sign with Ledger Nano S

### Steps to Reproduce

1. Go to https://beta.mycrypto.com/sign-and-verify-message/sign
2. Open the Ethereum app on my Ledger Nano S
3. Click "Connect to Ledger Wallet"
4. Select my address, click "Unlock"
5. Enter a message
6. Click sign message
7. Check my Ledger -- I see a message that says "Sign the message" and then the message hash
8. Click the right button (check mark) on my Ledger
9. Nothing happens ... 

I tested it on the production site and signing works fine with the same Ledger.

### Description of Your Machine

Windows 10 / Chrome

### Console Logs / Screenshots

Nothing special -- no errors in the console.

**Comment by dternyak** [comment]
Thanks for your report @phiferd 

I can confirm I am able to reproduce this issue on the latest beta.
