### ISSUE TITLE
Slider Tooltip doesn't track

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#1452]
![2018-04-05 14 18 07](https://user-images.githubusercontent.com/7861465/38387036-3215c8aa-38dc-11e8-8366-db718770afcb.gif)

- [ ] Have the tooltip track the slider during adjustment

**Comment by wbobeirne** [comment]
This is an issue with rc-slider, via subdependency rc-align. Issues are being tracked here: https://github.com/react-component/slider/issues/409 and here: https://github.com/react-component/align/issues/18. A workaround for now would be to pin `rc-align@2.3.5` in `yarn.lock`.
