### ISSUE TITLE
UBQ requests fail

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#1516]
This issue is [reported with Shepherd](https://github.com/MyCryptoHQ/shepherd/issues/52), but going to keep an issue open here on MyCrypto so we don't forget to update / prevent duplicate reports.

**Comment by HenryNguyen5** [comment]
Addressed in latest shepherd version: https://github.com/MyCryptoHQ/shepherd/issues/52
