### ISSUE TITLE
Cipher Browser Sign Message Bugs

### ISSUE THREAD

**Issue by EvilJordan** [MyCryptoHQ/MyCrypto#1527]
1. One can successfully sign a message with Cipher, but it lists the "transaction" twice within Cipher Browser, effectively generating two sign message requests for the user.
2. The result of the message signing is never shown to the user back on the beta.mycrypto.com site.

**Comment by wbobeirne** [comment]
I can replicate this. Unfortunately, due to the fact that it works in MetaMask & Mist, and there don't seem to be any debugging tools for the Cipher browser, I'm not sure how to figure out what's going wrong here.

**Comment by EvilJordan** [comment]
Cryptokitties integrates during the signup process with Cipher + Message Signing flawlessly, with the exception that it also does not display the result to the end-user (but this is probably because it's just not necessary in that instance). I'm hoping @petejkim can chime in, but given the browser's EOL (I assume, since it's becoming Toshi), not holding my breath!

**Comment by Azarielle** [comment]
Closing, please see this issue -  https://github.com/MyCryptoHQ/MyCrypto/issues/2060
