### ISSUE TITLE
Toshi browser doesn't unlock

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#1533]
### Description of the Issue

Something about our Web3 implementation doesn't play well with the Toshi app browser. Attempting to unlock doesn't work. It does, however, work on mycrypto.com, so there's something wrong with the new code. It pops up the following error:

> FetchSubprovider - cannot complete request. All retries exhausted. Original error: SyntaxError: Unexpected end of JSON input.

This may be a shepherd web3 implementation, cc @HenryNguyen5 

### Steps to Reproduce

1. Download and run the Toshi app on your phone
2. Navigate to https://beta.mycrypto.com
3. Attempt to unlock web3

### Description of Your Machine

Android Toshi

**Comment by wbobeirne** [comment]
We don't have any service worker stuff going on, so I don't think that's it.

**Comment by Azarielle** [comment]
Closing since there's an issue opened already addressing this. https://github.com/MyCryptoHQ/MyCrypto/issues/2060
