### ISSUE TITLE
Pressing backspace on empty unit selection DropDown throws error

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1554]
### Description of the Issue

When pressing backspace in the unit selection dropdown in the `RequestPayment` component, the component will throw errors

### Steps to Reproduce

1. Go to RequestPayment tab
2. In the unit selection dropdown, click on it
3. Press backspace with console open

![2018-04-17-190520_1694x303_scrot](https://user-images.githubusercontent.com/6404866/38904202-0ea0d6ae-4277-11e8-8ed9-4e430d843b29.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837079)
