### ISSUE TITLE
Clicking on Disclaimer causes React to throw setState error

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1555]
### Description of the Issue

Clicking on disclaimer on the footer to bring up the modal causes React to throw an `Warning: An update (setState, replaceState, or forceUpdate) was scheduled from inside an update function. Update functions should be pure, with zero side-effects. Consider using componentDidUpdate or a callback` error

### Steps to Reproduce

1. Be on development build
2. Click on disclaimer with console open

![2018-04-17-190336_1692x85_scrot](https://user-images.githubusercontent.com/6404866/38904297-876efef8-4277-11e8-977c-ac9547ca79c6.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336754)

**Comment by ConnorBryan** [comment]
Fixed.
