### ISSUE TITLE
Recent Transactions Invalid Dom Nesting

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1556]
### Description of the Issue

When messing around when the recent transactions component, React eventually threw an invalid dom nesting error
### Steps to Reproduce

1. Navigate to Recent transactions component with some transactions already in state
2. (Couldn't consistently repo) Error will be thrown in console

![2018-04-17-190308_1673x372_scrot](https://user-images.githubusercontent.com/6404866/38904347-e2b0717a-4277-11e8-953e-cbde13e76976.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336752)

**Comment by ConnorBryan** [comment]
Fixed.
