### ISSUE TITLE
Password strength indicator for generating a keystore file

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1558]
### Description of the Feature

Currently we only display to the user if the password is too weak, but it would be a better UX if we had a password strength indicator display

**Comment by tayvano** [comment]
Always been a fan of https://github.com/dropbox/zxcvbn

**Comment by wbobeirne** [comment]
We do in fact use that library! There's just no UI hooked up to it.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336750)
