### ISSUE TITLE
Clicking on already selected words in mnemonic phrase confirmation still fires onChange handler

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1560]
### Description of the Issue

Clicking on already selected words in mnemonic phrase confirmation still fires onChange handler. This is despite the elements showing as disabled.

### Steps to Reproduce

1. Go to `Create New Wallet`
2. `Generate Mnemonic Phrase`
3. `Confirm Phrase`
4. Click on the first correct word
5. Click on it again despite it showing disabled
6. Word will flash red

### Console Logs / Screenshots

![2018-04-17-181909_1553x607_scrot](https://user-images.githubusercontent.com/6404866/38905426-a89a0742-427e-11e8-8b65-c16de8b99efd.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336746)
