### ISSUE TITLE
[LEGACY] Verify signed message success has typo

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1562]
### Description
Between the word `signed` and the message itself, there is a missing space

### Console Logs / Screenshots

(If another product or app is doing this, please link it)
![2018-04-17-185551_1563x465_scrot](https://user-images.githubusercontent.com/6404866/38905516-229a3b98-427f-11e8-8d42-3a8a66f02678.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336744)
