### ISSUE TITLE
Swap Issue reporting has empty fields for first stage

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1564]
### Description of the Issue

On the first step after selection which currencies to swap on the swap tab, the following fields will be empty:
```
To: support@mycrypto.com
Subject: Issue regarding my Swap via MyCrypto
Message:
Provider: Shapeshift
REF ID#: 
Amount to send:  BTC
Amount to receive:  ETH
Payment Address: 
Receiving Address: 
Rate: 15.58333594 BTC/ETH
```
It would be useful to add an identification field for each step the user is at, so its easier to debug at what stage of swap their error report is in.

### Steps to Reproduce

1. Go to swap tab
2. Click on `Click here if link doesn't work`

### Console Logs / Screenshots

![2018-04-17-183943_1638x842_scrot](https://user-images.githubusercontent.com/6404866/38905591-a4c4aeb4-427f-11e8-8492-33f4c9edf329.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336742)
