### ISSUE TITLE
`Click here if link doesn't work` text on swap tab should be an anchor element

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1565]
### Description of the Issue

The `Click here if link doesn't work` element is a paragraph instead of an anchor element, leading to the cursor not displaying the link as clickable

### Steps to Reproduce

1. Go to swap tab
2. Hover over `Click here if link doesn't work`
3. Cursor does not change to reflect clickable state

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336740)
