### ISSUE TITLE
Clicking back button on Mnemonic Phrase confirmation goes back to first page instead of back one step

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1566]
### Description of the Issue

When on the Mnemonic Phrase confirmation tab (where you confirm each word in a shuffled order) if the back button is pressed, the user is taken back to the `Create New Wallet` page, when the user could have wanted to only go back one step.

**Comment by wbobeirne** [comment]
This is also the case when unlocking wallets (#1262,) we should probably come up with a pattern for pushing a new location and showing a new component.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837170)
