### ISSUE TITLE
Swap validation error messages dont line up with actual valid values

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1567]
### Description of the Issue

Validation error messages from swap telling the user the minimum amount required don't actually line up with a valid amount.

### Steps to Reproduce

1. Go to swap tab
2. Enter in a below minimum amount for a coin so validation error shows
3. Enter in a slightly higher amount that is still lower than what the inline error says
4. Box will then turn valid

### Console Logs / Screenshots

![2018-04-17-183706_1574x614_scrot](https://user-images.githubusercontent.com/6404866/38905776-b88e76cc-4280-11e8-85c4-a1859a87e9bf.png)
![2018-04-17-183731_1613x617_scrot](https://user-images.githubusercontent.com/6404866/38905796-cad01f84-4280-11e8-892b-151ad32b641e.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336738)
