### ISSUE TITLE
Empty amount box on swap gets filled with `0` when changing units, or the opposite box

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1568]
#### Case 1:
1. Go to swap tab
2. Inspect that both boxes are empty
3. Change unit to something else on either box
4. Both boxes will autofill 0 instead of staying empty

#### Case 2:
1. Go to swap tab
2. Inspect that both boxes are empty
3. Enter 0 in one box
4. The other box will autofill 0 instead of staying empty

### Console Logs / Screenshots

![2018-04-17-183506_1574x610_scrot](https://user-images.githubusercontent.com/6404866/38905834-0f77d410-4281-11e8-95ba-831bceab1fe9.png)
![2018-04-17-183500_1565x599_scrot](https://user-images.githubusercontent.com/6404866/38905835-0f868bcc-4281-11e8-91ef-b3a493ac127d.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336736)
