### ISSUE TITLE
No loading indicator for tokens in DeterministicWalletModal

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1570]
### Description of the Issue

Lack of loading indicator on tokens leads user to thinking that nothing is happening

### Steps to Reproduce

1. Go to `Send & Verify` tab
2. Choose `Ledger` wallet
3. Sign in `Ledger` wallet
4. Observe that ETH has loading indicators
5. Choose a token
6. Observe that token amounts will stay `???` until loaded, no loading indicator

### Console Logs / Screenshots

![2018-04-17-182706_820x573_scrot](https://user-images.githubusercontent.com/6404866/38905989-09b696c8-4282-11e8-86fa-6f875698709b.png)

**Comment by wbobeirne** [comment]
Fixed via #1682
