### ISSUE TITLE
Prop type validation periodically fails for DeterministicWalletModal

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1571]
### Description

Sometimes when using DeterministicWalletModal, a prop type validation fails

### Steps to Reproduce

No solid reproduction steps yet, seems to randomly happen when the DeterministicWalletModal component mounts

### Console Logs / Screenshots

(If another product or app is doing this, please link it)
![2018-04-17-183110_1693x737_scrot](https://user-images.githubusercontent.com/6404866/38906063-5b435580-4282-11e8-8e91-ed3d3bdbdf04.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336734)

**Comment by ConnorBryan** [comment]
Fixed.
