### ISSUE TITLE
Memory leak when logging off a web3 wallet

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1573]
### Description of the Issue

Because of our use of `setTimeout` to setState in an component, sometimes it can call `this.setState` when the component has already been unmounted. I've seen this pattern being used a couple times in the codebase, we should cancel these timeouts in `componentWillUnmount` where possible to avoid these errors.

### Steps to Reproduce
1. Go to `Sign & Verify Message` Tab on development build
2. Open console
3. Use Metamask login
4. Login
5. Click on another tab to logout
6. See error thrown in console

### Console Logs / Screenshots

![2018-04-17-190336_1692x85_scrot](https://user-images.githubusercontent.com/6404866/38906187-135e5714-4283-11e8-8097-9d09c36a44fa.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336732)
