### ISSUE TITLE
Changing networks sometimes causes DeterministicWalletModal to not load properly

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1576]
### Description of the Issue

When switching between networks (lets say ETH and Ropsten) and opening DeterministicWalletModal inbetween each switch, sometimes balances will fail to load on some address until re-tried a couple times.

### Steps to Reproduce (Not 100% repo rate)

1. Switch between networks
2. Between each switch, check DeterministicWalletModal to see if address balances load properly

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336722)

**Comment by ConnorBryan** [comment]
Attempted to repro, unable to, might just be switching network and then opening modal too fast.
