### ISSUE TITLE
Changing to a different network on Broadcast transaction invalidates current filled field

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1580]
### Description of the Issue

Because of a saga `takeEvery` effect when the network is changed, the entire transaction reducer state is cleared. But when this is done while the `Broadcast Transaction` field is filled with a valid transaction, it'll get invalidated as the state will be empty. This can either be fixed by:
1. Adding exceptions to the sagas/reducers to only partially clear state on certain tabs on network switch
2. Re-dispatching the field's data when the state gets cleared (little bit hacky)

### Steps to Reproduce

1. Go to `Broadcast Transaction` tab
2. Fill field with valid transaction
3. Change networks
4. Field will become invalid

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336720)
