### ISSUE TITLE
Sending via metamask on a different network gives invalid "Check Tx Status" button

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1581]
### Description of the Issue

Because Metamask/web3 locks the current node to the current web3 provider, if the web3 provider is on a different network than the user's previously selected node, then when they sign a transaction and the `Check Tx Status` notification pops up they'll have their network switched back to the original network. This causes the `Check Tx Status` page to not have the entry they were looking for since it was broadcasted on a different network. This can be fixed by using #1496 when `Check Tx Status` is clicked.

### Steps to Reproduce

1. Have your network be ETH
2. Have your metamask network be Kovan
3. Go to `View & Send` Tab
4. Send a transaction
5. Click on `Check Tx Status` button on the success notification
6. Your previously broadcasted transaction will not be displayed (broadcasted on kovan, but you're checking mainnet ATM)

**Comment by wbobeirne** [comment]
The query parameter won't work for custom web3 networks, so I'm not wild about that as a fix. I think it would be ideal if we could keep the user on the web3 network, but unlock it from being changed.

**Comment by wbobeirne** [comment]
On second thought, I think there's a more elegant solution here that involves firing a `changeNetworkRequested` action (added as a part of #1603) in the web3 sagas. I'd prefer to tackle this issue after that lands on develop.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336718)
