### ISSUE TITLE
Large amount of RPC calls causes lag on development build

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1582]
### Description of the Issue

Due how to shepherd handles finished rpc calls (https://github.com/MyCryptoHQ/shepherd/issues/32), after a large amount of RPC calls on development build + devtools open there will be noticeable FPS drops.

### Steps to Reproduce

1. Load up a deterministic wallet like Ledger
2. Open up dev tools
3. Cycle through the address tabs to generate a large amount of calls, or use the scan for tokens feature
4. Scroll around the page, observe noticeable FPS drops

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336716)

**Comment by ConnorBryan** [comment]
May institute some level of caching later on -- unable to repro on prod
