### ISSUE TITLE
When selecting a address to sign with in DeterministicWalletModal, balances are still loaded

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1584]
### Description of the Issue

We could avoid loading times and network requests by implementing a simpler version of the current modal that only displays addresses and does not perform any balance / token loading. Then the current version of the modal could extend that for cases where the user would want to know their balances.

### Steps to Reproduce

1. Go to `Sign And Verify Message` Tab
2. Log in with `Ledger` Wallet
3. Observe that ETH balances and Token balances are still being resolved (and are entries in the table) when they might not be needed

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336714)
