### ISSUE TITLE
Private key sometimes displays to browser console in private key access method

### ISSUE THREAD

**Issue by hahnmichaelf** [MyCryptoHQ/MyCrypto#1589]
### Description of the Issue

Using Private Key Method to access account sometimes displays private key to browser console.

### Steps to Reproduce

1. Navigate to https://beta.mycrypto.com/account.

2. Select the private key option.

3. Click the disclaimer checkboxes and 'Continue'.

4. Put in a random private key (I used: a00000000000000000000000000000000000000000000000000000000000000a)

5. Press F12 to open browser console.

![privatekey](https://user-images.githubusercontent.com/29407814/38952199-cd4d1b02-4318-11e8-8710-f2c0e0005f2d.PNG)

### Console Logs / Screenshots
![browser console displays private key](https://user-images.githubusercontent.com/29407814/38952228-e1c6047c-4318-11e8-9607-495ff9faed76.PNG)

**Comment by wbobeirne** [comment]
Yuck, it looks like Chrome _just_ added this warning. I can't believe they'd print that out on passwords... The worst part is, we have it set here. Set to `"off"`. I might consider this a bug in chrome.

For what it's worth, this message only shows up if you have verbose logging on, so most users won't see this, even if they open the console.

**Comment by tayvano** [comment]
I would definitely +1 for a comment on the bug in Chrome documenting this (as I'm sure there is a bug thread already for it).

According to https://stackoverflow.com/questions/47842910/after-upgrading-google-chrome-to-version-63-0-3239-84-i-have-started-receiving-e:

> If you don't have value for autocomplete just use autocomplete="foo" to make warning message disappear.

Since apparently "off" is not valid? Wat. 🤔

**Comment by HenryNguyen5** [comment]
So, playing around with this by adding `autocomplete="new-password"` gets rid of this log, but then a new log shows up under adding `username` for accessibility on forms, which then ends up revealing the field in the log again anyway.

We could implement a `Sensitive Input` component that takes user input, stores it in component state, and then instead replaces those values in the field itself with bogus values. This would mask the sensitive value from the DOM itself and instead keep it in component state.

**Comment by Azarielle** [comment]
No longer relevant since the removal of private key wallets on the web app.
