### ISSUE TITLE
[TREZOR] Uncaught promise when closing "Display Address on Trezor" window popup

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1590]
### Steps to Reproduce

1. Log in on `View & Send` tab
2. Log in with Trezor 
3. Click on `Display address on Trezor`
4. Close Trezor's popup window before it fully loads
5. Observe error in console

### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/6404866/38955775-9aa6f654-4323-11e8-9e05-a25b7ad4231c.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336712)
