### ISSUE TITLE
Address input allows for more than 42 characters

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1591]
### Description of the Issue

The maximum number of characters for a prefixed address is 42 characters. Allowing for input greater than that is invalid. Displaying this an an inline error to the user would be helpful for feedback. E.g. Display `The address needs to be either 40 or 42 characters` for prefixed or non-prefixed addresses.

### Steps to Reproduce

1. Go to a tab that uses the `AddressFieldFactory` component
2. Input more than 42 charcters
3. Field lets you continually input.

**Comment by wbobeirne** [comment]
Do ENS domains have a length limit? As unlikely as it is, could there be a 42+ char ENS domain?

**Comment by HenryNguyen5** [comment]
Ah you're right, we'd also have to check for the `.eth` ENS name TLD

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336710)
