### ISSUE TITLE
ETH Transaction History labels inaccurate

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1593]
### Description of the Issue

The transaction history labels for ETH network only show Ethplorer as `Tokens`, but all 3 websites support and list the wallet addresses tokens.

### Steps to Reproduce

1. Be on ETH network
2. Sign in `Send & View` tab
3. View Transaction History component
4. Labels are labelled inaccurately 

### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/6404866/38956688-592a0a06-4326-11e8-85bd-866aea56c5e2.png)

**Comment by wbobeirne** [comment]
We can probably get rid of ethplorer entirely, I think it's a holdover from when they were the only game in town for token balances.

**Comment by tayvano** [comment]
Perhaps just `via Etherscan` and `via Etherchain` and `via Ethplorer`? Keep it consistent and as clear and minimal as possible while still giving users options.

I think the same consistency will likely need to be applied to the message after you have sent a transactions.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336708)
