### ISSUE TITLE
QR Code label not centered

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1594]
The QR code display looks odd since its off centered and rectangle. It would look better if it was squared and centered

### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/6404866/38956859-def9694c-4326-11e8-8345-507416158803.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336706)
