### ISSUE TITLE
Loading the same language refreshes page

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1596]
### Description of the Issue

When a new language is selected, we reload the page so that the translations load properly. But when the same language is chosen twice (e.g. English -> English) this still triggers the refresh when nothing should happen

### Steps to Reproduce

1. Load site
2. Select same language as your current language
3. Observe site refresh despite no actual state change

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336702)

**Comment by ConnorBryan** [comment]
Fixed.
