### ISSUE TITLE
Clicking on the same tab/subtab remounts the same component again

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1597]
### Description of the Issue

Because of the current way we're doing routing, clicking on the same tab or subtab remounts the same component again, which can lead to extra network requests or loss of redux state

### Steps to Reproduce

1. Load site
2. Click on same tab or subtab twice

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336704)
