### ISSUE TITLE
Loading the same node fires off node change intent still

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1598]
### Description of the Issue

When clicking on the same node on the node dropdown, CHANGE_NODE_INTENT will still fire even though the node is the same, triggering the pending status indicator and extra network requests

### Steps to Reproduce

1. Load site
2. Click on node dropdown
3. Observe that the "pending" status indicator on the dropdown is triggered

**Comment by Azarielle** [comment]
No longer an issue since node refactor.
