### ISSUE TITLE
Consistent URL naming for tabs and subtabs

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1599]
### Description
Some tabs have naming that are consistent with their corresponding URL, but others are quite different. It would make it easier for users to recognize paths if they resembled the name of the tab its associated to.

### Steps to Reproduce

1. Load site
2. Mouse over each tab / subtab
3. Observe URL
4. Some tabs have consistent naming to their tab URL, but some dont

### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/6404866/38957929-c9abce4c-4329-11e8-9d1f-59b2d1d213d3.png)
![image](https://user-images.githubusercontent.com/6404866/38957956-e0359e0e-4329-11e8-805b-7f426c07e215.png)
![image](https://user-images.githubusercontent.com/6404866/38957980-ee253e48-4329-11e8-98cc-8724560810c7.png)

**Comment by wbobeirne** [comment]
We should also normalize path names (camelCase or dash-case) while we're at it.

As for View & Send, when did we remove "Account" from that anyway? I feel like it's not as clear anymore. I'd be more in favor of adding "Account" back in.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336700)

**Comment by ConnorBryan** [comment]
Part of route re-architecture.
