### ISSUE TITLE
Improve Error Messaging

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#160]
### This issue will serve as a list of potential improvements to error messaging across the application.

- [ ] "Transaction with the same hash was already imported" with red notification
   - **Better message**: "Transaction: ${txHash} has already been broadcast" with green notification
      - Additionally, show spinner in UI while TX is in mempool
      - Consider Moving Check TX Status (or a simplified version) to send view.
          - A mockup should be developed that would include a simplified Check TX Status in the Send View. Currently, users (including myself) are confused as to what action they should take when they see "Transaction with the same hash was already imported". If we can provide a status of the transaction directly on the send view, they can stay updated on the status of their broadcast tx (and not send another tx with the same amount as some users currently do). This will also help users who do not encounter an error, but still want to stay updated on the status of their transaction after it is broadcast. 
             - Error Case
                <img width="250" alt="screen shot 2017-09-01 at 11 19 16 am" src="https://user-images.githubusercontent.com/7861465/29982683-8d644a30-8f07-11e7-8999-2b8049f0c94e.png">
             - Success Case
                <img width="250" alt="screen shot 2017-09-01 at 11 19 22 am" src="https://user-images.githubusercontent.com/7861465/29982685-8d686732-8f07-11e7-926d-48937d1df5bc.png">
             - Tx Info
                <img width="250" alt="screen shot 2017-09-01 at 11 19 26 am" src="https://user-images.githubusercontent.com/7861465/29982684-8d6666f8-8f07-11e7-8fa1-e781a4725488.png">
             - Entire View
                <img width="250" alt="screen shot 2017-09-01 at 11 19 26 am" src="https://user-images.githubusercontent.com/7861465/29982785-f6fcd502-8f07-11e7-9b98-e2702a5d77e4.jpg">

- [ ] Don't have enough funds in your account
   - Error message: "Needed 2x got 0" with no Wei Label
   - Better Error Message: Include Wei Labeling, ???

**Comment by tayvano** [comment]
Lets go with:

> The transaction with TxHash ${txHash} has already been sent to the network and is waiting to be mined. 

> Account you are sending from does not have enough ETH. If sending tokens, you need ~0.01 ETH in your account to cover the [cost of gas](https://myetherwallet.groovehq.com/knowledge_base/topics/what-is-gas). If trying to send all your ETH, please use the "Send Entire Balance" button.

More updates: https://gist.github.com/tayvano/6c3967b05acfbad903c93d3098ed8762

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837159)
