### ISSUE TITLE
"Open an auction on MyCrypto V3" link for ENS does not prefill name properly

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1600]
### Description of the Issue

When searching for a name on the ENS tab, if the name comes up as available the user is prompted to go to v3 to open an auction. The link itself to go to the auction page has an invalid query parameter so the resulting V3 link does not prefil the name.

### Steps to Reproduce

1. Go to ENS tab
2. type in `mycrypto`
3. Check for availability
4. Click on `Open an auction on MyCrypto v3!`
5. Get taken to page
6. Observe name is not prefilled

### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/6404866/38958350-fff29f70-432a-11e8-8dec-cef12f36a1c1.png)

**Comment by wbobeirne** [comment]
Ah yes I'd forgotten to open an issue on MyCrypto.com for that. I added the query parameter just so that it'd be there when we were ready, but prefilling ens name was never a feature on the old site. This issue would be better suited over there.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336698)

**Comment by ConnorBryan** [comment]
ENS restructure.
