### ISSUE TITLE
Support struct returns / parameters on "Contracts" tab

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1604]
### Description of the Feature

Since the introduction of Solidity ABIv2, functions are now able to externally return structs. It would be nice to support this on site so we would be able to send structs in as parameters as well as return structs back to the user on the site.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336696)
