### ISSUE TITLE
Trim whitespace for inputs

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1605]
### Description of the Feature

To improve user UX, we should trim whitespace on both ends of any input field, since oftentimes when copy pasting a rouge whitespace will be introduced, causing an invalid field that's hard to see. A few places of where we might not want to do this is in sensitive fields such the password to a keystore file (but might be worth warning the user that there are whitespaces in their password)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778428277103401)

**Comment by ConnorBryan** [comment]
Being addressed.
