### ISSUE TITLE
Have "Custom" contract be a checkbox instead of a dropdown input for "Contracts" tab

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1606]
### Description of the Issue

Users that want to use custom contracts can currently just keep the dropdown blank, but if they decide to switch to the "Custom" selection in the dropdown midway through interacting with the contract (due to UI confusion from the dropdown still saying `Select a contract`) it'll clear the state of the component, making them restart again. It would be nice if "Custom" was instead just a checkbox, which then gets rid of the contract selection component entirely, leaving the user to fill in the contract's address and ABI.

### Steps to Reproduce

1. Go to "Contracts Tab"
2. Start filling in the address and ABI with a custom one
3. Switch the `Select Existing Contract` dropdown to "Custom"
4. Observe component state being cleared

### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/6404866/38960581-0201d5e4-4333-11e8-8736-8ecf5b4e8930.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336682)
