### ISSUE TITLE
Invalid ABI / JSON Interface does not outline the box as invalid

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1607]
### Steps to Reproduce

1. Go to `Contracts` tab
2. Enter in a valid contract address
3. Enter in an invalid JSON ABI
4. Observe that `Access` is greyed out, but the user has no feedback why ( ABI JSON should be outlined in red)
5. Observe that an invalid contract address does get outlined in red

### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/6404866/38960633-3bbc733e-4333-11e8-8627-a628afb400c6.png)

![image](https://user-images.githubusercontent.com/6404866/38960976-6192f78a-4334-11e8-9af3-c2e022d3fc95.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336684)
