### ISSUE TITLE
Update "Create New Wallet" warning banner to include Parity Signer

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1610]
### Description of the Issue

We list Parity Signer as a secure wallet, but in "Create New Wallet" we do not mention it

### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/6404866/38961771-165b12da-4338-11e8-9d3e-82f231d9a7fc.png)

**Comment by wbobeirne** [comment]
This will no longer be an issue once #1466 lands, so I'll just close this one out.
