### ISSUE TITLE
Typos in "Set Up Your Custom Node"

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1612]
### Description of the Issue

The title should instead be `Setup Your Custom Node`. Also, in the orange banner, it says "Your node must be HTTPS in order to connect to it via MyCrypto.com. You can download the MyCrypto repo & run it locally to connect to any node. Or, **get free** SSL certificate via LetsEncrypt" >> should be **get a free**

### Steps to Reproduce

1. Go to node dropdown
2. Select `Add a Custom Node`
3. Observe typos listed above

### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/6404866/38962171-0ad4933a-433a-11e8-9a58-b5f6149d1c50.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778428277103399)

**Comment by ConnorBryan** [comment]
Fixed.
