### ISSUE TITLE
Inconsistent Tab Naming

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1614]
### Description of the Issue

To a new user, short form names such as `TX` might be confusing to them especially with the full version of the word right beside the tab. We should keep `TX Status` expanded to `Transaction Status` or short form `Broadcast Transaction`

### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/6404866/38962320-b16c32f2-433a-11e8-8ed6-387e73fc721c.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778428277103397)
