### ISSUE TITLE
Capitalization / Additional information for "Broadcast Transaction" tab

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1615]
### Description of the Issue

The current description for the "Broadcast Transaction" tab is pretty poor, and is missing capitalization for "Send Transaction" (Paste a signed transaction and click 'send transaction'). It would be a significant improvement to user experience if we included a larger improvement on how to use the component and why the component exists. I.e. explain what cases this would be used in (knowledge base entry?) for things like transactions that were signed offline

### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/6404866/38962446-575b201a-433b-11e8-80d8-c1cf6fe84fd0.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778428277103395)
