### ISSUE TITLE
Current Ledger dependency unmaintained

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1616]
### Description of the Issue

Related to #921 

We currently depend on `ledgerco` which was a monolithic package that is now unmaintained. We should switch over to ledger's new packages hosted in their monorepo https://github.com/LedgerHQ/ledgerjs/tree/master/packages

This would also allow us to keep up to date with their packages, and handle transport layers much more easily (u2f vs nodehid), letting us implement hardware wallet signing for electron.

**Comment by wbobeirne** [comment]
Looks like we'll need to combine https://www.npmjs.com/package/@ledgerhq/hw-app-eth and https://www.npmjs.com/package/@ledgerhq/hw-transport-u2f to re-implement what we currently have, should be as simple as
```
import ledgerU2F from '@ledgerhq/hw-transport-u2f';
import ledgerEth from '@ledgerhq/hw-app-eth';

ledgerU2F.create().then(transport => this.ethApp = new ledgerEth(transport));
```

**Comment by HenryNguyen5** [comment]
Yeah, we can also dynamically swap between `@ledgerhq/hw-transport-u2f` and `@ledgerhq/hw-transport-hid` for electron enviroments
