### ISSUE TITLE
Interact with smart contract via cold storage (offline)

### ISSUE THREAD

**Issue by gernotpokorny** [MyCryptoHQ/MyCrypto#1624]
In MyCrypto you can send an offline tx by signing it offline and broadcasting it online. Can I also somehow interact with a smart contract in the same manner (eg. the kyber network contract)?

**Comment by dternyak** [comment]
Hi @gernotpokorny. 

Unfortunately, we don't support this today.

That said, we've already starting having discussions about supporting it. You can see more here: https://github.com/MyCryptoHQ/MyCrypto/issues/1495

I'll be closing this issue as a duplicate of #1495, but I definitely appreciate seeing the additional interest in this functionality, and we'll keep it in mind while developing our product roadmap.

**Comment by gernotpokorny** [comment]
Cool. Thx
