### ISSUE TITLE
Provide proxy interface with scheduled transactions

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#1626]
### Description of the Feature

One of the common cases mentioned when talking about EAC is sending a transaction for ICOs. However, with the current interface, a user might schedule the transaction, but have their tokens locked into the EAC contract. We'll need to implement an interface for proxying ICO tokens back to the user (or whatever address they choose.) You can see the function here: http://ethereum-alarm-clock.readthedocs.io/en/latest/transaction_request.html#proxy

A big challenge here is going to be helping the user know what to pass as data to send the right thing. We may do well to provide a specific interface for scheduling specific ICOs, or come up with a generic way of entering the ICO's token type and contract address, and generating the data for the user.

**Comment by wbobeirne** [comment]
Ah, the way proxy works actually makes this easier than I thought. It's a method you can call after the scheduled transaction has passed the execution window, so users won't screw themselves over by setting up the scheduled TX wrong. We could add a form for proxying to the TransactionStatus component if we determine the transaction is a scheduled one. Or we can just provide the contract ABI on /contracts, and let them call it themselves.

**Comment by PhABC** [comment]
Whitelists might be something users need to keep in mind, since they would need to whitelist their proxy contract (which is created when the tx is scheduled.Usually the whitelist process is done *before* the token sale contract is deployed, so the tx can't be scheduled (and proxy contract won't be created). Just nothing down something else we need to keep in mind with the EAC.

**Comment by kosecki123** [comment]
Whitelisting is very common as the way to keep KYC/AML in tact. 

Some ICOs provides the `BuyForReceipt(address receiver)` kind of methods where `receiver` is a whitelisted address. This cannot be guaranteed though.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336686)
