### ISSUE TITLE
Can't use Parity Signer on Firefox if Metamask is enabled

### ISSUE THREAD

**Issue by Tbaut** [MyCryptoHQ/MyCrypto#1628]
### Description of the Issue

Hey guys, Thibaut from Parity here.
When Metamask is installed on Firefox, the UI doesn't allow the user to use Parity Signer to access your wallet. The click on the icon just doesn't do anything. There are no console logs in the browser. The problem is not present in Chrome.

#### To make it fail
- Install Metamask for Firefox
- Make sure it's enabled (see the fox in the extension bar, no need to unlock it)
- Visit https://beta.mycrypto.com/account
- Click on Parity Signer... nothing happens

#### To make it work
- Go to Firefox extensions [about:addons](about:addons)
- Disable Metamask
- Go back to refresh MyCrypto beta page
- Click on Parity Signer... it works

### Description of Your Machine

- Firefox 59
- Linux (Ubuntu based)

### Console Logs / Screenshots

- No console error in Chrome.
- I can't open the console from Metamask to verify.
![image](https://user-images.githubusercontent.com/33178835/39008073-eceb2626-4407-11e8-95af-f6be91d39020.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/776566136827964)

**Comment by Tbaut** [comment]
FWIW Parity  chrome extension has beed deprecated. We now advise to use Metamask: https://wiki.parity.io/FAQ#how-to-use-parity-ethereum-chrome-extension-to-browse-a-web3-website
