### ISSUE TITLE
Consider using crowdin.com as language translation front-end  

### ISSUE THREAD

**Issue by sekisanchi** [MyCryptoHQ/MyCrypto#1630]
crowdin.com provides neat feature for crowd sourced translation team management, as LEDGER utiilze that for their apps, shown very bottom of this page https://www.ledgerwallet.com/apps/ethereum
for JSON language files.   
Looks like simple and handy than TRANSIFEX  based process.  Highly recommended to investigate, or kick bounty based work.

**Comment by dternyak** [comment]
Hey @sekisanchi 

Thank you so much for bringing this up!

We're already tracking this idea here https://github.com/MyCryptoHQ/MyCrypto/issues/1119, and will be investigating this in more detail after the launch of the new codebase.

I'm going to close this issue as a duplicate, but I really appreciate you taking the time to bring it up!
