### ISSUE TITLE
Disable ENS name resolving for non-eth networks

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1633]
### Description of the Issue

Currently, the ens resolver does not care what network it is on, it will attempt to resolve any ens name. To avoid user confusion, we should display an inline error such as (`Oops, this is specific to Ethereum and it's testnets. You are currently on the ${network} network`)

### Steps to Reproduce

1. Go to ETC network
2. Go to `View & Send` tab
3. Type in `mewtopia.eth`
4. Name still attempts to resolve, but displays 0x0 (as it should)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/776566136827962)
