### ISSUE TITLE
"Confirm transaction on hardware wallet" prompt appears twice on contracts interact

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1636]
### Steps to Reproduce

1. Go to `Contracts` tab
2. Go to `Interact` subtab
3. Use a contract that has methods that require a transaction
4. Use the a method that requires a transactions
5. Log in with a hardware wallet
6. Observe that the prompt shows twice

### Console Logs / Screenshots

![2018-04-19-162909_1524x455_scrot](https://user-images.githubusercontent.com/6404866/39016736-4d6e38c6-43ef-11e8-9d7f-3139da314488.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/776566136827960)
