### ISSUE TITLE
Broadcasting a transaction + attempting to send the same one again on a hardware wallet still shows signing status

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1642]
### Description of the Issue

We have checks in the sagas to make sure the user does not send the same transaction twice. They would get a notification along the lines of `This transaction has already been broadcasted`. The signing status component is not aware of such check, so it still visually shows the spinner even when the user cant continue on anyway.

### Steps to Reproduce

1. Go to `View & Send` tab
2. Use ledger sign in
3. Send a transaction
4. Click `Send Transaction` again without changing anything
5. Observe the `Signing Status` component still show up even though the user can't continue with broadcasting the transaction anyway

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/776566136827940)
