### ISSUE TITLE
Signing issues on Ledger Blue

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#1648]
Full discussion here: https://www.reddit.com/r/MyCrypto/comments/8dec4q/signing_message_does_not_seem_to_work_on_the/dxmtvbz/

**Comment by wbobeirne** [comment]
The line in question uses `as any` so I assume that that error happens for a good reason 🙄  https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/libs/wallet/deterministic/ledger.ts#L56

@HenryNguyen5 has a Ledger Blue, so he is probably best suited for testing this. But even if it's erroring on that code, that means there was an error in the first place.

**Comment by HenryNguyen5** [comment]
This actually isnt specific to the ledger blue, the error occurs when you try to sign an empty string
