### ISSUE TITLE
ASCIIfy contract data where possible

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#1650]
### Description of the Feature

Some contracts store human readable data as bytes16 / bytes32 etc. It'd be cool if in addition to printing out the hex, we also allowed you to view the ASCII version. Not sure if they should display next to each other, or be a toggle.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/776566136827942)
