### ISSUE TITLE
[beta] accept erc-681 for parity signer

### ISSUE THREAD

**Issue by ligi** [MyCryptoHQ/MyCrypto#1659]
It would be great if the parity signer flow could support erc-681 - currently I am seeing this:

![mycrypto_signer_erc681](https://user-images.githubusercontent.com/111600/39118534-eba1ef18-46e9-11e8-8d43-17cf53210ea1.png)

Background: I want to support this flow with [WallETH](http://walleth.org) - but I really do not want to show a QR-Code without context. 

ref: https://github.com/paritytech/parity-signer/issues/103

**Comment by wbobeirne** [comment]
Damn, we gotta make those error messages less obnoxious.

As for 681, that makes a lot of sense for the QR code generated by the site that the app signs, but I don't think it makes sense here in the unlock flow. 681 is for payments, not for identifying an address.

We'll just go along with whatever implementation is in parity-signer & https://github.com/Parity-JS/qr-signer, so I'm going to close this issue to funnel all discussion to the one you linked.

**Comment by wbobeirne** [comment]
Yeah I think context is always good, especially with QRs. Your point about, at the very least, prefixing with `0x` makes a lot of sense. But I'll defer to the Parity team on this, since they're in control of the app and packages used for this flow.

**Comment by ligi** [comment]
ack & thanks
