### ISSUE TITLE
Feature Request: Single click UI for "Get ETH from Faucet" for testnets

### ISSUE THREAD

**Issue by tayvano** [MyCryptoHQ/MyCrypto#1662]
When a user is connected to a testnet, display a button near their balance to get more test-ETH from a faucet. Could be a smart contract or just a API request.

Very low priority but a cool feature to have and pretty independent from most of the core code and therefore could be good intro task? 

We could either mine for a couple days on the testnets or I could reach out and get a bunch of test-ETH from people who already are test-ETH billionaires.

**Comment by wbobeirne** [comment]
This would be awesome! We'd definitely need to find a way to rate limit it though, to prevent abuse.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/776566136827944)
