### ISSUE TITLE
Feature Request: Recognize a user is using Metamask and suggest Metamask to access wallet

### ISSUE THREAD

**Issue by westvegh** [MyCryptoHQ/MyCrypto#1672]
Let me preface this by saying that I'm not a dev, so assuming this is feasible from a dev standpoint...

Under the "View and Send" tab, the UI should prompt/encourage/highlight using Metamask if the user's wallet is already unlocked via Metamask.

Give the opportunity to "Unlock without Metamask", which leads the user to the other options. 

User Story:
As a user that has Metamask installed, 
And I currently have a wallet unlocked,
MyCrypto should "highlight" Metamask as the primary method for accessing my wallet,
So that I am safely accessing my wallet

<img width="1438" alt="screen shot 2018-04-25 at 10 07 10 am" src="https://user-images.githubusercontent.com/23407603/39261165-7e1b172a-4870-11e8-8dc3-286c76bab1cd.png">

**Comment by westvegh** [comment]
@wbobeirne 
Oh nice, I didn't realize that. I'm suggesting that you go one step further though. Instead of just listing the Web3 provider, I'm recommending you list _only_ the Web3 provider (or display it in a more prominent way.)

Instead of the current header, "How would you like to....", it could say, "We noticed you're using MetaMask...." Include copy around safety, convenience, etc . . .

The content of the MetaMask box could be the same: "Connect & Sign via Your Browser or Extension"

Then for users that want to use a different method, they can press a link: "Use a different method (hardware, private key, etc . . .)"

I believe this is optimal for several reasons:

1. The more disconnected the user is from entering their private key, keystore, or mnemoinc, the better.
2. Not only is the web3 provider safer, the flow is so much simpler & convenient, at least in the case of MetaMask. And I don't think the average user knows this. They likely created their wallet using your service (generated a keystore/mnemonic/privatekey), and naturally, they're going to use one of those three to access it in the future. 

Just my two cents! Love the improvements so far.

**Comment by wbobeirne** [comment]
Personally, I alternate between my hardware wallet and MetaMask depending on what I'm doing, so I don't want to make decisions for the user just because they have MetaMask installed. We also have #1466 in the pipeline which should make the insecure options even less attractive.

I'm going to close this issue out as I think #1466 answers your main concerns about encouraging safer providers, hope that's alright!
