### ISSUE TITLE
Feature Request: "Remember Me" when using MetaMask

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#1674]
https://github.com/MyCryptoHQ/MyCrypto/issues/1672 is related.

I have had a few feature requests for persisting the MetaMask selection between sessions.

- [ ] Allow users to toggle a selection to persist metamask selection across tabs and sessions

**Comment by jspence425** [comment]
Would this mean you bypass the "access" screen?

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336694)
