### ISSUE TITLE
Refactor sagas to increase type safety

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1677]
With the introduction of TS 2.8, we're now able to extract types from inferences.
This allowed the creation of #1676, which now means we can infer all returned types from within sagas. Refactoring to use the above helper will reduce type fragility, and prevent types from being invalid. 

This was a common problem before as `yield` returns the type of `any`, so you would have to manually type each `yield` with the return type of the function, but if that functions return type ever changed then your type would now be invalid, and the compiler would not catch it.

```ts
/* Before */
function*  foo() {
 return 5;
}

function* bar() {
 const ret: number = yield call(foo) // have to manually type this
}

/* After refactor */
function*  foo() {
 return '5';
}

function* bar() {
 // this type is now invalid! 
 // But the compiler wont throw an error since typeof yield is "any"
 const ret: number = yield call(foo)
}
```

```ts
/ * With type inference #1676 * /

// import our type inference helper
import { ExtSaga } from 'redux-saga/effects'

/* Before */
// make sure we don't type the return type of this as `SagaIterator`
// it'll break type inference and return `never`
function*  foo() { 
 return 5;
}

function* bar() {
 // ret will be typeof 'number'
 const ret: ExtSaga<typeof foo> = yield call(foo) // type is now automatically extracted
}

/* After refactor */
function*  foo() {
 return '5';
}

function* bar() {
 // ret will be typeof 'string'
 const ret: ExtSaga<typeof foo> =  yield call(foo) // this type is still valid
}



```

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/776566136827946)
