### ISSUE TITLE
Can't offline sign non-mainnet tx

### ISSUE THREAD

**Issue by ulope** [MyCryptoHQ/MyCrypto#1681]
### Description of the Issue

Version tested: 1.0.0rc1

When using MyCrypto offline it's not possible to sign txs for anything but the mainnet. 

The reason is that it's impossible to switch to another Eth node due to the connection check preventing it. From that it follows that it's not possible to use anything else than the mainnet since the network id is coupled to the node selection.

### Steps to Reproduce

- Use MyCrypto on a system without internet connection
- Try to switch to anything that is not mainnet (ropsten, kovan, ...)
- See that it's not possible

**Comment by dternyak** [comment]
@wbobeirne Agreed.

Thanks for opening this @ulope! I'm sure there are plenty of others with a similar use-case.
