### ISSUE TITLE
[BUG-Beta] JSON Keystore is invalid

### ISSUE THREAD

**Issue by rstormsf** [MyCryptoHQ/MyCrypto#1691]
1. Go to https://beta.mycrypto.com/
2. Generate JSON Keystore
```json
{
  "version": 3,
  "id": "41e9531d-e880-4528-a4c4-30af71d78391",
  "address": "0x960818BA2E8760b9Ef3Ef37301143236cfEa9F0A",
  "crypto": {
    "ciphertext": "4198753b3d39237f8252d8243daeda8148083e975ca3147380573767e9fbb418",
    "cipherparams": {
      "iv": "c2631e1e7e4f5a9aa37816507d646d72"
    },
    "cipher": "aes-128-ctr",
    "kdf": "scrypt",
    "kdfparams": {
      "dklen": 32,
      "salt": "3d66439922f42187f7ee99e36b0821a9dc917c6ec3a70043869448276cf86b3c",
      "n": 8192,
      "r": 8,
      "p": 1
    },
    "mac": "cbd3436cd12d91db6703cc4359311dbf93c3ce44828ee5610672c0bfc964c7a7"
  }
}
```

Notice the `address` field,
it has mixed upper and lower case and it also  has `0x` at the start
Also `crypto` is lowercase

Valid JSON from Mew
```json
{
  "version": 3,
  "id": "b358a7e0-d455-4610-937f-89357a97ac0e",
  "address": "b506698581484572b6ccfbd6c976f0948775eace",
  "Crypto": {
    "ciphertext": "468277d6272f91037052e8a948904333b3b1fa61acc3947babd980e9d3823744",
    "cipherparams": {
      "iv": "886e6367b69084cd24fe2f9face3947b"
    },
    "cipher": "aes-128-ctr",
    "kdf": "scrypt",
    "kdfparams": {
      "dklen": 32,
      "salt": "8ae9cf58248f37184d51990d8a9ab7072438a9f1240e47fc9efc1bd130de8a63",
      "n": 8192,
      "r": 8,
      "p": 1
    },
    "mac": "1807ab330ec306dd5d164365a613d91c856c0da8c33c61dd1372349ffe3b1044"
  }
}
```
this  is valid  json from MEW

## How did I find it? 
I was trying to import it with parity 

![image](https://user-images.githubusercontent.com/9360827/39390533-b4fa4cc6-4a4a-11e8-92e7-47d15af50de8.png)

**Comment by HenryNguyen5** [comment]
Thanks for the bug report, @dternyak @wbobeirne looks like we have to have addresses unchecksummed and without the hex prefix.

**Comment by rstormsf** [comment]
The fix was very easy for me, I simply removed `0x` 

I'm not sure if case sensitivity is an issue. it worked fine with parity. `crypto` field also worked fine with lowercase.
Seems like the only problem with `0x`, but I'd double check on  the  JSON keystore standard on how this should be

**Comment by rstormsf** [comment]
Please note that when you use just Private key, and go to 
https://beta.mycrypto.com/account/info
and click on Generate a Keystore File, it generates correct file

**Comment by dternyak** [comment]
Thanks for the note @rstormsf!

You can see the proposed solution in action here: https://mycryptobuilds.com/36278bd8324d856fbfc238e5096bcbde1ea30928/#/generate/keystore

It'll be merged shortly unless we discover any issues with it.
