### ISSUE TITLE
Print Wallet button doesn't work in Electron

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#1692]
### Description of the Issue

Button does nothing, no console output.

### Steps to Reproduce

1. Generate keystore file
2. Click "Print Wallet"
3. Nothing 😢 

### Description of Your Machine

Windows 10

**Comment by bryanwb** [comment]
The issue is that `window.open` here https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/utils/printElement.ts#L25 returns null

It appears to be an issue w/ electron
https://github.com/electron/electron/issues/11471#issuecomment-352627083
