### ISSUE TITLE
BQX token should be named ETHOS

### ISSUE THREAD

**Issue by gilcn** [MyCryptoHQ/MyCrypto#1694]
The BQX (Bitquence) token, contract 0x5Af2Be193a6ABCa9c8817001F45744777Db30756, changed its name on november 2017 and is now called ETHOS.

See this links for further infos:
- https://www.ethos.io/2017/11/20/why-ethos/
- https://etherscan.io/token/0x5af2be193a6abca9c8817001f45744777db30756

**Comment by hahnmichaelf** [comment]
@gilcn Can you post this issue up in the Ethereum-Lists/tokens repository (https://github.com/ethereum-lists/tokens) for us please? We source our token information from there.

**Comment by gilcn** [comment]
Done!

https://github.com/ethereum-lists/tokens/issues/64

Thanks.
