### ISSUE TITLE
Token balance "try again" button doesn't work on initial scan

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#1701]
### Description of the Issue

The logic for re-fetching the balances bails out if they have no tokens attached to their wallet. So if the initial scan fails, the try again button is a no-op. @dternyak had caught this in the wild a bit back, but couldn't reproduce.

I took a stab at fixing it in branch `rescan` but haven't had a chance to do a thorough test before my machine started acting up. If the fix works, I think this should make it into the next RC.

### Steps to Reproduce

1. Open a new address in the send view that you haven't scanned with before
2. Initiate scan, cause it to fail somehow
3. Click "try again" button
4. Nothing happens

**Comment by dternyak** [comment]
Closed in #1708
