### ISSUE TITLE
Nonce gets wiped out on token change, isn't refetched

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#1702]
### Description of the Issue

This one's kind of tricky and I haven't been able to pin down precise steps, but sometimes when switching from ETH -> token or token -> ETH, the transaction gets reset (nonce included) but the nonce isn't re-fetched. I think this requires generating the transaction, but I'm not 100% sure. Either way, this doesn't happen easily, so I don't think it's a show-stopper.

### Steps to Reproduce

1. Unlock a wallet with a token balance
2. Fill out transaction (to address, amount)
3. Generate the transaction
4. Switch to token
5. Fill out transaction again (to address, amount)
6. Send button is disabled due to lack of nonce

### Actions Triggered

<img width="375" alt="screen shot 2018-04-30 at 5 08 00 pm" src="https://user-images.githubusercontent.com/649992/39455798-7621036a-4cb0-11e8-94c7-b8becee590fc.png">

### Disabled State

<img width="779" alt="screen shot 2018-04-30 at 5 00 39 pm" src="https://user-images.githubusercontent.com/649992/39455791-6bfc286a-4cb0-11e8-8588-269bc9c1272f.png">

**Comment by tayvano** [comment]
Have another report of this

"Nonce doesn't always re-fill in when sending transactions back-to-back. The user must manually press the refresh icon on the nonce thing. Especially hard to do if the user doesn't have the advanced options open."

Video of behavior: https://app.hyfy.io/v/abDI1dq7frn/#!/player

Please ping Taylor/Jordan to update user via twitter when complete: https://twitter.com/scottmberry/status/1004481904148561920

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/776566136827948)
