### ISSUE TITLE
Standardize All Input Types 

### ISSUE THREAD

**Issue by james-prado** [MyCryptoHQ/MyCrypto#1706]
### Description of the Issue

Currently, we don't really have a standard for how we write inputs or how they're displayed. Since the inputs were last updated, we've added a few new types of input: inputs with searchable dropdowns, multi column dropdowns, and a few general changes to all input types. To maintain consistent styles across all input types, and to make abstraction easier, it's time to update how we write our `<Input />` components.

### Proposed Changes

- develop a consistent style for all input types
- provide a consistent method for adding inline error messages to all input types
- encapsulate all input types into into individual components for ease of use
	- i.e. `<Input {...props} />`, `<InlineDropdown {...props} />`, `<SearchDropdown {...props} />`, `<InlineMsg {...props} />`, etc...
- standardize all error messages, and displayed them consistently across all inputs
	- error messages should be displayed inline, __not__ displayed via notification bar
	- example: <img width="726" alt="screen shot 2018-05-01 at 3 29 20 pm" src="https://user-images.githubusercontent.com/7861465/39492197-721d5986-4d54-11e8-9e72-9b7cdb814941.png">

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/778474646336692)

**Comment by ConnorBryan** [comment]
Part of UI rework.
