### ISSUE TITLE
Need documentation for how a community member can translate the new codebase

### ISSUE THREAD

**Issue by jspence425** [MyCryptoHQ/MyCrypto#1725]
Community members are reaching out to us to help translate, and we need a proper location to send them so they can get it going. It would be nice to have this documentation complete before we even go from Beta to Production so people can just start as soon as possible.

@balozar @tayvano @dternyak @wbobeirne @hahnmichaelf

**Comment by tayvano** [comment]
As an example, here are what the instructions I wrote for MEW back in the day:

<img width="879" alt="2018-05-07 at 4 31 38 pm" src="https://user-images.githubusercontent.com/7924827/39730069-44223028-5214-11e8-94b4-0804b8841899.png">

**Comment by dternyak** [comment]
@tayvano Do you have a link to this article? I think we can just change a few lines, it's basically the same but with translations housed in https://github.com/MyCryptoHQ/MyCrypto/tree/develop/common/translations/lang

**Comment by tayvano** [comment]
It's about halfway down the excessively long readme here:

https://github.com/kvhnuke/etherwallet/blob/mercury/README.md

**Comment by Azarielle** [comment]
This already exists? https://github.com/MyCryptoHQ/MyCrypto/wiki/Contributor-Guidelines#providing-translations

**Comment by dternyak** [comment]
Thanks for the reminder @Azarielle! @jspence425 I'm going to close this, as we should be able to point users to the Contributor Guidelines pretty easily. Let me know if there's anything else you think we need to add to it.

**Comment by tayvano** [comment]
Oh sweet! 

@Azarielle Can we get this copied & pasted into the new knowledge base so that I can search for it. I know I will never remember this link in the future when we are encouraging our translator contributors.
