### ISSUE TITLE
Encoding of data field under Contracts is wrong

### ISSUE THREAD

**Issue by GoldenDave** [MyCryptoHQ/MyCrypto#1726]
### Description of the Issue

Data field of contract gets ascii encoded - 0 -> 0x30 - see in log section

### Steps to Reproduce

Contracts / Consensys wallet enter data as below 

### Description of Your Machine

Mac / OSX 10.11.6 / Google Chrome Version 66.0.3359.139 (Official Build) (64-bit)

### Console Logs / Screenshots

contract - consensys multisig @  0x0F4a28085713c1a5DEdc5D6f471c79AFe2d9321e

function : "Submit Transaction" with data 
address : 0xba2184520A1cC49a6159c57e61E1844E085615B6
value : 0
data : 0xa9059cbb0000000000000000000000005c842a4f93bbd06b73a69c5cb12a1430c6f37ba30000000000000000000000000000000000000000000000000000067e6929e800

{
  "value": "0x0",
  "data": "0xc6427474000000000000000000000000ba2184520a1cc49a6159c57e61e1844e085615b600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000008a30786139303539636262303030303030303030303030303030303030303030303030356338343261346639336262643036623733613639633563623132613134333063366633376261333030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030363765363932396538303000000000000000000000000000000000000000000000",
  "to": "0x0f4a28085713c1a5dedc5d6f471c79afe2d9321e",
  "nonce": "0x75",
  "gasPrice": "0x77359400",
  "gasLimit": "0x186a0",
  "chainId": 1
}

---

**Comment by dternyak** [comment]
Thanks for your report. We'll be issuing a fix immediately.

**Comment by dternyak** [comment]
@GoldenDave Can you confirm the proposed fix here should solve this issue?

https://github.com/MyCryptoHQ/MyCrypto/pull/1731

You can see a live staging environment at this commit at 66565217b70b32a796f976b6f12cfef7d16441d1

**Comment by dternyak** [comment]
@GoldenDave Feel free to message here or dt AT mycrypto.com should you determine that our fix does not solve your issue. 

Best,
Daniel

**Comment by GoldenDave** [comment]
Will test - no decent internet ATM.

**Comment by GoldenDave** [comment]
Consensus Multisig @ `0xc03281af336e2c25b41ff893a0e6ce1a932b23af`
submitTransaction
address : `0xba2184520A1cC49a6159c57e61E1844E085615B6`
value : 0
data :  `0xa9059cbb0000000000000000000000000f4a28085713c1a5dedc5d6f471c79afe2d9321e0000000000000000000000000000000000000000000000000000b5e620f48000`

=>

"data": `0xc6427474000000000000000000000000ba2184520a1cc49a6159c57e61e1844e085615b6000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000`,

The same transaction under MEW gives
"data"
`0xc6427474000000000000000000000000ba2184520a1cc49a6159c57e61e1844e085615b6000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000044a9059cbb0000000000000000000000000f4a28085713c1a5dedc5d6f471c79afe2d9321e0000000000000000000000000000000000000000000000000000b5e620f4800000000000000000000000000000000000000000000000000000000000`

**Comment by GoldenDave** [comment]
data : command to multisig (submitTransaction) followed by data and some trailing zeroes.
```
0xc6427474
000000000000000000000000ba2184520a1cc49a6159c57e61e1844e085615b6
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000060
0000000000000000000000000000000000000000000000000000000000000044
a9059cbb
0000000000000000000000000f4a28085713c1a5dedc5d6f471c79afe2d9321e
0000000000000000000000000000000000000000000000000000b5e620f48000
00000000000000000000000000000000000000000000000000000000
```
(last line all zeroes just pads to number of words I guess - not necessary)
