### ISSUE TITLE
Right click context menu doesn't work in Electron

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#1738]
### Description of the Issue

Right clicking in the app doesn't pop up the typical context menu. For some people, this is how they prefer to copy and paste, so we should try to add this back in. A module like https://github.com/sindresorhus/electron-context-menu should do the trick.

### Steps to Reproduce

1. Open Electron app (in Windows only?)
2. Right click
3. No menu

### Description of Your Machine

Windows 10

**Comment by bryanwb** [comment]
I should have a PR ready for this early next week
