### ISSUE TITLE
Waiting on MetaMask - Nothing Happens

### ISSUE THREAD

**Issue by Azarielle** [MyCryptoHQ/MyCrypto#1741]
---

If you've experienced a bug, please provide the following information:

### Description of the Issue

When the MetaMask extension is having problems connecting to the ETH network, when you select "access wallet with MetaMask" nothing happens. Would prefer if it went to the next page where it asks to connect to MetaMask and says something to tell me that MetaMask is having connection problems. I had to manually open up MetaMask to see that it was having problems in order to figure out why MyCrypto wasn't taking me to the next page to connect to MetaMask. 

### Console Logs / Screenshots

![sharex_2018-05-04_18-11-25](https://user-images.githubusercontent.com/25834495/39888767-d88c58f0-5463-11e8-9e0e-295ae6bf2bad.png)
![image](https://user-images.githubusercontent.com/25834495/39888782-e2e70782-5463-11e8-8772-cce3f67973ff.png)
Nothing happens, no warning, just sits here. 

---

**Comment by tayvano** [comment]
I just encountered this issue as well (but while using Peepeth) and fixed it by switching to Ropsten and then switching back. I'm wondering if this is due to a MetaMask update, not an update on our end?
