### ISSUE TITLE
Sending Transaction - Amount field

### ISSUE THREAD

**Issue by Azarielle** [MyCryptoHQ/MyCrypto#1752]
---

If you've experienced a bug, please provide the following information:

### Description of the Issue

Trying to type numbers into the "Amount" field, the letter e is accepted
Can also have multiple decimals

### Steps to Reproduce

1. Unlock wallet
2. Go to send transaction
3. try to type in letters - only e will be logged then you can also add numbers
4. type in multiple decimal points with numbers

### Description of Your Machine

Chrome, Windows 10

### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/25834495/39948602-c38bad7a-5544-11e8-8339-0dfb0deb3ce4.png)

![image](https://user-images.githubusercontent.com/25834495/39948648-02a3eb26-5545-11e8-83f7-38ef61c25624.png)

---

**Comment by ConnorBryan** [comment]
"e" is a valid number input. All "number" fields need to be moved to "text".
