### ISSUE TITLE
When gas limit is too low

### ISSUE THREAD

**Issue by Azarielle** [MyCryptoHQ/MyCrypto#1757]
---

If you've experienced a bug, please provide the following information:

### Description of the Issue

When I manually input a gas limit that is too low, the calculation of the equivalent price in USD isn't calculated, instead it shows that it is loading and fails to load even after waiting a long time. An error should be given instead of just loading forever.  (When gas limit is reasonable, the calculation of the equivalent price in USD is shown almost instantly)

### Steps to Reproduce
1. Unlock wallet
2. Go to advanced options for sending a transaction
3. Input a low gas limit (keep gwei normal)

### Description of Your Machine

Windows 10, Chrome

### Console Logs / Screenshots
![image](https://user-images.githubusercontent.com/25834495/39949916-f5d8ab0a-554b-11e8-8bee-91ffacb0ef3d.png)

(Console logs or screenshots go here, if applicable)
![image](https://user-images.githubusercontent.com/25834495/39949910-f04dce04-554b-11e8-9348-aed71b5e7be7.png)

---

If you're suggesting a feature, make sure someone hasn't already posted it. If
no one has, please provide the following information:

### Description of the Feature

(Your description goes here)

### Example(s) of Feature

(If another product or app is doing this, please link it)

**Comment by HenryNguyen5** [comment]
Related to #1706  #901

**Comment by ConnorBryan** [comment]
There have been changes since this issue that do not show the calculation if that field is invalid, though it is still not informative for the user. I recommend using 

https://github.com/MyCryptoHQ/MyCrypto/issues/1706

as an overhaul to inputs, which should target this story too.
