### ISSUE TITLE
Switching metamask accounts while "Signed in" does not change wallet context in state

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1771]
### Description of the Issue

When switching between metamask accounts and being "logged" in, the state does not update corresponding to reflect the new wallet. We should either refresh the page on account switch, or update the wallet context.

### Steps to Reproduce

1. Make two metamask accounts
2. Log into `View & Send` tab with a metamask account
3. Switch accounts
4. Observe that the wallet address does not change on the top right corner
![2018-05-12-164525_370x370_scrot](https://user-images.githubusercontent.com/6404866/39961433-e6ca4764-5603-11e8-8ee6-e5465a2965db.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/776566136827920)
