### ISSUE TITLE
Request Payment - Amount can be 3.4.56.6

### ISSUE THREAD

**Issue by Azarielle** [MyCryptoHQ/MyCrypto#1789]
---

If you've experienced a bug, please provide the following information:

Amount field for Request payment

### Console Logs / Screenshots
![image](https://user-images.githubusercontent.com/25834495/40032929-1fc17224-57c4-11e8-83d6-539d1b5d11cd.png)

---

**Comment by ConnorBryan** [comment]
I've opened a PR for making the field show invalid, but I believe

https://github.com/MyCryptoHQ/MyCrypto/issues/1706

should be used in order to relate that information to the user.
