### ISSUE TITLE
Swap support: should be forwarded at same time to ShapeShift

### ISSUE THREAD

**Issue by Azarielle** [MyCryptoHQ/MyCrypto#1795]
---

If you've experienced a bug, please provide the following information:

### Description of the Issue

For the support contact, the orange button and the link underneath it, the email should be forwarded to both MyCrypto support and ShapeShift at the same time. Right now, the email goes only to support@mycrypto, but as soon as support gets it, it gets forwarded to ShapeShift right away. So to make it easier, both emails for MyCrypto and ShapeShift should be included. 

### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/25834495/40035601-79dfa652-57d0-11e8-9019-9e23fa69fce1.png)

---

**Comment by dternyak** [comment]
@tayvano Can you confirm / suggest what additional email should be added?

**Comment by tayvano** [comment]
To field should be

support@shapeshift.zendesk.com, support@mycrypto.com
