### ISSUE TITLE
Wrong version ? (1.0.0. latest release)

### ISSUE THREAD

**Issue by repsorp** [MyCryptoHQ/MyCrypto#1805]
Ubuntu 16.04

Last version 1.0.0 has been installed:
https://github.com/MyCryptoHQ/MyCrypto/releases/download/1.0.0/linux-x86-64_1.0.0-alpha.4_MyCrypto.AppImage

Keeps on asking me to update:
![capture du 2018-05-15 19-41-04](https://user-images.githubusercontent.com/6297032/40074099-09197e4e-5879-11e8-9a90-6f956ba2486a.png)

**Comment by dternyak** [comment]
Thanks for the heads up @repsorp! We had an off-by-one error on the filename ;).

This should be all fixed up now. Give it a few minutes and then close + reopen the desktop application. You shouldn't get the warning anymore.

**Comment by repsorp** [comment]
Fine thanks
One last thing... ;-)
![a](https://user-images.githubusercontent.com/6297032/40076884-61db6518-5880-11e8-9cb6-58d87eb5ee5b.png)

**Comment by dternyak** [comment]
yup, that looks correct! :)
