### ISSUE TITLE
Possible to unlock without an address selected

### ISSUE THREAD

**Issue by Mrtenz** [MyCryptoHQ/MyCrypto#1812]
### Description of the Issue

In the "Select an Address" pop-up after unlocking with a mnemonic phrase or hardware wallet, it is possible to unlock without any address selected, causing a `Wallet not found` error.

### Steps to Reproduce

1. Access a hardware wallet/mnemonic phrase
2. Select an address in the pop-up
3. Select a different derivation path
4. Click 'Unlock'

### Description of Your Machine

Google Chrome 66.0.3359.139 64-bit, Arch Linux

### Console Logs / Screenshots

[https://imgur.com/a/AXstx24](https://imgur.com/a/AXstx24)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/776566136827897)
