### ISSUE TITLE
Update "U2F Not Supported" Error Message

### ISSUE THREAD

**Issue by tayvano** [MyCryptoHQ/MyCrypto#1816]
"Just ran across your excellent video on registering EOS tokens using Ledger Nano S - great job! That said, I've run into an error mesg on mycrypto - "Error: U2F not supported" - so could not connect. Any suggestions? Thanks!"

via https://twitter.com/JLWade4/status/997528861926715394

---

**"U2F not supported"**

could be improved to read

**"The U2F standard that hardware wallets use does not seem to be supported by your browser. Please try again using Google Chrome."**

More inspiration on the subject 😉: https://webflow.com/blog/how-not-to-write-an-error-message

**Comment by falkonprods** [comment]
Also getting this on July 6
