### ISSUE TITLE
Parity Signer Wallet creation in app - Seed recovery is 11 words

### ISSUE THREAD

**Issue by SharonManrique** [MyCryptoHQ/MyCrypto#1818]
### Description of the Issue

If you create a new wallet in the Parity Signer app, you are given a recovery phrase that is 11 words long. No where in the app does it let you import an already existing wallet with the phrase. The recovery phrase is also not valid in MyCrypto or MetaMask since the phrase needs to be 12 words long. Where is one suppose to recover the wallet created on the app?

### Steps to Reproduce

Create a new wallet on the Parity signer app 

### Console Logs / Screenshots

(Console logs or screenshots go here, if applicable)
![image](https://user-images.githubusercontent.com/25834495/40261252-84b7f70a-5acd-11e8-9c4f-06fd8fd6d786.png)
![image](https://user-images.githubusercontent.com/25834495/40261257-8c23fda4-5acd-11e8-877d-058d2fadfe5a.png)
![image](https://user-images.githubusercontent.com/25834495/40261281-b985ac34-5acd-11e8-899b-8b97d802b22c.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/776566136827893)

**Comment by wtzb** [comment]
Closing - newer Parity Signer versions use 24-word recovery phrases.
