### ISSUE TITLE
Bring back the "Latest!" button/tab

### ISSUE THREAD

**Issue by jspence425** [MyCryptoHQ/MyCrypto#1819]
It's beneficial overall and especially from a marketing standpoint to have a link to important updates/blogs/etc. in the header.

**Comment by tayvano** [comment]
For reference

<img width="1070" alt="2018-05-25 at 2 01 44 pm" src="https://user-images.githubusercontent.com/7924827/40566150-3870b588-6024-11e8-8cf8-59329ee5e0f4.png">

**Comment by james-prado** [comment]
I believe new plan for this issue is to resolve it in the navigation redesign.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/776566136827891)
