### ISSUE TITLE
Creating Keystore Wallet - Identicon does not display

### ISSUE THREAD

**Issue by Azarielle** [MyCryptoHQ/MyCrypto#1824]
### Description of the Issue

When you create a new wallet using Keystore file method, the Identicon is not loaded on the paper wallet, even when you download it. It does not appear. 

### Steps to Reproduce
Create a New wallet via Keystore file
### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/25834495/40273941-a0177af4-5b98-11e8-999d-c696d6c6a270.png)

**Comment by tayvano** [comment]
We just got another report of this from a user (Brian).

> However, when I do generate a wallet and then the paper wallet, the identicon is empty, just a gray circle. I looked at some paper wallets I've generated in the past and they all have identicons.

We should update him when this is resolved.

**Comment by Azarielle** [comment]
@tayvano we can update the user now that this is fixed in next launch. I would do it, but I don't know where the report came in from.

**Comment by tayvano** [comment]
Found him in Front 👍

Thanks Sharon! 💖
