### ISSUE TITLE
Show MyCrypto URL on payment requests tab

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#1826]
### Description of the Feature

The EIP 687 URL standard is probably going to get adopted more and more, but I think to make the request payment tab more useful, it'd be nice to also display a MyCrypto URL with all of the parameters encoded. It might also alleviate #1817 if both are labeled, one being EIP 687 url, and one being MyCrypto URL.

**Comment by dternyak** [comment]
Just to confirm, you mean [EIP 681](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md) correct?

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/776566136827881)
