### ISSUE TITLE
Show online status of a node in custom node modal 

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1828]
### Description of the Feature

To improve UX, we should show a symbol similar to the online symbol we show at the top of the site 
![2018-05-21-184015_431x50_scrot](https://user-images.githubusercontent.com/6404866/40333424-6a14852a-5d26-11e8-90d1-7cac3001ed20.png) when the user completes enough form inputs. That way they can know the node will be connected to successfully before adding the custom node and later being notified if it was successful or not

**Comment by gaia** [comment]
I second this. Show selected node PLUS whether the selected node is connected.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/776566136827879)
