### ISSUE TITLE
Resolve ENS for View Address Only unlock

### ISSUE THREAD

**Issue by Astrantia** [MyCryptoHQ/MyCrypto#1835]
https://i.imgur.com/KnX1sMb.png
I remember posting this issue back when you hadn't moved from MEW to MYC, but it's still not fixed.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/776566136827877)

**Comment by Azarielle** [comment]
[Added to Jira](https://mycrypto.atlassian.net/secure/RapidBoard.jspa?rapidView=24&projectKey=ENSX&view=planning&selectedIssue=ENSX-8)

**Comment by Astrantia** [comment]
@ConnorBryan Why did you close this issue?
