### ISSUE TITLE
Unable to Unlock with non-MetaMask Web3 Wallet

### ISSUE THREAD

**Issue by EvilJordan** [MyCryptoHQ/MyCrypto#1841]
### Description of the Issue

When using Toshi mobile wallet and attempting to unlock via Web3, an "Unlock your Web3" dialogue appears with the only options being, "Connect to MetaMask" and "Download MetaMask".

I assume this means MyCrypto does not support any Web3 compatible wallets other than MM.

### Steps to Reproduce

Click on the Web3 unlock button when using a mobile wallet (like Toshi or Cipher).

**Comment by EvilJordan** [comment]
I haven't dug deeply in to the MyCrypto code, but I would assume it's `common/components/WalletDecrypt/WalletDecrypt.tsx` that is the issue since when browsing using an interface like Toshi, the wallet is already unlocked and one shouldn't see the "Unlock your Web3" and "Connect to MetaMask" buttons.

Oversimplifying here, but it may just be an issue of detecting if the web3 wallet is already unlocked before prompting to Connect to MetaMask. There's also the added use-case of a web3 browser having multiple wallets and offering the user a chance to pick which one they'd like to use.

**Comment by Azarielle** [comment]
Referenced in another open issue https://github.com/MyCryptoHQ/MyCrypto/issues/2060, since they're similar, this one is being close to clean up the backlog.
