### ISSUE TITLE
Legacy "Sign Message" Link in Footer redirects to New Site

### ISSUE THREAD

**Issue by EvilJordan** [MyCryptoHQ/MyCrypto#1842]
It's all in the title!

The old sign message at least worked with non-MetaMask web3 wallets (except Cipher: https://github.com/MyCryptoHQ/MyCrypto/issues/1527), so it would be nice to still be able to access it.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/775227584579191)
