### ISSUE TITLE
Sending Token - Can't send 0.000001 

### ISSUE THREAD

**Issue by Azarielle** [MyCryptoHQ/MyCrypto#1850]
### Description of the Issue

Can't send a value of 0.000001 token, (Accelerator Token), you can though on legacy

**Comment by HenryNguyen5** [comment]
Related to #1754

**Comment by tayvano** [comment]
Related

https://twitter.com/DigboLuigi/status/1000106546658004998?s=19

**Comment by skubakdj** [comment]
@Azarielle I'm having trouble replicating. I grabbed some tokens and was able to put a TX through of `0.000001` ACC. Can you confirm you still have the issue?
