### ISSUE TITLE
windows_1.0.0-alpha.3_MyCrypto version displays 'Your Alpha Build Has Expired'

### ISSUE THREAD

**Issue by ptrkshv** [MyCryptoHQ/MyCrypto#1851]
### Description of the Issue

The windows_1.0.0-alpha.3_MyCrypto version displays a message 'Your Alpha Build Has Expired' after installation.

### Steps to Reproduce

1. Downloaded the MyCrypto alpha version from https://download.mycrypto.com/
2. Installed it
3. The MyCrypto alpha version installed successfully. Then, it opened automatically and displayed the message 'Your Alpha Build Has Expired'
4. Clicked 'Download a New Build' button from the opened MyCrypto window.
5. Downloaded the MyCrypto alpha version from this Github
6. Installed it
7. See point 3.

### Description of Your Machine

Ran MyCrypto on Windows 10 Pro, Version 1709, OS Build 16299.431

### Console Logs / Screenshots

![20180525-mycrypto-error](https://user-images.githubusercontent.com/35541334/40555521-18a80106-6052-11e8-9ec3-d684cd4d4891.png)

**Comment by tayvano** [comment]
We *just* pushed new builds to https://download.mycrypto.com/ that should resolve this issue. Can you please let me know if it doesn't?

Thank you!
