### ISSUE TITLE
[Desktop App] Add a fourth download button for the OS that you are visiting the page from.

### ISSUE THREAD

**Issue by jspence425** [MyCryptoHQ/MyCrypto#1854]
Confusing for users when they don't realize the big Download button is for the OS they're on. They think that the Desktop App is not supported for their OS because they don't see their OS in the center with the other Download buttons.

![screen shot 2018-05-25 at 3 22 25 pm](https://user-images.githubusercontent.com/26891718/40568452-73e74c3e-602f-11e8-8851-6ba0b3748d9b.png)

<img width="1364" alt="screen shot 2018-05-25 at 3 18 11 pm" src="https://user-images.githubusercontent.com/26891718/40568441-68ad2d84-602f-11e8-8310-3d548645740d.png">

**Comment by tayvano** [comment]
https://github.com/MyCryptoHQ/download.mycrypto.com/pull/23
