### ISSUE TITLE
cocacola ENS name is shown as available in Ropsten when in fact it is already reserved.

### ISSUE THREAD

**Issue by fjrojasgarcia** [MyCryptoHQ/MyCrypto#1855]
### Description of the Issue

`cocacola.eth` ENS name is shown as **available** in Ropsten when in fact **it is already reserved**.

### Steps to Reproduce

1. Open -> https://mycrypto.com/ens
2. Select Ropsten as working network.
3. Search by `cocacola`.

Your search **result should be**: 

```
cocacola.eth is already owned:
Owner: 0x796df1a602c3e910cabadea6a4c2573c38e56b54
```

But **you get**:
`cocacola.eth is available`

### Description of My Machine
Reproduced in:

- Opera `53.0.2907.68`
- Chrome `66.0.3359.181` (Build oficial) (64 bits)
- Linux Mint `18.3` (x86_64; X-Cinnamon)

--

### Screenshot
![2018-05-26 02-18-42_mycryptoensfailure](https://user-images.githubusercontent.com/5104824/40570450-57be8f16-608b-11e8-9d88-50f16e72ab53.png)

#### Proof of correct operation with geth
![2018-05-26 02-26-06_mycryptoensgeth](https://user-images.githubusercontent.com/5104824/40571011-a4a13daa-6091-11e8-8a55-400da5f455c4.png)

---

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/775227584579189)

**Comment by Azarielle** [comment]
Can not reproduce bug. Closing.
