### ISSUE TITLE
Shapeshift no longer loads rates in restricted regions

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#1858]
### Description of the Issue

Shapeshift used to load rates, but not allow for swaps to happen in restricted regions. Now it blocks the rates request as well.

### Steps to Reproduce

1. Be in NYC
2. Load Swap
3. Get error

### Console Logs / Screenshots

<img width="1440" alt="screen shot 2018-05-28 at 1 38 47 pm" src="https://user-images.githubusercontent.com/649992/40624795-9e854e1a-627c-11e8-8a9e-de33cd7ec659.png">

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/775227584579185)
