### ISSUE TITLE
Parse custom node information from query string parameters 

### ISSUE THREAD

**Issue by skubakdj** [MyCryptoHQ/MyCrypto#186]
It might be valuable to have better integration with third-party node providers that are either private or temporary, and thus wouldn't make it into the default node list dropdown on MEW. 

One way to accomplish this would be to have MEW read from query string params on boot and inject any valid nodes it finds into the node list. So for example, something like `myetherwallet.com/?defaultNodeAddr=rpc.icocrowdsale.com&defaultNodeName=ICO+Crowdsale` would add `ICO Crowdsale` to the dropdown, make it the default, and send RPC requests to `rpc.icocrowdsale.com`.

Two potential benefits off the top of my head:

 - It would allow our friends over at [QuikNode.io](https://quiknode.io/)  (or any other private node provider) to offer a link to MEW with their customer's node info baked in.
- ICOs could spin up their own cluster of nodes and serve up a MEW link specific to their crowdsale that uses their backend by default.

**Comment by HenryNguyen5** [comment]
I'll address this in a PR today that will offer the back-end functionality to implement this.

**Comment by dternyak** [comment]
@HenryNguyen5 To confirm, this still needs to be implemented correct?

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837157)
