### ISSUE TITLE
Add Google Site Verification to head

### ISSUE THREAD

**Issue by tayvano** [MyCryptoHQ/MyCrypto#1864]
`<meta name="google-site-verification" content="dRWkvANAUNAhNyMnTyc7M7S3lnucotMY8j8R-gsZhbo" />`

Again, reference https://legacy.mycrypto.com/'s head for the stuff we need to include in our head.

**Comment by dternyak** [comment]
I've just opened https://github.com/MyCryptoHQ/MyCrypto/issues/1864. I believe @james-prado took care off porting previous SEO considerations (various meta tags). Please let me know if there are any other specific additions we want!

**Comment by tayvano** [comment]
Just confirmed that this is working on beta.mycrypto.com and monerovision so we should be good. Thanks James and DT!
