### ISSUE TITLE
[UI] Monero Ledger Views

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#1868]
As part of an on-going goal of supporting Monero via Ledger's U2F support, we will begin building views while the logic (and especially signing) is getting researched and implemented.

- [ ] Create a Monero specific view with Ledger, potentially soon to be Trezor hardware wallet support. Monero will be added to the dropdown as a new network option. This task is NOT for the JS logic/implementation, only the un-wired views.

Initially, one view should suffice. In it, we'll include
1. A method for viewing balance (or at least as much is possible via view-keys only)
2. Receiving address
3. Form for sending
      - to address
      - amount 
      - fee
      - payment id
4. Redesigned wallet unlock view specific for Ledger-only unlock.

for a live example of the form, https://mymonero.com/ might be a good reference.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/775270102199213)
