### ISSUE TITLE
Incorrect gas limit estimation when sending to contract

### ISSUE THREAD

**Issue by tayvano** [MyCryptoHQ/MyCrypto#1873]
### Description of the Issue

The gas limit estimated when sending to a contract is not always correct 

### Steps to Reproduce

1. Go to send a transaction via MyCrypto

2. Enter the address `0x37f25bd26848cf02614c29338dd71a4d03b62218`

3. A gas limit of `21065` is estimated

4. If you send with this gas limit, the transaction will fail

For reference, this is the gnosis multisig wallet.

MyEtherWallet estimates `22511` 

MetaMask estimates `33766`.

This essentially makes MyCrypto unusable for sending to certain contracts and makes MEW/MetaMask a better choice. Sending with a gas limit of `22511` results in a successful transaction.

**Comment by HenryNguyen5** [comment]
We need to add `VALUE_FIELD_SET` as an action that'll fire off gas estimation
https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/sagas/transaction/network/gas.ts#L48

**Comment by tayvano** [comment]
Another report. We should update him when fix is live

https://twitter.com/LembleAugusto/status/1002656458796879872?s=19

**Comment by dternyak** [comment]
This will go into the next sprint @tayvano
