### ISSUE TITLE
Report of keystore files not opening properly on new MyCrypto.com (needs more info)

### ISSUE THREAD

**Issue by tayvano** [MyCryptoHQ/MyCrypto#1879]
> hey taylor.

> just an FYI — the new my crypto site doesn’t open keystore files properly

> says password failed

> but same keystore works fine on old mycrypto and MEW

That's all I've got.

**Comment by Azarielle** [comment]
No longer relevant since accessing private key wallets on the web app does not exist anymore. Closing.
