### ISSUE TITLE
Auto-parse ENS lookups to remove '.eth' instead of searching for .....eth.eth

### ISSUE THREAD

**Issue by tayvano** [MyCryptoHQ/MyCrypto#1889]
<img width="755" alt="2018-06-01 at 2 54 55 pm" src="https://user-images.githubusercontent.com/7924827/40865144-cc73213a-65ab-11e8-85cb-49f7decc2cc6.png">

**Comment by tayvano** [comment]
Actually, we shouldn't even display that it's available as it's not a valid domain name.....

**Comment by ConnorBryan** [comment]
After speaking with @tayvano in Slack, this issue can be resolved by not allowing period delimiters in the textbox until https://github.com/MyCryptoHQ/MyCrypto/issues/1977 is resolved.
