### ISSUE TITLE
"Cannot read property 'color' of undefined" when accessing GoChain wallet with Metamask

### ISSUE THREAD

**Issue by voldemarz** [MyCryptoHQ/MyCrypto#1894]
### Description of the Issue

Getting an error page when trying to access GoChain wallet via Metamask with error:
"Cannot read property 'color' of undefined"

### Steps to Reproduce

Set up as described in this guide https://medium.com/gochain/how-to-use-myetherwallet-with-gochain-e1c331d0dca2

Works with MyEtherWallet, but not MyCrypto.

### Description of Your Machine

Google Chrome Version 66.0.3359.181 on Windows 10 

### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/1264210/40974890-b7ee48e2-68d1-11e8-81ae-bf444ecdfc62.png)

**Comment by tayvano** [comment]
I can reproduce this and it's likely related to the combination of a Metamask Custom Network + MyCrypto Custom Network that's throwing the error.

However, I'm not convinced that it's actually working on legacy.mycrypto.com or myetherwallet.com. I think that it's just using the ETH network when you connect to Metamask—not the GoChain network.

**Comment by voldemarz** [comment]
It worked on MEW as it showed the correct balance.

**Comment by tayvano** [comment]
@voldemarz how did you add the custom network in MetaMask? Just using the URL in the medium post?

**Comment by voldemarz** [comment]
@tayvano Yes. Tried these two ways 
![image](https://user-images.githubusercontent.com/1264210/41001320-41f10a7e-6919-11e8-86eb-8887583c9fff.png)

**Comment by skubakdj** [comment]
I'm not able to replicate. I am able to successfully unlock my MetaMask account after adding GoChain as a custom network in MyCrypto and in MetaMask. I suspect our latest release to production (~14 days ago) might have fixed whatever caused the issue. 

@voldemarz @tayvano @dternyak could any of ya'll please give this a shot and confirm it's fixed?

**Comment by voldemarz** [comment]
@skubakdj seems to work
