### ISSUE TITLE
Typos in Contract tab - Need capitalization 

### ISSUE THREAD

**Issue by Azarielle** [MyCryptoHQ/MyCrypto#1901]
![image](https://user-images.githubusercontent.com/25834495/41005692-9181961c-68ec-11e8-96a8-f64986720833.png)

**Comment by dternyak** [comment]
What needs capitalization here?

**Comment by Azarielle** [comment]
Destination Address

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/775227584579171)
