### ISSUE TITLE
Accessing MetaMask to Interact with Contract

### ISSUE THREAD

**Issue by SharonManrique** [MyCryptoHQ/MyCrypto#1905]
At the end of inputting all needed values for interacting with a Contract, when you try to access your wallet via MetaMask, but you're not logged in, nothing happens. There isn't a warning or error given letting you know that your MetaMask isn't connected

This warning is given when you try to access your wallet via MetaMask on the View & Send tab when you aren't already signed in. 
![image](https://user-images.githubusercontent.com/25834495/41009626-2bfccc58-6900-11e8-8f03-0b5d5426988a.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/775227584579165)
