### ISSUE TITLE
Contract - Accessing MetaMask wallet to sign transaction does not work

### ISSUE THREAD

**Issue by SharonManrique** [MyCryptoHQ/MyCrypto#1906]
At the end of the contract page and inputting valid values, after clicking "Write", the "Generate Transaction" button stays greyed out forever, can not proceed to send. See gif below. Using values from #1726 
![metacontract](https://user-images.githubusercontent.com/25834495/41010228-2f39efaa-6904-11e8-8789-885c4ab262ac.gif)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/774893129398379)

**Comment by todofixthis** [comment]
Encountered a similar issue when testing a contract running on Ganache and auth'ing using private key.

I notice an exception in the console, but I'm not sure if it's related to this issue specifically:

> Failed to load resource: the server responded with a status of 500

<img width="575" alt="captura de pantalla 2018-11-23 a la s 10 53 37" src="https://user-images.githubusercontent.com/202040/48922814-17a3ee00-ef0e-11e8-82c8-42f64035a4ae.png">
