### ISSUE TITLE
Changing Nodes while Logged in 

### ISSUE THREAD

**Issue by SharonManrique** [MyCryptoHQ/MyCrypto#1908]
When you have already accessed the wallet, and do anything that exits the wallet (ex. switching tabs), you are presented with a warning that lets you know that you are about to log out of the wallet. When you switch nodes (Eth to Etc and other networks) while already logged in, you are redirected to the beginning screen of accessing a wallet without the warning. 

This is the warning you are presented with when you do anything to log out of the wallet:
![image](https://user-images.githubusercontent.com/25834495/41038479-4b5e8b7c-6964-11e8-8f4c-e3b694af6d5f.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/774893129398377)
