### ISSUE TITLE
Form fields reset when sending back-to-back transactions

### ISSUE THREAD

**Issue by tayvano** [MyCryptoHQ/MyCrypto#1910]
When changing from TOKEN_1 (e.g. VIU) to TOKEN_2 (e.g. ENJ), the entire form gets reset, including the address, amount, and currency. 

- The address should remain in the form so the user doesn't have to copy and paste it again and potentially make a mistake

- The amount could be reset or we could just leave it. Not sure it matters

- The currency should be whatever the user selected. In this case the user had to switch from VIU -> ENJ -> ETH -> ENJ when they should have been able to switch from VIU -> ENJ

- Gas limit should change each time the address, amount, or currency is swapped

- Nonce should be pulled again at some point so the user doesn't have to manually refresh it. (This is related to https://github.com/MyCryptoHQ/MyCrypto/issues/1702)

---

The above was composed from the video demo provided by the user here: https://app.hyfy.io/v/abDI1dq7frn/#!/player

Please ping Taylor/Jordan to update user via twitter when complete: https://twitter.com/scottmberry/status/1004481904148561920

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/774893129398375)
