### ISSUE TITLE
Remove buttons once a user has pressed the "Send" button on the confirmation dialog

### ISSUE THREAD

**Issue by tayvano** [MyCryptoHQ/MyCrypto#1911]
The buttons on the confirmation dialog should disappear or become invalid once the user has pressed the send button and the display changes to a loading icon. 

<img width="697" alt="2018-06-06 at 4 06 05 pm" src="https://user-images.githubusercontent.com/7924827/41069596-87eb591e-69a3-11e8-9b26-8b169d1f4679.png">

---

The above was composed from the video demo provided by the user here: https://app.hyfy.io/v/abDI1dq7frn/#!/player

Please ping Taylor/Jordan to update user via twitter when complete: https://twitter.com/scottmberry/status/1004481904148561920

**Comment by KanteLabs** [comment]
@ConnorBryan @dternyak You guys mind if i work on this?

**Comment by ConnorBryan** [comment]
@KanteLabs Go ahead! I'll re-assign to prevent confusion.

**Comment by dternyak** [comment]
@KanteLabs Are you still planning to work on this? If not, I'll reassign internally,

**Comment by KanteLabs** [comment]
Yes, I am but I ran into some difficulties it might be better to just reassign this.
