### ISSUE TITLE
Nodes - Ropsten (Testnet) -> Infura not labelled (testnet)

### ISSUE THREAD

**Issue by Azarielle** [MyCryptoHQ/MyCrypto#1912]
The Infura testnet node is not labelled as testnet in the dropdown menu. 

![image](https://user-images.githubusercontent.com/25834495/41071840-5570c7e2-69c8-11e8-9ccf-1630cab02bd6.png)

**Comment by wbobeirne** [comment]
Nodes aren't labeled testnets, only networks. All nodes on a network are only for that network.
