### ISSUE TITLE
Display address on Ledger feature sends incorrect address to Ledger

### ISSUE THREAD

**Issue by ikilled** [MyCryptoHQ/MyCrypto#1914]
### Description of the Issue

When clicking on "**Display address on Ledger**" MyCrypto sends an incorrect ethereum address to Ledger Nano S device. Ledger device dispays and incorrect addres - the address derived from MyCrypto's default derivation path `/m/44'/60'/0'` -- even though I opened my wallet a custom derivation path (MetaMask's `m/44'/60'/0'/0`) and MyCrypto is displaying the correct address on the web interface.

On MyEtherWallet the same feature works correctly (i just tested it).

### Steps to Reproduce

0. Connect to your computer your Ledger device (with Ethereum App runnung and web browser setting Enabled) 
1. Go to: https://www.mycrypto.com/account
2. Click on "Ledger - Connect & sign via your hardware wallet"
3. Click on "Connect to Ledger Wallet"
4. From the "Addresses" dropdown menu select "Custom", then enter `m/44'/60'/0'/0` and click on green tick button.
5. Select address `#1` (or any other) and click "Unlock".
6. Click "Display address on Ledger".
7. Compare the address displayed on Ledger device and the address on MyCrypto. **They are different!**

### Description of Your Machine

I am using: 
- Windows 10 Pro (64bit)
- Google Chrome Version 66.0.3359.181 (Official Build) (64-bit)
- Ledger Nano S, Firmware v1.4.2, MCU 1.5
- The only app installed on my Ledger device is Ethereum App
- On MyCrypto I am using a "Custom" derivation path: the MetaMask's `m/44'/60'/0'/0`.

**Comment by dternyak** [comment]
Hey @ikilled,

Thank you for this extremely detailed bug report. I've just opened a fix at https://github.com/MyCryptoHQ/MyCrypto/pull/1918, and I'm going to double-check trezor as well to ensure the custom dPaths are set correctly.

You should see the fix live on mycrypto.com with our next release (which should be live within a few days).
