### ISSUE TITLE
Node Singleton

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#192]
Attributed to @HenryNguyen5 

Proposal:
Change Node to a singleton instance that keeps track of its own state.

This way, you won't have `getNodeLib` everywhere, and you won't need to store functions/class instance in your store.

Your reducers/sagas would still exist, but purely for changing the node singleton state (in the saga) and keeping the UI synced (in the state with purely serializable data instead of objects with functions)

**Comment by HenryNguyen5** [comment]
Related code here:
https://gist.github.com/HenryNguyen5/b1bcb3e9445e7efefb223015552ec429
https://gist.github.com/HenryNguyen5/76a4896efc50aca32e8e42125ddad165
The node class has methods for getting/settings configurations for itself and network configs.
Any JSON-RPC calls are put into a seperate file and then proxied into the node object.
