### ISSUE TITLE
Hardware wallet notifications

### ISSUE THREAD

**Issue by Azarielle** [MyCryptoHQ/MyCrypto#1923]
When I log in with hardware wallet, but then disconnect the wallet from the computer it still shows that I'm logged in. Would be nice to show that my device has been disconnected and be logged out. It would also be nice to be notified when my device has been connected.

**Comment by wbobeirne** [comment]
Because of the way hardware wallets are implemented (either U2F on the web, or our HTTP-like way in the app) there are no events to hook into for the app to know when devices are added or removed.
