### ISSUE TITLE
MyCrypto logo 

### ISSUE THREAD

**Issue by Arslanshn** [MyCryptoHQ/MyCrypto#1940]
Hi, I want to design a new logo for the project completely free...

**Comment by wbobeirne** [comment]
Hey @Arslanshn, the offer is much appreciated. I don't think there are any plans to rebrand the project right now (Still got T-shirts and stickers coming hot off the presses!) But you're more than welcome to propose anything. Just know that I don't think that there are any plans to change in the near future!
