### ISSUE TITLE
Update to TS 2.9 to leverage JSON imports

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1941]
### Description of the Feature

The latest typescript version allows for typesafe JSON imports, allowing us to have typesafe and intellisense'd translations for the entire codebase. This would be a huge boost to ensuring i18n is done more thoroughly.

### Example(s) of Feature

https://blogs.msdn.microsoft.com/typescript/2018/05/31/announcing-typescript-2-9/#json-imports

**Comment by nickmccurdy** [comment]
This is not difficult and will have a huge impact on productivity when developing with translations (which we're starting to do a lot). I'd be happy to do this as soon as I have time.
