### ISSUE TITLE
query params of transaction URL pop up - need rewording

### ISSUE THREAD

**Issue by SharonManrique** [MyCryptoHQ/MyCrypto#1943]
You are given this after you log into the wallet. I dont think you need the "Unlock your wallet to get started." since you've already unlocked your wallet

Bug Fix for #1813 #1927
https://user-images.githubusercontent.com/25834495/41323563-2412eb44-6e7d-11e8-8961-2ad7337316dc.png

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/774893129398365)
