### ISSUE TITLE
Undersized Gaslimit for Token transfer (ERC20)

### ISSUE THREAD

**Issue by marczeller** [MyCryptoHQ/MyCrypto#1944]
If you've experienced a bug, please provide the following information:

### Description of the Issue

This might be a metamask-related issue.
During a transfert of ERC20 tokens the suggested Gaslimit was 21K, that's undersized and lead to a outOfGas.

here's the Tx : https://etherscan.io/tx/0xfeb2c1b40d99c2fa51966d4cdcdac725eaee85de4aaa79189fc26cd48514eae7

(i have manually changed the GasLimit to 25k (that wasn't enough)

### Steps to Reproduce

View & Send -> Metamask -> Scan For Token -> Select token (LGO in this case) -> Send Transaction

### Description of Your Machine

(Your browser = Chrome, browser version = Last version, operating system= W10, device = Windows surface pro4)

### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/21088542/41345805-90b898c8-6efc-11e8-9984-14f785c9299f.png)

---

**Comment by marczeller** [comment]
I just tried to reproduce the bug, and everything was working perfectly.

https://etherscan.io/tx/0x63c83f4c9cc2948a7966a4110f42122abf4975664a097db53ea878ba20e6a032

I'll let you folks close the issue. sorry for the inconvenience.

**Comment by tayvano** [comment]
@marczeller no worries, and I appreciate your honesty. I'm fairly certain this is related to https://github.com/MyCryptoHQ/MyCrypto/issues/1873 and should be fixed in the next sprint.
