### ISSUE TITLE
[Regression] Node dropdown remains disabled after 

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#1948]
If you're having an issue with unlocking your wallet, a transaction, a swap,
or an ENS auction, please email support@mycrypto.com. Github issues are for
development only, and support questions that aren't bugs or feature requests
will not be answered.

---

If you've experienced a bug, please provide the following information:

### Description of the Issue

(Your description goes here)

### Steps to Reproduce

(Explain how you got this issue)

### Description of Your Machine

(Your browser, browser version, operating system, device)

### Console Logs / Screenshots

(Console logs or screenshots go here, if applicable)

---

If you're suggesting a feature, make sure someone hasn't already posted it. If
no one has, please provide the following information:

### Description of the Feature

(Your description goes here)

### Example(s) of Feature

(If another product or app is doing this, please link it)

**Comment by wbobeirne** [comment]
#1949
