### ISSUE TITLE
Replace "Open MyCrypto" image with Desktop App

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#1959]
<img width="1312" alt="screen shot 2018-06-16 at 6 40 56 pm" src="https://user-images.githubusercontent.com/7861465/41503282-d34cb378-7194-11e8-98e2-0982265416e4.png">

**Comment by wbobeirne** [comment]
Huh, I had for sure done this at some point, as evidenced by https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/assets/images/unlock-guide/open-app.png and https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/assets/images/unlock-guide/tab-app.png. Are they not hooked up?

**Comment by dternyak** [comment]
@wbobeirne Hm, this is actually an interesting situation. That screenshot was generated on mycryptobuilds, so I assume the logic is to show the MyCrypto app icon on desktop, and the web screenshot on web. 

However, since Wallet Generation web won't be available anymore (except on mycryptobuilds), users won't ever generate keystores on the web.

I think I'll close this issue for now, since it only appears on mycryptobuilds, which is exclusively a dev env.
