### ISSUE TITLE
Adjust Wallet Options

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#1965]
## Current
<img width="1309" alt="screen shot 2018-06-19 at 11 56 52 am" src="https://user-images.githubusercontent.com/7861465/41612236-e31bfd66-73b7-11e8-8a7f-d40dad832d0b.png">

## New
Row 1: Ledger | TREZOR | Safe-T
Row 2: Web3 (MetaMask) | Parity | View with Address
Row 3: Private Key | Keystore | Mnemonic

**Comment by dternyak** [comment]
@KanteLabs It's not assigned to anyone currently, so feel free to take a crack.

I have to say as a warning, this is a really critical portion of the site, so we might go through a few design iterations / end up going with an internal implementation after all is said and done. So far warning that work on this PR may or may not get merged.

**Comment by jspence425** [comment]
Row 1 and Row 2 should be swapped (I mentioned in Slack but it didn't get reflected here). 
Put it in order of most secure & recommended (Top) to least secure & not recommended (Bottom).

**Comment by KanteLabs** [comment]
@dternyak I noticed that the SAFE-T one isnt currently in the codebase. Is there a way for me to add it?

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/774893129398363)
