### ISSUE TITLE
suggestion to make better translation management and environment

### ISSUE THREAD

**Issue by dakeshi** [MyCryptoHQ/MyCrypto#1972]
Hi. Recently, I was taking proofreading for korean translation(https://github.com/MyCryptoHQ/MyCrypto/pull/1880/)

I has joined and managed several localization projects and learned that it is very hard to manage localization with github platform alone. For example, if the original content gets updated, every translator need to find it out manually. And it's really hard to keep review discussion on github in some situation. 

So, many project has already integrated localization platform with their project. 

- eletron: https://crowdin.com/project/electron
- react: https://crowdin.com/project/react

> famous localization platform is crowdin and transifex. (crowdin is more popular one)

There are pros and cons of crowdin. 

## pros
- for translators, it helps to keep track of latest changes of original contents(most of case, it is english). 
- for project manager, all of translation results on crowdin will create PR on github automatically.
- free pricing plan for open source project(both crowdin and transifex)

## cons
- crowdin is uni-directional. You can not merge from github to crowdin.
(You can do this using transifex)
- there are some limitation for uploading format. So, if you have a lot of translated results, you need to check first it can be uploaded
(this is crowdin issue. that's why some people choose to transifex)

I think that MyCrypto has same issue for localization. So, I highly recommend you to introduce translation platform to MyCrypto project. It will help to make better translation and management env.

**Comment by dakeshi** [comment]
this could be helpful resource too, if you are considering about crowdin https://github.com/electron/i18n/issues/215

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/774893129398359)

**Comment by wtzb** [comment]
Thanks for opening this issue! We are moving to using a different platform for managing translations, so I'm closing this issue. Thank you for your feedback!
