### ISSUE TITLE
Suggestion - contracts page

### ISSUE THREAD

**Issue by DaveAppleton** [MyCryptoHQ/MyCrypto#1973]
Even before reading this, I was thinking of scraping the ABI from etherscan

https://medium.com/@sowmay/smart-contract-dapps-de19d892b0cd

I created a pretty poorly written bit of go code to do this - 
https://github.com/DaveAppleton/EtherscanAPI/blob/master/verified.go

but I am sure you could do better :-)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837176)

**Comment by wtzb** [comment]
This feature request has been moved to our internal project management system. Thank you so much for your feedback! It's really appreciated.
