### ISSUE TITLE
Correct the way features/ENS handles ENS subdomains

### ISSUE THREAD

**Issue by ConnorBryan** [MyCryptoHQ/MyCrypto#1977]
The current methodology for resolving a subdomain is not correct. As it stands, the entire entry (including period delimiters) is tested as a single unit, instead of looking at the subdomain registry for a given entry.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/774893129398357)

**Comment by Azarielle** [comment]
[Added to Jira](https://mycrypto.atlassian.net/secure/RapidBoard.jspa?rapidView=24&projectKey=ENSX&view=planning&selectedIssue=ENSX-7)
