### ISSUE TITLE
Fix Translation Strings

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#1981]
Several translation strings made their way into `en.js` in an unconventional format.

https://github.com/MyCryptoHQ/MyCrypto/pull/1976/files#r197339025 includes a reference to where the strings exist, but not a set of all the relevant strings.

TODO:
- Determine all strings that need to be re-done

**Comment by dternyak** [comment]
@dakeshi Definitely, I'll take a look now! 

Thanks for your suggestion. I'll take a look into the translation platform as well.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/774893129398355)

**Comment by Edgar2032** [comment]
https://github.com/MyCryptoHQ/MyCrypto/pull/1976/files#r197339025
