### ISSUE TITLE
Gas slider defaults to far left, fixes when checking/unchecking Advance

### ISSUE THREAD

**Issue by jspence425** [MyCryptoHQ/MyCrypto#1999]
OS: Windows
Browser: Chrome Version 67.0.3396.99 (Official Build) (64-bit)
via: MetaMask

Steps to replicate:
Go to MyCrypto.com
Click MetaMask
"Connect to MetaMask"

### **Upon getting to the view/send page, I see the slider is set to the far left price (currently 50 gwei):**
![ss 2018-07-01 at 08 13 34](https://user-images.githubusercontent.com/26891718/42143772-d2fe5e34-7d6b-11e8-95e2-274b73038b4d.png)

### **Upon clicking the "Advanced" button, the gwei does not change from 50 gwei:**
![ss 2018-07-01 at 08 13 42](https://user-images.githubusercontent.com/26891718/42143794-fe348e34-7d6b-11e8-9d0e-1b9450d74a44.png)

### **Upon clicking the "Simple" button to close the advanced section, the gas price seems to recalculate (or actually calculate for the first time):**
![ss 2018-07-01 at 08 13 47](https://user-images.githubusercontent.com/26891718/42143835-2c15c96c-7d6c-11e8-8e0b-0927830900e1.png)

**Comment by dternyak** [comment]
Related to https://github.com/MyCryptoHQ/MyCrypto/issues/1703
