### ISSUE TITLE
On-boarding Modal Re-vamp

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#2005]
After going through the design process, we're finally ready to revamp our onboarding modal. The new designs are available in zepplin and [on the web](https://zpl.io/V4JKp4Q).

**Comment by jspence425** [comment]
This will be in the next release that includes PK deprecation and updated desktop app, yeah?

**Comment by dternyak** [comment]
Not quite -- this issue has just gotten assigned for this sprint. We're just wrapping up a release for the previous sprint, which doesn't contain this issue. 

The on-boarding modal revamp will be implemented over the course of the current sprint, which ends on the 17th of July. After that, we'll package up a new release that will contain it!

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/774893129398353)
