### ISSUE TITLE
Suggestion - Electron, Contracts: Option to save ABI / Address pair 

### ISSUE THREAD

**Issue by Ramarti** [MyCryptoHQ/MyCrypto#2007]
### Allow to save locally a list of ABI / Address pair

We have to interact often with a set of smart contracts with wallets stored in HD Wallets. Since doing scripts / dapps for this is not trivial we usually go for a quick MyCrypto contract page.

If we could store the address / ABI combination locally in the electron MyCrypto app, this would be really handy.

To save I propose a button aligned to the right of the "ABI" text field, and the stored contracts could be visible through a section of "Select Existing Contracts"

**Comment by Azarielle** [comment]
Closing this issue since there's already an open issue regarding having the option to save frequently used ABI
