### ISSUE TITLE
Ledger Blue: "Unknown error when sending transaction. Ethkey (InvalidSignature)"

### ISSUE THREAD

**Issue by Mrtenz** [MyCryptoHQ/MyCrypto#2018]
### Description of the Issue

A user reported that after updating a Ledger Blue to the latest firmware (2.1) the error "Unknown error when sending transaction. Ethkey (InvalidSignature)" appears when trying to send a transaction. I'm not sure if this is an issue with MyCrypto or with the new firmware. The user reports that he's unable to sign transactions on other sites as well.

### Steps to Reproduce

1. Unlock your account with a Ledger Blue on the latest firmware
2. Try to send a transaction

### Description of Your Machine

Google Chrome

**Comment by XanderNod** [comment]
I got same problem:
04.07 - was old version 2.0 - everything work
05.07 - update 2.1.0 -  Unknown Error when sending transaction. Ethkey (InvalidSignature)
Ledger Support said update 2.1.1 and try
06.07 - update 2.1.1 -  same problem in MyCrypto - Unknown Error when sending transaction. Ethkey (InvalidSignature) 
i tryed send ETH from Ledger Wallet Ethereum - and again ERROR
ScreenShot both error in file (not nomber of ERROR)

I ask about this i MyCrypto discord support - and there are more people like me with same problem
MyCrypto discord support answer -   ts probably a Ledger bug in the recent update. Im searching around to see if i can find more info

I cant more update in Ledger Manager - it says that i have last version.
I can see right ballance on wallet (and MEW and MyCrypto and Ledger Wallet Ethereum) BUT i can sent nothing

Ledger Support try to help - now i am waiting

![2](https://user-images.githubusercontent.com/40892934/42381694-2fc0d3bc-8132-11e8-8f55-f9f14e3a0959.jpg)

**Comment by btchip** [comment]
This is closed by installing ETH app version 1.1.2 on your Ledger Blue, sorry for the inconvenience

**Comment by tayvano** [comment]
Thanks btchip 💖
