### ISSUE TITLE
Feature: View X amount of Addresses on Ledger/Trezor/Mnemonic

### ISSUE THREAD

**Issue by SharonManrique** [MyCryptoHQ/MyCrypto#2021]
Right now, when you log in with Ledger, you are given a list of 5 addresses and have to scroll each page. Would it be possible to have an option to select how many addresses are shown on each page? Ex. I'm using 10 addresses simultaneously and want to view all 10 on one page, I'd be able to see all 10 addresses instead of having to scroll back and forth.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/772183789713935)

**Comment by Azarielle** [comment]
https://github.com/MyCryptoHQ/MyCrypto/issues/1071

**Comment by wtzb** [comment]
This issue has been moved to our internal project management system.
