### ISSUE TITLE
TX Status button enabled for invalid TXhash or no hash provided

### ISSUE THREAD

**Issue by SharonManrique** [MyCryptoHQ/MyCrypto#2032]
Button is enabled even before you paste a transaction in. Should not be able to click it before a valid transaction hash has been pasted in. Button also works when an invalid tx hash has been pasted in.

![image](https://user-images.githubusercontent.com/25834495/42402825-2a0cf040-814b-11e8-8978-b40858a6c84d.png)

![image](https://user-images.githubusercontent.com/25834495/42402875-6a94b4d6-814b-11e8-8f43-70bba714a7b9.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/772183789713933)

**Comment by KanteLabs** [comment]
@dternyak @Azarielle @ConnorBryan I can start working on this issue.

**Comment by Azarielle** [comment]
@KanteLabs Go for it! I'll take note that you're working on this. Thank you very much for taking this one :D

**Comment by Azarielle** [comment]
[Added to Jira](https://mycrypto.atlassian.net/secure/RapidBoard.jspa?rapidView=19&projectKey=CORE&modal=detail&selectedIssue=CORE-103)

**Comment by KanteLabs** [comment]
@Azarielle Looks like this was actually already done on the main site. Unless I'm mistaken.
