### ISSUE TITLE
Send Entire Balance not showing what coin to send 

### ISSUE THREAD

**Issue by SharonManrique** [MyCryptoHQ/MyCrypto#2037]
You can send entire balance without picking a currency. But will still let you send a transaction without the coin being selected. Then during  transaction confirmation there will be a currency shown.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25834495/42473231-0f07ca42-8392-11e8-8582-19788b4d30e3.gif)

**Comment by Azarielle** [comment]
This is okay on this commit: https://mycryptobuilds.com/16010eb097261b03827e0c26b72ee592955b1021/#/account/send 

possible regression?

**Comment by Azarielle** [comment]
This is also making this fix for the gas/contract interaction only sometimessss work. Not all the time

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/772183789713931)
