### ISSUE TITLE
ENS retains availability of ENS even after switching tabs

### ISSUE THREAD

**Issue by SharonManrique** [MyCryptoHQ/MyCrypto#2039]
Availability of ENS results should not be retained after switching tabs. 

![image](https://user-images.githubusercontent.com/25834495/42477961-0cd5c1f2-83a1-11e8-91f7-23879e8181e1.png)

![image](https://user-images.githubusercontent.com/25834495/42477967-0ffcf7ce-83a1-11e8-8bfc-cb24a3b1be72.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/772183789713928)

**Comment by Azarielle** [comment]
Simillar issue: https://github.com/MyCryptoHQ/MyCrypto/issues/1634

**Comment by mwbailey** [comment]
I don't have access to your Asana, so I don't know if anyone else is working on this. But if not, I'll fix it.

**Comment by ConnorBryan** [comment]
@mwbailey No one is currently on it, we would appreciate it!

**Comment by wtzb** [comment]
GAU should make this issue obsolete.
