### ISSUE TITLE
Better message error for ENS

### ISSUE THREAD

**Issue by SharonManrique** [MyCryptoHQ/MyCrypto#2040]
Makes it clearer what symbols are allowed in your ENS

![image](https://user-images.githubusercontent.com/25834495/42482722-3c46c0c4-83b7-11e8-805e-4a82028fde73.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/772183789713926)

**Comment by Azarielle** [comment]
[Added to Jira](https://mycrypto.atlassian.net/secure/RapidBoard.jspa?rapidView=24&projectKey=ENSX&view=planning&selectedIssue=ENSX-9)

**Comment by wtzb** [comment]
GAU should make this issue obsolete.
