### ISSUE TITLE
Add custom token - balance before "save" is missing a decimal

### ISSUE THREAD

**Issue by SharonManrique** [MyCryptoHQ/MyCrypto#2041]
![image](https://user-images.githubusercontent.com/25834495/42483498-d0a1021c-83bb-11e8-965a-2c604287b154.png)

Its good after save: 
![image](https://user-images.githubusercontent.com/25834495/42483506-e733f822-83bb-11e8-990e-22bb28c8bacb.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/772183789713924)
