### ISSUE TITLE
Contract ABI persists when changing nodes

### ISSUE THREAD

**Issue by SharonManrique** [MyCryptoHQ/MyCrypto#2043]
However, "Select Existing Contract" and "Contract Address" get cleared

![abistays](https://user-images.githubusercontent.com/25834495/42485585-3e09f19c-83c6-11e8-9efd-aa8f1ef02fae.gif)

**Comment by mwbailey** [comment]
I'll fix this.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/772183789713920)

**Comment by wtzb** [comment]
This issue has been moved to our internal project management system.
