### ISSUE TITLE
Integrate Address Book Functionality into Recent Addresses on the "View Address" Feature

### ISSUE THREAD

**Issue by tayvano** [MyCryptoHQ/MyCrypto#2044]
The "Select a recent address" feature on "View Address" should have the labels from the address book.

All recent addresses I view should be added to the address book. 

Basically, these two features should pull from the same master list that consists of `Name/Label` and `Address`.

Talking with James today, it would be nice if every address you unlocked was added to your address book by default (like it does with "recent addresses") and given a generic name. The generic name could be "My Address 1", "My Address 2" or "My Address [date/timestamp]"

### My Recent Addresses: 
<img width="841" alt="2018-07-09 at 2 22 39 pm" src="https://user-images.githubusercontent.com/7924827/42476717-aee0613c-8383-11e8-9c92-e4bc50771497.png">

<img width="841" alt="2018-07-09 at 2 22 30 pm" src="https://user-images.githubusercontent.com/7924827/42476718-aefc9be0-8383-11e8-804f-ee88d019bfde.png">

### My Address Book

<img width="422" alt="2018-07-09 at 8 25 36 pm" src="https://user-images.githubusercontent.com/7924827/42487529-42d11b52-83b6-11e8-8fbc-ba55409531ae.png">

**Comment by tayvano** [comment]
Adding Connor and James to this issue as they would be the best to add insight to it.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/772183789713918)
