### ISSUE TITLE
Remove Equivalent Values for any network that doesn't have Equiv Values

### ISSUE THREAD

**Issue by tayvano** [MyCryptoHQ/MyCrypto#2045]
Currently it displays an error when on a test network and I think it would be better to just hide it entirely if there are no equivalent values. I don't feel super strongly about this.

Would be excellent starter task.

<img width="286" alt="2018-07-09 at 8 26 27 pm" src="https://user-images.githubusercontent.com/7924827/42487563-614cf7f4-83b6-11e8-924b-972a1e227062.png">

**Comment by nelsonkam** [comment]
Hello, I would like to complete this task. Can I have more context or info on the issue ?

**Comment by Azarielle** [comment]
@nelsonkam when you're on ETH networks you have this: 
![image](https://user-images.githubusercontent.com/25834495/43052102-31e9ec26-8df0-11e8-83c9-e48fbb223f71.png)

On the testnets you get this: 
![image](https://user-images.githubusercontent.com/25834495/43052105-3dc034f6-8df0-11e8-81d7-1b270a5b03db.png)

And on other networks where there are no equivalent values you get this: 
![image](https://user-images.githubusercontent.com/25834495/43052108-4af2760c-8df0-11e8-9ead-eb27dc858b83.png)

Essentially, the "Equivalent Values" box should not be visible when there aren't any to show. 
Thank you for taking this on, it's highly appreciated!

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/772183789713916)

**Comment by wtzb** [comment]
GAU should make this issue obsolete.
