### ISSUE TITLE
Update Copy on "Wallet Info" tab to be consistent and make translations more consistent

### ISSUE THREAD

**Issue by tayvano** [MyCryptoHQ/MyCrypto#2053]
<img width="816" alt="2018-07-11 at 3 35 10 pm" src="https://user-images.githubusercontent.com/7924827/42602887-4d9b8a84-8520-11e8-9a7f-2229e41dffbf.png">

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/772183789713912)

**Comment by wtzb** [comment]
GAU should make this issue obsolete.
