### ISSUE TITLE
[Desktop] Move Night Mode Toggle to Support Us page, or elsewhere

### ISSUE THREAD

**Issue by jspence425** [MyCryptoHQ/MyCrypto#2058]
As part of #2057, the night mode toggle needs to be moved away from the logo. 

I recommend adding on the Support Us page, or giving a dedicated button on the left nav. It's a novelty but it will increase user stickiness if they see it sooner than later and get to "customize" their experience.

**Comment by wtzb** [comment]
GAU should make this issue obsolete.
