### ISSUE TITLE
[Desktop] Any way to make Chromebooks accessible to download the app?

### ISSUE THREAD

**Issue by jspence425** [MyCryptoHQ/MyCrypto#2059]
Had two mentions so far about users using Chromebooks thus not being able to get the app.

Most recent mention: https://twitter.com/drhus/status/1017655336621273088

They complain about not having access to functionalities on the web version and back it up by saying they can't use the app due to their ChromeOS, which is fair.

**Comment by tayvano** [comment]
Easiest would probably continue support of the standalone versions for those Chromebook users?

**Comment by wtzb** [comment]
This issue has been moved to our internal project management system.
