### ISSUE TITLE
Support more Web3 providers than just MetaMask (e.g. toshi / brave / trust / cipher)

### ISSUE THREAD

**Issue by drhus** [MyCryptoHQ/MyCrypto#2060]
### Description of the Issue
I have expected from front-page icon of Web3 to be able to use mycrypo smoothly for Toshi browser or Brave, I've tried in both from Android but non working, but instead the "connect to metamask" on click >> metamask not found error

### Steps to Reproduce
Visit mycrypo from Web3 browser 

### Description of Your Machine
Pixel 2//Android 8.1//up-to-date apps

Thank you:)

**Comment by drhus** [comment]
I've tried 
Trust https://play.google.com/store/apps/details?id=com.wallet.crypto.trustapp
It's not working
Cipher https://play.google.com/store/apps/details?id=com.cipherbrowser.cipher
Working smoothly

**Comment by Azarielle** [comment]
https://github.com/MyCryptoHQ/MyCrypto/issues/1841 Similar

**Comment by Azarielle** [comment]
^ these closed issues have more information

**Comment by wtzb** [comment]
Thank you for opening this issue! While this issue is still present on our current site, the work we're doing on the new version of MyCrypto should make it obsolete. Please come check out the beta [here](https://beta.mycrypto.com/).
