### ISSUE TITLE
Going Offline Warning not sufficient 

### ISSUE THREAD

**Issue by SharonManrique** [MyCryptoHQ/MyCrypto#2072]
When you disconnect from the internet you are given this warning (screenshot). However, its not noticeable since it blends in with footer. And the wording "some features will be unavailable", what features? How is the user suppose to figure out what is available and what isn't without going through the entire app. 

![image](https://user-images.githubusercontent.com/25834495/42739083-eaabc15a-885d-11e8-830c-ed66dec24258.png)

**Comment by wbobeirne** [comment]
^ That's already the case, the green dot goes red.

**Comment by tayvano** [comment]
+1 to making it not blend in with footer

Not sure how to update the messaging to be more informative without being super long winded about it and needing to update it constantly. "Features that require the internet are disabled"? 😂

Right now if they click on an item that is disabled, it says that specific feature is only able to be accessed if the user is online.

**Comment by Azarielle** [comment]
(Added to Asana)[https://app.asana.com/0/763966770926912/771983371770046]
