### ISSUE TITLE
Cannot enter empty passphrase

### ISSUE THREAD

**Issue by gruvin** [MyCryptoHQ/MyCrypto#2073]
If you're having an issue with unlocking your wallet, a transaction, a swap,
or an ENS auction, please email support@mycrypto.com. Github issues are for
development only, and support questions that aren't bugs or feature requests
will not be answered.

---

If you've experienced a bug, please provide the following information:

### Description of the Issue

This standalone app (v1.2.1) refuses to accept an empty passphrase.

### Steps to Reproduce

Connect a Trezor with pass phrases enabled. Enter the PIN. Leave passphrase entry field blank and click "unlock". Nothing happens. 

This is at odds with the online website version and for me, means I cannot use the standalone app to access most of my accounts. :-( Blank pass phrases SHOULD BE ACCEPTED -- if only because they always have been in the past.

### Description of Your Machine

iMac late 2013. Browser version N/A 'cause standalone app.

### Console Logs / Screenshots

N/A

---

If you're suggesting a feature, make sure someone hasn't already posted it. If
no one has, please provide the following information:

### Description of the Feature

(Your description goes here)

### Example(s) of Feature

(If another product or app is doing this, please link it)

**Comment by TAiS46** [comment]
+1

**Comment by tayvano** [comment]
@ConnorBryan I think you already have a fix for this? Or know how to fix it at least?

**Comment by ConnorBryan** [comment]
@tayvano I sure do. I'll self-assign that story.

[Added to Asana](https://app.asana.com/0/763966770926912/board)
