### ISSUE TITLE
Reading Contracts - Function name is not shown

### ISSUE THREAD

**Issue by rstormsf** [MyCryptoHQ/MyCrypto#2074]
When  I select a function, I should be able to see the name of the  selected function.

![2018-07-16 12 20 14](https://user-images.githubusercontent.com/9360827/42778676-c0df16e8-88f2-11e8-95c4-adcd106f5574.gif)

it keeps showing: "Select function" even though it's already been selected

**Comment by mwbailey** [comment]
Duplicate of #2042, which should be fixed by PR #2071.
