### ISSUE TITLE
[Feature Request] Scatter Integration

### ISSUE THREAD

**Issue by matarz** [MyCryptoHQ/MyCrypto#2076]
### Description of the Feature

[Scatter](https://github.com/GetScatter/ScatterWebExtension) is a key/identity management web extension. It currently supports Ethereum and EOS keys. The feature would be to have it as one of the options to access the wallet on MyCrypto.

Their github is [here](https://github.com/GetScatter/ScatterWebExtension).

### Example(s) of Feature

[Scattellet](http://www.scattellet.com/) - Web wallet that uses scatter to connect 
[EOStoolkit](https://eostoolkit.io/home) - Multi usage dApp that uses scatter to connect 
[MonsterEOS](http://monstereos.io/) - Sample game that uses scatter to connect

**Comment by tayvano** [comment]
This is essentially a Web3 Chrome Extension (similar to MetaMask)

We don't have the resources available at the moment to get this on our roadmap, but would welcome a PR for integration. Please ping us if anyone wants to work on this.
