### ISSUE TITLE
Send Page: change the currency to be sent to be defaulted to the first item in the list (ETH, MUSIC, and so forth)

### ISSUE THREAD

**Issue by Varunram** [MyCryptoHQ/MyCrypto#2077]
## MyCrypto Desktop App
When we select a network and unlock the account, it still seems to ask for network type even though we selected that in the previous step. Sending a tx works without selecting that option, so I guess the button/dropdown could be removed? A side note in case this button has some other purpose I'm not aware of, we should remove `border-radius` for network type (notice the teeny weeny curvature in the bottom)

Great App btw, works flawlessly :)

<img width="588" alt="screen shot 2018-07-17 at 7 12 54 pm" src="https://user-images.githubusercontent.com/18598959/42821140-82259496-89f5-11e8-8abf-9efb3ab03686.png">
<img width="592" alt="screen shot 2018-07-17 at 7 20 23 pm" src="https://user-images.githubusercontent.com/18598959/42821598-86e8a882-89f6-11e8-8693-3550ae83e976.png">

**Comment by tayvano** [comment]
Agreed. It makes more sense when the dropdown is ETH, Token_1, Token_2, Token_3, Token_4, etc.

- Ideally the first choice would be automatically selected (especially makes sense for networks where tokens aren't really a thing).

- The radius should indeed also be fixed. The selector is here but not sure why it would ever have a border or border-radius unless it's being used elsewhere. https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/sass/styles/overrides/react-select.scss#L68

**Comment by ConnorBryan** [comment]
[Added to Asana[(https://app.asana.com/0/763966770926912/766176255632803)
