### ISSUE TITLE
ENS Lookup bug

### ISSUE THREAD

**Issue by blurpesec** [MyCryptoHQ/MyCrypto#2085]
### Description of the Issue

When looking up owned ENS addresses, sometimes the owner's address is incorrect. It may be linked to ens addresses that have had the `changeOwner()` method invoked.

### Steps to Reproduce

Navigate to the ENS tab in either the desktop app or the web app. 

Type in **administrative** in the ENS name field so that you can look-up **administrative.eth**. 

Click `Check Availability`. Note the Owner address listed. Look up the same ENS name on etherscan.io and notice the difference. 

### Description of Your Machine
Google Chrome, Windows 10; This is present in both the Desktop Application and the WebApp.

**Comment by tayvano** [comment]
Would a good solution be to better label what we are displaying? Or display both the deed owner and the......domain owner? Not sure on correct language here or the full details but worth figuring out a fix as its obviously causing confusion. 

I would opt for matching language displayed on etherscan to ensure consistency.

Would also be nice to maybe add some tooltips ( ? ) for these labels with further details.

**Comment by mwbailey** [comment]
I agree that the "Owner" should be consistent with etherscan to prevent confusion. If there are no objections, I can make a PR to change the displayed result from the deed owner to the name owner.

I'm not sure it's necessary to show the deed owner at all, but if you want to, maybe it would be better to split the output into two sections: one for the name info (labelhash, namehash, name owner, resolved address) and another for the auction info (deed owner, highest bid, value locked up, registration date).

Either way, some tooltips would definitely be helpful.

**Comment by ConnorBryan** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/764146476480800)

**Comment by Azarielle** [comment]
[Added to Jira](https://mycrypto.atlassian.net/secure/RapidBoard.jspa?rapidView=24&projectKey=ENSX&view=planning&selectedIssue=ENSX-10)

**Comment by blurpesec** [comment]
Fixed.
