### ISSUE TITLE
Option to save frequent ABIs

### ISSUE THREAD

**Issue by Ramarti** [MyCryptoHQ/MyCrypto#2088]
### Save frequently used ABIs in local storage

I'm a frequent user of mycrypto desktop, usually to interact with smart contracts when developing. Productivity would skyrocket if I could access previously pasted ABIs

### Proposal

1. Have a "Save ABI" button in opposite side to "Access"
2. Dialog to enter a name for the contract
3. Have a "local contracts" section in the "Select existing contract" selector.
4. Have a "Remove ABI" button close to the save one in case you want to clean up.

**Comment by Azarielle** [comment]
(Added to Asana)[https://app.asana.com/0/763966770926912/771983371770044]

**Comment by Azarielle** [comment]
https://github.com/MyCryptoHQ/MyCrypto/issues/2007 

Similar suggestion.

**Comment by wtzb** [comment]
Thank you for submitting this feature request! This issue has been moved to our internal project management system.
