### ISSUE TITLE
Unable to build working prod web version

### ISSUE THREAD

**Issue by bgits** [MyCryptoHQ/MyCrypto#2095]
If you're having an issue with unlocking your wallet, a transaction, a swap,
or an ENS auction, please email support@mycrypto.com. Github issues are for
development only, and support questions that aren't bugs or feature requests
will not be answered.

---

If you've experienced a bug, please provide the following information:

### Description of the Issue

When opening `index.html` from the prod folder the site does not load.

### Steps to Reproduce

1) yarn build
2) open index.html  from `/dist/prod` in browser

### Description of Your Machine

Chrome 68,OSX High Sierra

### Console Logs / Screenshots

(Console logs or screenshots go here, if applicable)
<img width="1022" alt="screen shot 2018-08-02 at 3 35 58 pm" src="https://user-images.githubusercontent.com/4020296/43606744-3c405034-966a-11e8-93c9-38043593dde6.png">

---

If you're suggesting a feature, make sure someone hasn't already posted it. If
no one has, please provide the following information:

### Description of the Feature

(Your description goes here)

### Example(s) of Feature

(If another product or app is doing this, please link it)

**Comment by bgits** [comment]
`yarn build:downloadable` does not work either in chrome, firefox or safari. This seems to be an error with the build itself.

**Comment by mwbailey** [comment]
I'm able to build and run the downloadable version using macOS High Sierra and Firefox (but not Chrome or Safari). Make sure you're opening index.html in the `dist/download` folder, not `dist/prod.` The build is output to different folders depending on which command you use.

**Comment by HenryNguyen5** [comment]
Hey @bgits, @mwbailey hit the nail on the head with this one, closing this for now since it seems solved. Don't hesitate to re-open if the problem persists. Thanks!
