### ISSUE TITLE
Remove REP under Equivalent Values

### ISSUE THREAD

**Issue by jspence425** [MyCryptoHQ/MyCrypto#2097]
![ss 2018-08-02 at 04 36 43](https://user-images.githubusercontent.com/26891718/43655628-424dc2c8-9704-11e8-9916-576d85c85954.png)

Screenshot attached.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/771942046640550)

**Comment by KanteLabs** [comment]
@jspence425 @dternyak I just did this task if you guys were still interested in implementing it. 

https://github.com/MyCryptoHQ/MyCrypto/pull/2201
