### ISSUE TITLE
Chainkorea shows up under ETC, despite being configured as a CLO network

### ISSUE THREAD

**Issue by pyskell** [MyCryptoHQ/MyCrypto#2109]
### Description of the Issue

Chainkorea is for CLO, and configured as a CLO network. Despite this it oddly appears in the dropdown under ETC. Doesn't make any sense.

### Steps to Reproduce

Just look at the drop-down. Now look at the code: https://github.com/MyCryptoHQ/MyCrypto/blob/f3f1d12084952c3d5a501e42a30b94520ad8e57c/common/libs/nodes/configs.ts#L164

### Description of Your Machine

Chrome (latest); Windows 7

### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/9665963/44178361-0aca5f80-a0c0-11e8-8a3d-d411f979a62d.png)

**Comment by pyskell** [comment]
Great! Any chance to merge either mine or @splix's PR to add nodes to MyCrypto today? Just a bit worried about server performance with the impending listing.

**Comment by hahnmichaelf** [comment]
Yours got pushed yesterday, and I told you about the timeline on Discord. Closing this now. Poke me on discord if you need any other help!

**Comment by pyskell** [comment]
Yup, all good, thanks!
