### ISSUE TITLE
Can't connect with a Parity local node over WS

### ISSUE THREAD

**Issue by Tbaut** [MyCryptoHQ/MyCrypto#2113]
If you've experienced a bug, please provide the following information:

### Description of the Issue

Hey guys, Thibaut from Parity here.
Using the Dektop App on linux Mint with `linux-x86-64_1.2.1_MyCrypto.AppImage`
I can't manage to connect it to my local node by HTTP and the App is behaving weirdly depending on the configuration.

### Steps to Reproduce

Run a parity node using `parity --chain kovan --jsonrpc-cors all --ws-origins all -l rpc` to allow to access both HTTP and WS server from any origin and log the rpc calls and answers made to the node.

#### Websockets custom node without luck
- Set a custom node with http://127.0.0.1:8546 (the default WS port).
 
--> The node does not get any rpc request and MyCrypto JS console shows:
![image](https://user-images.githubusercontent.com/33178835/44222607-60b50b00-a185-11e8-933d-28350330d802.png)

#### HTTP node actually connecting to 8546 (while I specified 8545)

- Set a custom node with http://127.0.0.1:8545 (the default **HTTP** port).
--> The node does get requests and answers. The Desktop App is happy and "works".
However, the requests are actually made on 8546 
![image](https://user-images.githubusercontent.com/33178835/44222675-978b2100-a185-11e8-9656-10f469077a19.png)
![image](https://user-images.githubusercontent.com/33178835/44222678-9c4fd500-a185-11e8-9955-296f6ead13d0.png)

#### My questions :

- Can you explain the above mentioned behaviours?

### Description of Your Machine

Ubuntu based linux
Running linux-x86-64_1.2.1_MyCrypto.AppImage

**Comment by tayvano** [comment]
It looks like this is resolved. Please comment and reopen if its not.

**Comment by stone212** [comment]
@tayvano I confirm the same problem @Tbaut has.  I can not connect using a similar connection.  My Parity node is remote but I am forwarding ports 8545, 8546 using SSH tunnel.

For comparison I have immediate connection using the deprecated https://github.com/parity-js/shell on the same computer.  I am happy to troubleshoot if there are steps I can try.

Can anyone confirm that Tbaut's setup works (ssh tunnel is a second level of potential issue).

**Comment by stone212** [comment]
@Tbaut Did you resolve this?  Are you able to re-open this as @tayvano suggested?

**Comment by Tbaut** [comment]
I haven't resolved it nor do I have the adequate rights on the repo to reopen..

**Comment by tayvano** [comment]
Honestly, this is a bit beyond the scope of my knowledge. Couple questions

- Are you both on Linux?

- Do you think this has to do with something regarding the ports on our end? Or something else?

**Comment by Tbaut** [comment]
I'm on Linux.
There is most probably something wrong with the network selector.
As I tried today with 1.61 the following happened:
- Mycrypto is connected to Ropsten (infura)
- I setup a custom network connection named "Kovan local WS" on 127.0.0.1:8546 and run a node (ssh tunnel) with `--chain kovan --jsonrpc-cors-all --ws-origins all`
- in the UI, I select my newly created "Kovan local WS"
- I instantly get the error message 
  >Could not connect to the node. Refresh your page, try a different node (upper right corner), check your firewall settings. If custom node, check your configs.
  
  although the network tab tells me the connection actually got initiated with a response from the node being: "WebSocket interface is active. Open WS connection to access RPC."
- Now if in the UI I select "Kovan>Etherscan".. it connects to my localhost (using WS) and if I stop my node MyCrypto rightfully throws error, but the UI shows that I'm connected to Etherscan!

Here is a quick overview: https://imgur.com/ND3MrYH

**Comment by stone212** [comment]
@tayvano Yes Linux.  

You asked `Do you think this has to do with something regarding the ports on our end?`

What does this mean?  The ports to access are on localhost, not within the app or the MyCrypto servers.  The ports are accessible by other applications including this `curl` test:

```
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}' 127.0.0.1:8545
```

@Tbaut Can you please run this curl command on localhost where you run this app and tell me the output?

```
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}' 127.0.0.1:8545
```

**Comment by tayvano** [comment]
Sorry, by "our side" I meant how we are handling ports within the app / javascript code / https://github.com/MyCryptoHQ/shepherd/, etc.

**Comment by stone212** [comment]
@tayvano Then the answer is yes I definitely think the problem is on "your side".  Is there another forum that the dev team uses to receive bug reports? The issue was reported in August by TBaut and still no beginning has been made to fixing it.  You have access to Tbaut and me and we are both very competent to do deep testing.

**Comment by stone212** [comment]
@tayvano Then the answer is yes I definitely think the problem is on "your side".  Is there another forum that the dev team uses to receive bug reports? The issue was reported in August by TBaut and still no beginning has been made to fixing it.  You have access to Tbaut and me and we are both very competent to do deep testing.

**Comment by tayvano** [comment]
We're looking into this now and will keep you posted. It may be a symptom of a bigger underlying issue. If we need any more information that we can't recreate ourselves, we'll ping you and possible set up a telegram or discord for discuss more quickly.

**Comment by SharonManrique** [comment]
Our node balancer [Shepherd](https://github.com/MyCryptoHQ/shepherd) does not currently support WB, it can only handle http requests. 

I believe the solution would be to update shepherd to include WS.

**Comment by stone212** [comment]
@tayvano

> we'll ping you and possible set up a telegram or discord

Or you could just post here like normal.

**Comment by stone212** [comment]
@SharonManrique 

> Our node balancer Shepherd does not currently support WS, it can only handle http requests.
> I believe the solution would be to update shepherd to include WS.

But Tbaut and I are both specifying port 8545 and the setup screen defaults to setting port 8545.  That is the RPC port that you can reach over http.  I tested this with this `curl` command:

```
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}' 127.0.0.1:8545
```

**Comment by stone212** [comment]
This is not "stale."  It is unresolved.  We are still waiting for @tayvano to reply as she said she would.
