### ISSUE TITLE
After entering TREZOR passphrase, it shows the "export public key" screen again and then quickly skips it

### ISSUE THREAD

**Issue by jspence425** [MyCryptoHQ/MyCrypto#2119]
Confirmed that it happens on both Windows and Mac web, with an empty and non-empty passphrase.

![trezor](https://user-images.githubusercontent.com/26891718/44232521-313ada00-a156-11e8-9329-d744212fa121.gif)

**Comment by tayvano** [comment]
This is something on TREZORs end, not ours.
