### ISSUE TITLE
Verifying an invalid signed message should not be allowed

### ISSUE THREAD

**Issue by Azarielle** [MyCryptoHQ/MyCrypto#2124]
When verifying a message, you should not be able to select the button "Verify Message" until you have inputted a valid message to verify. 

![image](https://user-images.githubusercontent.com/25834495/44283848-a4634f80-a22d-11e8-933e-ad00384effbc.png)

**Comment by KanteLabs** [comment]
@dternyak  @ConnorBryan  @Azarielle I saw that this was unassigned and went ahead a resolved this issue. Would like someone to look this over when given a chance. 

https://github.com/MyCryptoHQ/MyCrypto/pull/2207
