### ISSUE TITLE
desktop wallet didn't really change the wallet on MacOs

### ISSUE THREAD

**Issue by abara-kedavra** [MyCryptoHQ/MyCrypto#2127]
If you're having an issue with unlocking your wallet, a transaction, a swap,
or an ENS auction, please email support@mycrypto.com. Github issues are for
development only, and support questions that aren't bugs or feature requests
will not be answered.

---

If you've experienced a bug, please provide the following information:

### Description of the Issue

On MacOs: If you change wallet using the button "change wallet" and make new transaction with the same recipient and amount - desktop wallet shows error - "the same hash, this transaction already broadcasting to broadcasted". It could be right if you didn't change the wallet, but after changing it is completely new transaction from new address. That means the app change wallet in interface, but didn't change somewhere inside. If you close the app and open it again - everything works good. 

### Steps to Reproduce

unlock wallet, send tokens, after it change wallet using button "change wallet", unlock new wallet, make transaction to the same address and same amount of tokens and same gas price and gas amount - see broadcasting error

### Description of Your Machine

(Your browser, browser version, operating system, device)

### Console Logs / Screenshots

(Console logs or screenshots go here, if applicable)

---

If you're suggesting a feature, make sure someone hasn't already posted it. If
no one has, please provide the following information:

### Description of the Feature

(Your description goes here)

### Example(s) of Feature

(If another product or app is doing this, please link it)

**Comment by ConnorBryan** [comment]
This is due to the nonce not automatically updating. [See here for details.](https://github.com/MyCryptoHQ/MyCrypto/issues/1030)
