### ISSUE TITLE
[Enhancement] Signing message with Ledger

### ISSUE THREAD

**Issue by SharonManrique** [MyCryptoHQ/MyCrypto#2133]
When you are signing a message with Ledger:
step 1: Go to Sign & Verify message
step 2: Go to Sign message - Type in any message
step 3: Select the "Sign Message" button
-- When this button is pressed, nothing happens on screen. Users should be reminded that to finish signing a message, you must finish the process on the Ledger itself.

**Comment by wtzb** [comment]
GAU should make this issue obsolete.
