### ISSUE TITLE
Issue with pre-filled data field

### ISSUE THREAD

**Issue by pauliax** [MyCryptoHQ/MyCrypto#2134]
### Description of the Issue

When trying to send a pre-filled tx using Metamask, if you do not expand the "Advanced" section first, the data field is left empty.

### Steps to Reproduce

On the Ropsten testnet go to the pre-filled page, for instance:

[MyCrypto Pre-Filled](https://www.mycrypto.com/account/send?&to=0xfEfFcEeF3E7B13aAC3a916647BD75071f96b7B3a&value=0.1&data=0xba298494000000000000000000000000feffceef3e7b13aac3a916647bd75071f96b7b3a&gasLimit=200000)

Select "Metamask". When new window loads do not expand the "Advanced" section. If you press "Send Transaction" your tx will be sent with empty data field (it will fail). If you press "Send transaction", then "Cancel" and then expand the "Advanced" section, the fields "To Address", "Amount" and "Nonce" becomes empty.

If you want to make it work, firstly you need to expand the "Advanced" section and only then press "Send Transaction". I think that makes some inconveniences, especially for inexperienced users.

(I have only tested it with Metamask, not sure if this issue also appears by using other methods).

### Description of Your Machine

Google Chrome (version: 68.0.3440.106), Windows 10, ASUS laptop

**Comment by voldemarz** [comment]
Just ran into this issue as well. It has nothing to do with Metamask though, I was using Ledger. It seems simply that if you don't expand Advanced, data passed via URL get's ignored.
