### ISSUE TITLE
ETC Ledger HD path is outdated (m/44'/60'/160720'/0')

### ISSUE THREAD

**Issue by cdetrio** [MyCryptoHQ/MyCrypto#2139]
The Ledger Live app (https://www.ledger.com/pages/ledger-live) displays the path that MyCrypto uses as "Ethereum Classic 1 (legacy)" (`"freshAddressPath": "44'/60'/160720'/0'/0",` when you click on the settings icon in Ledger Live).

The default Ethereum Classic path on Ledger Live is `"freshAddressPath": "44'/61'/0'/0/0",`, which doesn't seem to be supported by MyCrypto.

**Comment by hahnmichaelf** [comment]
Hey @cdetrio, Ledger Live uses a different method of HD Derivation that relies on BIP-44, breaking our current implementation using BIP-39. We have an issue open for it here: #2070. In the mean time, you can still access the funds from Ledger Live on MyCrypto, you'll just need to access them using the custom derivation path option. To find the correct path to use on MyCrypto from Ledger Live, you'll need the path specified in your Ledger Live application by `"freshAddressPath": "44'/61'/0'/0/0"`
