### ISSUE TITLE
opening mac_1.2.2_MyCrypto.dmg on Sierra 10.12.6 installs MyCrypto 1.2.1

### ISSUE THREAD

**Issue by cdetrio** [MyCryptoHQ/MyCrypto#2140]
Downloading [mac_1.2.2_MyCrypto.dmg](https://github.com/MyCryptoHQ/MyCrypto/releases/download/1.2.2/mac_1.2.2_MyCrypto.dmg) on an older version of MacOS Sierra (10.12.6) will install MyCrypto 1.2.1. However opening the same file on a more recent MacOS High Sierra (10.13.6) will install MyCrypto 1.2.2. This happens without explanation and could be quite startling for the user.

**Comment by pedrouid** [comment]
Happening the same here!
<img width="731" alt="screenshot 2018-08-30 13 39 49" src="https://user-images.githubusercontent.com/10136079/44852115-53eee780-ac5a-11e8-8ce6-eeea5e7184d9.png">
<img width="1738" alt="screenshot 2018-08-30 13 40 28" src="https://user-images.githubusercontent.com/10136079/44852116-54877e00-ac5a-11e8-80b0-0ec150a82716.png">

**Comment by pedrouid** [comment]
Not sure if matters, but my version is on macOS High Sierra v10.13.16

**Comment by tayvano** [comment]
We're pushing a new release this afternoon which should kill two birds with one stone. I'll keep you posted. Thanks all for letting us know about this issue.
