### ISSUE TITLE
How to cache contract addresses and ABI with desktop app?

### ISSUE THREAD

**Issue by postables** [MyCryptoHQ/MyCrypto#2147]
I'm using the Linux desktop app to interact with smart contracts using a hardware wallet, and having to copy+paste the ABI string and the contract address if i change to use a different contract, or log out and in again is pretty tiresome! Is there any way to cache/store the contracts that have been interacted with?

**Comment by todofixthis** [comment]
Possible duplicate of #2088

**Comment by postables** [comment]
It's a duplicate, I will close
