### ISSUE TITLE
[LEGACY] Digital Bitbox Hardware Wallet Support

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#217]
Re-implement Digital Bitbox decrypting and send support from v3

**Comment by wbobeirne** [comment]
I've hit a wall on this one, I'm getting the very opaque client error code 4, `DEVICE_INELIGIBLE` (See [here](https://developers.yubico.com/U2F/Libraries/Client_error_codes.html)) It seems v3 is also facing this problem, and my implementation is identical, so I'm not sure how this was ever working. @douglasbakkum if you are available to talk this out, you can find me on slack or shoot me an email on my profile.

**Comment by douglasbakkum** [comment]
@wbobeirne Will send an email. 

Note that the Digital Bitbox will only communicate with a website that has `https://www.myetherwallet.com` as a base URL (or `https://digitalbitbox.com`) (`https://www.myetherwallet.com/test` or like that will work) - this prevents phishing attacks. Maybe you are testing using a different server?

**Comment by Zwilla** [comment]
Does this mean, that everyone who want to run an absolute cold storage can’t use a digital bitbox?

**Comment by wbobeirne** [comment]
In our email correspondence, I requested that `localhost` also be whitelisted for running MEW offline.

**Comment by wbobeirne** [comment]
The Digital Bitbox team just shot me this reference implementation of it running in Electron by directly interfacing with HID: https://github.com/digitalbitbox/ElectronDemo. This means that Digital Bitbox support will _probably_ be limited to Electron until they update the firmware to whitelist mycrypto.com, but this will allow it to work offline.

**Comment by tapir** [comment]
Digital bitbox supports mycrypto since firmware 3.0.0. It's been quite a while since it's released. This is a feature originally existed in MEW. Why isn't it enabled yet?

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837155)
