### ISSUE TITLE
how can i add my sxl in mycrypto?

### ISSUE THREAD

**Issue by Willy-Sonderegger** [MyCryptoHQ/MyCrypto#2177]
If you're having an issue with unlocking your wallet, a transaction, a swap,
or an ENS auction, please email support@mycrypto.com. Github issues are for
development only, and support questions that aren't bugs or feature requests
will not be answered.

---

If you've experienced a bug, please provide the following information:

### Description of the Issue

(Your description goes here)

### Steps to Reproduce

(Explain how you got this issue)

### Description of Your Machine

(Your browser, browser version, operating system, device)

### Console Logs / Screenshots

(Console logs or screenshots go here, if applicable)

---

If you're suggesting a feature, make sure someone hasn't already posted it. If
no one has, please provide the following information:

### Description of the Feature

(Your description goes here)

### Example(s) of Feature

(If another product or app is doing this, please link it)

**Comment by Willy-Sonderegger** [comment]
hello
i just send eth + omg to mycrypto.com/can see.How can i add my sxl too?Have problem to login myetherwallet,where my sxl are.

**Comment by tayvano** [comment]
You can add it as a custom token as described here:
https://support.mycrypto.com/tokens/adding-new-token-and-sending-custom-tokens.html

**Comment by tayvano** [comment]
Let us know here or ping support@mycrypto.com if you need anymore assistance.
