### ISSUE TITLE
KeepKey Hardware Wallet Support

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#218]
Look into implementing KeepKey support for decrypting and send. Do we have any contacts there? Can we get our hands on some test device(s) for implementation?

**Comment by tayvano** [comment]
I pinged them twice over the past few months. This was all shortly before Shapeshift aquired them.

Still haven't heard anything back & I'm not sure what Shapeshift's plans with them are. I can ping again if you want. Their Twitter is semi-active: https://twitter.com/bitcoinkeepkey

**Comment by tayvano** [comment]
If you want a test device:

1. Ping Jordan on Slack and ask when our expense request process has been flushed out. (😂)

2. Buy one.

3. Send receipt to invoice@myetherwallet.

**Comment by wbobeirne** [comment]
I just shot 'em a tweet, if that doesn't go anywhere I'll buy my own.

**Comment by tolinwei** [comment]
Any progress of this support? I recently got a KeepKey and just realized that only MyEtherWallet can show up other ERC20 altcoins that are scored in it. Really hope you guys can add support to KeepKey soon. 

Is there anything that I can help with?

**Comment by wbobeirne** [comment]
Glad to hear there's interest! Just shot them another message, but it's going to require some help from the KeepKey team to get it implemented. We'll see if they're interested.

**Comment by tolinwei** [comment]
Great! Please keep us updated here, this page is the first result when we search "MyEtherWallet KeepKey" in Google (and maybe other search engines).

**Comment by majestic10110** [comment]
Keepkey is a BIP44 device. News out recently that they are working to incorporate ERC20 native support. Would love to see this device compatible with my favorite wallet Myetherwallet.com

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837153)

**Comment by keepkeyjon** [comment]
We have a better library for this now: https://github.com/keepkey/keepkey.js and I'm happy to provide test devices to help with the implementation.
