### ISSUE TITLE
Deep Link to Contract Interface in MyCrypto Desktop

### ISSUE THREAD

**Issue by ldub** [MyCryptoHQ/MyCrypto#2186]
### Description of the Feature

As a developer I occasionally use MyCrypto desktop to send manual transactions via the contracts tab and my ABIs. I like that it generates a UI for me to interact with my own contracts, and I prefer it to remix (and ethfiddle) because I can use it locally and don't have to open my code in it.

I would use it much more often for this purpose if I could generate a deep link into MyCrypto that would prefill certain values including:
* network parameters
* contract address 
* ABI 
* function signature + function parameters (or just tx.data) 
* value
* private key to sign the tx

Turns out that this was implemented in the MEW days:
https://github.com/MyCryptoHQ/MyCrypto/issues/356
* Does the MyCrypto rewrite still support this?
* is it possible to activate it on Desktop?
* the MEW version just prefills a tx with some data. is it possible to implement this to go to the Contracts tab instead?

### Example(s) of Feature

EIP-681 comes to mind:
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md

Minimal electron project with deep linking capabilities: 
https://github.com/oikonomopo/electron-deep-linking-mac-win

Trust wallet supports something kind of similar:
https://medium.com/@trustwallet/mobile-dapps-with-deep-linking-and-trust-wallet-6a4712b9b9a4

**Comment by wtzb** [comment]
Thanks for your feature request! We have since implemented this in the new beta which can be found [here](https://beta.mycrypto.com/home). Unfortunately, this does currently not work in the desktop app, but it would be a great idea. We really appreciate your feedback!

https://github.com/MyCryptoHQ/MyCrypto/pull/2920
