### ISSUE TITLE
Searching for tokens not possible anymore

### ISSUE THREAD

**Issue by SimonHausdorf** [MyCryptoHQ/MyCrypto#2192]
It was possible to search for a token (type the first character) in older versions. Please bring back the feature.

1. Open dropdown (next to amount field)
2. type first character
3. list should scroll / focus tokens with that letter

**Comment by wtzb** [comment]
Thank you so much for your feedback! We're busy working on a new version of MyCrypto, which shoud include this change. You can check it out [here](https://beta.mycrypto.com/).

![image](https://user-images.githubusercontent.com/11412480/72996697-79c3f000-3e3e-11ea-868b-b39b741b95f0.png)

I will close this issue now, but be sure to let us know if you have any additional feedback, it's really appreciated! :)
