### ISSUE TITLE
Sending two token transactions is not possible

### ISSUE THREAD

**Issue by SimonHausdorf** [MyCryptoHQ/MyCrypto#2193]
1. enter address
2. enter amount and select token
3. send the transaction
4. select another token
5. type in a new amount
6. send the transaction

Current:
The token selection is ignored. The amount will be transferred in ETH

Expected:
The transfer should be made in the selected token and not in ETH

<img width="804" alt="screen shot 2018-10-01 at 10 56 01 am" src="https://user-images.githubusercontent.com/1446685/46269068-c4926800-c568-11e8-8d78-00f213abccda.png">

**Comment by blurpesec** [comment]
I'll look into this. Thanks for the report :) I think that this is caused by transaction field clearing, as normal when transaction is broadcast successfully, but the token display is not correctly reset.

**Comment by tayvano** [comment]
This is resolved by https://github.com/MyCryptoHQ/MyCrypto/pull/2335

The fix is live on web and will be live in the 1.5.3 version of desktop shortly. 

Thanks for the report.
