### ISSUE TITLE
Cannot confirm new mnemonic when two words are repeated

### ISSUE THREAD

**Issue by ilanolkies** [MyCryptoHQ/MyCrypto#2197]
### Description of the Issue

When creating a new mnemonic, if two words are repeated, the confirmation phase cannot be done.

Also, reveal word does not work.

### Steps to Reproduce

Create a new wallet, make two words equal...

### Description of Your Machine

Mac Pro

### Screenshot

<img width="962" alt="screen shot 2018-10-06 at 16 40 34" src="https://user-images.githubusercontent.com/36084092/46575172-9a84df80-c986-11e8-95fe-c09c37a48e99.png">

**Comment by ilanolkies** [comment]
Hi! I think you forgot this issue... is still happening. Thanks

**Comment by ilanolkies** [comment]
Is there any news? I ran into this error again. Thanks.

**Comment by awantoch** [comment]
Still occurring as of 11/23/19

**Comment by wtzb** [comment]
Thank you for opening this issue! Please accept my apologies for lack of response up until now, but I added this to our internal project management system and added a note that this should be solved before we release the next big version of MyCrypto, which you can check out [here](https://beta.mycrypto.com/).

In an effort to clean up our GitHub issues, I'll be closing this one, but thanks for making us aware of it! Your feedback really helps us improve our product. Please never hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us).
