### ISSUE TITLE
Not support for access with private key to RSK mainnet (MyCrypto Desktop)

### ISSUE THREAD

**Issue by jonathansmirnoff** [MyCryptoHQ/MyCrypto#2213]
I cannot access to RSK mainnet network using 'Private Key'. But in other network, like Ethereum or EOS, I can.
I think this a problem because the only way I can access is by a hardware wallet or mnemonic.
Thanks!

**Comment by alepc253** [comment]
@ConnorBryan any idea about this? I guess it changed when you guys removed "unsafe wallets" but not completely sure. I don't know why this options are available for other chains and not for RSK...
