### ISSUE TITLE
Transactions Won't Complete and Other Issues When Using a Ledger Nano S

### ISSUE THREAD

**Issue by Errol1886** [MyCryptoHQ/MyCrypto#2234]
Let me start of by saying I have not experienced any problems with making a transaction when using your website https://mycrypto.com with my Ledger Nano S, but I can not make any transactions when using your MyCrypto desktop application software (version 1.4.0) with my Ledger Nano S on a Windows 10 64-bit computer (Windows 10 Home Edition - version 1803).

When I unlock my Ledger Nano S's Callisto and Ethereum Classic wallets in the MyCrypto desktop application and then try to send a Callisto or Ethereum Classic transaction, nothing happens afterwards (my Ledger Nano S does not tell me to verify and approve the transaction). The spinning wheel underneath the "Send Transaction" button just keeps on spinning.

![send-transaction-won t-complete](https://user-images.githubusercontent.com/41203384/47618180-f9420280-dac7-11e8-842d-dadddba00bf6.jpg)

If I then click the "Change Wallet" button in the upper-right hand corner of the MyCrypto desktop application to be taken back to the "How would you like to access your wallet screen?", and then I select the Ledger option again, I am then greeted with the following error message: "Failed to Connect to Ledger".

![failed to connect to ledger error message](https://user-images.githubusercontent.com/41203384/47617885-31dfdd00-dac4-11e8-8489-7c326f609c5e.jpg)

If I close down the MyCrypto application completely and then run the MyCrypo application again, the MyCrypto application will let me either access my Callisto/Ethereum Classic wallet again or the MyCrypto application will get stuck on the "Unlock Your Ledger" screen.

![won t unlock](https://user-images.githubusercontent.com/41203384/47617931-dd892d00-dac4-11e8-9c79-eeebb45855c3.jpg)

I am using my Ledger Nano S with other desktop wallets such as Scatter, Fairy Wallet, and Ledger's own Ledger Live desktop application and my Ledger Nano S works perfectly with those applications. Your MyCrypto desktop application is the only desktop wallet that is giving me problems.

**Comment by Errol1886** [comment]
@mkrufky 

I have all the latest apps already installed. I think the problem I am experiencing is related to the following:

The MyCrypto desktop application says to make sure that **"browser support" is turned off.** The latest Ethereum Classic and Callisto apps have removed the option (that was there in the previous versions) to disable browser support. Browser support now seems to be permanently turned on by default. But can't be turned off as the option to do so has been removed from the Ethereum Classic app and the Callisto app.

**Comment by mkrufky** [comment]
Please follow my instructions exactly.  I know you think you have the correct software, but please do this anyway.

You should erase all apps from your Ledger. (DO NOT reset your seed) Don't worry - your wallet addresses will remain the same when you reinstall those apps again later. Upgrade to the latest Ledger Nano S firmware, then install the latest Ethereum app before installing the latest Callisto app. Then, please try again.

The most important bit here is that you remove all apps and start with an empty ledger with no apps installed.

**Comment by Errol1886** [comment]
@mkrufky 

I don't think I know I have the correct software, I know for a fact I have all the latest versions of my apps and my Ledger Nano S is on the latest firmware (version 1.4.2). In the "About" section of each app on My Ledger Nano S I can see that I have the latest version of the following apps: Ethereum (version 1.1.7), Callisto (version 1.1.7), and Ethereum Classic (version 1.1.7).

I took your advice and uninstalled all the apps on my Ledger and then reinstalled them in the order you suggested and I am still having the same problem. I also tested the MyCrypto app on 2 other Windows 10 machines and I'm experiencing the same problem on does machines as well.

Like I said in my original post, I am using my Ledger Nano S with other desktop wallets such as Scatter, Fairy Wallet, EOS Voter by Greymass, and Ledger's own Ledger Live desktop application and my Ledger Nano S works perfectly with those applications. The MyCrypto desktop application is the only desktop wallet that is giving me problems. My Ledger Nano S works perfectly on the MyCrypto website (https://mycrypto.com), it's just the Windows .exe version of the MyCrypto application that I am experiencing problems with.

Thank you for the help, but I have now uninstalled the MyCrypto desktop application from my computer.

**Comment by tayvano** [comment]
@Errol1886 We haven't received any other reports of this but we will keep our eyes peeled and see if we can reproduce and/or fix something on our end. 

It may have to do with having other applications open or something blocking the interaction with the device via USB. The web uses the U2F protocol while the desktop application using USB. Ledger also changed how they detect and support each of these (the user used to have to turn browser support ON or OFF but now no longer needs to.)

Again, we'll re-open this issue if we are able to re-produce or get further reports.

**Comment by Uryens** [comment]
Same problem - plugged in Ledger Nano S with latest firmware update (1.5.5), got all errors with Mycrypto, both before and after erasing all apps on Nano (Fido U2F and Ethereum):

- Browser, pre-erasing Ledger apps: "U2F not supported" error
- Browser, post-erasing apps: browser gets stuck
- Desktop, pre-erasing apps: "Failed to connect to Ledger" error
- Desktop, post-erasing apps: app gets stuck

Not sure what is happening here, it worked on a different computer.
