### ISSUE TITLE
Contracts - Selected function is selected, but not shows in the view

### ISSUE THREAD

**Issue by rstormsf** [MyCryptoHQ/MyCrypto#2235]
### Description of the Issue

![2018-10-28 23 00 31](https://user-images.githubusercontent.com/9360827/47622482-9b341000-db05-11e8-866c-058c9c88e8b3.gif)

### Steps to Reproduce

Select any function in Contract's tab.
1.4.0 version as shown in the footer

### Description of Your Machine

Mac OSX, Chrome 70

**Comment by Azarielle** [comment]
@rstormsf Yes, we have this bug internally documented. Thank you for bringing it back up to our attention!

**Comment by tayvano** [comment]
I believe this is now resolved. If not, please comment & reopen.
