### ISSUE TITLE
The "more" link in "Select an Address" doesn't use the right block explorer

### ISSUE THREAD

**Issue by mkrufky** [MyCryptoHQ/MyCrypto#2242]
The "more" link in "Select an Address" modal always uses ethplorer, rather than the provided block explorer for the given chain

**Comment by Errol1886** [comment]
@mkrufky 

Have you used the Ledger Nano S with the MyCrypto desktop application to send a transaction? Is your Ledger Nano S working with the MyCrypto desktop application? I'm using a Windows 10 machine and can not get the MyCrypto desktop application to send any transactions?

**Comment by mkrufky** [comment]
@Errol1886 it all works.  Please create your own issue - your question is not related to this issue.
