### ISSUE TITLE
WebChain is using a non-unique Chain ID

### ISSUE THREAD

**Issue by suryanshkumr** [MyCryptoHQ/MyCrypto#2248]
### Description of the Issue

EtherInc first block was created on 2018-02-13 21:59:01 +0530 (https://explorer.einc.io/block/1)

WebChain first block was created on 2018-05-08 14:12:10 +0530 (https://explorer.webchain.network/block/1)

so as you can see EtherInc was running chainID 101 from Feb and WebChain using same chainid from May.

**Comment by tayvano** [comment]
Thanks for the report. We are holding off on merging both etherinc and webchain until this is resolved. See: https://github.com/MyCryptoHQ/MyCrypto/pull/2246 & https://github.com/MyCryptoHQ/MyCrypto/pull/2217
