### ISSUE TITLE
Portable builds

### ISSUE THREAD

**Issue by leafcutterant** [MyCryptoHQ/MyCrypto#2287]
### Description of the Feature

Create builds which can be run without installing and all the data and libraries are stored in the same directory as the application.

### Example(s) of Feature

For an excellent example, see how a portable software using the Portable Apps Format works by picking anything from [PortableApps.com](https://portableapps.com/apps).

[Electrum](https://electrum.org/#download), albeit working differently, has portable and standalone versions for Windows.

**Comment by tayvano** [comment]
Hey @leafcutterant we have a standalone version available on https://download.mycrypto.com/ but I'm not exactly sure if that's what you are referencing here. Basically its a package that can be run in-browser but has all the desktop application functionality.

Primarily we have seen it be used by those running on Chomebooks as Electron doesn't have Chrome OS support.

Is this what you are talking about or is there something else we need to do to make it fully "portable"?

**Comment by leafcutterant** [comment]
Thanks, I didn't know about the standalone version! I checked it out and no, I meant something different. I envisioned a version of the Windows application which, similarly to the Windows app, functions by starting an .exe, but instead of having to install it ("bonding" it to the operating system) and having the files it needs spread out over many different locations, everything is contained in one directory and can be moved anywhere, even to other operating systems, without any loss in security, function or data.

Other advantages include:
* No reliance on a browser. If you use the current standalone version, you either run it in your present browser (wouldn't recommend it to anyone due to security implications), or you dedicate a separate browser to it (still reliant on the browser's security, but much better -- however, you need to handle and maintain another piece of software, which is extra effort).
* I suspect the "stateful" features I've outlined in #2288 wouldn't work with the current standalone version (although I may be wrong on it).

If the idea of portable apps seems tough, try using any app from PortableApps.com on Windows and it'll be immediately evident.

**Comment by tayvano** [comment]
We use electron builder for our desktop builds so I actually think its possible to add a specifically portable built (I think?)

Reading: https://www.electron.build/

**Comment by AC0DEM0NK3Y** [comment]
Would it be possible to get a standalone web version or allow the app to read from a custom contracts file? I like to hardcode in the contracts I use, abi and address for myself and to share with my team and I can do this with (vintage at least) MEW by editing the .js but I can't do this in myCrypto and would prefer to be using it if I can.

Thanks.

**Comment by nickmccurdy** [comment]
You should be able to edit the contract configuration in the source code and run `yarn dev`, `yarn build`, `yarn build:downloadable`, or `yarn build:electron:windows`  depending on how you want to install/run it.

**Comment by tayvano** [comment]
@AC0DEM0NK3Y the contracts that show in the dropdown are here: https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/config/contracts/eth.json

You could build a custom version with just the contracts you desire, or add your contracts to that list via a PR so it's available to everyone (including your team)

**Comment by AC0DEM0NK3Y** [comment]
I would if I was on windows 10 pro. I can't install docker requirement (iirc) to be able to build/test.

**Comment by nickmccurdy** [comment]
You might be able to use Ubuntu via Windows Subsystem for Linux or VirtualBox alternatively.

**Comment by AC0DEM0NK3Y** [comment]
Yep I could but for now it's far simpler to use MEW, I just need to alter one .js file and it works great. Maybe in the future this can be considered as a feature for myCrypto too and/or I can do the workaround, I do prefer the direction you are taking on the whole.

Thanks.

**Comment by nickmccurdy** [comment]
Could you show an example of what the difference is in setting it up with MEW vs MyCrypto and what changes we could make in MyCrypto to make it easier? Our build tooling should work fine, so it sounds like you're looking for more centralized configs, I'm just not sure how MEW does it.

**Comment by AC0DEM0NK3Y** [comment]
Yep, altering MEW for this is changing .\js\etherwallet-master.js with the contract and abi info, then double clicking index.html to open in a browser.

MyCrypto build AFAIK is altering a similar js file as @tayvano mentioned and having to build the standalone app using docker which I cannot do with on windows 10 home and would have to go through the annoyance of having to setup an ubuntu or vbox setup just to build it.

Pretty significant differences in effort needed with almost identical results for the usecase.

----

If the standalone app could pull in a loose file to allow custom additions or allow editing of the defaults a user wouldn't need to build they could just pull the app locally and re-use their old data.
It's quite useful for devs/companies (imho) to be able to edit that data and share to their team and QA, but it could be a niche use case and not worth the effort for you to change I couldn't say, I don't know who your typical user is.

Although, if I could (easily) build the code I'd be tempted to put this sort of thing in myself and PR it.
But for now I've re-purposed MEW 3.37.0.

**Comment by nickmccurdy** [comment]
We're planning on getting our build process to work on Windows in the future. If you'd like to contribute and get this working sooner, feel free.

**Comment by wtzb** [comment]
Thank you so much for requesting this! I've added it to our internal project management system. For this reason, I'm closing this here, but we really appreciate you giving your feedback. Please never hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us) :)
