### ISSUE TITLE
Tor integration

### ISSUE THREAD

**Issue by leafcutterant** [MyCryptoHQ/MyCrypto#2289]
### Description of the Feature

The current ways of using of Ethereum are ridden with privacy leaks. I propose adding an option to connect to the internet through Tor, routing *every* application request through it.

As a start, MyCrypto could detect an already-running Tor instance and use that, but properly, it should have Tor integrated into the application and use its own Tor circuit.

This setting could be placed in the "Change network" menu. It should persist after exiting the application.

### Example(s) of Feature

[Electrum](https://github.com/spesmilo/electrum) can connect through an existing Tor instance.
[Bisq](https://github.com/bisq-network/bisq) runs its own instance of Tor.

**Comment by Ultraphaze** [comment]
Great idea, I've also tried to use MyCrypto in Tails but got no connection. Would be nice to use that wallet like Electrum on Tails...

**Comment by wtzb** [comment]
As part of an effort to clean up our GitHub issues, I've added this to our internet project management system. Thank you so much for requesting this feature, we appreciate it a lot! We really value privacy at MyCrypto, so I think this would be a great thing to support in the future.
