### ISSUE TITLE
No txs in Recent Transactions

### ISSUE THREAD

**Issue by ilanolkies** [MyCryptoHQ/MyCrypto#2321]
## Reproduce

1. Make a tx with any network (I tried this with Ropsten, Kovan and RSK TestNet)
2. Open Recent transactions tab

It should display tx recently done but it doesn't.

## Debugging it

https://github.com/MyCryptoHQ/MyCrypto/blob/b9a53f336a2cff3ef86d5d0e5c4f34047295d516/common/features/transactions/sagas.ts#L62

It seems like `res.payload.indexingHash === txIdx` is always false. This causes the `addRecentTransaction` to never be executed.

**Comment by blurpesec** [comment]
Hey @ilanolkies, I actually already fixed this in this PR:  #2312 in this line:  https://github.com/MyCryptoHQ/MyCrypto/blob/b9a53f336a2cff3ef86d5d0e5c4f34047295d516/common/features/transactions/sagas.ts#L113
