### ISSUE TITLE
Offline mode not usable in stand-alone app - can't get nonce from network, field grayed out

### ISSUE THREAD

**Issue by veox** [MyCryptoHQ/MyCrypto#2336]
### Description of the Issue

`subj`. Can't set the nonce manually, most likely because the app is trying to get the information "from the network" - I assume this due to the perpetual "spinner" animation in the relevant input field.

### Steps to Reproduce

0. Use an air-gapped machine.
1. Open the stand-alone app.
2. Unlock a JSON keyfile.
3. Go to the "View & Send" page (should be selected by default).
4. Enter destination and amount, uncheck "Automatically calculate gas limit".

At this point, try clicking on the "Nonce" field - it is impossible.

### Description of Your Machine

Linux 64-bit, Fedora 28
`linux-x86-64_1.5.3_MyCrypto.AppImage`

### Console Logs / Screenshots

N/A (air-gapped set-up).

**Comment by veox** [comment]
Issue not present when using `linux-x86-64_1.4.2_MyCrypto.AppImage`, so this is a regression.

**Comment by blurpesec** [comment]
Hey veox. Thanks for the tip. Happy holidays.

**Comment by tayvano** [comment]
Added to Jira as CORE-172. I'm guessing this has to do with other recent nonce changes.

**Comment by egdn** [comment]
Hey @tayvano  @blurpesec, have this issue on the latest desktop build (1.5.7) using `linux-x86-64_1.5.7_MyCrypto.AppImage` on Debian.

Impossible to manually set the `Nonce` field - it's non-editable on the offline computer. Thus [these instructions](https://support.mycrypto.com/offline/making-offline-transaction-on-mycrypto.html) are not accurate as of now. Please fix this one in the next minor release, if possible.

Downgrading the desktop app to `linux-x86-64_1.4.2_MyCrypto.AppImage` solves this issue with readonly `Nonce` field but arises another one: on 1.4.2, one cannot select any other token except ETH in offline mode (a currency dropdown has the only `ETH` value when offline).

Managed to send offline by using version 1.5.0 (`linux-x86-64_1.5.0_MyCrypto.AppImage`) which allows setting Nonce manually and selecting any token in offline mode.

P.S. please close [this issue](https://github.com/MyCryptoHQ/support.mycrypto.com/issues/218), this info is already in the support article.

**Comment by tayvano** [comment]
@blurpesec can you look into this and implement a fix this week?

**Comment by cjasonm** [comment]
I'd just like to note that this issue is still present in the current release, @tayvano @blurpesec

**Comment by blurpesec** [comment]
@cjasonm I'm sorry for the delay on this one. I've added a fix for this in #2427. It may not go live until next release due to QA process -> in 2 weeks on Thursday, 27th.

**Comment by cjasonm** [comment]
Thanks, Michael. I really appreciate your efforts and MyCrypto in general.

**Comment by robertandrewsmith** [comment]
I am experiencing the same problem on the *WINDOWS* build 1.6.0
