### ISSUE TITLE
Valid wallet address not recognized

### ISSUE THREAD

**Issue by cleanforestco** [MyCryptoHQ/MyCrypto#2339]
1. Visit https://mycrypto.com/account

2. Click on "View Address". Paste in: 
0x7BdDB2deD86B8e635a179F997BB964285CaD129A

The address is not recognized as valid.

<img width="531" alt="screenshot 2018-12-27 09 51 13" src="https://user-images.githubusercontent.com/653153/50484161-15c1c480-09bd-11e9-9aa1-32e909e409d8.png">

3. Paste in:
0x7BdDB2deD86B8e635a179F997BB964285CaD129a
(Ending with a lower case "a").

The address is recognized as valid.

<img width="527" alt="screenshot 2018-12-27 09 51 18" src="https://user-images.githubusercontent.com/653153/50484153-0c385c80-09bd-11e9-95f8-b256bd39db49.png">

**Comment by blurpesec** [comment]
I think this is probably an issue with the `isValidChecksum` check that is conducted. Not sure though. Will give it a look. Thanks for the heads up :-)

**Comment by tayvano** [comment]
EIP 55 is the one that describes how the backwards-compatible checksums work: 

- https://github.com/ethereum/eips/issues/55

- https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md

I assume we are using the ethereumjs-utils implementation?

https://github.com/ethereumjs/ethereumjs-util/blob/75f529458bc7dc84f85fd0446d0fac92d991c262/index.js#L473-L475

I think the issue may be that simply making the last letter lowercase doesn't necessarily void the checksum detection. The check verifies that both: 

1. the address is a valid address (it's 40 hex characters) 

2. the address matches what is output by `toChecksumAddress()`. 

In this case it doesn't fulfill both requirements so returns false.

**Comment by blurpesec** [comment]
After looking into this: This definitely has to do with `isValidChecksum`. While the potential issues associated with invalid checksummed addresses on this view-only section of the app is small, it's probably better left alone as there are only a few small edge-cases where a user wouldn't use an address that is either lowercase or valid checksummed addresses.

**Comment by ButteryGuitars** [comment]
Was seeing this pretty frequently with MyCrypto for Win 1.5.3. Haven't seen it in 1.5.6 yet, but also haven't been using it for more than a few days.

**Comment by tayvano** [comment]
@ButteryGuitars Where were you getting the addresses from? e.g. an exchange, block explorer, etc?

**Comment by ButteryGuitars** [comment]
> @ButteryGuitars Where were you getting the addresses from? e.g. an exchange, block explorer, etc?

Behavior doesn't appear to be tied to specific source of address. Exchanges, other ETH wallets under my control.

Deleting the 0 at the beginning of the address and re-adding always fixes.

**Comment by wtzb** [comment]
Thank you for opening this issue. Since this issue applies to an older, no longer supported version of MyCrypto, I'm closing this to keep a better overview of issues that are currently applicable.

If you believe this was in error, or if this issue still applies, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us). Thanks for helping us and letting us know of any issues you might run into!
