### ISSUE TITLE
Refactor libs to self contained npm modules

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#235]
- [ ] contract
- [ ] nodes
- [ ] validators
- [ ] units
- [ ] values

The purpose of putting each one of these into their own NPM modules is to facilitate seperation of concerns and improve testing + reduce clutter.

Additionally, it'll make it easier to keep track of our dependencies, and speed up webpack build times because the files will stay static.

**Comment by wbobeirne** [comment]
For the crypto-centric stuff, I totally agree with this to especially keep an eye on PRs for those types of things. But having tried to do this kind of aggressive separation on other projects, I've found it's extremely difficult to work on any features that require multiple dependencies to be updated. If we have a new default contract that requires a new validator that needs a new translation for an error message, it becomes a pain to file 3 pull requests that depend on each other.

I'd vote to keep as much in the same repository for ease of contributors.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837151)
