### ISSUE TITLE
New version 1.5.4 breaks Gwei pricing.

### ISSUE THREAD

**Issue by Emperornero** [MyCryptoHQ/MyCrypto#2351]
If you've experienced a bug, please provide the following information:

### Description of the Issue

When doing a transaction, the user is unable to change the Gwei price.

### Steps to Reproduce

Upgrade to 1.5.4, attempt a transaction.

Seems odd that this happens so easily.  I have upgraded and downgraded twice and still experience the issue.  This happens in 1.5.4, but not in 1.5.3.

**Comment by blurpesec** [comment]
Looking into it now. Thanks for the heads up :)

**Comment by blurpesec** [comment]
Reverted here: #2353
