### ISSUE TITLE
Allow Notes to be made in the Select an Address window

### ISSUE THREAD

**Issue by housemobile** [MyCryptoHQ/MyCrypto#2356]
Right now there is #, Address, ETH, Token, More (link to etherscan)

It would be great if I could name each address or provide a note to each address.

Please include this feature in future releases.

**Comment by blurpesec** [comment]
So you actually can already add notes to addresses. We call them "address labels". On the **Send & View** page (after logging in), you can see an **Add Label** button underneath your address on the right side of the page. When you try to go to your address selection page after adding a label, it will show up like this: 

![you can](https://user-images.githubusercontent.com/29407814/51143732-32fbed00-181d-11e9-9872-e8e8c1dcf272.PNG)
