### ISSUE TITLE
Add x button to remove custom nodes on web-interface.

### ISSUE THREAD

**Issue by blurpesec** [MyCryptoHQ/MyCrypto#2357]
### Description of the Issue

I am unable to remove the custom nodes on web-interface. I would like to be able to do this in the interface. There is one in the desktop app already.

### Console Logs / Screenshots

![sidebar](https://user-images.githubusercontent.com/29407814/51142143-11006b80-1819-11e9-8357-82a682a7c09a.png)

**Comment by wtzb** [comment]
Should be obsolete in GAU due to no custom networks.

**Comment by wtzb** [comment]
@blurpesec AFAIK we're not doing custom networks anymore for GAU, but will custom nodes still be a thing? If so, I'll move this to CH if it's still applicable.
