### ISSUE TITLE
Network color, where is it used?

### ISSUE THREAD

**Issue by PeterTheOne** [MyCryptoHQ/MyCrypto#2361]
### Description of the Issue

There is a `color` property in every network in [`common/features/config/networks/static/reducer.ts`](https://github.com/MyCryptoHQ/MyCrypto/blob/master/common/features/config/networks/static/reducer.ts). Where is it used in the frontend? Is it used at all? When adding a network I came across this question when added a network ( https://github.com/MyCryptoHQ/MyCrypto/pull/2358 ) and I still don't know the answer.  I can just set some color for the network but it highly depends where it is displayed to decide which color to set. A good place to put an explanation would be in the Wiki Page [Adding a Network](https://github.com/MyCryptoHQ/MyCrypto/wiki/Contributing-%E2%80%90-Network-or-Node#adding-a-network).

### Steps to Reproduce

1. Read [Adding a Network](https://github.com/MyCryptoHQ/MyCrypto/wiki/Contributing-%E2%80%90-Network-or-Node#adding-a-network)
1. Add network to `common/features/config/networks/static/reducer.ts`
2. Be confused about what color to put there.

**Comment by tayvano** [comment]
I'm honestly not sure where / if it is currently used but we will use it at some point if it's not in use. It is a simple border color or small circle indicator color—never a background color or text color—which gives you a lot of flexibility in color choices.

The goal of the color was to give people an easy way to tell if they were on a different network, especially when sending transactions.

**Comment by wtzb** [comment]
Thank you for opening this issue! We're working on a [brand new version of MyCrypto](https://beta.mycrypto.com/), where networks are handled a bit differently. In an effort to clean up our GitHub issues, I'm closing this one. However, if you have any questions or concerns, please don't hesitate to reach out to us, either through a comment or [directly](https://support.mycrypto.com/contact-us). Thanks! :)
