### ISSUE TITLE
Replace Infura RPC endpoint for POA Network

### ISSUE THREAD

**Issue by vbaranov** [MyCryptoHQ/MyCrypto#2372]
[Infura’s POA Core nodes to be disabled on 2/1/19](https://forum.poa.network/t/infuras-poa-core-nodes-to-be-disabled-on-2-1-19/1881)

**Comment by blurpesec** [comment]
Hello! Thanks for the heads up and PR for this one. We should be getting it into a release later :-)

**Comment by vbaranov** [comment]
@blurpesec thanks!
