### ISSUE TITLE
Deep link to prefill forms

### ISSUE THREAD

**Issue by ilanolkies** [MyCryptoHQ/MyCrypto#2375]
### Motivation

Developing dApps, it is necessary to have different types of active payment. The integration of MyCrypto would be much easier if, in a single click, you can take the user to the page or desktop app with all the fields to complete ready.

### Description of the Feature

Add deep links to switch on inner tabs and prefill fields on forms.

**Comment by wtzb** [comment]
Thanks for your input, @ilanolkies!

This is currently already a thing in MyCrypto, however not fully compliant with [EIP-681](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md) and not documented very well. The current fields can be found [here](https://github.com/MyCryptoHQ/MyCrypto/blob/3074e50909495d171edff2ec63a3e30bbeeb335a/common/components/renderCbs/Query.tsx#L17), but I can't guarantee for them all to work correctly at this time.

The team was made aware of this, and full support should be added in the near future :)

**Comment by ilanolkies** [comment]
Thanks! What about contract interaction? This feature is not implemented, am I right?

**Comment by wtzb** [comment]
Not right now, unfortunately.

**Comment by ilanolkies** [comment]
I'll open a more specific issue, about contracts. Thanks!
