### ISSUE TITLE
estimateGas does not supply gasPrice parameter

### ISSUE THREAD

**Issue by wjmelements** [MyCryptoHQ/MyCrypto#2377]
When sending TrueUSD, the automatic `gasLimit` is incorrect because the `eth_estimateGas` request does not supply the `gasPrice` parameter.

Smart contracts can condition on `gasPrice` using the `GASPRICE` opcode, `3a`. Not supplying the `gasPrice` parameter leads to incorrect estimates and reverted transactions.

You can test this by calculating the gasLimit for a TrueUSD transfer. The automatic gasLimit should be approximately 21k lower for 1 wei than for 40 gwei; instead, it is the same.

**Comment by blurpesec** [comment]
Hey @wjmelements , we're not in the habit of rewriting jsonRPC endpoints, but we can add the gas limit for this to be set manually at 200k or so, to overwrite potential gas limit calculation issues. Do you think that would work for all uses?

**Comment by wjmelements** [comment]
You do not need to change the endpoint. You only need to supply the parameter.

**Comment by wjmelements** [comment]
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_estimategas

https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_call

**Comment by blurpesec** [comment]
I've made the first change locally. Sourcing some TUSD to try to test it tomorrow. We're talking about the padding idea in Slack, but i think if we decide to do that it'll wait until we have better tx estimation time so we can do dynamically-sized padding based on risk of tx failure in estimated tx timeframe.

**Comment by wjmelements** [comment]
I can send you $0.02 if you supply an address.

**Comment by blurpesec** [comment]
@wjmelements Yes please: 0x5197B5b062288Bbf29008C92B08010a92Dd677CD . It's been pretty hard finding tools that support the new token contract/have liquidity.

**Comment by wjmelements** [comment]
https://etherscan.io/tx/0xf729c12520c4a36c08f858f8732e6e1a4ce31f0b5b69d1cde02e8ae821ea5ee0

**Comment by vikmeup** [comment]
Thanks for reporting!
We noticed many users reported the same problem for Trust Wallet, but could not figure out what’s going on with TUSD contract.

**Comment by wjmelements** [comment]
I have an update to the testing instructions. We have temporarily lowered the refund threshold in order to relieve our users while fixes are implemented. The lower gasPrice you should use is 1 wei. The estimated gas for 1 wei should be approximately 21 kgas less than for 50 gwei. I have also updated the description of this issue.

**Comment by wjmelements** [comment]
You can also use the contract at 0x28a958cD020efeA3734a0bb36DDdc5F9B872cEa8 to test estimateGas. If you are estimating correctly, the result should be less than 22k.

**Comment by wtzb** [comment]
Thanks for opening this issue! We're currently working on a brand new version of MyCrypto, which you can check out [here](https://beta.mycrypto.com). Unfortunately, I don't have any TUSD to test this with myself, could you verify whether this issue is solved in the beta, or is still present? It would be really appreciated! :)
