### ISSUE TITLE
MyCrypto Desktop offline transaction broadcasting using secondary device.

### ISSUE THREAD

**Issue by blurpesec** [MyCryptoHQ/MyCrypto#2382]
### Description of the Feature

After creating/signing a transaction on the MyCrypto Desktop app offline, I would like to be able to broadcast the transaction by scanning a qr code using a second device. Currently after signing an offline transaction, I have to copy the transaction onto an online device to broadcast it. This can be done with a usb drive, but it is a time consuming a process. Create a method to handle processing the signed transaction on the offline device so that an online device can scan and then broadcast it.

### Example(s) of Feature

XRP's Toast Wallet offers offline transaction broadcast support.

-----

**Thanks to [/u/chrivasintl](https://www.reddit.com/r/MyCrypto/comments/ap3zxu/suggestion_mycrypto_transaction_broadcasting/) for suggesting this feature.
[Source](https://www.reddit.com/r/MyCrypto/comments/ap3zxu/suggestion_mycrypto_transaction_broadcasting/)**

**Comment by wtzb** [comment]
Moving this to our internal project management system :)
