### ISSUE TITLE
Wrong chainId when sending AQUA from a Ledger Nano S wallet using the Mac OS app.

### ISSUE THREAD

**Issue by luismcv** [MyCryptoHQ/MyCrypto#2414]
### Description of the Issue

Wrong chainId when sending AQUA from a Ledger Nano S wallet using the Mac OS app.

Sending from a keystore wallet works fine. Sending from the Ledger Nano S wallet but using the website instead of the app works too.

### Steps to Reproduce

Make sure you're connected to the Aquachain network. Unlock a Ledge Nano S wallet with some balance. Try to send some AQUA. After confirming the transaction on the Ledger, and clicking on Details, the raw transaction will show:

"chainId": 57

while the chainId should be 61717561 and if you try to submit the transaction you'll get an "invalid sender" error.

As mentioned above, the same steps using a keystore wallet and the Mac OS app, or the same Ledger wallet using the website work (transactions are successfully submitted; the raw transactions also has the correct chain id).

### Description of Your Machine

Mac OS 10.13.6
MyCrypto app 1.6.0

**Comment by blurpesec** [comment]
Hey! Thanks for the report. We're looking into replicating this issue :-)
