### ISSUE TITLE
MyCrypto Desktop nonce is mixed up across the different testnet networks

### ISSUE THREAD

**Issue by bokkypoobah** [MyCryptoHQ/MyCrypto#2426]
### Description of the Issue

I'm using MyCrypto Desktop to deploy contracts from the same account across the Ropsten, Kovan, Rinkeby and Görli testnets. MyCrypto Desktop nonce is mixed up across the different testnet networks.

In the steps below, the latest transaction on Rinkeby has a nonce of 4 but MyCrypto Desktop calculates 1,460. This number remains the same after the nonce refresh button is clicked.

### Steps to Reproduce

1. Switch networks to Rinkeby

2. Unlock my account 0x49D8621f8862c423AbbA0dfAe4916F838Cd264F6 using a JSON / UTC file. The following screen shows that the next nonce on Rinkeby is 1,460. 

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/17121975/54101688-04635280-4419-11e9-9661-4b3b4d5f6e07.png">

On Ropsten, https://ropsten.etherscan.io/tx/0x6934fda843ffce1d66ef9b19f13ebc9edb55671a47a913b08f0d3a4448688d25 is my latest transaction from my 0x49D8 account, with a nonce of 1,454.

On Rinkeby, https://rinkeby.etherscan.io/tx/0xa0ffb0ae1bc73316437839542523751ba116a6fb8d7c0fe66ea159b78b0ab717 is my latest transaction from my 0x49D8 account, with a nonce of 4

The same happens with Kovan and Görli networks.

### Description of Your Machine

mac_1.6.0_MyCrypto.dmg on a MacBook Pro

**Comment by MrLuit** [comment]
Since your nonce is actually just the number of transactions sent from your account, which is different on each network, your nonce seems to be calculated correctly to me:

![](https://i.imgur.com/vcEPyT1.png)

Sorry if I missed anything!

**Comment by MrLuit** [comment]
Your nonce seems to be returned correctly from web3 to me:

![](https://i.imgur.com/vcEPyT1.png)

Could you please try opening the dev tools on our desktop app, switching to `Network`, and look for any web3-related eth_getTransactionCount calls? Let me know if you need help with that!

**Comment by bokkypoobah** [comment]
The following shows that I am on the Rinkeby network, and the call to `getTransactionCount`

<img width="1491" alt="image" src="https://user-images.githubusercontent.com/17121975/54119059-9040a300-4448-11e9-9c20-07d6cd357716.png">

And here is the response to `getTransactionCount`:
<img width="557" alt="image" src="https://user-images.githubusercontent.com/17121975/54119099-ac444480-4448-11e9-858b-6c8f0ee3625b.png">

And my account's last tx on Rinkeby is https://rinkeby.etherscan.io/tx/0xc14776f433731dbe1f123c16e426672f7c017e2a6473231b22d33890d362294f - the nonce is 6, so the next is expected to be 7. However, the first screen above displays the nonce 1460.

**Comment by blurpesec** [comment]
Hey Bokky, thanks for the report - You're using the same pub/priv keypair across the networks, correct? 

This is an issue with the way our nonces are calculated. 
When calculating we currently do two things: 
* We check `eth_getTransactionCount` and 
* We check the local cache for transactions from the same address

Then, we pick the highest nonce between the two, allowing you to stack transactions and send back-to-back. Currently, we're not differentiating between networks, so that would explain this behavior. I'll look into a fix for this :D
