### ISSUE TITLE
Updated Trezor firmware breaks compatibility with MyCryptoWallet

### ISSUE THREAD

**Issue by andreweximchain** [MyCryptoHQ/MyCrypto#2439]
### Updated Trezor firmware breaks compatibility with MyCryptoWallet

Hello, I have tried sending a transaction recently with the latest firmware update on trezor, but for whatever reason I'm getting a safety check failed red notification error when running in the yarn electron:dev mode. I also tested this issue with a fully built version of MyCrypto application, and to no avail. I also tested this against an older trezor with older firmware, and it seems to be fine there. For whatever reason, it seems that the ethereum signing check on the trezor fails.

https://github.com/trezor/trezor-mcu/blob/master/firmware/ethereum.c

If you want to check out the link above and go through it with a simple ctrl-f of "safety check failed" will show you where in the code the error is coming from. 

### Steps to Reproduce

1. Update trezor one to firmware version 1.8.0 
2. Try to send a transaction
3. Fail sending transaction due to safety check notification error.

### Description of Your Machine
Running a 13 inch 2017 Macbook Pro with MacOS Mojave Version 10.14.3 (18D109)

### Console Logs / Screenshots
![image](https://user-images.githubusercontent.com/36312802/54560713-5405c900-4999-11e9-92dc-c9b9d12e5ff4.png)

I modified the trezor.js node_modules to print out the request and responses going to the trezor, and here are the console logs

![image](https://user-images.githubusercontent.com/36312802/54560901-c5de1280-4999-11e9-93cf-3a8f9da0635a.png)

**Comment by tayvano** [comment]
So basically, trezor.js is now deprecated but the new trezor connect isnt compatible with Electron. 

Add'l info on Trezor's end here: https://github.com/trezor/connect/issues/245

For now, advice for users is "use the website with your Trezor" until we figure out what needs to be done to resolve this

**Comment by andreweximchain** [comment]
@tayvano found a workaround based on the @rodrigopavezi's suggestion in https://github.com/trezor/connect/issues/245

**Comment by blurpesec** [comment]
@andreweximchain That's odd because i tested the same thing yesterday after @rodrigopavezi 's post and it didnt work. But then i tested again just now and it did... >.> odd. Would you like to PR for this one, so you can get the credit for the work, or would you rather i did? :-)
