### ISSUE TITLE
Add Ledger Ethereum Derivation Path

### ISSUE THREAD

**Issue by Kryptoxic** [MyCryptoHQ/MyCrypto#2448]
If you're suggesting a feature, make sure someone hasn't already posted it. If
no one has, please provide the following information:

### Description of the Feature

Ethereum addresses on Ledger Live makes use of a different derivation path (m/44'/60'). Currently the option named "Ledger ETH" on MyCrypto is using the legacy derivation path and not the Ledger Live derivation path.

### Example(s) of Feature

A solution would be to do something similar to MEW and default the "Ledger ETH" option to the Ledger Live derivation path and rename the old one to "Legacy ETH".

![image](https://user-images.githubusercontent.com/15937274/54801712-2b384900-4ca3-11e9-840f-8a878fa404f9.png)

The screenshot above shows an example from MEW that you guys can consider when adding the option.

I believe there is an issue open on this specific problem from the Ledger team themselves on issue #2070 but there has not been any replies since Nov 2018. I hope someone can give an update on this issue.

**Comment by tayvano** [comment]
#2070 is going to be the place to track this. It's at the top of our backlog, it just takes quite a bit of effort. You can use the "custom path" for now and just know, we're well aware of how frustrating this is.

**Comment by wtzb** [comment]
Thanks for opening this issue! In an attempt to clean up our Github issues, I'm closing this and will mention https://github.com/MyCryptoHQ/MyCrypto/issues/2070, which discusses this issue further.

We really appreciate you opening this issue and for your suggestion, I hope we can provide a solid solution in our [beta](https://beta.mycrypto.com/) soon!
