### ISSUE TITLE
Cannot connect to local node

### ISSUE THREAD

**Issue by stone212** [MyCryptoHQ/MyCrypto#2449]
### Description of the Issue

After creating a custom node, app can not connect, and defaults back to main ETH network.
(Your description goes here)

### Steps to Reproduce

Download MyCrypto 1.6.1 linux 64 bit.

Run AppImage

Go to `Change Network` > `Add Custom Node`

Add info, choose `Save and Use`

See this error:

```
Could not connect to the node. Refresh your page, try a different node (upper right corner), check your firewall settings. If custom node, check your configs.
```

Notice that your app is back on ETH.

### Description of Your Machine

(Your browser, browser version, operating system, device)

Ubuntu 16.04 running linux-x86-64_1.6.1_MyCrypto.AppImage and local custom Parity node.

Parity is started with toml file with this setting:

```
cors = [""]
```

### Console Logs / Screenshots

(Console logs or screenshots go here, if applicable)

---

If you're suggesting a feature, make sure someone hasn't already posted it. If
no one has, please provide the following information:

### Description of the Feature

I suggest that "local node" should be one of the default choices.

### Example(s) of Feature

This would work the way the deprecated Parity JS Shell worked.

**Comment by tayvano** [comment]
Note: Probably related to #2113

**Comment by stone212** [comment]
@tayvano Yes very possible.  I have a slightly different configuration and the second report might be different or might help find the problem.

**Comment by stone212** [comment]
This is not "stale."  It is unresolved.  This Issue is waiting for @tayvano to reply, or someone else to help reproduce the error (or to say that it is resolved in a newer version)
