### ISSUE TITLE
Critical Javascript error in 1.6.2

### ISSUE THREAD

**Issue by GustavMarwin** [MyCryptoHQ/MyCrypto#2462]
<img width="433" alt="Screenshot 2019-03-28 at 21 38 55" src="https://user-images.githubusercontent.com/37633593/55207976-0c095200-51a2-11e9-8c9b-acc600fbb756.png">

**Comment by nickmccurdy** [comment]
Thanks for catching this so soon, I can confirm that desktop is broken on macOS. For now 1.6.1 desktop and 1.6.2 web should work, but we'll try to release a hotfix soon.

**Comment by tayvano** [comment]
Resolved in new release 1.6.3
