### ISSUE TITLE
[Feature Request] Allow setting for various confirmation pop-ups to automatically dismiss

### ISSUE THREAD

**Issue by jspence425** [MyCryptoHQ/MyCrypto#2464]
From psnotadev#2800 in Discord:

"feature request: allow to define number of seconds before confirmation popups automatically disappear.  currently, all notifications must be manually dismissed"
---

Basically, all of the current pop-ups on the site require you to manually dismiss them. This user is requesting a setting that allows pop-ups to automatically dismiss after X seconds. 

This would be a good addition to the future Settings page.

**EXAMPLE OF POPUP THAT REQUIRES MANUAL DISMISSAL:**
(I think this should remain manual until redesign is live)
![ss (2019-03-28 at 10 11 27)](https://user-images.githubusercontent.com/26891718/55210845-9784e200-51a6-11e9-98d5-daa164289087.png)

**EXAMPLE OF POPUP THAT ALREADY IS AUTOMATICALLY DISMISSED:**
(dismisses after ~4 seconds)
![ss (2019-03-28 at 10 19 06)](https://user-images.githubusercontent.com/26891718/55211045-8ee0db80-51a7-11e9-86d1-f6da9e2d3087.png)

**Comment by wtzb** [comment]
We're handling notifications differently in [GAU](https://beta.mycrypto.com/), so this should be obsolete :)
