### ISSUE TITLE
[Feature Request] Display "nonce is too low" error BEFORE user goes to "Confirm Transaction"

### ISSUE THREAD

**Issue by jspence425** [MyCryptoHQ/MyCrypto#2465]
From psnotadev#2000 in Discord:

"feature request: if txn is going to receive a "nonce too low" error, show error before "confirm transaction" popup"

Basically, if a transaction is going to fail because the nonce is too low, we should detect that beforehand and display the error/warning before the user attempts to go through with the transaction. (That's how I interpreted this)

**Comment by jspence425** [comment]
More about nonce: 

"might be nice to be able to click anywhere in the notice box to dismiss it, not just the X
my strategy for fixing the "nonce too low" issue is to click over to the Request Payment tab, then click back to the Send Ether & Tokens tab.  This seems to refresh the nonce"

**Comment by wtzb** [comment]
This error seems to no longer be a thing in GAU, and uses the appropriate nonce if a lower one is manually used :+1:
