### ISSUE TITLE
Transaction with specific data fails from Ledger wallet in Google Chrome 

### ISSUE THREAD

**Issue by voldemarz** [MyCryptoHQ/MyCrypto#2485]
### Description of Issue
Transaction from Ledger wallet with specific DATA contents results in "incorrect" transaction with wrong "From" address and thus transactions fails with error claiming that there are not enough funds.

Data causing this error:
0xaa0b7db72e4ce97d7a3090b086c7a48b1df5c0986fd2ab42ab6b69a1543d2c5b55c00d960000000000000000000000000000000000000000000000000000000000712cdd0000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000004110bc253955794fb2e444675db13cf351ce4cf6635ffb8584f33b15728a5823293707af47f700c2577ab0b3448e20d004d90059494125919bad118bab318b02e30000000000000000000000000000000000000000000000000000000000000000

Problems seems to happen only in Google Chrome. Brave browser and Opera didn't have the problem. Reproduced with 2 different Ledger initialized with different seeds.

### What exactly were you doing when you encountered this issue?
Trying to send ETH to a contract with specific data.

### How were you accessing your wallet?
Ledger Nano S (Firmware 1.4.2, MCU 1.6)

### Description of Your Machine

- Browser: Google Chrome
- Browser version: Version 73.0.3683.103 (Official Build) (64-bit)
- Operating system: Windows 10 (version 1803)
- Device: Reproduced on 2 different PCs
- MyCrypto.com

### Console Logs / Screenshots
![mcr3](https://user-images.githubusercontent.com/1264210/55676417-475bfd00-58d5-11e9-961f-7a9b64395992.png)
![mcr4](https://user-images.githubusercontent.com/1264210/55676419-4c20b100-58d5-11e9-97d9-a7f4f28e9eab.png)

**Comment by voldemarz** [comment]
Just updated ledger to firmware 1.5.5 and MCU 1.7 and issue is gone.

**Comment by tayvano** [comment]
https://twitter.com/nicksdjohnson/status/1124800564666089473?s=19

**Comment by wtzb** [comment]
Thanks for opening this issue! As this appears to be solved by updating your Ledger device to the latest version, I'm closing this issue. However, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us) if you think there might be more to this issue. Thanks for helping us and letting us know of any issues you might run into!
