### ISSUE TITLE
Nonce check on confirmation screen

### ISSUE THREAD

**Issue by robertandrewsmith** [MyCryptoHQ/MyCrypto#2502]
This is a work flow update request based on conversation with Tay in Issue #2484.

The purpose is to provide the user with network feedback about nonce construction during steps taken in MyCrypto software in the broadcasting of a transaction.  If the nonce is unsequenced or out of order MyCrypto will return a message on the confirmation screen BEFORE broadcasting the transaction.  This ought to prevent bad nonce constructions from being sent with the broadcast transaction and prevent users from wondering why their transaction wasn't mined or isn't pending.

Ideally the nonce check would happen between the continue screen and broadcast screen presenting the user with a green or red nonce check mark or 'x' indicating incorrect or correct construction.  If incorrect the user would not be able to go ahead and broadcast.  A "?" link could be included next to the nonce verification indicator on this screen, as well as during the generation of a transaction (both online and offline)

Users need clear information about what is required and/or happening with regard to nonce use, as this is a critical aspect of sending value and data into the blockchain.

Feel free to discuss below.

This applies to all versions of MyCrypto.

**Comment by wtzb** [comment]
Closing - see https://github.com/MyCryptoHQ/MyCrypto/issues/2484#issuecomment-578687409.
