### ISSUE TITLE
sign transaction button disabled when offline

### ISSUE THREAD

**Issue by dec1** [MyCryptoHQ/MyCrypto#2510]
### Description of Issue

Not possible to sign a transaction offline

...

### What exactly were you doing when you encountered this issue?

Download linux-x86-64_1.5.3_MyCrypto.AppImage, copy to offline computer and install it  there

start mycrypto.

open wallet by entering private key

enter to address, amount etc
Unable to enter nonce .. spinner spinning
and "Sign Transaction" button is disabled

### How were you accessing your wallet?

Private key

### Description of Your Machine

- Browser: Firefox
- Browser version:
- Operating system: opensuse leap 15
- Device: virtual machine (vmware)  linux guest on mac (mojave) host (with network disabled for guest)
- linux-x86-64_1.5.3_MyCrypto.AppImage

### Console Logs / Screenshots
vendors~client.undefined.js:22 POST https://mainnet.infura.io/mycrypto net::ERR_INTERNET_DISCONNECTED
Ke.call.e @ vendors~client.undefined.js:22
getCurrentBlock @ vendors~client.undefined.js:22
(anonymous) @ vendors~client~vendor.undefined.js:19
C @ vendors~client~vendor.undefined.js:19
(anonymous) @ vendors~client~vendor.undefined.js:19
(anonymous) @ vendors~client~vendor.undefined.js:19
C @ vendors~client~vendor.undefined.js:19
O @ vendors~client~vendor.undefined.js:19
v @ vendors~client~vendor.undefined.js:19
(anonymous) @ vendors~client~vendor.undefined.js:19
C @ vendors~client~vendor.undefined.js:19
O @ vendors~client~vendor.undefined.js:19
_ @ vendors~client~vendor.undefined.js:19
I @ vendors~client~vendor.undefined.js:19
(anonymous) @ vendors~client~vendor.undefined.js:19
C @ vendors~client~vendor.undefined.js:19
O @ vendors~client~vendor.undefined.js:19
v @ vendors~client~vendor.undefined.js:19
Promise resolved (async)
U @ vendors~client~vendor.undefined.js:19
(anonymous) @ vendors~client~vendor.undefined.js:19
C @ vendors~client~vendor.undefined.js:19
O @ vendors~client~vendor.undefined.js:19
v @ vendors~client~vendor.undefined.js:19
P @ vendors~client~vendor.undefined.js:19
e.cont @ vendors~client~vendor.undefined.js:19
O @ vendors~client~vendor.undefined.js:19
v @ vendors~client~vendor.undefined.js:19
c @ vendors~client~vendor.undefined.js:19
v @ vendors~client~vendor.undefined.js:19
Promise resolved (async)
U @ vendors~client~vendor.undefined.js:19
(anonymous) @ vendors~client~vendor.undefined.js:19
C @ vendors~client~vendor.undefined.js:19
(anonymous) @ vendors~client~vendor.undefined.js:19
(anonymous) @ vendors~client~vendor.undefined.js:19
C @ vendors~client~vendor.undefined.js:19
O @ vendors~client~vendor.undefined.js:19
v @ vendors~client~vendor.undefined.js:19
(anonymous) @ vendors~client~vendor.undefined.js:19
C @ vendors~client~vendor.undefined.js:19
O @ vendors~client~vendor.undefined.js:19
_ @ vendors~client~vendor.undefined.js:19
I @ vendors~client~vendor.undefined.js:19
(anonymous) @ vendors~client~vendor.undefined.js:19
C @ vendors~client~vendor.undefined.js:19
O @ vendors~client~vendor.undefined.js:19
v @ vendors~client~vendor.undefined.js:19
Promise resolved (async)
U @ vendors~client~vendor.undefined.js:19
(anonymous) @ vendors~client~vendor.undefined.js:19
C @ vendors~client~vendor.undefined.js:19
O @ vendors~client~vendor.undefined.js:19
v @ vendors~client~vendor.undefined.js:19
P @ vendors~client~vendor.undefined.js:19
e.cont @ vendors~client~vendor.undefined.js:19
O @ vendors~client~vendor.undefined.js:19
v @ vendors~client~vendor.undefined.js:19
c @ vendors~client~vendor.undefined.js:19
v @ vendors~client~vendor.undefined.js:19
(anonymous) @ vendors~client~vendor.undefined.js:19
client.undefined.js:1 4
...

**Comment by robertandrewsmith** [comment]
The older version 1.5.3 that you are using was known to have that bug. (I had that same problem)
The bug was fixed. Try downloading and using the latest release 1.6.4.  It will work.

**Comment by blurpesec** [comment]
Hello! As was mentioned by @robertandrewsmith, this was fixed in a previous release by PR #2427

**Comment by dec1** [comment]
OK. Thanks.
Downaload links  (eg https://download.mycrypto.com/ ?) must have been stale  since this was the latest version which was available a few days ago.

**Comment by nickmccurdy** [comment]
What version do you see on the download site? It should download 1.6.4, and 1.6.2-1.6.4 should work.

**Comment by seigs6** [comment]
live your liev.. bingo 
hallifex viber RIPER
