### ISSUE TITLE
Will Not Connect to Ledger Nano S

### ISSUE THREAD

**Issue by kshoufer** [MyCryptoHQ/MyCrypto#2516]
*Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email support@mycrypto.com for faster attention.*

*If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!*

---

### Description of Issue

...

### What exactly were you doing when you encountered this issue?

...Give us some steps to reproduce...

### How were you accessing your wallet?

...Ledger, Trezor, MetaMask, Private Key, Keystore File, Parity Signer, Mnemonic Phrase?...

### Description of Your Machine

- Browser:
- Browser version:
- Operating system:
- Device:
- MyCrypto.com vs Desktop Application?
- MyCrypto Version Number:

### Console Logs / Screenshots

...

**Comment by kshoufer** [comment]
I'm trying to connect to my Ledger Nano S and it gives the error message "Your Ledger is currently in use with another application. Please wait, or close other wallet applications before trying again."

I have no other wallets open.
![mycrypto error message](https://user-images.githubusercontent.com/2176679/56460949-aa32a700-635f-11e9-939c-560d75b9a9e4.jpg)

**Comment by SharonManrique** [comment]
What ledger firmware are you on @kshoufer 

These issuse could be related: 
https://github.com/MyCryptoHQ/MyCrypto/issues/2485
https://github.com/MyCryptoHQ/MyCrypto/issues/2433

**Comment by wtzb** [comment]
Thank you so much for opening this issue. From our experience, it appears that this issue is solved by updating your Ledger firmware to the latest version. Because of this, I'm closing this issue here. However, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us) if you think there might be more to this issue, thank you so much for reporting it!
