### ISSUE TITLE
Cancel Previous Transaction

### ISSUE THREAD

**Issue by robertandrewsmith** [MyCryptoHQ/MyCrypto#2517]
This a functional design request for all MyCrypto wallet versions based on discussion and feedback from Issue #2484 .  

The design function should easily allow a user the ability to construct and broadcast a transaction, for the purpose of cancelling a previously broadcast tx, using the same nonce as the previously broadcast tx, but using zero ETH plus a higher gas price.

The place to add and operate this CANCEL function would be in the "Check Transaction Status" menu item.  A rename of the menu item to "Check Status or Cancel Transaction" should be made.  In this UI, the transaction to be cancelled should be selected, as normally would be to check the tx status.  Once the date or hash of the previous tx is selected, a cancel option is presented.  MyCrypto then wizards the UX with a reconstructed TX where the user must only select a higher gas price.  Lower gas price options aren't allowed.

Additional context: I broadcast a tx on March 26, 2019 (but it did not show as pending at the time on either etherscan or etherchain).  This tx was mined into a block on April 14, 2019.  A mining pool <apparently> withheld the tx at the time due to my use of a non-sequential nonce.  Therefore, immediately after I broadcast a new tx with the correctly sequenced nonce (-1) from my error, then the mining pool released the old tx and mined it into a block.

This should never happen to a user.

Please provide suggestions or your feedback below:

**Comment by wtzb** [comment]
Closing - see https://github.com/MyCryptoHQ/MyCrypto/issues/2484#issuecomment-578687409.
