### ISSUE TITLE
how to connect to my private chain?

### ISSUE THREAD

**Issue by MrFanLee** [MyCryptoHQ/MyCrypto#2518]
how to connect to my private chain?

I install MyCrypto, but i don't kown how to connect to my private chain, if there is a way to do that?

**Comment by nickmccurdy** [comment]
If you have your own node you'd like to use locally, try this: https://support.mycrypto.com/developers/run-your-own-node-with-mycrypto

If you want to set up a new network or node, try this: https://support.mycrypto.com/developers/adding-a-new-network

**Comment by MrFanLee** [comment]
thank you , got it

**Comment by MrFanLee** [comment]
i kown how it works， but I am using a windows system, how to set up in mycrypto software to connect to my own Ethereum private chain：

**Comment by MrFanLee** [comment]
> 如果您想在本地使用自己的节点，请尝试以下操作：[https](https://support.mycrypto.com/developers/run-your-own-node-with-mycrypto)：[//support.mycrypto.com/developers/run-your-own-node-with-mycrypto](https://support.mycrypto.com/developers/run-your-own-node-with-mycrypto)
> 
> 如果要设置新的网络或节点，请尝试以下操作：[https](https://support.mycrypto.com/developers/adding-a-new-network)：[//support.mycrypto.com/developers/adding-a-new-network](https://support.mycrypto.com/developers/adding-a-new-network)

I am using a windows system, how to set up in mycrypto software to connect to my own Ethereum private chain：

**Comment by nickmccurdy** [comment]
Did you try those links on Windows?

**Comment by danirabbani90** [comment]
i have problem connecting to private chain on TOMO its not showing the balance the reason for that is we need to change the eth_GetBalance , pending to latest . but its in library so cannot do anything but the problem is that

**Comment by wtzb** [comment]
Thank you for opening this issue! In an effort to clean up our Github issues, I will be closing this issue here. However, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us) if you need any additional help, or have any questions.
