### ISSUE TITLE
Names Migrated to new ENS Registrar don't resolve

### ISSUE THREAD

**Issue by blurpesec** [MyCryptoHQ/MyCrypto#2545]
### Description of Issue

After migrating an ens name to the new registrar, it no longer resolves on MyCrypto.

### What exactly were you doing when you encountered this issue?

View-Only address page in https://localhost:3443/account
Type in `mycryptoid.eth` and it resolves correctly.
Type in `harrydenley.eth` and it does not resolve correctly.

**Comment by wtzb** [comment]
This is solved in [GAU](https://beta.mycrypto.com) :+1:
