### ISSUE TITLE
Can Not Connect to Custom Node

### ISSUE THREAD

**Issue by stone212** [MyCryptoHQ/MyCrypto#2547]
### Description of Issue

myCrypto can not connect to Custom network and node

### What exactly were you doing when you encountered this issue?

Open myCrypto desktop app

Change Network

Add Custom Node

Choose "Custom" for coin

Fill in information with:

Name
chain spec ID (decimal value)
http://ip-address:8545

### How were you accessing your wallet?

...Ledger, Trezor, MetaMask, Private Key, Keystore File, Parity Signer, Mnemonic Phrase?...

### Description of Your Machine

- Browser:
- Browser version:
- Operating system:
- Device:
- MyCrypto.com vs Desktop Application?
- MyCrypto Version Number:

### Console Logs / Screenshots

UI Error:

```
Could not connect to the node. Refresh your page, try a different node (upper right corner), check your firewall settings. If custom node, check your configs.
```

**SOLUTION** Must specify

[rpc]
interface = "all"

[websockets]
interface = "all"

**Comment by danirabbani90** [comment]
i am facing the similar issue inside that for the custom node can someone please help thanks

**Comment by danirabbani90** [comment]
i have figured it out that why the libraries arent showing the balance of the particular address its there any possibility we can change requests.ts ('pending ') status to 'latest'  so that custom node will be able to gather there information.

**Comment by stone212** [comment]
SOLUTION Must specify

[rpc]
interface = "all"

[websockets]
interface = "all"
