### ISSUE TITLE
Link to PGP key used for signing the checksums file

### ISSUE THREAD

**Issue by john-light** [MyCryptoHQ/MyCrypto#2560]
On the release page, a signed `checksums.txt` file is provided to users. However there are no instructions in the release notes or the README file for how to verify this signed file, including where to download the PGP key used to sign this file. After some searching, I found instructions on the [MyCrypto blog](https://medium.com/mycrypto/announcing-the-mycrypto-desktop-alpha-release-44e09f8b3248) but I think these instructions / at least a link to the key could be put in the release notes and/or README file too.

**Comment by robertandrewsmith** [comment]
I had the same problem when I first downloaded MyCrypto.  This is a great idea. I hope they actually implement this.  It should be a very easy fix and would benefit many first time users.

**Comment by nickmccurdy** [comment]
There's a link on the download page.

![](https://files.slack.com/files-pri/T79FNK78W-FK5RKJUNR/67e71efc21540e46.png)
