### ISSUE TITLE
JS asset file name hashes are 'undefined'

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#2563]
### Description of Issue

The url's of the various JS bundles contain the word `undefined`, which would seem to indicate whatever content hash is added there for cache busting isn't properly set. This might cause launches of new code to load old assets if they have them cached, especially since there are some hefty cache-control headers in place right now.

Example of one such asset: https://mycrypto.com/badBrowserCheckA.undefined.js

**Comment by nickmccurdy** [comment]
I don't think we've had issues with caching like this, but thanks for pointing this out, we'll be cautious of it
