### ISSUE TITLE
[LEGACY] Issues with address array vs. single-entry

### ISSUE THREAD

**Issue by tayvano** [MyCryptoHQ/MyCrypto#257]
Just ran into this on v3 and had never seen it before. Low prio, but wanted to make sure we keep this in mind for v4. It may be that it's not an issue in v4, in which case we can simply close this.

https://github.com/kvhnuke/etherwallet/issues/1047

> My contract can get array of "address" values as method parameter. But when I try to execute that method from MyEtherWallet (by pressing Write button), it fails with console errors: `BigNumber() not a number:..............`

![](https://user-images.githubusercontent.com/987517/30656891-457b9c1e-9e3e-11e7-95e5-eb665477da18.png)

**Comment by HenryNguyen5** [comment]
This issue is still presenting using the ABI
```json
[
   {
      "constant":false,
      "inputs":[

      ],
      "name":"kill",
      "outputs":[

      ],
      "payable":false,
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "constant":false,
      "inputs":[
         {
            "name":"to",
            "type":"address[]"
         }
      ],
      "name":"share",
      "outputs":[

      ],
      "payable":true,
      "stateMutability":"payable",
      "type":"function"
   },
   {
      "constant":true,
      "inputs":[

      ],
      "name":"got",
      "outputs":[
         {
            "name":"",
            "type":"uint256"
         }
      ],
      "payable":false,
      "stateMutability":"view",
      "type":"function"
   },
   {
      "constant":false,
      "inputs":[

      ],
      "name":"mortal",
      "outputs":[

      ],
      "payable":false,
      "stateMutability":"nonpayable",
      "type":"function"
   }
]
```
On the function `send`

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837163)

**Comment by elenadimitrova** [comment]
Definitely still a problem

![Screen Shot 2019-05-13 at 14 37 34](https://user-images.githubusercontent.com/703848/57618749-efc44780-758c-11e9-9274-83c254cb18e5.png)

**Comment by wtzb** [comment]
This issue has been moved to our internal project management system.
