### ISSUE TITLE
Custom tokens don't get saved when there's no balance on Go network, possibly multiple

### ISSUE THREAD

**Issue by wtzb** [MyCryptoHQ/MyCrypto#2590]
### Description of Issue

Custom tokens don't get saved when the wallet has no balance of such tokens on networks such as Go. This is especially confusing to people who believe their wallet holds funds of said tokens, but are unable to find them as there is no clear indicator of there being none, it simply disappears. An improvement would be to show a zero instead, like on other networks.

On the ETH and ETH testnet networks, it works as intended, showing a 0 when there are no funds. I'm unsure why this doesn't appear to happen on other networks such as Go. I'm unsure if multiple networks are affected.

### What exactly were you doing when you encountered this issue?

1. Access Go network.
2. View wallet address, any address will suffice.
3. Add custom token, such as `0x5347FDeA6AA4d7770B31734408Da6d34a8a07BdF` as contract address.
4. The fields will get populated, but the token won't get saved when clicking 'Save', it will simply disappear.

### Description of Your Machine

Any.

### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/11412480/58433317-fd162180-80b6-11e9-93ee-1376d07a0600.png)

![image](https://user-images.githubusercontent.com/11412480/58433323-01423f00-80b7-11e9-9baa-72cc3569330f.png)

**Comment by tayvano** [comment]
Ohh we should make sure this doesnt stay in GAU codebase.

Basically, all tokens should be hidden if they have a 0 balance EXCEPT when they are a custom token that the user manually added.

**Comment by wtzb** [comment]
I believe this issue is no more in GAU, closing :)
