### ISSUE TITLE
Broken input "Data" field in section "View & Send > Send Ether & Tokens" of MyCrypto Desktop Application v1.6.6

### ISSUE THREAD

**Issue by ltfschoen** [MyCryptoHQ/MyCrypto#2592]
*Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email support@mycrypto.com for faster attention.*

*If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!*

---

### Description of Issue

MyCrypto Desktop Application's "Data" field is broken, because when I go to the section "View & Send", unlock a sender account, choose "Send Ether & Tokens" from the selection box, then enter a valid "To Address", 0 ETH for the "Amount", and a specific hex value like `0x012345123451234512345123451234512345123451234512` for the "Data" field (Input Data) to send, and then click the "Send Transaction" button it opens a popup called "Confirm Transaction" but when I click the "Details" button in the popup it shows a "Raw Transaction" heading where the value of the "data" key hasn't been populated with the value
that I'd just entered as the value of the "Data" field.

It shows:
```
{
  "value": "0x0",
  "data": "0x",
  ...
}
```

Instead of showing
```
{
  "value": "0x0",
  "data": "0x012345123451234512345123451234512345123451234512",
  ...
}
```

### What exactly were you doing when you encountered this issue?

I am using Debian 9 (Linux).
I downloaded MyCrypto Desktop file linux-x86-64_1.6.6_MyCrypto.AppImage.
I validated the SHA256 checksum of the downloaded file.
I make the file executable by running `chmod u+x linux-x86-64_1.6.6_MyCrypto.AppImage`.
I double clicked the icon of the file to run the MyCrypto Desktop app
I clicked "View & Send" to navigate to "MyCrypto > View & Send"
I then chose and unlocked the account I wanted to use to send the transaction.
I then chose "Send Ether & Tokens" from the selection box.
I then entered another valid Ethereum mainnet address for the value of the "To Address".
I then entered 0 ETH for the "Amount".
I then clicked the "Advanced" button and it revealed the "Data" field.
I then entered a value in the the "Data" field (e.g. `0x012345123451234512345123451234512345123451234512`).
I then clicked the "Send Transaction" button and it opened a popup called "Confirm Transaction" where I could confirm the transaction.
I then clicked the "Details" button in the popup and under the "Raw Transaction" heading
it showed that the value of the "data" key hadn't been populated with the value
that I'd just entered as the value of the "Data" field.
```
{
  "value": "0x0",
  "data": "0x",
  ...
  "chainId": 1
}
```
I then sent the transaction and after it was mined successfully I went to inspect the transaction at etherscan.io, and found that the value of the transaction's "Input Data" was empty. 

### How were you accessing your wallet?

Keystore File

### Description of Your Machine

- Browser: Chrome
- Browser version: Version 73.0.3683.86 (Official Build) (64-bit)
- Operating system: Debian 9
- Device: N/A
- MyCrypto.com vs Desktop Application? MyCrypto Desktop Application
- MyCrypto Version Number: v1.6.6

### Console Logs / Screenshots

N/A

**Comment by ltfschoen** [comment]
When the user enters a value in the "Data" field, it calls [`isValid`](https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/components/DataField.tsx#L15) to check if the field is valid or not. The "Data" field is valid if it's an empty string (user hasn't entered a value for it at all) or if the user has entered a non-empty string, it checks if value as an argument to `isHexString(RAW_INPUT_DATA_STRING)` (from the 'ethereumjs-util' library) returns `true`, [as shown here](https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/components/DataFieldFactory/DataInputFactory.tsx#L37)

But it if you [look at that function in the 'ethereumjs-util' library](https://github.com/ethjs/ethjs-util/blob/master/dist/ethjs-util.js#L2104), and you try matching a hex address like `0x0123456789ABCDEFABCDEFABCDEFabcdefabcdefabcdefab` (which contains only 0-9, A-F, and a-f, with that Regular Expression `!value.match(/^0x[0-9A-Fa-f]*$/)`, it returns false. But if you remove the trailing `$` from the regex then it returns true as expected (e.g. https://regexr.com/4eq2s).

But doing it this was without the `$`, then if the hex value contains a non-hex characters (i.e. G-Z or g-z), it still returns `true` if it finds are valid hex characters on the left of the non-hex characters.

Is `isHexString` incorrect? Do we need to raise an issue in the  'ethereumjs-util' repository?
Should we be using `isHexString` from 'ethereumjs-util' with MyCrypto? Or am I using it incorrectly?

What is the purpose of this part of the `isHexString` function?
```
if (length && value.length !== 2 + 2 * length) {
  return false;
}
```

Based on the signature of the `isHexString` function, I'd write it's body something like the following, instead of the way it has been written in 'ethereumjs-util' :
```
function isHexString(value, length) {
  if (typeof value !== 'string') {
    return false;
  }

  // Check for hex prefix
  if (value.substring(0, 2) !== '0x') {
    return false;
  }

  // Extract hex value without the 0x prefix
  const postfixValue = value.slice(2);
  if (!postfixValue.length) {
    console.log("No characters found after 0x prefix");
    return false;
  }
  
  // Check if non-hex character exists after 0x prefix
  const match = /[^0-9A-Fa-f]/.exec(postfixValue);
  if (match) {
    console.log("Non-hex character match found at " + match.index);
    return false;
  }

  // Check if the hex string is the expected length
  if (postfixValue.length !== length) {
    console.log(`Hex value length is ${postfixValue.length} but should be ${length}`);
    return false;
  }

  return true;
}

console.log(isHexString('0x0123456789ABCDEFABCDEFABCDEFabcdefabcdefabcdefab', 48));
```

**Comment by ltfschoen** [comment]
Note that at "View & Send" if you enter a "data" value of 0x123 and click "Send Transaction", it opens the "Confirm Transaction" window, where if you click "Details" and choose "Raw Transaction", it then shows that this value is changed to a "data" value of 0x0123 (i.e. it added an extra '0')

**Comment by ltfschoen** [comment]
This should not be a stale issue

**Comment by mwbailey** [comment]
Hi @ltfschoen,

Is it possible you're inadvertently adding an extra space (or control character) at the end of the data field input? That's the only way I can reproduce the error.

It looks like the newer [beta version](https://beta.mycrypto.com) of MyCrypto handles this case better. The user is informed of the invalid hex string before they can hit 'Send' instead of silently omitting the data from the transaction.

> But it if you look at that function in the 'ethereumjs-util' library, and you try matching a hex address like 0x0123456789ABCDEFABCDEFABCDEFabcdefabcdefabcdefab (which contains only 0-9, A-F, and a-f, with that Regular Expression !value.match(/^0x[0-9A-Fa-f]*$/), it returns false. But if you remove the trailing $ from the regex then it returns true as expected (e.g. https://regexr.com/4eq2s).

That should definitely return true (and does for me). If removing the trailing '$' changes the return value from false to true, that would be consistent with a space character at the end.

> What is the purpose of this part of the `isHexString` function?
> 
> ```
> if (length && value.length !== 2 + 2 * length) {
>   return false;
> }
> ```

The `length` parameter of `isHexString()` refers to the length in bytes. Since one byte is represented by two hex characters, the length of the hex string after the '0x' should be twice the number of bytes.

> Note that at "View & Send" if you enter a "data" value of 0x123 and click "Send Transaction", it opens the "Confirm Transaction" window, where if you click "Details" and choose "Raw Transaction", it then shows that this value is changed to a "data" value of 0x0123 (i.e. it added an extra '0')

Since each byte of data is derived from two hex characters, the hex string length needs to be even. Odd-length hex strings are padded with '0' to make it even.
