### ISSUE TITLE
Desktop App calls unselected third party APIs on connection failure

### ISSUE THREAD

**Issue by Gustav-Simonsson** [MyCryptoHQ/MyCrypto#2651]
### Description of Issue
When starting the Desktop App offline, it makes HTTPS requests to github, Infuria, Etherscan and MyCrypto's servers, even though only "MyCrypto" is selected by default under the "Ethereum tab" in the "Change Network" menu.

It then continuously attempts requests to Infuria, Etherscan and MyCrypto's servers, even though only one network provider is selected.

These requests include a HTTP User-Agent identifying the users app version and OS type.

If changing the network selection to e.g. Infuria, the app still attempts requests to Etherscan and MyCrypto.

The app was intentionally launched offline, the issue here seems to be that another (unselected) third party is called if the request to the selected party fails.

So this looks like a privacy issue in the sense that it would leak user IP, app version and OS type to an unselected third party provider if there are connectivity issues with the selected provider.

Would recommend to rework the provider connectivity logic so that requests to an unselected provider can never happen, and also more clearly inform the user of provider choices as it impacts user privacy.

Would also more clearly inform the user that e.g. github is called once on app startup now that M$ have acquired github and is not known for having the best history of user privacy/tracking.

As github appears to be called to check for the latest release, we can improve user privacy by tracking the latest app version on the blockchain™ and comparing against the local app version.

### What exactly were you doing when you encountered this issue?

Started the desktop app offline and then selected different providers under the "Change Network" menu.

### How were you accessing your wallet?

This is before accessing any wallet.

### Description of Your Machine

- Browser: N/A (desktop app)
- Browser version: N/A
- Operating system: Linux
- Device: N/A
- MyCrypto.com vs Desktop Application? Desktop
- MyCrypto Version Number: linux-x86-64_1.6.8_MyCrypto.AppImage

### Console Logs / Screenshots
```
Failed to load resource: net::ERR_NAME_RESOLUTION_FAILED
api.mycryptoapi.com/eth Failed to load resource: net::ERR_NAME_RESOLUTION_FAILED
api.etherscan.io/api Failed to load resource: net::ERR_NAME_RESOLUTION_FAILED
mainnet.infura.io/v3/c02fff6b5daa434d8422b8ece54c7286 Failed to load resource: net::ERR_NAME_RESOLUTION_FAILED
api.mycryptoapi.com/eth Failed to load resource: net::ERR_NAME_RESOLUTION_FAILED
api.github.com/repos/MyCryptoHQ/MyCrypto/releases Failed to load resource: net::ERR_NAME_RESOLUTION_FAILED
```

```
Uncaught (in promise) Error: eth_mycrypto to manually set to is not online
    at fe.callback.r (vendors~client.undefined.js:22)
    at vendors~client.undefined.js:37
    at Generator.next (<anonymous>)
    at O (vendors~client~vendor.undefined.js:19)
    at v (vendors~client~vendor.undefined.js:19)
    at a (vendors~client~vendor.undefined.js:19)
    at Object.put (vendors~client~vendor.undefined.js:19)
    at vendors~client~vendor.undefined.js:19
    at Array.<anonymous> (vendors~client~vendor.undefined.js:19)
    at Object.emit (vendors~client~vendor.undefined.js:19)

```

**Comment by tayvano** [comment]
Hey, thanks for bringing this to our attention. In attempt to resolve another unrelated issue, this became an issue. I didn't realize the scope of it but....ugh.

We are currently in the midst of a big update and the way we handle networks and nodes is different and handled in such a way that doesn't needlessly ping out, especially when a user is offline or have a custom node set up. We are working on the assumption that anyone that is working offline or with a custom node is an advanced user and doing so with intention, likely for privacy and/or security purposes. 

I'll have someone look into the github ping as that may need to be proxied or removed entirely moving forward to protect the privacy of end users.

Thanks again for such a detailed report and making your concerns known.

**Comment by tayvano** [comment]
This is partially resolved via https://github.com/MyCryptoHQ/MyCrypto/pull/2674/

Basically we added proxy so at least github doesn't get your direct info, we do. However, we don't track/log any of this (and even if we did, we would already be tracking your ass elsewhere 😉)

**Comment by wtzb** [comment]
Thank you so much for opening this issue, and describing your feedback in such detail. It's really appreciated! With the work we're doing on the new version of MyCrypto, we hope to solve this issue as we're handling networks a bit different.

You can find the new version [here](https://beta.mycrypto.com). I will be closing this issue here, but please let us know if you have any feedback or concerns, we'd love to hear it!
