### ISSUE TITLE
Support iframe based wallets (e.g. ethvault)

### ISSUE THREAD

**Issue by moodysalem** [MyCryptoHQ/MyCrypto#2661]
### Description of Issue

I am working on [Ethvault](https://github.com/ethvault) and want to integrate MyCrypto. Creating this tracking issue to support adding a new wallet type for iframe based providers and for any other discussion

I have an iframe web3 provider that follows the EIP-1193 spec [here](https://github.com/ethvault/iframe-provider)

I am working on implementing this in my fork ethvault/MyCrypto

**Comment by tayvano** [comment]
see discussion on #2663. If anyone is looking for more insight, feel free to open a new issue or ping us at security@mycrypto.com to understand the security concerns we (and our security auditors) have regarding framing.
