### ISSUE TITLE
i have a troble ...

### ISSUE THREAD

**Issue by tppk** [MyCryptoHQ/MyCrypto#2703]
I have some 6 seed grains saved, but I don't have private keys, I also have 20 erc eth addresses with 300eth is somehow I can find them quickly because I can get up to 200 addresses on the grain as I check
nned help
:frowning:
I only used 3 wallets of gulls, operawallets and metamas

**Comment by tayvano** [comment]
Hey @tppk can you email us at support@mycrypto.com so we can better understand your issue and work with you one-on-one to resolve? Thank you.
