### ISSUE TITLE
Support Ledger 44'/60'/1'/0/0 ETH

### ISSUE THREAD

**Issue by nyetwurk** [MyCryptoHQ/MyCrypto#2715]
Support 44'/60'/1'/0/0 natively for the Ledger Nano S so "Custom" isn't required.

**Comment by wtzb** [comment]
Thank you for opening this issue! As this is discussed in detail in https://github.com/MyCryptoHQ/MyCrypto/issues/2070, I'll be closing this issue to keep a better overview of our Github issues. However, thanks for helping us and letting us know of any issues you might run into! It's really appreciated.

Please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us) anytime.
