### ISSUE TITLE
Strange behavior when key-file is invalid

### ISSUE THREAD

**Issue by ligi** [MyCryptoHQ/MyCrypto#2757]
this video shows the error best:

https://youtu.be/2OE6w0zBfcA

so I think 2 things are wrong:
 * the error message should be something like "Invalid Key file" (at this point in time I was not even able to enter a password that I was told is wrong)
 * trying the second time it should also show me an error

**Comment by tayvano** [comment]
Thanks for the report, ligi. I'm on mobile so I couldn't see, are just just selecting a random ass file, or a corrupted keystore file?

Regardless well debug and see if we can fix in short-term.

**Comment by ligi** [comment]
you are most welcome
In this case I am selecting an empty file - mainly to try to reproduce the user error

**Comment by wtzb** [comment]
Thanks for opening this issue, Ligi! We're working on a brand new version of MyCrypto where this should be handled better. You can find it over at [beta.mycrypto.com](https://beta.mycrypto.com/). It doesn't appear to give the odd "Please enter a valid password" error, but instead currently returns nothing at all. I agree it should return something more clear like "Invalid Key file".

I'll add this to our internal project management system, thanks for the report! We really appreciate your feedback :)
