### ISSUE TITLE
MyCrypto no longer works with Frame

### ISSUE THREAD

**Issue by john-light** [MyCryptoHQ/MyCrypto#2848]
### Description of Issue

Up until recently (as recent as a week or two ago) I could use MyCrypto with [Frame](https://frame.sh) using the "Web3" account option. However now when I click on "Web3" I get this error message:

> Web3 not found. Please check that MetaMask is installed

Frame is open, and has given permission to MyCrypto to access the open account. So it should work as it always has for me.

### How were you accessing your wallet?

Frame 0.2.4 + Ledger

### Description of Your Machine

- Browser: Firefox
- Browser version: 70.0.1
- Operating system: Linux Mint 18.3
- Device: Laptop
- MyCrypto.com vs Desktop Application? Web client

### Console Logs / Screenshots

![web3mycrypto](https://user-images.githubusercontent.com/9424721/68598265-78ed0600-046c-11ea-8793-3dd3efa95693.png)

```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). inject.js:12:77

: "Web3 not found. Please check that MetaMask is installed"
    E https://mycrypto.com/client.3dba8f7307fa9ff8f7cb.js:1
    l https://mycrypto.com/client.3dba8f7307fa9ff8f7cb.js:1
    l https://mycrypto.com/client.3dba8f7307fa9ff8f7cb.js:1
    E https://mycrypto.com/client.3dba8f7307fa9ff8f7cb.js:1
    C https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    C https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    O https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    _ https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    I https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    C https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    C https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    O https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    _ https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    R https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    C https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    O https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    v https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    a https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    put https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    s https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    t https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    a https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    c https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    o https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    t https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    emit https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    l https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:57
    n https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:50
    onUnlock https://mycrypto.com/client.3dba8f7307fa9ff8f7cb.js:1
    onUnlock https://mycrypto.com/client.3dba8f7307fa9ff8f7cb.js:1
    s https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:73
    h https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:73
    A https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:73
    A https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:73
    T https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:73
    D https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:73
    E https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:73
    P https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:73
    kr https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:73
    mo https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:73
    He https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:73
    xr https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:73
    yo https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:73
    Er https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:73
client.3dba8f7307fa9ff8f7cb.js:1:170701
    j https://mycrypto.com/client.3dba8f7307fa9ff8f7cb.js:1
    O https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    v https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    P https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    s https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    cont https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    O https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    v https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
    U https://mycrypto.com/vendors~client~vendor.261202b3d844b44e97af.js:13
```

**Comment by bowensanders** [comment]
@john-light What version of Frame are you using? I successfully used it to create an agent transaction to send money to a funds-forwarder contract using MyCrypto on Thursday, and I could re-test this today. Also, are you trying to use the beta.mycrypto.com site?

**Comment by john-light** [comment]
@bowensanders Frame 0.2.4 and this issue is still present. I am using mycrypto.com main site.

**Comment by bowensanders** [comment]
We'll likely have to wait to hear from the devs as to why the old main site no longer works (this was something that worked before Devcon but not after) in the meantime, if you use beta.mycrypto.com frame works just fine.

**Comment by john-light** [comment]
@bowensanders when I select "Web3" on the beta site, I am shown a page with the MetaMask image that says:

> Install Metamask to continue
> Our recommended desktop Web3Provider is the Metamask.io browser extension. Download now to get started!

**Comment by bowensanders** [comment]
I sent you a message via Keybase (only to try to expedite the process of finding where it's failing for you and not me - but in the meantime I'll do a screenshot series to show you what happens on my end (and i'll post it here)

**Comment by bowensanders** [comment]
I know you know what you're doing, btw - I just wanted to demonstrate it working from my end. 
This is from the "send assets" point to finished TX:
<img width="927" alt="Screen Shot 2019-11-12 at 5 42 49 PM" src="https://user-images.githubusercontent.com/27023908/68725750-46c6cb80-0574-11ea-8b57-2ca54a59c212.png">
<img width="916" alt="Screen Shot 2019-11-12 at 5 43 07 PM" src="https://user-images.githubusercontent.com/27023908/68725754-49292580-0574-11ea-9543-18a00ce6ecf7.png">
<img width="1286" alt="Screen Shot 2019-11-12 at 5 43 18 PM" src="https://user-images.githubusercontent.com/27023908/68725759-4b8b7f80-0574-11ea-965c-a812df8abf31.png">
<img width="1256" alt="Screen Shot 2019-11-12 at 5 43 44 PM" src="https://user-images.githubusercontent.com/27023908/68725766-4e867000-0574-11ea-8acc-8f639999ec45.png">
<img width="356" alt="Screen Shot 2019-11-12 at 5 43 59 PM" src="https://user-images.githubusercontent.com/27023908/68725770-5219f700-0574-11ea-9a08-d602196030f0.png">

If you've allowed frame to connect to beta.mycrypto.com, and you've added the account (by using "add account" on the new dashboard) - this should happen when you go to "manage assets > send assets". I'm wondering if you haven't added the account to the dashboard yet? also, maybe try a shift-reload after connecting? There seem to be a couple caching issues there, but we're supposedly using the same version of frame here.

**Comment by john-light** [comment]
@bowensanders I don't think you sent to the right keybase account. anyways, I don't even get as far as the send screen. I cannot open my account at all. This is as far as I get:

![Screenshot_2019-11-12 MyCrypto](https://user-images.githubusercontent.com/9424721/68732356-22cdaf00-05a1-11ea-8451-288792790fba.png)

**Comment by bowensanders** [comment]
Do you have time tomorrow after 11am PT to look into this? I had this problem once but was able to fix it relatively easily, it seemed to be a caching issue... My keybase is @misterboyfriend

**Comment by bowensanders** [comment]
Just replicated the issue on two machines in Firefox Browser (69.0.4 & 70.0.1 64-bit MacOS Catalina) with Frame 0.2.4 and Frame Firefox plugin 0.1.5 (freshly installed)

This does not occur in Chrome or Brave with the same version of Frame. 

The Frame.sh site shows that frame is connecting with the browser and shows account data. 

So far this appears to be a firefox specific issue with MyCrypto rather than with other sites (such as opensea.io)

**Comment by wtzb** [comment]
Thanks for the report! I believe this may be related to https://github.com/MyCryptoHQ/MyCrypto/issues/2061, a CSP issue with Firefox which also affects using Metamask + MyCrypto.

I have since added this issue to our internal project management system, and will also mention Frame along with it. I'll be closing this issue here, as we mainly use our internal system as point of reference. Again, thank you so much for reporting it to us, we really appreciate it!
