### ISSUE TITLE
Adjust Web3 account copy to be more provider-neutral

### ISSUE THREAD

**Issue by john-light** [MyCryptoHQ/MyCrypto#2849]
### Description of Issue

Currently when "Web3" is selected as the account option, the copy is very MetaMask-centric:

![web3mycrypto](https://user-images.githubusercontent.com/9424721/68501767-ed396680-022c-11ea-8c2e-b49e763b59f8.png)

(see main web page copy and error message copy at the bottom)

However, MetaMask, as great as it is, is not the only interface to Web3. There are other options such as Frame (https://frame.sh) that offer similar functionality for interfacing with Web3 enabled apps. I would like to see the copy on this page updated to be more neutral rather than giving the impression that MetaMask is the only Web3 interface (which may have been true at one point but is not true anymore).

**Comment by wtzb** [comment]
Thank you for opening this issue! While this issue is still present on our current site, the work we're doing on the new version of MyCrypto should make it obsolete. Please come check out the beta [here](https://beta.mycrypto.com/).
