### ISSUE TITLE
PGP key used to sign checksums for release 1.7.3 has expired

### ISSUE THREAD

**Issue by anomogh** [MyCryptoHQ/MyCrypto#2861]
### Description of Issue

The PGP key used to sign checksums.txt for release 1.7.3 has expired.

### Steps to reproduce
1. Download checksums.txt.gpg (https://github.com/MyCryptoHQ/MyCrypto/releases/tag/1.7.3)
2. Use gpg to verify signature. It displays a warning saying "This key has expired!"
```
$ gpg --verify checksums.txt.gpg

gpg: Signature made Fri, Nov  8, 2019  3:45:44 AM GTBST
gpg:                using RSA key 1B7A2D12DE76F0F0A2153B62697F4D4B81B15C84
gpg: Good signature from "Taylor <tayvano@gmail.com>" [expired]
gpg: Note: This key has expired!
Primary key fingerprint: 1B7A 2D12 DE76 F0F0 A215  3B62 697F 4D4B 81B1 5C84
```

**Comment by Nogreedy** [comment]
Paging @tayvano 
I have the same issue...   
Thanks in advance for your answer.

**Comment by tayvano** [comment]
Can you guys check now? I believe I've extended the key AND pushed it up everywhere so that it won't return expired anymore.

```
$ gpg --output checksums.txt --decrypt checksums.txt.gpg
gpg: Signature made Thu Nov  7 17:45:44 2019 PST
gpg:                using RSA key 1B7A2D12DE76F0F0A2153B62697F4D4B81B15C84
gpg: Good signature from "Taylor <tayvano@gmail.com>" [ultimate]
```

However I'm checking myself...myself so it's hard for me to tell

**Comment by Nogreedy** [comment]
@tayvano 
Thanks.
I checked and I think it's OK now...

 Invoke-RestMethod https://keybase.io/tayvano/pgp_keys.asc | gpg --import
gpg: clef 8DADC5E518486550 : « Taylor Monahan <tayvano@gmail.com> » n'est pas modifiée
gpg: clef 697F4D4B81B15C84 : « Taylor <tayvano@gmail.com> » 2 nouvelles signatures
gpg:       Quantité totale traitée : 2
gpg:                 non modifiées : 1
gpg:          nouvelles signatures : 2

**Comment by anomogh** [comment]
Everything looks good now @tayvano. Thank you!
