### ISSUE TITLE
MyCrypto Desktop: High CPU and non-responsive UI. (v1.7.3)

### ISSUE THREAD

**Issue by jordanmack** [MyCryptoHQ/MyCrypto#2864]
*Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email support@mycrypto.com for faster attention.*

*If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!*

---

### Description of Issue

During the viewing of my Ethereum account balance, the page became completely non-responsive.

### What exactly were you doing when you encountered this issue?

Viewing my Ethereum account balance on a Ledger S Nano. The page was functioning as expected. I then resized the window and started scrolling. It scrolled fine, then stopped scrolling. The page was basically frozen and all page elements were non-responsive. The File, View, and Help menus still worked.

I was unable to reproduce this issue upon relaunch.

### How were you accessing your wallet?

Ledger S Nano

### Description of Your Machine

- Browser: N/A
- Browser version: N/A
- Operating system: Windows 10
- Device: Ledger S Nano
- MyCrypto.com vs Desktop Application? Desktop
- MyCrypto Version Number: v1.7.3

### Console Logs / Screenshots

This is a screenshot of the CPU usage. This is 100% of 2/8 cores.

![20191119152318](https://user-images.githubusercontent.com/37931/69197488-513e1380-0ae6-11ea-801c-f6989c9659d5.png)

**Comment by wtzb** [comment]
Hi @jordanmack, thank you for letting us know about this issue! Did you by any chance select a token in this '-Token-' field in the address list? We're aware that selecting a token here will make MyCrypto spike CPU usage to 100%, so I wanted to make sure that this is what you may have selected as well.

![image](https://user-images.githubusercontent.com/11412480/69215156-3fbf3f00-0bac-11ea-8ff1-69f61ef7f388.png)

**Comment by jordanmack** [comment]
I don't remember if I had a token selected. I just ran the test again, selecting a random token and it does behave very similarly. I'd guess that this is probably the same issue.

**Comment by lionsoftware** [comment]
I have same issue, when use Device: Ledger S Nano, under Mac OS Catalina (10.15.2), MyCrypto Helper process eats 100% CPU and interface doesn't response

**Comment by wtzb** [comment]
Thank you for opening this issue! While this is still present on our current site, the work we're doing on the new version of MyCrypto should make it obsolete. Please come check out the beta [here](https://beta.mycrypto.com/).

In the meantime, a workaround for this issue on the current site is to not select any option in the "-Token-" dropdown field, as it will cause the application to freeze.

Thanks for helping us and letting us know of any issues you might run into, as it really helps us improve our product. I'm closing this issue here, but please know that we really appreciate any feedback you might have!
