### ISSUE TITLE
Ability to search addresses by index

### ISSUE THREAD

**Issue by nikharR** [MyCryptoHQ/MyCrypto#2879]
This is a feature request on all platforms to allow the user to search for an account by derivation index eg. 'm/44'/0'/0/{index}'

Currently a user would have to click through multiple rows of 5 which is highly inefficient.

**Comment by wtzb** [comment]
Thank you so much for your feedback and for opening this issue! I've added this to our internal project management system, so we have a better overview of what to work on, hence why I'm closing this here. Again, we really appreciate your feedback, if you ever have any other ideas or questions regarding MyCrypto, please be sure to [reach out](https://support.mycrypto.com/contact-us)!
