### ISSUE TITLE
MyCrypto Desktop won't connect to a Ledger Nano S while geth is running

### ISSUE THREAD

**Issue by john-light** [MyCryptoHQ/MyCrypto#2916]
### Description of Issue 

I am trying to use MyCrypto Desktop + Ledger Nano S with a locally-running geth node and getting an error "Your Ledger is currently in use with another application".  I have confirmed that if I shut down the geth node, I can then use the Ledger. So it appears there is something about the geth node running that is causing a conflict.

### What exactly were you doing when you encountered this issue?

1. Start geth node
2. Start MyCrypto Desktop
3. Plug in Ledger and try to connect from MyCrypto Dekstop

### How were you accessing your wallet?

Ledger

### Description of Your Machine

- Operating system: Linux Mint 19.2
- Device: laptop
- MyCrypto.com vs Desktop Application? Desktop
- MyCrypto Version Number: 1.7.4

### Console Logs / Screenshots

![ledgererror2](https://user-images.githubusercontent.com/9424721/70939452-4b205180-2016-11ea-9b54-49c38037c33b.png)

**Comment by Mrtenz** [comment]
It's possible that Geth is trying to access your Ledger somehow. Try running geth with the `--nousb` option and see if it works.

**Comment by john-light** [comment]
@Mrtenz indeed, seems it is not possible for multiple pieces of software to use the Ledger at once. thanks
