### ISSUE TITLE
MyCrypto Desktop works even when local node is shut off

### ISSUE THREAD

**Issue by john-light** [MyCryptoHQ/MyCrypto#2917]
### Description of Issue

I have MyCrypto Desktop set up to use a local geth node as the network. However, even if the geth node is turned off, MyCrypto Desktop is still able to connect to my wallet, sync my balances, etc. How is it doing this if my node is turned off?

**Comment by wtzb** [comment]
MyCrypto uses [Shepherd](https://github.com/MyCryptoHQ/shepherd) to automatically send requests to the best available nodes, you can find a demo [here](https://overflow.mycrypto.com/). If you open up the networks tab in the desktop app (View -> Toggle Developer Tools > Network), it should show the requests being sent to another node.

**Comment by john-light** [comment]
@wtzb I consider that a bug, the point of using my own node is that my data isn't shared with any third parties. If my own node is off, mycrypto should not be trying to connect to third parties behind my back. is there a way to turn "shepherd" off?
