### ISSUE TITLE
socks proxy?

### ISSUE THREAD

**Issue by yohohoro** [MyCryptoHQ/MyCrypto#2937]
How i can use mycrypto linux client over socks?

**Comment by wtzb** [comment]
Thank you for opening this issue! Currently, MyCrypto does not offer any way of connecting through SOCKS from within the application. The best solution to this would be to run a SOCKS proxy on OS-level on your device, so all traffic is routed through the proxy.

Again, thank you so much for opening this issue. Let me know if you have any additional questions!
