### ISSUE TITLE
no data in checksums.txt.gpg

### ISSUE THREAD

**Issue by K4r4Curt** [MyCryptoHQ/MyCrypto#2938]
### Description of Issue
Hi! I've tried to checksum in Kleopatra but after importing the checksums.txt.gpg
got 0 (zero) imports from a file.
What should be done to complete the procedure?

**Comment by wtzb** [comment]
Unfortunately, I'm unaware how to use this with Kleopatra, but we wrote a [knowledge base](https://support.mycrypto.com/staying-safe/verifying-authenticity-of-desktop-app) article explaining in detail how to verify checksums using the command line, it should be pretty straightforward.

Be sure to let us know if you have any questions during the process.
