### ISSUE TITLE
ETC Public API End Point Moving

### ISSUE THREAD

**Issue by gitr0n1n** [MyCryptoHQ/MyCrypto#2985]
*Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email support@mycrypto.com for faster attention.*

*If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!*

---

**Comment by gitr0n1n** [comment]
The Ethereum Classic Kotti Testnet is moving as well.

From "https://kotti.ethereumclassic.network/"  to
"https://www.ethercluster.com/kotti"

**Comment by wtzb** [comment]
Thanks for the report! The updated endpoints will be included in the new version release of MyCrypto :+1: 

https://github.com/MyCryptoHQ/MyCrypto/pull/2983
