### ISSUE TITLE
yarn build:electron fails in Catalina

### ISSUE THREAD

**Issue by nyetwurk** [MyCryptoHQ/MyCrypto#3017]
`yarn build:electron:osx` fails because
```
Error: Exit code: 2. Command failed: /usr/bin/perl /private/var/folders/xz/2y8r_j654sx984cnws7y545h0000gn/T/t-usuhNH/1-dmgProperties.pl
Can't locate Mac/Memory.pm in @INC (you may need to install the Mac::Memory module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.4 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /private/var/folders/xz/2y8r_j654sx984cnws7y545h0000gn/T/t-usuhNH/1-dmgProperties.pl line 4.
BEGIN failed--compilation aborted at /private/var/folders/xz/2y8r_j654sx984cnws7y545h0000gn/T/t-usuhNH/1-dmgProperties.pl line 4.
```
Yep. No `Mac::Memory` in 64 bit perl. Great job Apple.

`yarn build:electron:windows` fails because of all the 32bit wine crap hardcoded in `builder-util/wine.js`

I can do some hacking around it, but eventually rc-edit fails too because it is hardcoded to -ia32.exe

Wonderful.

**Comment by nyetwurk** [comment]
https://github.com/electron-userland/electron-builder/issues/3990
https://github.com/milosdanilov/composer/commit/166d4cf2fbf7bcf05e4e3ed8995e614665c8f932

**Comment by blurpesec** [comment]
Heya, thanks for the report!

Did you run this against `master` or `legacy` branch?
`master` is the branch for beta.mycrypto.com, and `legacy` is the branch for mycrypto.com & the existing production desktop application.

**Comment by nyetwurk** [comment]
`master` and `1.7.7`

**Comment by nyetwurk** [comment]
IMO these stale bots are not ideal

**Comment by mwbailey** [comment]
I get the same error in Catalina (10.15.6) with `legacy`, but `master` branch runs fine. `legacy` is still using an old version of electron-builder (20.13.4) that apparently doesn't have the fix.

**Comment by Mrtenz** [comment]
@mwbailey Thanks for looking into this. This should be fixed when #3363 is merged.

**Comment by nyetwurk** [comment]
#3363 is still unmerged

**Comment by Mrtenz** [comment]
@nyetwurk Thank you for the reminder, there's a few issues we need to resolve before we can merge it. We'll try to get it done ASAP.

**Comment by nyetwurk** [comment]
#3363 is still unmerged

**Comment by Mrtenz** [comment]
Currently blocked by an issue with Trezor devices.

**Comment by Mrtenz** [comment]
Sorry for the delay on this issue. We're still running into issues using specific macOS versions. This will be fixed as soon as those issues are resolved.
