### ISSUE TITLE
Support building on Python 3

### ISSUE THREAD

**Issue by filips123** [MyCryptoHQ/MyCrypto#3055]
Since last year, `node-gyp` supports both Python 2.7 and 3.5+. You should now update `node-gyp` to also support it, or just update documentation if it is already supported.

**Comment by FrederikBolding** [comment]
Agreed, I'll look into this 😄

**Comment by filips123** [comment]
Based on README, it seems Python 3 is still not supported:

> ***Python 3 is **not** supported, since our dependencies use `node-gyp`.

However, newer versions of `node-gyp` already support Python 3 (https://github.com/nodejs/node-gyp/issues/1687#issuecomment-541471076). I haven't tried building this myself on Python 3, but maybe just README needs to be updated.

**Comment by Mrtenz** [comment]
This seems to be related to `node-sass`, still depending on an old version of `node-gyp`: https://github.com/sass/node-sass/blob/master/package.json#L67

We may need to look into an alternative for `node-sass` if we want to support Python 3.
