### ISSUE TITLE
Outdated ENS Registry contract address.

### ISSUE THREAD

**Issue by homotopycolimit** [MyCryptoHQ/MyCrypto#3059]
The MyCrypto Linux App v1.7.7 contains 0x314159265dD8dbb310642f98f50C066173C1259b as the ENS Registry address in the Contracts tab.
This is outdated.
The new address is 0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e

Details:
https://docs.ens.domains/ens-migration/guide-for-dapp-developers

**Comment by homotopycolimit** [comment]
ditto for the public resolver
should be
0x4976fb03C32e5B8cfe2b6cCB31c09Ba78EBaBa41
but is
0x5FfC014343cd971B7eb70732021E26C35B744cc4

**Comment by homotopycolimit** [comment]
ditto for public ens resolver
old: 0x5FfC014343cd971B7eb70732021E26C35B744cc4
current: 0x4976fb03C32e5B8cfe2b6cCB31c09Ba78EBaBa41

**Comment by wtzb** [comment]
Thank you for making us aware of this! We'll include this in the next release, we really appreciate it!
