### ISSUE TITLE
Default Goerli node is outdated or not synced

### ISSUE THREAD

**Issue by lsaether** [MyCryptoHQ/MyCrypto#3067]
When trying to make a transfer of Goerli testnet ether using the default Goerli connection in MyCrypto, the wallet presented an error claiming there was no balance in the account. After switching to an alternative endpoint for Goerli, the transfer could be made without error.

I believe the endpoint that MyCrypto is using for the default Goerli connection is outdate or not synced. Could this be changed so that people using Goerli are not confused?

**Comment by wtzb** [comment]
Hi there @lsaether! Thanks for reporting this to us - it should be all good now. Could you see if you are still experiencing this issue? Thanks! :)
