### ISSUE TITLE
Wrong usage of ABIs in desktop app

### ISSUE THREAD

**Issue by reiven** [MyCryptoHQ/MyCrypto#3076]
### Description of Issue

I'm using gnosis multisig from Contracts, and in the Desktop APP looks like there is something wring, because they way it should work (or at least how it is working in the old mew web interface) it throws an error, asking for `data` which is not requiered, and using `0x` as data, it creates a completely wrong transaction

### What exactly were you doing when you encountered this issue?

Trying to interact with gnosis ABI from DESKTOP

![image](https://user-images.githubusercontent.com/362717/75489161-7f0de080-5990-11ea-882f-f4fe58dc3d4d.png)
![image](https://user-images.githubusercontent.com/362717/75489177-8634ee80-5990-11ea-8fb2-2c45bd2e3599.png)

### How were you accessing your wallet?

Private file (ropsten)

### Description of Your Machine

- MyCrypto.com vs Desktop Application?
Desktop

- MyCrypto Version Number:
v1.7.7

**Comment by wtzb** [comment]
Thanks for opening this issue! Hmm, using `0x` as data should solve this issue, at least for Mist multisigs. Could you let me know how it would generate a wrong transaction when you do that with the Gnosis multisig? I'm not too familiar with them contract-wise.

Thanks!

**Comment by reiven** [comment]
Hi @wtzb looks like its working as expected , thank you!
