### ISSUE TITLE
Unexpected behavior when using the parameters feature in the "Interact with Contracts" page

### ISSUE THREAD

**Issue by VinceBCD** [MyCryptoHQ/MyCrypto#3127]
### Description of Issue

Contract address is not resolved when passing parameters in the url of the "Interact with Contracts" page. Despite the "Select Existing Contract" is well selected, the "Contract Address" field stay empty and a red exclamation mark is displayed.

![image](https://user-images.githubusercontent.com/31089467/77363326-cfd7e580-6d52-11ea-8dac-738a7c1f346f.png)

Please note that when the contract is selected "manually", the address is well resolved.

![image](https://user-images.githubusercontent.com/31089467/77363369-e4b47900-6d52-11ea-963c-4969d0d21864.png)

### What exactly were you doing when you encountered this issue?

Just follow this link:
https://beta.mycrypto.com/interact-with-contracts?network=Ethereum&address=0x90bb0b538253d279642439d5f54f336414ec06f7&function=issuers&input=0:49

### How were you accessing your wallet?

no wallet needed

### Description of Your Machine

- Browser: chrome
- Browser version:  80.0.3987.149 (Official Build) (64-bit)
- Operating system: Windows 10
- Device: Microsoft Surface Pro
- MyCrypto.com vs Desktop Application? MyCrypto.com
- MyCrypto Version Number: beta

**Comment by VinceBCD** [comment]
I would add that in UX terms, the red exclamation mark to indicate the resolved address is not necessarily the best choice: it looks like there's a mistake when the goal would rather be to give confidence to the user

**Comment by FrederikBolding** [comment]
@VinceBCD Could you verify that #3267 fixes your problem?

**Comment by VinceBCD** [comment]
@FrederikBolding, yes ! it seems to be ok using mycryptobuild : https://mycryptobuilds.com/pr/3267/#/interact-with-contracts?network=Ethereum&address=0x90bb0b538253d279642439d5f54f336414ec06f7&function=issuers&input=0:95
but not yet on beta.mycrypto.com. Not yet merged and deploy there, I guess

**Comment by FrederikBolding** [comment]
@VinceBCD Nope not yet. PR will need to be reviewed etc first 😄
