### ISSUE TITLE
Ropsten contract list is not loaded in the "Interact with Contracts" page

### ISSUE THREAD

**Issue by VinceBCD** [MyCryptoHQ/MyCrypto#3128]
### Description of Issue

Unlike the others network, the contract list is not loaded when selecting the Ropsten Network in the "Network" combobox. Only an "Custom" entry is shown. however, there are many contracts listed in the source file ropsten : https://github.com/MyCryptoHQ/MyCrypto/blob/master/common/v2/database/data/contracts/ropsten.json

![image](https://user-images.githubusercontent.com/31089467/77417200-57f6d300-6dc5-11ea-84a5-0c6ca52f4f5d.png)

### What exactly were you doing when you encountered this issue?

Go to https://beta.mycrypto.com/interact-with-contracts and select "Ropsten" in the "Network" combo.
Please note that I've Reset Database in the settings and done a CTRL+F5 in my browser before testing.

### How were you accessing your wallet?

no wallet needed

### Description of Your Machine

Browser: chrome
Browser version: 80.0.3987.149 (Official Build) (64-bit)
Operating system: Windows 10
Device: Microsoft Surface Pro
MyCrypto.com vs Desktop Application? MyCrypto.com
MyCrypto Version Number: beta

**Comment by blurpesec** [comment]
Fixed when #3128 was merged c:
