### ISSUE TITLE
Beta doesn't resolve domain names

### ISSUE THREAD

**Issue by JohnnyJumper** [MyCryptoHQ/MyCrypto#3160]
### Description of Issue
The resolution of ens and unstoppable domains is not working correctly on the beta version of mycrypto. Seems like the code for selecting the address from the address-book intervened with the resolution code. 

### What exactly were you doing when you encountered this issue?
- Went on https://beta.mycrypto.com/send
- Tried to send some ETH to brad.crypto, brad.zil, brad.eth. Instead of resolving them and continuing with the flow, I ended up with an empty dropdown. When I close the dropdown everything clears like I never typed anything. 

### Expectations
- Once the address book dropdown is closed and if nothing was selected from it the resolution code should trigger which will attempt to resolve the domain (.crypto, .eth, .zil) and in case of success placed the address in the label. In case of error should show users the reasons like (domain is not registered, not configured, doesn't have the currency you are trying to send)
 
### How were you accessing your wallet?
MetaMask
### Description of Your Machine

- Browser: Chrome 
- Browser version: Version 80.0.3987.149 (Official Build) (64-bit)
- Operating system: macOS Mojave version 10.14.5
- Device: MacBook Pro (13-inch)
- MyCrypto.com vs Desktop Application? I went to beta.mycrypto.com
- MyCrypto Version Number: 1.7.3 (took this number from bottom left of the website near the word Disclaimer)

### Console Logs / Screenshots
<img width="650" alt="Screen Shot 2020-04-03 at 2 25 36 PM" src="https://user-images.githubusercontent.com/16522024/78406225-0e716980-75b7-11ea-90d4-4b29a497789a.png">
<img width="1080" alt="Screen Shot 2020-04-03 at 2 25 44 PM" src="https://user-images.githubusercontent.com/16522024/78406230-0fa29680-75b7-11ea-9203-7bc1cd0ba658.png">
...

**Comment by blurpesec** [comment]
Thanks for pointing this out Johnny :-)
