### ISSUE TITLE
pushTx does not seem to understand token decimals and can display wrong token amounts

### ISSUE THREAD

**Issue by LefterisJP** [MyCryptoHQ/MyCrypto#3219]
### Description of Issue

Sending a raw signed transaction via https://mycrypto.com/pushTx the prompt does not display the decimals properly for some tokens.

![rect880-9](https://user-images.githubusercontent.com/1658405/80043867-275ca300-8503-11ea-9a28-975d248de173.png)

### What exactly were you doing when you encountered this issue?

Sending a raw signed transaction for a USDC transfer.

That token has 6 decimals as opposed to the usual 18: https://etherscan.io/address/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48#readProxyContract

.. so I assume there must be some UI error that does not take into account the decimals of the token.

**Comment by bowensanders** [comment]
Can you clarify what you're pointing out, exactly? 
The "you'll send" field shows "< 0.000001 USDC" (6 decimal places). 
The "transaction fee" is in ETH so its decimals do not apply to this as an issue.

**Comment by LefterisJP** [comment]
Apologies if the wording is not clear @bowensanders

Yes indeed the issue lies with the USDC sent. It's almost 2 months now so I don't really remember how much I tried to send but it was probably in the 10s or 100s of USDC, so the displayed amount is wrong.

**Comment by bowensanders** [comment]
We're trying to avoid working on the legacy codebase, but this shouldn't be an issue in the beta release going forward.

**Comment by LefterisJP** [comment]
So this is solved in the beta version of mycrypto? Just want to understand.

**Comment by bowensanders** [comment]
We haven't been able to reproduce the issue on beta. We'd love for you to come check it out at beta.mycrypto.com!😁
