### ISSUE TITLE
Please stop (automatically) resetting input fields in desktop App 

### ISSUE THREAD

**Issue by dec1** [MyCryptoHQ/MyCrypto#3222]
Hello.

The desktop app regularly resets its input fields (nonce, to address, amount..).

**Typical scenario**: I want to transfer some funds to an exchange. 

- I fill out all the fields in the desktop app on an offline computer (but use only a very small amount of coins as  a test, first) 
- Sign the transaction
- Go to mycrypto.com on an online computer and broadcast the signed transaction
- Make sure  the coins arrived at the exchange, to verify I entered address, nonce, gas limits and gas price etc appropriately 
- Go back to my offline computer and the desktop app where I want to increase the number of tokens and nonce, _without changing receivers address_!, but as soon as i click into the nonce input field the whole form resets to empty! 

So I effectively cant use the desktop to send a small amount first and then send the real quantity, which is very dangerous. Its very easy to make a mistake and doing a "dry run" first is a great precaution.

Maybe this resetting is by design ,but it is very disadvantageous and dangerous in situations such as above. Please stop this resetting of the input fields, or at least make it possible to disable it as an option somewhere.

Many Thanks in Advance

**Comment by dec1** [comment]
No one consider this important enough to take seriously?

**Comment by wtzb** [comment]
Hi there @dec1! Please accept my apologies for not getting back to you sooner, but I wanted to let you know that this issue has since been added to our internal project management system. At this time, we're working hard on creating a brand new version of MyCrypto, which you can find over at [beta.mycrypto.com](https://beta.mycrypto.com/). Unfortunately, we don't have the desktop app ready for this new version just yet, but I hope that once it's available, you won't have to experience this issue.

Again, we should've gotten back to you sooner. We really appreciate you opening this issue! As it has since been added to our internal system, I will be closing this issue here. Thank you so much!

**Comment by dec1** [comment]
Hello.

Ive just tried the desktop version of mycrypto 1.7.13 and this issue still has not been resolved.
When Can we expect a resolution (in the desktop app)

Best Wishes.

**Comment by Escarcega1989** [comment]
> Hello.
> 
> The desktop app regularly resets its input fields (nonce, to address, amount..).
> 
> **Typical scenario**: I want to transfer some funds to an exchange.
> 
> * I fill out all the fields in the desktop app on an offline computer (but use only a very small amount of coins as  a test, first)
> * Sign the transaction
> * Go to mycrypto.com on an online computer and broadcast the signed transaction
> * Make sure  the coins arrived at the exchange, to verify I entered address, nonce, gas limits and gas price etc appropriately
> * Go back to my offline computer and the desktop app where I want to increase the number of tokens and nonce, _without changing receivers address_!, but as soon as i click into the nonce input field the whole form resets to empty!
> 
> So I effectively cant use the desktop to send a small amount first and then send the real quantity, which is very dangerous. Its very easy to make a mistake and doing a "dry run" first is a great precaution.
> 
> Maybe this resetting is by design ,but it is very disadvantageous and dangerous in situations such as above. Please stop this resetting of the input fields, or at least make it possible to disable it as an option somewhere.
> 
> Many Thanks in Advance

Ok SO FIRST OFF , YOUR FIRST 3 LINES. MY QUESTION IS ARE YOU SURE INPUT FIELDS BELONG TO YOU? I MEAN JUST BE AWARE THAT ALL THINGS MIGHT CHANGE. IF YOU DIDN'T FORK  OR BRANCH SOMETHING.

STOP AND THINK ABOUT WHERE THE INFO COMES FROM ? IT DOESN'T JUST LAND ON "GITS HUB" FOR NO REASON. SOMEONE THAT IS ACTUALLY DOING THE WORK AND HEY IT MIGHT BE A SOURCING FOR SOMETHING THEY BEEN DOING THEIR WHOLE LIFE . 
MAYBE IT IS THEIR LIFE?.
ALL IM SAYING CHECK RESOURCES , MOST OF ALL 
READ READ READ. .

I'M SEEING THIS POST AND REPLYING  SO LATE I JUST IN A MADE  MY OWN PERSONAL PROFILE , NOT KNOWING :HOW THIS WEBSITE WORKS. MOSTLY PUBLIC . IF YOUR DOING BUSINESS PROJECTS MIGHT NEED TO MAKE THEIR INFO PRIVATE. YOU CANT BE GETTING HERE MAKING DEMANDS AND EXPECTING IT TO WORK , IF IT Ain't YOUR LINK TO BE CLICKING.
