### ISSUE TITLE
How there was an out transaction ????

### ISSUE THREAD

**Issue by smartserivceshjf** [MyCryptoHQ/MyCrypto#3238]
*Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email support@mycrypto.com for faster attention.*

*If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!*

---

I never did this transaction:
https://etherscan.io/tx/0xe4236b15519bb297a014baf174de8343f4c08d084e8af27b783e103782898c22

i have mycrypto on my pc i have a file.. the file is on a pendrive.. but a transaction was made...HOW!!!?!? !PLease explain!!!!

**Comment by Mrtenz** [comment]
I'm sorry to hear about this. It's possible that someone got access to your private key without you being aware, or you used your private key on a malicious site somehow. MyCrypto does not store funds for you and we don't have access to your keys.

For further questions please send an email to support@mycrypto.com.
