### ISSUE TITLE
subtract transaction fee from amount to send?

### ISSUE THREAD

**Issue by dchmelik** [MyCryptoHQ/MyCrypto#3249]
### Description of Issue

I'd like to subtract transaction fee from amount to send (to result in natural number in sender wallet.)

### What exactly were you doing when you encountered this issue?

Trying to send; couldn't see fee subtract option (in many/most cryptocurrency wallets such as bitcoin core, most/all imitators/derivatives have.)

### Description of Your Machine

Operating system: POSIX-based
Device: custom PC
Desktop Application MyCrypto Version Number: 1.7.9

### Console Logs / Screenshots

![screenshot](https://user-images.githubusercontent.com/10347890/81036857-8bf9f500-8e55-11ea-9ec4-e17b52bf469d.jpg)

**Comment by vilsbole** [comment]
Thank you for the suggestion.
Just ensure I understand correctly, do you mean that when you enter
`9 ETH` you actually want the recipient to receive `9ETH - 21000 gas`?

> most/all imitators/derivatives 
Could you share some examples so I can ask our design team to take a look?

**Comment by dchmelik** [comment]
Had to reread what gas is, but basically.  One situation was recently I had a long decimal-number of ether, but wanted to end up with whole/natural number (i.e., no decimals or decimals considered all zeroes,) so let's say I have 3.14159265359ETH (forgot how far decimals in wallet go, but this should hopefully be clear enough) but want to end up with 3ETH... so I'd select to 'send' only 0.14159265359 (including what is sent, and the gas, as their sum)... doesn't really send quite that much rather than  0.14159265359 minus whatever gas for that amount.

Some cryptocurrency wallets even let you send all you have, which of course is another situation (like in your case above if they only had 9 but wanted to send it all) where the user needs the gas subtracted automatically, because errors would be common and they may end up with some left that's too little to use/send.

I'm currently set to be doing days/weeks of re-setup after a couple OS reinstalls on my desktop and with more reinstalls coming up soon on several other workstations/servers, so may not get around to opening other cryptocurrency programs to show examples (I've heard sometimes it's not good to discuss different ones in different areas, but though Ethereum was the first such system adding programming capabilities to it, so technologically superior design, it is the case that the original Bitcoin Core has an option to subtract the transaction fee from what one sends... after things get back to normal for me, I could optionally screenshot that or something similar.)

**Comment by wtzb** [comment]
Hi there @dchmelik! First of all, thank you for letting us know that you would like to see this in MyCrypto. It has since been added to our internal backlog for new feature consideration. I will be closing this issue here, but we really appreciate you voicing your feedback! If there is anything else that you'd wish to see in MyCrypto to make your life easier, then definitely let us know.

Thanks for sticking with us!
