### ISSUE TITLE
Access to "node" functions in the desktop application despite "nodeIntegration" set to "false" in window.ts 

### ISSUE THREAD

**Issue by Flyy-yu** [MyCryptoHQ/MyCrypto#3261]
### Description of Issue

I am not sure what's the build process is or why, but "node" is enabled in the desktop application despite "nodeIntegration" set to "false" in window.ts: https://github.com/MyCryptoHQ/MyCrypto/blob/ad07f406970c8850eeb8c3738e9cdd053f06cf4a/electron-app/main/window.ts#L30

...

### What exactly were you doing when you encountered this issue?

0. Open the latest version(1.7.9) of MyCrypto Desktop application
1. Open the console(option+command+i in macOS)
2. type "require" in the console. Notice the function is found
3. Turn on computer sound, type "require('child_process').exec('say hello')" in the console. Notice the system command "say hello" is executed and you hear the voice "hello".

<img width="1397" alt="Screen Shot 2020-05-07 at 12 50 22 AM" src="https://user-images.githubusercontent.com/25512004/81255862-cf429800-8ffc-11ea-9c03-e1e93025ce9c.png">

#### More info:
Decompile the app.asar file located at  `/Applications/MyCrypto.app/Contents/Resources/app.asar`
with command `npx asar extract app.asar destfolder`

Search for string "nodeIntegration" with the command `grep -inr 'nodeIntegration' .` in the destfolder folder.

<img width="835" alt="Screen Shot 2020-05-07 at 12 59 36 AM" src="https://user-images.githubusercontent.com/25512004/81256293-0c5b5a00-8ffe-11ea-8578-c1aba0debe8c.png">

in the decompiled file "destfolder/main.js", "nodeIntegration" is set to "true"
<img width="1118" alt="Screen Shot 2020-05-07 at 12 56 01 AM" src="https://user-images.githubusercontent.com/25512004/81256123-8b03c780-8ffd-11ea-85ed-8d8bb86289cd.png">

#### What suppose to happen if "node" is disabled:

This is from a different electron wallet, you should see "require is not defined":
<img width="846" alt="Screen Shot 2020-05-07 at 1 00 58 AM" src="https://user-images.githubusercontent.com/25512004/81256351-3e6cbc00-8ffe-11ea-864a-c3a5a2bb2e4a.png">

### How were you accessing your wallet?

...Ledger, Trezor, MetaMask, Private Key, Keystore File, Mnemonic Phrase?...

### Description of Your Machine

- Browser: N/A
- Browser version: N/A
- Operating system: macOS Catalina 10.15.3
- Device: MacBook Pro
- MyCrypto.com vs Desktop Application? Desktop Application
- MyCrypto Version Number: 1.7.9

### Console Logs / Screenshots

...

**Comment by LuckyLuker** [comment]
[ch6072]

**Comment by vilsbole** [comment]
@Flyy-yu Thanks for reaching out! @409H fixed this issue with #3272.
It will be included in the next release.
We'll close this issue when at that moment.

**Comment by Flyy-yu** [comment]
Wait, I am confused. 

Why "nodeIntegration" set to `true` in  the "enhancement/electron-sandbox" branch https://github.com/MyCryptoHQ/MyCrypto/blob/e360082f956586ff6be75571450fcc43bef0a9c8/electron-app/main/window.ts#L28 

While In the master branch, it states
```
      // For security reasons the following params should not be modified
      // https://electronjs.org/docs/tutorial/security#isolation-for-untrusted-content
      nodeIntegration: false,
```
https://github.com/MyCryptoHQ/MyCrypto/blob/32804506c77b3e2401ae803c5e3477ba6c7a050b/electron-app/main/window.ts#L30

**Comment by vilsbole** [comment]
> Do you guys use the code from the Legacy branch to build the electron desktop app?
Yes, atm the Releases are done through the Legacy branch while we complete the new features. 

Previously the flag was set to `true` to enable the integration with shapeshift (the only external code that we would run). Now that this integration is deprecated we can set the flag back to false.
