### ISSUE TITLE
Cannot fetch Token Balance from Nethermind Node

### ISSUE THREAD

**Issue by MysticRyuujin** [MyCryptoHQ/MyCrypto#3305]
### Description of Issue

Cannot fetch Token Balance from Custom Node (specifically: Nethermind)

**This issue happens on both the Desktop app AND `https://www.mycrypto.com/`**

### What exactly were you doing when you encountered this issue?

1. Run a Nethermind node, and optionally NGINX in front of it if you want to test with HTTPS
2. Configure it as a custom node (either via `http://<node>:8545` or `https://<node>`, whatever)
3. Try to scan or refresh token balances

What then happens:
1. It fails, you get the red banner that says "You've lost your connection to the network, check your internet connection or try changing networks from the dropdown at the top right of the page."
2. After a few seconds you'll get the green banner that says "Your connection to the network has been restored" but the token balances still fail to load.

Refreshing the ETH balance of the account works fine. It seems to only be the token balance lookup?

I tried HTTP and HTTPS (with trusted cert) on the desktop and HTTPS on the website, the connection seems fine, just the token balance that's broken?

### How were you accessing your wallet?

In this case a Ledger but I assume that's unrelated

### Description of Your Machine

- Browser: Brave when using the website
- Browser version: `Version 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)`
- Operating system: Windows 10 x64 build 2004
- Device: `Desktop PC?`
- MyCrypto.com vs Desktop Application? BOTH
- MyCrypto Version Number: Desktop and Website are `v1.7.10`

### Console Logs / Screenshots

If you would like logs reach out to me on twitter `@MysticRyuujin` or Discord `MysticRyuujin#8157` and I can provide packet capture or `.HAR` file from Brave Developer Tools. I can also provide you access to a Nethermind node if you don't have one to play with. I assume this is probably an issue in processing/parsing/dealing with the reply data from the node so I understand you might need a node to query

Here is a screenshot of a random query from the Brave Dev Tools:
![RequestData](https://user-images.githubusercontent.com/8877131/82734283-acdc9a00-9cdf-11ea-8287-94917748c699.png)

![ResponseTab](https://user-images.githubusercontent.com/8877131/82734318-e31a1980-9cdf-11ea-8711-27c25494213e.png)

Here is the `response` tab from the above screenshot (I formatted if for you)
```
[
  {
    "jsonrpc": "2.0",
    "result": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "id": "28e1c81d5ed08395dd456270fa173678"
  },
  {
    "jsonrpc": "2.0",
    "result": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "id": "6fb3ee1056a7a6471dd8a7acb8ad3a7a"
  },
  {
    "jsonrpc": "2.0",
    "result": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "id": "473b186fc3270ab89def584e9ba8cfec"
  },
  {
    "jsonrpc": "2.0",
    "result": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "id": "213109cb4c6374eaa0be973d2a718807"
  },
  {
    "jsonrpc": "2.0",
    "result": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "id": "d0ae4368c34cb2c3c1f73db1c4e63047"
  },
  {
    "jsonrpc": "2.0",
    "result": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "id": "a4113450fa0a4203dc7f059969521223"
  },
  {
    "jsonrpc": "2.0",
    "result": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "id": "5013dfd228637b1ceffd9ce7455eddad"
  },
  {
    "jsonrpc": "2.0",
    "result": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "id": "e2ab9879f5ceefb20ad7e2e3ed8b4ba0"
  },
  {
    "jsonrpc": "2.0",
    "result": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "id": "3e586d1d275f844c8bbcfd5777884eb0"
  },
  {
    "jsonrpc": "2.0",
    "result": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "id": "eed8d9948ab675602a1336d2191554c8"
  }
]
```

**Comment by MysticRyuujin** [comment]
After looking at the reply from the MyCrypto node, it may be because Nethermind is not sending `content-type: application/json` in the reply?

**Comment by MysticRyuujin** [comment]
It appears that Nethermind does not send the response header `content-type: application/json` I suspect that may be the problem?

**Comment by MysticRyuujin** [comment]
Update: I used NGINX to inject the content-type header into the reply, but it did not solve the issue so it's gotta be more complex than that.

**Comment by MysticRyuujin** [comment]
After even more reading, I'm not sure. It seems like the JSON RPC spec should be transform independent and it specifically states that it should follow the HTTP specification. I don't think Nethermind is required to send Content-Length... 🤷‍♂️

**Comment by MysticRyuujin** [comment]
I convinced the Nethermind team to provide an option to not send `chunked` data. In the latest version of Nethermind `1.8.50` I can now test with both `Content-Type: application/json` AND
`Content-Length: <length>` set but the website and the latest desktop app (`1.7.11`) it still doesn't work.

**Comment by blurpesec** [comment]
Heya @MysticRyuujin, in order to limit concerns for our small team, for now we're only fixing issues in desktop app/legacy related to user security / significant UX issues. If the issue does pop up in beta at some point, please let us know! Sorry :pray:
