### ISSUE TITLE
Improvement of UX in the "Interact with Contracts" page

### ISSUE THREAD

**Issue by VinceBCD** [MyCryptoHQ/MyCrypto#3311]
### Description of Issue

In the "Interact with Contracts" page, the output zone can be really small compared to its content, which is not very user friendly.

![image](https://user-images.githubusercontent.com/31089467/82910854-6c914c00-9f6b-11ea-999a-a92129c1bb6b.png)

Ideally, output fields should fit the content or be resizable from a certain number of characters or be easy to view at a glance...

### What exactly were you doing when you encountered this issue?

Just follow [this link](https://beta.mycrypto.com/interact-with-contracts?network=Ropsten&address=0x13C61Ef65B6A60e8692Fa3bF5ba4d521236A48Ad&function=getTemplate&input=_issuerAddress:0x72Cf647508Da9bF398C50F817E16Edd397AF3177&input=_templateId:;0x03;)

### How were you accessing your wallet?

no wallet needed

### Description of Your Machine

Browser: chrome
Browser version: 80.0.3987.149 (Official Build) (64-bit)
Operating system: Windows 10
Device: Microsoft Surface Pro
MyCrypto.com vs Desktop Application? MyCrypto.com
MyCrypto Version Number: beta

**Comment by bowensanders** [comment]
Greetings, @VinceBCD -
It looks like the "Stale" bot decided to close this issue before anyone got back to you about this.

I've taken the note and added it to the log of improvement ideas for the contracts interaction page.

Thanks for your idea, and sorry about any confusion!
