### ISSUE TITLE
Gas Price slider doesn't take the right minimum value from config

### ISSUE THREAD

**Issue by alepc253** [MyCryptoHQ/MyCrypto#3348]
### Description of Issue

There is a problem related to gas price setting. Sometimes it takes the right minimum and sometimes it takes `0.1` gwei.
This applies at least for RSK network, where min gas price is `0.06` by configuration.  It's possible that the behavior changes when you logout your wallet and login again.

### What exactly were you doing when you encountered this issue?

Just creating a transaction. 

### How were you accessing your wallet?

I see the same issue using any type.

### Description of Your Machine

- Browser: Chrome
- Browser version: N/A
- Operating system: Mac
- Device:
- MyCrypto.com vs Desktop Application? Same
- MyCrypto Version Number: Not related to specific version

### Console Logs / Screenshots

<img width="646" alt="Captura de Pantalla 2020-07-03 a la(s) 12 34 47" src="https://user-images.githubusercontent.com/3451282/86483675-ecf55a80-bd2a-11ea-9aee-78bb11f42431.png">

<img width="639" alt="Captura de Pantalla 2020-07-03 a la(s) 12 35 04" src="https://user-images.githubusercontent.com/3451282/86483689-f41c6880-bd2a-11ea-9e6b-d8a83f423264.png">

<img width="631" alt="Captura de Pantalla 2020-07-03 a la(s) 12 37 42" src="https://user-images.githubusercontent.com/3451282/86483705-fed6fd80-bd2a-11ea-836f-90e787d33646.png">

**Comment by wtzb** [comment]
Hi there @alepc253! I just wanted to let you know that this issue has since been added to our internal project management system, and that we really appreciate you creating this issue. Please accept my apologies for not updating you earlier, but do know that we're aware of the issue! Because it has since been added to our system, I will close this issue here. Thank you so much!

**Comment by alepc253** [comment]
Thanks for letting me know @wtzb
