### ISSUE TITLE
In "Amount" Fields, either strip commas ( , ) or change them to dots ( . )

### ISSUE THREAD

**Issue by tayvano** [MyCryptoHQ/MyCrypto#335]
Every 6 weeks or so since the beginning of time, we have a random person from Europe who uses commas (6,99) instead of dots (6.99) and everything get's confused. Tiny detail, low priority, but itll make someone's life better (I hope)

non-blocking

**Comment by james-prado** [comment]
Closing this issue, at this time there unfortunately is no way to consistently send or receive internationalized number formats accurately
