### ISSUE TITLE
Can't re-submit with higher gasPrice: "Transaction is very similar to a recent transaction"

### ISSUE THREAD

**Issue by epheph** [MyCryptoHQ/MyCrypto#3403]
### Description of Issue
I have a pending transaction, created with another app (although i doubt it matters?). It was not being mined, so i set the nonce correctly to the pending nonce, recreated tx, and bumped the gas price significantly above 12.5% required. I signed the transaction, but even after I confirmed it on Ledger, MyCrypto refuses to send the transaction to the RPC, instead saying:

"This transaction is very similar to a recent transaction. Please wait a few moments and try again, or click 'Advanced' and manually set the nonce to a new value"

MyCrypto is for some reason deciding not to send a valid transaction, instead looking into the pool and (falsely) deciding it isn't valid?

I have looked into its communication with the RPC, it never even tries to send it. This error is originating in MyCrypto (and i have never had this problem before with MyCrypto)

### What exactly were you doing when you encountered this issue?

...Give us some steps to reproduce...

### How were you accessing your wallet?

Ledger

### Description of Your Machine

- Browser: n/a
- Browser version: n/a
- Operating system: mac
- Device: Ledger
- MyCrypto.com vs Desktop Application? yes
- MyCrypto Version Number: 1.7.11

### Console Logs / Screenshots

![Screen Shot 2020-07-30 at 12 42 54 PM](https://user-images.githubusercontent.com/361654/88967851-3752f400-d263-11ea-97fb-ebfd6d4a2491.png)

**Comment by epheph** [comment]
https://github.com/MyCryptoHQ/MyCrypto/commit/3f57520bcac5a32d2d6ede979f845b355ffef475#diff-84627ed5c0b4ce22824cb662a26ac7b0R50-R58

**Comment by Mrtenz** [comment]
I am not able to reproduce this issue. Could you let me know what exactly you did when you got this error message?
