### ISSUE TITLE
Broken input "Data" field in section "View & Send > Send Ether & Tokens" of MyCrypto Desktop Application v1.6.6

### ISSUE THREAD

**Issue by ltfschoen** [MyCryptoHQ/MyCrypto#3408]
Creating a new issue because a bot closed the previous unresolved issue as stale https://github.com/MyCryptoHQ/MyCrypto/issues/2592

**Comment by mwbailey** [comment]
I left a [comment](https://github.com/MyCryptoHQ/MyCrypto/issues/2592#issuecomment-671666339) in the original thread that may resolve this issue.

**Comment by Mrtenz** [comment]
I'm not able to reproduce this issue with the data you mentioned in the original issue. Can you double check that you didn't enter any extra spaces around the input, like mwbailey mentioned?
