### ISSUE TITLE
Global Account Unlock

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#341]
At its core, this proposal addresses the issue of treating a user's wallet as an account. Once a wallet is authenticated, it can be accessed across the site. Implementation details aside, this change will pave the way for a dashboard design, and thats a good thing.

Before any wireframes or tough decisions are made, I think some research into how to build a dashboard should be done. Looking through dashboards ([coinbase](https://www.coinbase.com/), [shopify](https://www.shopify.ca/), [stripe](https://stripe.com/ca), [trezor](https://trezor.io/), etc...) other design teams have built, sketching prototypes, and eventually creating wireframes and mockups are all part of that process. Going through this design process is an investment, but the payoff for the users, and the designers / developers down the line will be worth it.

I'm absolutely behind this proposal and I'm open to collaborating on solutions. - @james-prado

**Comment by dternyak** [comment]
UX Proposals #1

Account Sidebar (similar to Trezor UX).
    - Disabled tabs based on if account unlock is required to use.
         - Send Required
         - Swap not required

**Comment by james-prado** [comment]
At its core, this proposal addresses the issue of treating a user's wallet as an account. Once a wallet is authenticated, it can be accessed across the site. Implementation details aside, I think this change will pave the way for a dashboard design. 

Before any wireframes or tough decisions are made, I think some research into how to build a dashboard should be done. Looking through dashboards ([coinbase](https://www.coinbase.com/dashboard), [shopify](https://www.shopify.ca/), [stripe](https://stripe.com/ca), [trezor](https://trezor.io), etc...) other design teams have built, sketching prototypes, and eventually creating wireframes and mockups are all part of that process. Going through this design process is an investment, but the payoff for the users, and the designers / developers down the line will be worth it. 

I'm absolutely behind this proposal and I'm open to collaborating on solutions.

**Comment by dternyak** [comment]
I Didn't mean to delete @james-prado's comment, but it's a good enough summary of the issue that I've moved it into the main issue description.

**Comment by wbobeirne** [comment]
See #434 for some previous discussion & mockups.

**Comment by james-prado** [comment]
Issue moved to https://github.com/MyCryptoHQ/research/issues/3
