### ISSUE TITLE
Merge decryption of EncryptedPrivateKeyWallet to upstream

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#342]
After #316, `decrypt.ts` will only exist for EncryptedPrivateKeyWallet. Upstream (ethereumjs-wallet) already has >90% of the code required to implement this functionality in their `thirdparty` library.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837182)
