### ISSUE TITLE
Can't open on Mac - “MyCrypto” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by qmilangowin** [MyCryptoHQ/MyCrypto#3514]
_Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email support@mycrypto.com for faster attention._

_If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!_

---

### Description of Issue
On MacOS Catalina, 10.15.6 version of Catalina and latest of MyCrypto. Cannot open due to Malicious Software Warning. So seems like it might need to be signed???
...

### What exactly were you doing when you encountered this issue?

...Give us some steps to reproduce...

### How were you accessing your wallet?

...Ledger, Trezor, MetaMask, Private Key, Keystore File, Mnemonic Phrase?...

### Description of Your Machine

- Browser:
- Browser version:
- Operating system:
- Device:
- MyCrypto.com vs Desktop Application?
- MyCrypto Version Number:

### Console Logs / Screenshots

...

**Comment by qmilangowin** [comment]
Can open directly from Finder but not from Applications Menu. Closing as there is a work-around but would be good if this was fixed

**Comment by LukeWheeldon** [comment]
Hello - Any update on this? Thank you.

**Comment by itinance** [comment]
And what is the workaround? Why is this closed?
