### ISSUE TITLE
"Request timed out for eth_mycrypto"

### ISSUE THREAD

**Issue by t0rbalan** [MyCryptoHQ/MyCrypto#3526]
---

### Description of Issue
Time out
...

### What exactly were you doing when you encountered this issue?

I wanted to send 0.15 ether to another ETH addres

### How were you accessing your wallet?

Keystore File

### Description of Your Machine

- Browser: Edge
- Browser version:
- Operating system: Windows 10
- Device:PC
- MyCrypto.com vs Desktop Application?
Desktop app
- MyCrypto Version Number:
1.7.12
SHA256 hash of windows_1.7.12_MyCrypto.exe:
5f57a072db6ce401a4c48c45afd696f6116503812220c5da0a7bb777ec2c70b0

### Console Logs / Screenshots
"Request timed out for eth_mycrypto"
...
Confirm Transaction stays for a few seconds

![image](https://user-images.githubusercontent.com/71423099/93421075-139e4880-f8b9-11ea-8d85-e1ca70d7a6a6.png)

**Comment by wtzb** [comment]
Hi there @t0rbalan! Could you try clicking "Change Network", and then manually select the MyCrypto Ethereum node? It might be worth a shot to try a different node as well, such as Infura's. 

I'll be closing this issue here, but feel free to reply if this does not solve the issue. Additionally, you are free to reply to me through e-mail as well. Thank you so much!

**Comment by dubstard** [comment]
I just wanted to confirm that your solution has helped me.
Thank you.
![image](https://user-images.githubusercontent.com/49607867/93493626-c8b21e80-f914-11ea-9950-cc3982a8cf60.png)

**Comment by t0rbalan** [comment]
Hello,
Thank you sincerely, I just wanted to confirm your solution has helped me!
![image](https://user-images.githubusercontent.com/71423099/93493921-1890e580-f915-11ea-9c55-b2b3c5a9da0a.png)

**Comment by wtzb** [comment]
@t0rbalan I'm so glad to hear. Feel free to [reach out](https://support.mycrypto.com/contact-us) if you encounter any other issues in the future!

**Comment by t0rbalan** [comment]
Hi,
I would like to update that the transaction was never mined, 12 + hours after the broadcast event.

I still have the full balance 0.4 in my original account and 0 in the account i wanted to send 0.15 ETH to.

![image](https://user-images.githubusercontent.com/71423099/93558457-2599ed00-f986-11ea-9637-ba70e5b2aace.png)
Also what i did - selecting manually a node etc - is this needed for most users, should it happen by default and was it related to a timeout of sorts for this connector (or whatever it is)

Thanks so much - i don't understand the technical details very well, but i am curious. I also saw there is now a beta version, but only source and the bugfix is related to the slider and not my issue reported.
