### ISSUE TITLE
My digitex old contract i need change but my ledger is very hard to add new dgtx contract.. How can i do

### ISSUE THREAD

**Issue by nonitz** [MyCryptoHQ/MyCrypto#3598]
_Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email support@mycrypto.com for faster attention._

_If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!_

---

### Description of Issue

...

### What exactly were you doing when you encountered this issue?

...Give us some steps to reproduce...

### How were you accessing your wallet?

...Ledger, Trezor, MetaMask, Private Key, Keystore File, Mnemonic Phrase?...

### Description of Your Machine

- Browser:
- Browser version:
- Operating system:
- Device:
- MyCrypto.com vs Desktop Application?
- MyCrypto Version Number:

### Console Logs / Screenshots

...

**Comment by Mrtenz** [comment]
Thank you for reaching out. If you are running into a bug or have a suggestion for a feature, please fill out the required information in a new issue, for other questions please send an email to support@mycrypto.com, and we'll help you out from there.
