### ISSUE TITLE
Bad checksum validation in "Add custom token" for RSK (or non ETH chains)

### ISSUE THREAD

**Issue by alepc253** [MyCryptoHQ/MyCrypto#3606]
### Description of Issue

"Add custom token" has an invalid address checksum validation for non ETH networks (RSK in this case)

### What exactly were you doing when you encountered this issue?

1- Connect to RSK Mainnet
2- "Add custom token"
3- Put `0xE700691Da7B9851F2F35f8b8182C69C53ccad9DB` as address
4- Check "Not a valid address" message

### How were you accessing your wallet?

It doesn't matter in this case

### Description of Your Machine

- MyCrypto Desktop Application
- MyCrypto Version Number: 1.7.10

### Console Logs / Screenshots

<img width="1220" alt="Captura de Pantalla 2020-11-11 a la(s) 12 09 06" src="https://user-images.githubusercontent.com/3451282/98829820-69eeba00-2418-11eb-8f33-05673240fec6.png">

**Comment by Mrtenz** [comment]
Thanks for the report. Is this the case for all non-Ethereum networks, or just RSK? IIRC, RSK uses a different way to generate address checksums, so it's possible that the function to validate the address isn't using that for the custom token functionality.

**Comment by alepc253** [comment]
Hi @Mrtenz, TBH I didn't try other networks but it should fail for every network that implements EIP1191 or with a different checksum calculation

**Comment by Mrtenz** [comment]
Ok, thank you. I will investigate further and push a fix soon. You might be able to get around this by using lowercase addresses for now (though I haven't tested this).

**Comment by Mrtenz** [comment]
This is currently blocked by #3363 due to Node.js incompatibilities. Once that PR is merged, I'll make a PR for this issue.

**Comment by Mrtenz** [comment]
I figured out a solution, it should be included in the next release of the legacy app.
