### ISSUE TITLE
MacOS: "MyCrypto.app can't be opened because Apple cannot check it for malicous software"

### ISSUE THREAD

**Issue by itinance** [MyCryptoHQ/MyCrypto#3629]
Is someone aware of this?

```
MacOS Catalina 10.15.7
MyCrypto 1.7.13

```

<img width="415" alt="Screen Shot 2020-11-20 at 19 38 09" src="https://user-images.githubusercontent.com/1758597/99837677-43432880-2b68-11eb-8c51-f0f2d2780d32.png">

**Comment by LukeWheeldon** [comment]
#3207 #3514

**Comment by LukeWheeldon** [comment]
@Mrtenz You could, uh, I don't know, notarize your app? Look it's even easy, how great!

https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

**Comment by kyranjamie** [comment]
Came here to report the same issue. Interested what Apple's restrictions are? In the Stacks Wallet we have [code signing & notarization handled with a Github Action](https://github.com/blockstack/stacks-wallet/blob/beta/.github/workflows/publish-version.yml)

**Comment by Mrtenz** [comment]
I'm not responsible for the release process myself, but I'll see if that's something we can do. Thanks for the heads up!
