### ISSUE TITLE
Do you support MyCrypto in Android playstore? (com.mycrypro.nd)

### ISSUE THREAD

**Issue by themsay** [MyCryptoHQ/MyCrypto#3631]
#### Security concern
Do MyCryptoHQ support or maintain any mobile application in Gogle Playstore named: `MyCrypto` under domain `com.mycrypro.nd`?

**Comment by 409H** [comment]
Hi, **this is not our application - it is malicious designed to steal secrets and sweep cryptocurrency from users**. We have filed trademark reports and abuse reports. So far, Google Play have only actioned the trademark reports in the regions we actively hold the trademark. We are working to continue the takedowns.

https://twitter.com/sniko_/status/1329800533318754305

You can see our official domains which will link you to any relevant mobile apps: https://support.mycrypto.com/general-knowledge/about-mycrypto/official-domain-names-used-by-mycrypto

If we were to release a branded MyCrypto mobile application, you will likely see it advertised on our main domain (mycrypto.com, app.mycrypto.com)
