### ISSUE TITLE
Debian 10: undefined symbol: udata_setCommonData_59

### ISSUE THREAD

**Issue by MatthewLM** [MyCryptoHQ/MyCrypto#3634]
An error occurs when starting `linux-x86-64_1.7.13_MyCrypto.AppImage` on a fully up-to-date Debian 10 (Kernel: 4.19.0-12-amd64):

    /tmp/.mount_linux-t6xBi2/app/mycrypto: symbol lookup error: /tmp/.mount_linux-t6xBi2/app/mycrypto: undefined symbol: udata_setCommonData_59

`linux-x86-64_1.7.11_MyCrypto.AppImage` also fails currently, but it was working before for some reason.

**Comment by MatthewLM** [comment]
Oddly the error went away after restarting my computer. I'm not sure then if this might reoccur.

**Comment by Mrtenz** [comment]
Looks like this issue was resolved. If you're running into the same issue again, feel free to open a new issue. Thanks!
