### ISSUE TITLE
Feature Request: TOR on desktop app

### ISSUE THREAD

**Issue by raymonddurk** [MyCryptoHQ/MyCrypto#3685]
I believe TOR is officially integrated into React which is how the desktop app was built so I wanted to toss out that idea to be added to the back burner projects of the new app you're working on.

**Comment by Mrtenz** [comment]
After some Googling I was only able to find [react-native-tor](https://github.com/Sifir-io/react-native-tor) (for native iOS and Android apps primarily), however we use react-dom for both the web and desktop application. I'm not sure if there's an easy way to integrate TOR into that? It's an interesting suggestion though, and maybe worth looking into further in the future.

**Comment by raymonddurk** [comment]
Thanks for the insight. I'll try and go back to the source on that update and get back to you if I find anything useful but I trust your Googling skills.
