### ISSUE TITLE
Small typo in migrate app

### ISSUE THREAD

**Issue by GriffGreen** [MyCryptoHQ/MyCrypto#3690]
<img width="620" alt="Screen Shot 2020-12-29 at 12 02 13 AM" src="https://user-images.githubusercontent.com/14945613/103259894-a449f180-499b-11eb-92de-e6d9471b61eb.png">

It says REP but it should be ANT

**Comment by FrederikBolding** [comment]
Thanks for reporting Griff! Will commit a fix for this which will be included in the next release 👍
