### ISSUE TITLE
Desktop app and beta missing "Send Offline" feature

### ISSUE THREAD

**Issue by secinthenet** [MyCryptoHQ/MyCrypto#3696]
Is this feature planned to be added? If so, where can I track progress?

**Comment by Mrtenz** [comment]
The current desktop app supports offline signing, but there's no dedicated page for it like on the legacy version of MyCrypto. You can find a full guide here: https://support.mycrypto.com/how-to/sending/how-to-make-an-offline-transaction. The desktop app will automatically go into an offline signing mode when it does not detect an internet connection.

**Comment by secinthenet** [comment]
Thanks, I already know and read this guide and know about the offline signing. I'm looking for the nonce computation and fee estimation (both gas price and limit), which is currently missing as far as I can see.
Will this be added?

**Comment by Mrtenz** [comment]
We don't have plans to add this to the current desktop app, but we are working on a replacement for the desktop app for the beta version of MyCrypto, and this is definitely something we'll take into account. Thanks for the suggestions!
