### ISSUE TITLE
GPG key for GITHUB commits and tags

### ISSUE THREAD

**Issue by mlario** [MyCryptoHQ/MyCrypto#3712]
Could you please publish on your website, or on https://github.com/MyCryptoHQ.gpg or any public server such as https://pgp.mit.edu/ your key used for signing github commits and tags? 

Meaning this key: 4AEE18F83AFDEB23

Verifying git commits after download and before building would be super helpful

Thanks

**Comment by Mrtenz** [comment]
All commits are automatically signed by GitHub itself, and we don't own this key. You can find the public key for it [here](https://github.com/web-flow.gpg). We do provide signed checksums for the [desktop application](https://download.mycrypto.com/), of which the public key is published on [Keybase](https://keybase.io/tayvano/pgp_keys.asc).

For more information:
* https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/about-commit-signature-verification
* https://security.stackexchange.com/questions/173493/who-owns-the-gpg-key-4aee18f83afdeb23-and-how-did-it-sign-a-commit-in-my-github
