### ISSUE TITLE
AppImage wont run: "No such file or directory"

### ISSUE THREAD

**Issue by doncatnip** [MyCryptoHQ/MyCrypto#3748]
### Description of Issue

The AppImage of the latest release linux-x86-64_1.7.13_MyCrypto.AppImage does not work. It says:

    donc@nip ~/AppImage$ ./linux-x86-64_1.7.13_MyCrypto.AppImage
    bash: ./linux-x86-64_1.7.13_MyCrypto.AppImage: No such file or directory

The file clearly is there:

    donc@nip ~/AppImage> ls
    linux-x86-64_1.7.13_MyCrypto.AppImage*

### What exactly were you doing when you encountered this issue?

I tried to execute the AppImage. I also did a chmod a+x on it beforehand.

### Description of Your Machine

I'm using guix system on a standard PC.

**Comment by Mrtenz** [comment]
It looks like the filename has an asterisk in it. Usually this means that the file is executable, but only shows when using `ls -F` from my understanding of `ls`. Can you please double-check that the filename is correct?

**Comment by doncatnip** [comment]
Hi, it has nothing to do with my ls command. I am using fish. This is normal. I tried to execute it using bash and sh, though.
