### ISSUE TITLE
Token Name: T Finance

### ISSUE THREAD

**Issue by alizere** [MyCryptoHQ/MyCrypto#3762]
Token Name: T Finance
Symbol: TFI
Decimals: 18
Total Supply: 1,000,000,000 TFI
Contract Address: 0xf567537ddb62Fa964Fb6d877738905789ab57Efd

_Originally posted by @wannadrop in https://github.com/MyEtherWallet/ethereum-lists/pull/1729#issuecomment-764579638_

**Comment by Mrtenz** [comment]
To add your token to MyCrypto, you can add submit a PR to [ethereum-lists/tokens](https://github.com/ethereum-lists/tokens). Our token list is automatically fetched from that repo.

**Comment by wannadrop** [comment]
thank you
