### ISSUE TITLE
Dutch translation issues, link does not work

### ISSUE THREAD

**Issue by radoeka** [MyCryptoHQ/MyCrypto#378]
1) Incorrect url, because of this the page being referred to does not work;
At the (home) page in the tab "generate new wallet" with the text, in the Dutch translation, the page
referred to by ... Hoe maak je een Wallet   ·   Aan de slag
does not work.

Hoe maak je een Wallet ; refers to https://myetherwallet.github.io/knowledge-base/getting-started/creating-a-new-wallet-on-myetherewallet.html

that should be https://myetherwallet.github.io/knowledge-base/getting-started/creating-a-new-wallet-on-myetherwallet.html

There is an 'e" too much in the last string: myether{e}wallet  

2) At the page with the text:
Unlock your wallet to see your address
Je Adres wordt ook wel je Account # of je Publieke Sleutel ("Public Key") genoemd. Dit is wat je deelt met anderen zodat ze je Ether of Tokens kunnen toesturen. Zie ook je kleurrijke adres icoon. Zorg ervoor dat het matched met je paper wallet & waar dan ook wanneer je je adres ergens invoerd. Dit icoon is een makkelijke manier om je adres te herkennen.

The word "invoerd" moet zijn "invoert".

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837149)
