### ISSUE TITLE
Unable to confirm generated mnemonic phrase when it has duplicate words

### ISSUE THREAD

**Issue by ltfschoen** [MyCryptoHQ/MyCrypto#3792]
_Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email support@mycrypto.com for faster attention._

_If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!_

---

### Description of Issue

I chose to create an account with a mnemonic phrase, but it generated it with the 2nd and 4th words "Brisk" being the same (duplicate), so when i had to confirm it by entering the mnemonic phrase words in the correct order, when i clicked the 2nd word it labelled it with (2), but at the same time it labelled the 4th word (which is the same word) with (2) as well, and so i could not click that word as the 4th word anymore (see screenshot attached) 

### What exactly were you doing when you encountered this issue?

Creating a wallet with mnemonic phrase

### How were you accessing your wallet?

Mnemonic Phrase

### Description of Your Machine

- Operating system: macOS
- MyCrypto.com Desktop Application
- MyCrypto Version Number: 1.7.11

**Note: I haven't had time to update to the latest version of MyCrypto, so this issue may have already been resolved.**

### Console Logs / Screenshots

![Screen Shot 2021-01-28 at 10 48 43 pm](https://user-images.githubusercontent.com/6226175/106203565-afe53e00-620f-11eb-9bde-30a023055816.png)

**Comment by Mrtenz** [comment]
Thanks for letting us know. We are working on a replacement for the current desktop application, and we'll make sure that this will be fixed there.

The easiest way to get around this issue for now is to generate a new mnemonic phrase.
