### ISSUE TITLE
Unclear where in the UI to obtain the wallet's private key that they should save after creating a new wallet

### ISSUE THREAD

**Issue by ltfschoen** [MyCryptoHQ/MyCrypto#3794]
_Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email support@mycrypto.com for faster attention._

_If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!_

---

### Description of Issue

When you click to create a wallet at the screen below, it says it will "Generate your own private key"

![Screen Shot 2021-01-29 at 9 49 52 am](https://user-images.githubusercontent.com/6226175/106253204-4d219000-626b-11eb-96ed-abb2088a7c0d.png)

Then on the next screen you can choose either Keystore File or Mnemonic Phrase. Let's assume you choose Mnemonic Phrase and you get given it and confirm it successfully.

And lastly you get to choose your Wallet Address.

Then you get logged in with that Wallet Address and it takes you to the "View & Send" page.

So at this point you know your Wallet Address and your Mnemonic Phrase, but where do you get the Private Key?

In the screenshot below there's a selection box (drop-down menu), with a label "Select..." 
![Screen Shot 2021-01-29 at 9 49 36 am](https://user-images.githubusercontent.com/6226175/106253208-4dba2680-626b-11eb-82b5-357e9d5cd07d.png)

If you click "Select..." then it reveals options including "Wallet Info". If you click that you can get your Private Key.

I didn't find it easy to find this. But it can be important and convenient to get it, since if the user created it with Mnemonic Phrase, but didn't save the Private Key, they won't be able to seamlessly import their account into something like MetaMask, because MetaMask only allows you to import with your Private Key or JSON Keystore File (not with just the Mnemonic Phrase)
 
![Screen Shot 2021-01-29 at 9 59 06 am](https://user-images.githubusercontent.com/6226175/106254238-99b99b00-626c-11eb-9c79-39f622cb92fb.png)

If you don't record your Private Key before you log out, you won't get that opportunity record it again.

Also, after you log out (by clicking a different menu item on the left in the UI, like "TX Status", and then clicking "Logout" when prompted), you can access your account again by going to the "View & Send" menu item, and then choosing "View Address" (as shown in screenshot below), where you can find your Wallet Address from the drop-down of recent addresses. 

![Screen Shot 2021-01-29 at 10 02 01 am](https://user-images.githubusercontent.com/6226175/106254850-53b10700-626d-11eb-8042-4f080c2033c6.png)

But now when you go to "Select...", it still shows "Wallet Info" as an option, but it no longer allows you to click it. 

### What exactly were you doing when you encountered this issue?

Creating a wallet

### How were you accessing your wallet?

Mnemonic Phrase, Private Key

**Comment by Mrtenz** [comment]
Your mnemonic phrase or keystore file is all you need to access an account. With the mnemonic phrase you can derive one or multiple private keys, and the keystore file contains one encrypted private key. There is no need to separately save the raw private key.

If you would like to do so, you can use the Wallet Info tab like in your screenshot, and save your private key from there. You can access this tab after opening the app again, by using the same keystore file or mnemonic phrase again.
