### ISSUE TITLE
New MyCrypto web app fails on connecting hardware wallets to RSK network

### ISSUE THREAD

**Issue by alepc253** [MyCryptoHQ/MyCrypto#3815]
### Description of Issue

If you want to access using Ledger or Trezor to RSK network, it expects Ethereum app anyway.
- Ledger -> error message: "Error connecting to device. Incorrect network application selected on your Ledger device. Please select the application for the correct network.". If I open ETH app, it "works".
- Trezor -> tries to export ETH account: "Export public key of Ethereum account #1"

### What exactly were you doing when you encountered this issue?

Accessing my account

### How were you accessing your wallet?

Ledger and/or Trezor

### Description of Your Machine

- Browser: Chrome
- Browser version:
- Operating system: Mac
- Device:
- MyCrypto.com
- MyCrypto Version Number: 1.7.13

**Comment by Mrtenz** [comment]
Thanks for the heads up. This should be fixed in #3817.
