### ISSUE TITLE
Possible Error in Description - Unlock your Mnemonic Phrase

### ISSUE THREAD

**Issue by Ka2is** [MyCryptoHQ/MyCrypto#3854]
Hello,

First of all, thanks for the app. It is great and easy to use.

After I read some articles, including the ones below, I think I understand a little better how a mnemonic phrase works.

However, I think  that the explanation attached to the question mark symbol next to "Passphrase (optional):" in the "View & Send" menu is confusing or maybe even misleading.

It says "If you did not setup this additional password when your seed phrase was generated, you do not need to enter anything into this field." However, during my process to create a new wallet using a mnemonic phrase, I never got the chance to setup a password.

In addition to this and, if I'm not wrong, it is the combination of a mnemonic phrase and a password (or the absence of it), that will provide a list of available addresses to operate with.

Therefore, the same user could be operating with several accounts generated with the same mnemonic phrase, some with a password, some without them.

I might be completely wrong about this, as I am still learning about it.

- https://support.mycrypto.com/general-knowledge/ethereum-blockchain/difference-between-wallet-types
- https://support.mycrypto.com/general-knowledge/cryptography/how-do-mnemonic-phrases-work

Thanks for your time,

**Comment by Mrtenz** [comment]
Thank you for the feedback! You're right that the help description is slighlty misleading in that you don't enter a passphrase during the creation of a new mnemonic phrase. We are working on a replacement for the current desktop application, and this is definitely something we'll keep in mind.

> In addition to this and, if I'm not wrong, it is the combination of a mnemonic phrase and a password (or the absence of it), that will provide a list of available addresses to operate with.
> 
> Therefore, the same user could be operating with several accounts generated with the same mnemonic phrase, some with a password, some without them.

Yep! Private keys are derived ("generated") from the mnemonic phrase based on the mnemonic words and optional passphrase. There is no "wrong" passphrase here, using a different one will simply result in other private keys (and thus addresses) being derived.

If you're interested in learning more about how mnemonic phrases work in-depth, please check [this article](https://medium.com/mycrypto/the-journey-from-mnemonic-phrase-to-address-6c5e86e11e14).

**Comment by Ka2is** [comment]
Thanks @Mrtenz for the answer! I read the article and I found it very interesting. 

Good luck with the new application development and keep the great work!

**Comment by Mrtenz** [comment]
I think this issue can be closed. In the new desktop app (separate repo) we use different copy, which should be easier to understand. Thanks again for the feedback!
