### ISSUE TITLE
camera error: Cannot read property 'substr' of null

### ISSUE THREAD

**Issue by januszg7** [MyCryptoHQ/MyCrypto#3859]
_Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email support@mycrypto.com for faster attention._

_If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!_

---

### Description of Issue

Can't sent coins from my parity signer wallet, computer camera don't work.

### What exactly were you doing when you encountered this issue?

- open app
- go to: Parity Signer, Connect & sign via your Parity Signer mobile app
- open my wallet and write all data (adress, amount, transaction fee)
- scan QR code by my phone in Parity Signer
- and in the end can't scan QR code from my phone, camera isn't work (tried on 2 different laptops)
- see error "Cannot read property 'substr' of null" when i click "cancel"

### How were you accessing your wallet?

Private Key - Select an account from your Parity Signer

### Description of Your Machine

- Browser: -
- Browser version: -
- Operating system: Win10 home
- Device: 
- MyCrypto.com vs Desktop Application?
- MyCrypto Version Number: v1.7.13

### Console Logs / Screenshots

...

Sorry for ma language skills :/ I don't use it for a long time.

**Comment by wtzb** [comment]
Hi @januszg7! When you say that your camera doesn't work, does it not show you your webcam feed in the MyCrypto desktop app (showing a black/grey screen) when trying to sign this transaction?

Are you experiencing any issues with using your webcam on other services? You might try to open your desktop app as Administrator, to see whether that might solve the issue.

**Comment by januszg7** [comment]
![153540100_127520239201232_6330506842795180856_n](https://user-images.githubusercontent.com/79538749/110240676-5fb77500-7f4d-11eb-917d-7877a6373da6.jpg)

This I see all the time. I can type the wallet address on the keyboard, scan QR code and in the end see only this white-grey 
square.

Other laptop (Asus g14, without camera, I am using Canon camera + eos webcam utility, It's work well in many app) have the some problem but I see only bars:

![153231761_1942349622596222_175131135934421912_n](https://user-images.githubusercontent.com/79538749/110240873-38ad7300-7f4e-11eb-9278-e71d795ce25e.png)

I tried on Mac with camera and again saw only white-grey square(1st photo).

I opened app as Administrator but still problem is the same.

**Comment by wtzb** [comment]
@januszg7 thanks for getting back to me with this info! It's odd that you seem to be experiencing this issue with MyCrypto on both laptops, but are not experiencing this with other apps.

Could it be that you have any other applications open which might be using your webcam/camera? The grey box might show up if another application is already using your webcam/camera.

**Comment by januszg7** [comment]
Hi again, problem solved, NDI tools blocked my camera, after uninstall it, I send my crypto easy.
