### ISSUE TITLE
Wrong link for downloading Parity Signer

### ISSUE THREAD

**Issue by TomskDiver** [MyCryptoHQ/MyCrypto#3872]
### Description of Issue

Wrong link to download Parity Signer mobile app on "Create New Wallet" window.

![image](https://user-images.githubusercontent.com/2425151/109381398-e399ad80-790c-11eb-9009-4dacfd3c2ace.png)

This button go to https://play.google.com/store/apps/details?id=com.nativesigner - 404 Not found. Must be https://play.google.com/store/apps/details?id=io.parity.signer

### What exactly were you doing when you encountered this issue?

1. Install MyCrypto 1.7.13 desktop app
2. Run application
3. Click Create New Wallet on left
4. Click button "Download for Android" for Parity Signer

### How were you accessing your wallet?

No need wallet

### Description of Your Machine

- Operating system: Windows 10 Pro x64 (build 19041)
- Device: PC
- Desktop Application
- MyCrypto Version Number: 1.7.13

**Comment by Mrtenz** [comment]
Thanks for the heads up. This is fixed in #3874.

**Comment by TomskDiver** [comment]
Please fix also:
1. Click "View & Send"
2. Click Parity Signer badge
3. Here wrong url to Google Play (https://github.com/MyCryptoHQ/MyCrypto/blob/legacy/common/components/WalletDecrypt/components/ParitySigner.tsx#L68) and link to dead wiki (https://github.com/MyCryptoHQ/MyCrypto/blob/legacy/common/libs/wallet/non-deterministic/parity.ts#L3).
![image](https://user-images.githubusercontent.com/2425151/109407631-f8318080-79b4-11eb-8ea5-35622fd6376b.png)

May be link to wiki change to https://github.com/paritytech/parity-signer/blob/master/docs/tutorials/MyCrypto-tutorial.md ?

**Comment by Mrtenz** [comment]
Fixed those as well. Thanks again!

**Comment by Mrtenz** [comment]
#3874 was merged, so this can be closed now.
