### ISSUE TITLE
Cannot delete custom network with erroneos ChainID of another custom nw

### ISSUE THREAD

**Issue by solvizz** [MyCryptoHQ/MyCrypto#3875]
The desktop app doesn't have an interface to manage custom networks, only nodes. If I create a network with chain ID of some other custom network, I cannot delete it anymore or at least change its name/currency etc... to what I want.

Steps to reproduce:
When creating a new wallet, the app shows "How would you like to access your wallet?" screen.
Go to "Change network" -> "Add custom node".
Node name: test 1
Network: Custom
Network name: test 1
Currency: tst
ChainID: 12345
url: https://127.0.0.1/
Click "Save"

Go to change network again,
delete test 1 node, by clicking x to the right of it.

This is where error occurs: the node gets deleted, but the test 1 network with wrong ChainID is still there!
Suppose, I mistyped network name or currency, erased the node, and now I want actually to create a new network with this ChainID:

Click "add custom node" again
Node name: test 2
Network: custom
NW name: test 2
Currency: ts2
ChainID: 12345

A warning appears: Custom network cannot share chain ID with 'test 1'

That's it, I cannot anymore add any network with ChainID 12345.
Need to wipe mycrypto memory? As a workaround. How do I do that? Uninstall/reinstall doesn't help. Where does it keep its settings, like custom networks?

**Comment by Mrtenz** [comment]
Thanks for the report. We are working on a replacement for the current desktop app to work with the new MyCrypto, and the current desktop app likely won't be updated with new features anymore.

As a workaround, you can delete all app data for the desktop app:

1. Open the desktop app
2. Press Ctrl + Shift + I on your keyboard, or go to View > Toggle Developer Tools in the context menu
3. In the dev tools, go to the Application tab
4. Under stroage, go to Local Storage > file://
5. Look for the field with the name `REDUX_STATE` and select it
6. Press Del(ete) on your keyboard, or click on the Delete Selected (`x`) button
7. Reload the desktop app by pressing Ctrl + R on your keyboard

Note that this will delete any data from the app, including any other custom networks or tokens that you may have added to the app. Of course you can add them again afterwards.
