### ISSUE TITLE
Missing environment variable

### ISSUE THREAD

**Issue by leminh27102000** [MyCryptoHQ/MyCrypto#3878]
Failed to load ./.env. C:\Users\LENOVO\MyCrypto-master\node_modules\dotenv-webpack\dist\index.js:89 throw new Error("Missing environment variable: ".concat(key)); ^

Error: Missing environment variable: E2E_PRIVATE_KEY

Help me !!!

**Comment by FrederikBolding** [comment]
Hey there!

We use environment variables to store certain secrets used for testing. You can use the `.env.example` as a guidance on what you need to provide. This file should be renamed to `.env` for it to be picked up 👍  (See Environments in the https://github.com/MyCryptoHQ/MyCrypto/blob/master/README.md for more details)

Let me know if you have further questions.
