### ISSUE TITLE
MyCrypto Desktop wallet doesn't find Tokens

### ISSUE THREAD

**Issue by vodkadrunkinski** [MyCryptoHQ/MyCrypto#3880]
### Description of Issue
Loaded a wallet file with Tokens.  Wallet doesn't show tokens.  Ethplorer.io disagrees (as do I).
...

### How were you accessing your wallet?

Keystore File

### Description of Your Machine

Desktop Application
- MyCrypto Version Number: v1.7.13

...

**Comment by Mrtenz** [comment]
If your token does not show up, you may have to add it as a custom token first by following the instructions here: https://support.mycrypto.com/how-to/tokens/how-to-add-a-custom-token

If that does not solve it, please send an email to support@mycrypto.com with your Ethereum address and the tokens you are trying to see. Thanks!

**Comment by vodkadrunkinski** [comment]
I should mention that this is the (BNK) BANKERA Tokens, so it's an old, well-established token.   Not going to email support as I've decided not to use the wallet.  Please be aware of this issue though.
