### ISSUE TITLE
Duplicate word in mnemonic phrase

### ISSUE THREAD

**Issue by ColdDevil** [MyCryptoHQ/MyCrypto#3885]
Hey there :) I just found an interesting edge case or bug when using the desktop version of MyCrypto..

---

### Description of Issue

When creating a wallet using a mnemonic phrase there was a single word that showed up as duplicate, which caused an error in the confirmation screen.

- "Create New Wallet" button in the menu on the left
- "Generate a Wallet" button on the right
- "Generate a Mnemonic Phrase"
- I received a mnemonic phrase where two words were identical (is this even allowed?) .. I wasn't able to reproduce this even after regenerating the phrase 10-15 times..
- "Confirm Phrase"
- When clicking on the word that showed up as a duplicate, both words were selected, as shown in the screenshot:

<img width="1220" alt="mycrypto-duplicate-word-screenshot" src="https://user-images.githubusercontent.com/142297/110394936-8ec50800-806d-11eb-905e-49dc46186257.png">

I guess this should not occur as I was not able to finish the confirmation and had to restart the process. Maybe this is a pretty extreme edge case but maybe this can be prevented by simply checking for duplicates in the screen before ;)

### How were you accessing your wallet?

Mnemonic Phrase

### Description of Your Machine

- Operating system: macOS Big Sur 11.2.2
- Device: MacBook Pro (16", 2019)
- MyCrypto Desktop Application
- MyCrypto Version Number: 1.7.13

**Comment by Mrtenz** [comment]
This is a known issue (#3792 for example), but should not happen very often and when it happens you can simply generate a new mnemonic phrase as a workaround. We are working on a replacement for the current desktop application where this will be resolved. Thanks for the report though!

**Comment by ColdDevil** [comment]
Oh, I'm sorry. I haven't looked into closed issues.. I thought if it is not fixed in the latest version, it is a new issue ;) 
Alright, good to know!

**Comment by Mrtenz** [comment]
No worries, any feedback is very much appreciated!
