### ISSUE TITLE
Wrong derivation path for Avalanche C-Chain

### ISSUE THREAD

**Issue by jpop32** [MyCryptoHQ/MyCrypto#3952]
### Description of Issue

Unable to connect Ledger Nano S to MyCrypto.

### What exactly were you doing when you encountered this issue?

Tried to pair my Ledger Nano S to MyCrypto. At the 'Select an Account' several confirmations are asked on the device, but no address is found.

The problem seems to be the wrong derivation path used on the device. This is the Avalanche Wallet interface, when logging into the same device:

<img width="392" alt="Screenshot 2021-05-06 at 21 48 48" src="https://user-images.githubusercontent.com/6398640/117362239-4c784580-aebb-11eb-9131-8e4052b37658.png">

Note the second derivation path: `m/44'/60'/0'/0/0`. That one is used for accessing the C-Chain. Same derivation path shown on the device at login used with Avalanche Wallet:

<img width="901" alt="Screenshot 2021-05-06 at 22 37 57" src="https://user-images.githubusercontent.com/6398640/117362591-babd0800-aebb-11eb-9be1-8d8f60402745.png">

But MyCrypto has a shorter derivation path:

<img width="755" alt="Screenshot 2021-05-06 at 22 39 01" src="https://user-images.githubusercontent.com/6398640/117362700-e04a1180-aebb-11eb-9451-d14eac5a4b88.png">

Which is also used on the device:

<img width="901" alt="Screenshot 2021-05-06 at 22 39 43" src="https://user-images.githubusercontent.com/6398640/117362799-ff48a380-aebb-11eb-824e-00b56e3d58d9.png">

And that results in:

<img width="519" alt="Screenshot 2021-05-06 at 22 40 55" src="https://user-images.githubusercontent.com/6398640/117362906-23a48000-aebc-11eb-8d7f-eb3c06ecd0d0.png">

As a result, I am unable to pair the device with MyCrypto to access my Avalanche C-Chain wallet.

The funny thing is, I was the one that made [the PR to include Avalanche](https://github.com/MyCryptoHQ/MyCrypto/pull/3889) in the first place, and back then, after it was merged it all worked fine and there were no problems. So, sometimes between March 25th and today, something changed on the website that broke Avalanche access.

### How were you accessing your wallet?

Ledger Nano S

### Description of Your Machine

- Browser: Chrome
- Browser version: latest
- Operating system: MacOS
- Device: Nano S
- MyCrypto.com vs Desktop Application? Web
- MyCrypto Version Number: ea3aca5

**Comment by FrederikBolding** [comment]
Heya! The path shown is without the account index appended, this is done automatically in our scanning process.

If you toggle "show empty addresses" you should be able to see which accounts were scanned like so: 
![image](https://user-images.githubusercontent.com/1561200/117836669-12bb8c00-b279-11eb-87de-0ac4329424ce.png)

Perhaps we aren't picking up the balances correctly? Are you seeing the expected address if you use "show empty addresses"?

**Comment by FrederikBolding** [comment]
Hmm, weird that it is not showing any addresses. Do you see an error in the console? Can you try downloading the CSV to see if that contains any addresses?

@blurpesec Any ideas?

**Comment by jpop32** [comment]
Downloaded csv was an empty file.

The console shows an error:
[getMultipleAddresses]: Error Je {name: "TransportStatusError", message: "Ledger device: Security not satisfied (dongle locked or have invalid access rights) (0x6982)", stack: "Error↵    at new Je (https://app.mycrypto.com/main…crypto.com/main.fc1da81ea812b205d291.js:45:56471)", statusCode: 27010, statusText: "SECURITY_STATUS_NOT_SATISFIED"}

Which is interesting. Same device works without any problem in Avalanche Wallet.

**Comment by Mrtenz** [comment]
Looking at the derivation paths config, it was set to `m/44'/60'/...`, which was not changed afterwards. If you updated your Ledger firmware since the initial release, it's possible that you can no longer (easily) access your tokens on the `m/44'/60'/...` derivation path (since Ledger is blocking access to this path for non-Ethereum networks).

What is the expected derivation path for Avalanche?

**Comment by jpop32** [comment]
Yes, the derivation path for Avalanche's C-Chain is indeed `m/44'/60'/...`, that was deliberately chosen to be easier to port and integrate existing Ethereum solutions to Avalanche. For the X and P chains (exchange and platform chains), it's `m/44'/9000'...`.

Where can I find more information about that Ledger behaviour you mentioned? Haven't seen that before.

For what it's worth, both Ledger S and Ledger X work on the official Avalanche wallet with `m/44'/60'/...` path with no issues., all updated to the latest versions.

**Comment by Mrtenz** [comment]
Sorry for the late reply. Ledger has a list of possible derivation paths for each network here: https://github.com/LedgerHQ/app-ethereum/blob/master/Makefile#L41

I'm not sure if I understand what the issue is exactly. We use `m/44'/60'/...` for Avalanche C-Chain, which should be the standard derivation path for this network if I understand correctly?
