### ISSUE TITLE
Connection to the RSK network

### ISSUE THREAD

**Issue by KingVW** [MyCryptoHQ/MyCrypto#3956]
### What exactly were you doing when you encountered this issue?

I connected my Ledger Nano S to the PC desktop app. I connected to the RSK network. I got a list of my addresses, including the one where I hold my funds. I tried to unlock the address that holds my funds. I got a big red screen with the error code: Assertion Failed.

### How were you accessing your wallet?

Ledger nano S.
When I use the browser app (with chrome) and connect to the RSK network, the app can't find any of my addresses. I turned to the desktop app.

### Description of Your Machine

Desktop app v1.7.13
Windows

### Console Logs / Screenshots

![Capture](https://user-images.githubusercontent.com/41543138/117878014-472c4980-b273-11eb-88ff-cd20c41111cd.PNG)

**Comment by Mrtenz** [comment]
This should be fixed in the latest version of the desktop app (1.7.16). Thanks for the report!
