### ISSUE TITLE
Trouble connecting to Infura and Etherscan testnets (Ropsten, Kovan, Rinkeby)

### ISSUE THREAD

**Issue by stakingpoolspace** [MyCryptoHQ/MyCrypto#3958]
_Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email support@mycrypto.com for faster attention._

_If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!_

---

### Description of Issue

All three testnets using Infura and/or Etherscan (Ropsten, Kovan, Rinkeby) are currently unavailable. I was able to connect to Ropsten just a few days ago with no problems. (Ethereum mainnet is also showing POST issues in the Developer Tools at the moment.)

### What exactly were you doing when you encountered this issue?

When I try to switch from Ethereum mainnet to Ropsten, Kovan, or Rinkeby on the MyCrypto Desktop Application, I get the error messages "You’ve lost your connection to the network, check your internet connection or try changing networks from the dropdown at the top right of the page." and "Could not connect to the node. Refresh your page, try a different node (upper right corner), check your firewall settings. If custom node, check your configs.".

### Description of Your Machine

- Operating system: Windows 10
- Device: Laptop
- Desktop Application
- MyCrypto Version Number: 1.7.13

### Console Logs / Screenshots

![mycrypto_errors](https://user-images.githubusercontent.com/80047487/117930983-eba79d80-b2fe-11eb-8a51-3d48b46db41b.png)

**Comment by Mrtenz** [comment]
This is due to rate limiting by Infura and Etherscan, and not something we can do much about. For the best reliability, you can use MyCrypto's node, or run your own Ethereum node. Alternatively, you can use something like QuikNode to run a node by following the steps [here](https://support.mycrypto.com/how-to/nodes-networks/how-to-use-quiknode-with-mycrypto).
