### ISSUE TITLE
Assertion failed - 401 Infura

### ISSUE THREAD

**Issue by Rav3nPL** [MyCryptoHQ/MyCrypto#3960]
### Description of Issue

Mycrypto crashes "OOPS!"

### What exactly were you doing when you encountered this issue?

Connect Trezor wallet, pick address, wait for load balance

### How were you accessing your wallet?

Trezor, enabled passphrase

### Description of Your Machine

- Operating system: Win10x64
- Device: laptop
- Desktop Application
- MyCrypto Version Number: 1,7,13

### Console Logs / Screenshots
Log attached
[-1620860391131.log](https://github.com/MyCryptoHQ/MyCrypto/files/6469472/-1620860391131.log)

**Comment by Mrtenz** [comment]
This should be fixed in the latest version of the desktop app (1.7.16). Thanks for the report!
