### ISSUE TITLE
ar Ledger

### ISSUE THREAD

**Issue by ManoloEti** [MyCryptoHQ/MyCrypto#3973]
_Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email support@mycrypto.com for faster attention._

_If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!_

---

### Description of Issue

...

### What exactly were you doing when you encountered this issue?

...Give us some steps to reproduce...

### How were you accessing your wallet?

...Ledger, Trezor, MetaMask, Private Key, Keystore File, Mnemonic Phrase?...

### Description of Your Machine

- Browser:
- Browser version:
- Operating system:
- Device:
- MyCrypto.com vs Desktop Application?
- MyCrypto Version Number:

### Console Logs / Screenshots

...

**Comment by ManoloEti** [comment]
Nunca he encontrado tantos problemas como los encontrados al utilizar y transferir mis EWT desde mi Ledger a otra cuenta.
Es algo para no recomendar

**Comment by ManoloEti** [comment]
Tengo unos EWT en Metamask en mi billetera física, cuando intento transferirlos a otra EWT de Metamask  sale una pantalla de seguridad de Windows Acerca la clave de seguridad y me remite a Github, algo que no me ocurre con ninguna otra aplicación, y después de varios intentos me permite aceptar en el Ledger, pero nunca llega a realizarse la transacción. He estado en Github y no me reconoce el Ledger dando error. No encuentro la forma de recuperar mis EWT. Un saludo

**Comment by ManoloEti** [comment]
Aparece el siguiente error: Failed to execute “remove Child” on Node : The node to be removed is not a child of this node.

**Comment by Mrtenz** [comment]
If you have questions regarding using MyCrypto, please send an email to support@mycrypto.com (preferably in English). Thanks!
