### ISSUE TITLE
MyCrypto doesn't work with Trezor with BIP 39 passphrase, when passphrase entered on Trezor device

### ISSUE THREAD

**Issue by johnzweng** [MyCryptoHQ/MyCrypto#3975]
### Description of Issue

MyCrypto does not work with Trezor and BIP 39 passphrase, when Trezor is configured to enter passphrase on trezor device (and not on the computer).

### What exactly were you doing when you encountered this issue?

- Have a Trezor Model T (as only the Model T supports entering passphrase on device)
- Install `trezorctl` (https://github.com/trezor/python-trezor)
- Configure the Trezor to use BIP 39 passphrase with entering passphrase on device only, by entering the command: `trezorctl set passphrase enabled -f` (note the **`-f`** at the end, this is the flag which enforces passphrase-entering on-device)
- Open MyCrypto desktop application and click **"Connect to Trezor"**
- The following error is displayed in red: `Cannot read property 'name' of undefined`

### How were you accessing your wallet?

Trezor with BIP 39, and configured to allow passphrase entering only on Trezor device (not on host computer)

### Description of Your Machine

- Operating system: macOS, Big Sur
- Device: **Trezor Model T, Firmware 2.3.6**
- MyCrypto.com vs Desktop Application: MyCrypto Desktop Application
- MyCrypto Version Number: **1.7.16**

### Console Logs / Screenshots

![Screenshot 2021-05-26 at 07 17 00](https://user-images.githubusercontent.com/285900/119606777-71dddc80-bdf3-11eb-8ae6-3df144742674.png)

**Comment by Mrtenz** [comment]
Does the same issue occur on app.mycrypto.com?

**Comment by johnzweng** [comment]
No, on the website it works without problem.

**Comment by Mrtenz** [comment]
I made note of this on our internal bugtracker. As a workaround, you can use the web version on app.mycrypto.com instead. We don't actively update the desktop application anymore since we are working on a replacement, and we'll make sure this is not a problem there. Thanks for the report!
