### ISSUE TITLE
Does "yarn build" builds a working wallet? Can you run it locally?

### ISSUE THREAD

**Issue by sofasurfa** [MyCryptoHQ/MyCrypto#3984]
I am a bit confused... is this source code just a reflection of what's hosted on mycrypto.com, or can you build/run this locally on localhost? Also can you create an electron app? 

Thanks.

**Comment by Mrtenz** [comment]
You can build it locally by running `yarn build`. This will create the HTML and JS files in `dist/web`, which you can access through a local HTTPS server.

We have an Electron app for the old website (on the [legacy branch](https://github.com/MyCryptoHQ/MyCrypto/tree/legacy)), and we're working on a replacement for it that will work with the current web app.

**Comment by sofasurfa** [comment]
That's great, thanks. It would be nice if someone could update README with this information. Bcz now it seems like this is not an open-source wallet that you can run locally. But just a code-base for the website with an option to "build for dev and production". I know this wallet is for more advanced users, but since you spent so much energy/time making it... a more clear description in README would attract more "less advanced, privacy-concerned users" to use this open source wallet :)  I know you have a website hosting this code, but I bet a lot of less techy users would want to run it locally.
Thanks a lot guys 👍

**Comment by Mrtenz** [comment]
It's mentioned in the "About" section on the right, but I agree that the README could be updated to make this more clear as well. I'll make a note about it. Thank you for the feedback!
![image](https://user-images.githubusercontent.com/7503723/119882447-b91cb800-bf2e-11eb-8824-19b4ee4a070f.png)

**Comment by sofasurfa** [comment]
@Mrtenz Looking at package.json, it seems like in my case if I want to run the wallet at localhost, I will need to run `yarn prod`? In that case adding a section above "Development" such as "Start using the wallet, run `yarn prod`", so it's the first command/thing people see.

**Comment by Mrtenz** [comment]
You can use `yarn prod` to run a local server, but you can also use your own local server if you prefer. The fiiles in `dist/web` are just HTML and JS files which can be served over any HTTPS server.

**Comment by sofasurfa** [comment]
@Mrtenz makes sense, thank you. Just looked at the code, didn't know webpack can also act as a server... pretty cool :)
