### ISSUE TITLE
Unable to open MyCrypto on MacOS

### ISSUE THREAD

**Issue by somyapanda** [MyCryptoHQ/MyCrypto#4032]
_Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email support@mycrypto.com for faster attention._

_If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!_

---

### Description of Issue
I downloaded the MyCrypto software to install it on my system. I am not able to open the app after installing.

### What exactly were you doing when you encountered this issue?

Trying to install MyCrypto on a MacBook Air.

### How were you accessing your wallet?
N/A

### Description of Your Machine

- Browser:
- Browser version:
- Operating system: macOS Big Sur
- Device: MacBook Air (M1, 2020)
- MyCrypto.com vs Desktop Application? Desktop
- MyCrypto Version Number: 1.7.16

### Console Logs / Screenshots
I am getting the following error

> “MyCrypto” can’t be opened because Apple cannot check it for malicious software.
> This software needs to be updated. Contact the developer for more information.
>

**Comment by Mrtenz** [comment]
This is a known issue for the desktop app. You can find instructions for a workaround here: https://support.mycrypto.com/troubleshooting/unable-to-install-the-desktop-application

We're working on a replacement for the desktop app that won't have this issue.
