### ISSUE TITLE
MyCrypto does not work when connecting MetaMask with local full node

### ISSUE THREAD

**Issue by the-metalworker** [MyCryptoHQ/MyCrypto#4040]
### Description of Issue

MyCrypto gives me an error when I connect MetaMask with network set to Localhost 8545 local full node:

> MyCrypto doesn't support the network with chain ID '1337'

### What exactly were you doing when you encountered this issue?

I was trying to connect to MyCrypto using MetaMask.

### How were you accessing your wallet?

MetaMask

### Description of Your Machine

- Browser: Firefox
- Browser version: 89.0
- MetaMask version: 9.6.1
- Ethereum version: Geth 1.10.4
- MyCrypto.com vs Desktop Application? web app
- MyCrypto Version Number: the web app does not say anywhere as far as I can tell. whatever version is online at the time of creating this issue.

### Console Logs / Screenshots
No errors show up in the console. The error shows up in the web app on the connection screen.
...

**Comment by FrederikBolding** [comment]
Hey! We don't support custom networks on app.mycrypto.com at this time. You can run the application locally in dev mode for this option to be present. Then you should be able to add your custom network via the settings page. There are instructions in the README for running the dev build. 

Let me know if you have any more questions!
