### ISSUE TITLE
ENS support incorrect, doesn't support all ENS names

### ISSUE THREAD

**Issue by brantlymillegan** [MyCryptoHQ/MyCrypto#4042]
### Description of Issue

When I try to send ETH to the ENS name [brantly.art](https://app.ens.domains/name/brantly.art), it doesn't recognize the name and throws the error "Domain brantly.art is not supported".

This likely means that MyCrypto has a hardcoded list of domain suffixes in order to recognize an ENS name. This is incorrect. You should instead treat any dot-separated name as a potential ENS name and attempt a look-up. ENS is about to fully integrate the DNS namespace (adding ~1300 suffixes to ENS), and the DNS suffix namespace itself expands over time. So a hardcoded list will be constantly out of date. If you use a library like etherjs, it'll work correctly and be future proof.

### What exactly were you doing when you encountered this issue?

<img width="658" alt="Screen Shot 2021-06-22 at 8 32 05 PM" src="https://user-images.githubusercontent.com/30162762/123016717-37874100-d399-11eb-9b5d-334e9005bd94.png">

### How were you accessing your wallet?

MetaMask

### Description of Your Machine

- Browser: latest Chrome
- Browser version: latest
- Operating system: macos
- Device: Macbook Pro
- MyCrypto.com vs Desktop Application?: Website
- MyCrypto Version Number: latest

### Console Logs / Screenshots

...

**Comment by FrederikBolding** [comment]
This is due to an error in the library we use for ENS resolution. Will be solved with #4041 - thanks for reporting!
