### ISSUE TITLE
Can't use the App for DAO tokens!

### ISSUE THREAD

**Issue by GriffGreen** [MyCryptoHQ/MyCrypto#4058]
0xbb9bc244d798123fde783fcc1c72d3bb8c189413

<img width="815" alt="Screen Shot 2021-07-16 at 2 23 53 PM" src="https://user-images.githubusercontent.com/14945613/125946984-05e54051-7d22-4c67-a93d-5718956a08ba.png">

**Comment by FrederikBolding** [comment]
Hey Griff!

Long time no see 😄 

If you add it via the token panel on the dashboard your balance should show up and it should be included in the dropdown on the send page.

There is a guide here: https://medium.com/mycrypto/how-to-add-a-custom-token-to-mycrypto-a51a18ea3f74

If not, let me know and we can go from there 😄

**Comment by GriffGreen** [comment]
That worked!!
