### ISSUE TITLE
Legacy: Add new RSK tokens

### ISSUE THREAD

**Issue by 7alip** [MyCryptoHQ/MyCrypto#4118]
### Description of Issue

I have added new RSK tokens to the repository in which you prefer unlisted tokens to be added [https://github.com/ethereum-lists/tokens/pull/580](https://github.com/ethereum-lists/tokens/pull/580). But I've noticed that you only fetch eth tokens in the updater script:

https://github.com/MyCryptoHQ/MyCrypto/blob/f1338c32e7eaf71bae2f8f30217d3dda5b878662/scripts/update-tokens.ts#L55

Am I checking a wrong script? Otherwise I'm worried if RSK tokens will not be included in the next release.

**Comment by jspence425** [comment]
Hey @7alip, thanks for opening this issue. We've built a newer token system that allows us to add any tokens that are desired and we pull pricing and image data from CoinGecko to make it even easier.

This means, however, that if a token doesn't have an associated CoinGecko ID (the token slug in the url of the token's coingecko page), we likely won't be able to display the pricing data or asset imagery for it. 

We've gone ahead and added all these tokens to our list.

It seems that most of these tokens don't have associated CoinGecko IDs, so many of these likely won't appear as desired on MyCrypto, and if whoever is responsible for these tokens can get them listed on CoinGecko, it'll be better.

**Comment by 7alip** [comment]
Hi @jspence425, thanks for supporting the tokens. That's right, we are aware of that most of those tokens are not being supported by CoinGecko yet. 

I didn't know that the asset imagery system is related to CoinGecko. I would expect the images I prepared earlier to be added to the API. Nevertheless, it's great to have the tokens that users don't have to add them manually.

Thank you!
