### ISSUE TITLE
Custom Ledger derivation path for zero-th address with zero balance not showing

### ISSUE THREAD

**Issue by chuckb** [MyCryptoHQ/MyCrypto#4124]
### Description of Issue
When attempting to access a custom derivation path for Ethereum like (m/44'/60'/2'/0), addresses with zero balance (if option is picked to display them) start with address index 1 (for example (m/44'/60'/2'/0/1)). The zero-th address is not shown (which has a zero balance). Derivation paths that do have a balance on the zero-th address are showing up automatically, like (m/44'/60'/1'/0/0) for example.

### What exactly were you doing when you encountered this issue?
Trying to enumerate addresses on my Ledger device that were added to Ledger live a while back and I have some public keys referenced referenced and not changable for which a balance is to be soon expected.

### How were you accessing your wallet?
Ledger

### Description of Your Machine

- Browser: Chrome
- Browser version: 93.0.4577.63 (Official Build) (x86_64)
- Operating system: OSX 10.15.7
- Device: Macbook
- MyCrypto.com vs Desktop Application? MyCrypto.com
- MyCrypto Version Number: Not sure how to tell on web site

### Console Logs / Screenshots

...

**Comment by FrederikBolding** [comment]
Thanks for the report! I have reproduced the bug and will be opening a PR with a fix that should be included in the next release or two 😄
