### ISSUE TITLE
Need to change derivation path manually for Rinkeby

### ISSUE THREAD

**Issue by SvenMeyer** [MyCryptoHQ/MyCrypto#4128]
- installed `linux-x86-64_1.7.17_MyCrypto.AppImage`
- changed network to Rinkeby
- choose to access my wallet (which I use for testing) with Mnemonic
- pasted Mnemonic from Metamask in to MyCrypo
- ended up with different accounts ... ????

The only thing I could come up with was to change the derivation path, and as soon as I changed that to `Default (ETH) (m/44' /60' /0' /0)` the right addresses, matching the ones in Metamask showed up.

This is really not ideal, and I would claim that even some Eth developer never had to deal with a derivation path, and it was actually the first time, and first app where I ever had to set it manually

**Comment by Mrtenz** [comment]
You should use different addresses for different networks. We default to the testnet ETH derivation path, so by default you don't use a mainnet Ethereum address for testnets. I understand that this may be a bit inconvenient, but as of right now there is no easy way to change the default derivation path yourself.
