### ISSUE TITLE
lost internet connection - no account balance

### ISSUE THREAD

**Issue by SvenMeyer** [MyCryptoHQ/MyCrypto#4129]
- installed `linux-x86-64_1.7.17_MyCrypto.AppImage`
- got "lost internet connection" right from the start , although my Internet connection is good and no other application complains about it
- created account with parity signer
- accessed wallet using QR code
- MyCrypto does not manage to show account balance

![MyCrypto - lost Internet connection](https://user-images.githubusercontent.com/25609/133386893-5e3c35d3-ddf7-4a64-be93-0ca80ef40393.png)

![MyCrypto - lost Internet connection - no account balance](https://user-images.githubusercontent.com/25609/133387003-9ca6a3ab-9e34-4675-b667-591d1680f492.png)

**Comment by SvenMeyer** [comment]
Looks like as if , whatever node is use behind the kovan config, it does not work (well).

I created a new network "kovan-Infura" using my own Infura API key, that at least got the "lost Internet connection" away ...

**Comment by Mrtenz** [comment]
Unfortunately our Infura nodes may get rate limited sometimes. Like you said, you can use your own Infura key as a workaround for this issue, sorry for the trouble!
