### ISSUE TITLE
Addressbook ... how to choose an entry

### ISSUE THREAD

**Issue by SvenMeyer** [MyCryptoHQ/MyCrypto#4131]
- I can add an entry to the address book
- when I enter an address the name of the label shows up
- ... but in the address input field, I can not choose from the entries in my address book

**Comment by SvenMeyer** [comment]
My fault , did not click on the input field "the right way"

**Comment by FrederikBolding** [comment]
We have made improvements to these dropdowns recently too. Hopefully it should be more clear. Let us know if you have any other issues! 😄
