### ISSUE TITLE
Verifying release fails, GPG error

### ISSUE THREAD

**Issue by business-tomcat** [MyCryptoHQ/MyCrypto#4140]
### Description of Issue

Verifying desktop release fails

### What exactly were you doing when you encountered this issue?

Steps 3 and 4 of https://support.mycrypto.com/staying-safe/verifying-authenticity-of-desktop-app.
See console logs down there.

### Description of Your Machine

- Browser: /
- Browser version: /
- Operating system: Ubuntu 21.04
- Device: Desktop PC
- MyCrypto.com vs Desktop Application? Desktop Application
- MyCrypto Version Number: 1.7.17

### Console Logs / Screenshots

```
> curl https://keybase.io/tayvano/pgp_keys.asc | LANGUAGE=en gpg --import
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8509  100  8509    0     0   7820      0  0:00:01  0:00:01 --:--:--  7820
gpg: key 8DADC5E518486550: public key "Taylor Monahan <tayvano@gmail.com>" imported
gpg: key 697F4D4B81B15C84: public key "Taylor <tayvano@gmail.com>" imported
gpg: Total number processed: 2
gpg:               imported: 2

> LANGUAGE=en gpg --output checksums.txt --decrypt checksums.txt.gpg
gpg: Signature made Do 26 Aug 2021 05:46:52 CEST
gpg:                using RSA key 1B7A2D12DE76F0F0A2153B62697F4D4B81B15C84
gpg: Good signature from "Taylor <tayvano@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 1B7A 2D12 DE76 F0F0 A215  3B62 697F 4D4B 81B1 5C84
```
(no difference with or without `LANGUAGE=en`)

**Comment by Mrtenz** [comment]
Thanks for the report. "Good signature from "Taylor <tayvano@gmail.com>" [unknown]" indicates that the signature is valid. The warning below (not an error) basically means that GPG cannot ensure that the key that was used to sign _actually_ belongs to MyCrypto (Taylor), since it's not a "trusted" key. It's safe to ignore this warning however, as the key matches with the one shown on [Keybase](https://keybase.io/tayvano/) (second key).

**Comment by chaserene** [comment]
@Mrtenz from what I see, 1.7.17's checksums.txt is [signed with](https://github.com/MyCryptoHQ/MyCrypto/releases/download/1.7.17/checksums.txt.gpg) key ID ABC76446, which key is not on Taylor's Keybase, not even as a subkey.
