### ISSUE TITLE
MyCrypto wallet not able able to send ETH on hardhat network

### ISSUE THREAD

**Issue by jibrail-idris** [MyCryptoHQ/MyCrypto#4147]
_Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email support@mycrypto.com for faster attention._

_If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!_

---

### Description of Issue

Error `Trying to send an incompatible EIP-155 transaction, signed for another chain.` happened when I tried to send ETH from one account to another on a localhost hardhat network.

### What exactly were you doing when you encountered this issue?

Given the following hardhard config file.
```
/**
 * @type import('hardhat/config').HardhatUserConfig
 */
module.exports = {
  solidity: "0.8.4",
  networks: {
    hardhat: {
      chainId: 31337
    },
  },
};
```
Execute the local node listening process
```
$ hardhat --config hardhat.config.local.js node
Started HTTP and WebSocket JSON-RPC server at http://127.0.0.1:8545/`
```

### How were you accessing your wallet?

Restoration of generated private keys by hardhat in MyCrypto wallet. Mycrypto wallet is connected to local node.

### Description of Your Machine

- Browser:
- Browser version:
- Operating system: Windows 10
- Device: Desktop
- MyCrypto.com vs Desktop Application?
- MyCrypto Version Number: 1.7.17

### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/3234559/134795054-e4f5d391-3d32-4d6d-a1ec-468ec58f231f.png)

**Comment by jibrail-idris** [comment]
Managed to solve it. I simply set the `chainId` to `1` and it works.
Reference from https://github.com/MyCryptoHQ/MyCrypto/blob/master/hardhat.config.ts
![image](https://user-images.githubusercontent.com/3234559/134795726-63c0846b-5bb6-47ec-871c-693ce1ec8e0e.png)

**Comment by Mrtenz** [comment]
Glad to hear that you solved it. Feel free to reach out again if you encounter any issues.
