### ISSUE TITLE
desktop app not connecting to network on TailsOS

### ISSUE THREAD

**Issue by degenprivacy** [MyCryptoHQ/MyCrypto#4149]
### Description of Issue
According to your [blog](https://blog.mycrypto.com/how-to-use-mycrypto-more-privately/) and [support page](https://support.mycrypto.com/staying-safe/how-to-use-mycrypto-more-privately) MyCrypto should run on TailsOS.

It is not quite clear which version you are referring to but the Linux desktop app does not connect to the network. See screenshot below:

### What exactly were you doing when you encountered this issue?
Starting AppImage app and seeing error message right away.

### Description of Your Machine

- Browser: N/A
- Browser version: N/A
- Operating system: Tails OS 4.22 (latest)
- Device: Laptop
- MyCrypto.com vs Desktop Application? Desktop
- MyCrypto Version Number: `linux-x86-64_1.7.17_MyCrypto.AppImage`

### Console Logs / Screenshots
![Screenshot from 2021-09-29 18-24-55](https://user-images.githubusercontent.com/74694504/135330574-36986f01-f409-49ed-80fa-7315a5bce468.png)

**Comment by degenprivacy** [comment]
Here the output from the debug output in the app
![Uploading Screenshot from 2021-10-02 21-10-21.png…]()

**Comment by Mrtenz** [comment]
Thanks for the report - I will look into this issue further!

**Comment by Jassy2** [comment]
Great project

**Comment by Mrtenz** [comment]
Not stale - need to find some time to look into this but it's not the highest priority at the moment.

**Comment by kyoukisu** [comment]
Getting same issue. Is it possible to let app use proxy for tor at least using arguments in cmd?
https://tor.stackexchange.com/questions/3435/how-do-i-configure-chrome-to-use-tor
