### ISSUE TITLE
No MyCrypto icon shown in menu when integrating linux-x86-64_1.7.17_MyCrypto.AppImage on Debian

### ISSUE THREAD

**Issue by DeeDeeRanged** [MyCryptoHQ/MyCrypto#4156]
No MyCrypto icon shown in menu when integrating linux-x86-64_1.7.17_MyCrypto.AppImage on Debian

./linux-x86-64_1.7.17_MyCrypto.AppImage first time it asked for integration, confirm it installs a menu item but there is no mycrypto icon. Application runs fine.

- Operating system: Debian testing/bookworm
- Device: PC
- MyCrypto.com vs Desktop Application? Desktop Application
- MyCrypto Version Number: 1.7.17

### Console Logs / Screenshots
(node:331575) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): FetchError: request to http://127.0.0.1:21325/ failed, reason: connect ECONNREFUSED 127.0.0.1:21325
(node:331575) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jxu** [comment]
I have the same issue. In .desktop file: `Icon=appimagekit-mycrypto`
