### ISSUE TITLE
Binance Smart Chain - Scan for tokens doesnt work / Add custom tokens breaks the app functionality.

### ISSUE THREAD

**Issue by ARZUMATA** [MyCryptoHQ/MyCrypto#4176]
### Description of Issue

MyCrypto Desktop app doesn't detect tokens neither let's add custom one in Binance Smart Chain.

### What exactly were you doing when you encountered this issue?

Clean install of MyCrypto (made sure "AppData\Roaming\MyCrypto" also cleaned)
I add Custom Node in networks list.
Add Binance Smart Chain as per official guide (https://academy.binance.com/en/articles/connecting-metamask-to-binance-smart-chain)
Checked I'm connected the network on the left panel.
I add my address, in this case let's use Binance Hot wallet.
0xe2fc31F816A9b94326492132018C3aEcC4a93aE1

Once info is updated, an app shows account balance in BNB. All correct.
This account also holds tokens so I click "Scan for tokens "and immediately get "No tokens found".
Then I click "Add Custom Token" and add:
BUSD Token (BUSD) ERC20 Token in Binance Smart Chain Mainnet
https://explorer.bitquery.io/bsc/token/0xe9e7cea3dedca5984780bafc599bd69add087d56/smart_contract

App queries an address, shows decimals value, symbol, and balance. All seems correct.
Upon clicking "Save" nothing happens, and app still shows "No tokens found".
After that, clicking Scan again yields nothing, as well.
And then if I click "Change Wallet" and go back to main screen and try to load address again via "View Address" an app shows loading icon under Account Balance and gets stuck.
Restarting app helps to get it back to working state except for token support.

### How were you accessing your wallet?

Private Key
Mnemonic Phrase
in this case - View Address

### Description of Your Machine

- Browser: not applicable
- Browser version: not applicable
- Operating system: Windows 10
- Device:
- MyCrypto.com vs Desktop Application? Desktop
- MyCrypto Version Number: 1.7.17

### Console Logs / Screenshots

Once I entered address via View Wallet option.
![image](https://user-images.githubusercontent.com/54457203/138317500-429be2f1-da38-442a-b09c-a07098327260.png)

Right before clicking "Save" on adding custom token.
![image](https://user-images.githubusercontent.com/54457203/138317664-64294108-52d0-4625-afde-a13aed3761a2.png)

Scan for tokens doesn't write anything to console.

**Comment by wtzb** [comment]
Hey @ARZUMATA! Thanks for opening this issue, it's much appreciated. I was able to reproduce this behavior from my end.

This might be because BNB isn't officially supported by the desktop app at this time, but nevertheless, this isn't expected behavior. If you're able to, can you attempt to access your address (or view-only) with [app.mycrypto.com](https://app.mycrypto.com/)? Binance Smart Chain is supported there, by selecting "Smart Chain" upon adding your address to the dashboard.

My apologies for the inconvenience this must've caused, but I hope that using the MyCrypto Dashboard might resolve your issue for the time being!

**Comment by Afsoning** [comment]
> ### Description of Issue
> 
> MyCrypto Desktop app doesn't detect tokens neither let's add custom one in Binance Smart Chain.
> 
> ### What exactly were you doing when you encountered this issue?
> 
> Clean install of MyCrypto (made sure "AppData\Roaming\MyCrypto" also cleaned)
> I add Custom Node in networks list.
> Add Binance Smart Chain as per official guide (https://academy.binance.com/en/articles/connecting-metamask-to-binance-smart-chain)
> Checked I'm connected the network on the left panel.
> I add my address, in this case let's use Binance Hot wallet.
> 0xe2fc31F816A9b94326492132018C3aEcC4a93aE1
> 
> Once info is updated, an app shows account balance in BNB. All correct.
> This account also holds tokens so I click "Scan for tokens "and immediately get "No tokens found".
> Then I click "Add Custom Token" and add:
> BUSD Token (BUSD) ERC20 Token in Binance Smart Chain Mainnet
> https://explorer.bitquery.io/bsc/token/0xe9e7cea3dedca5984780bafc599bd69add087d56/smart_contract
> 
> App queries an address, shows decimals value, symbol, and balance. All seems correct.
> Upon clicking "Save" nothing happens, and app still shows "No tokens found".
> After that, clicking Scan again yields nothing, as well.
> And then if I click "Change Wallet" and go back to main screen and try to load address again via "View Address" an app shows loading icon under Account Balance and gets stuck.
> Restarting app helps to get it back to working state except for token support.
> 
> ### How were you accessing your wallet?
> 
> Private Key
> Mnemonic Phrase
> in this case - View Address
> 
> ### Description of Your Machine
> 
> - Browser: not applicable
> - Browser version: not applicable
> - Operating system: Windows 10
> - Device:
> - MyCrypto.com vs Desktop Application? Desktop
> - MyCrypto Version Number: 1.7.17
> 
> ### Console Logs / Screenshots
> 
> Once I entered address via View Wallet option.
> ![image](https://user-images.githubusercontent.com/54457203/138317500-429be2f1-da38-442a-b09c-a07098327260.png)
> 
> Right before clicking "Save" on adding custom token.
> ![image](https://user-images.githubusercontent.com/54457203/138317664-64294108-52d0-4625-afde-a13aed3761a2.png)
> 
> Scan for tokens doesn't write anything to console.
> 
> 
>
