### ISSUE TITLE
unclear if MyCrypto desktop application is maintained or not

### ISSUE THREAD

**Issue by adrelanos** [MyCryptoHQ/MyCrypto#4189]
I want to use MyCrypto offline. Found this article:

https://support.mycrypto.com/how-to/offline/how-to-run-mycrypto-offline-and-locally

> The MyCrypto desktop application is part of an older version of MyCrypto that is not actively maintained. You can find the latest version of MyCrypto on mycrypto.com.

Ok, go to https://mycrypto.com/ -> see this

> Get the Original MyCrypto Desktop App
> A fan favorite since 2018, the MyCrypto Desktop App continues to provide an additional layer of security for your Ethereum assets. Want more info?

Alright, I click "Want more info?". Now I am here:
https://download.mycrypto.com/

Makes a good impression. Looks maintained.

I want to learn about "Signed Checksums", clicking that, now I am here:
https://support.mycrypto.com/staying-safe/verifying-authenticity-of-desktop-app/

Now I am back full cycle.

> The MyCrypto desktop application is part of an older version of MyCrypto that is not actively maintained. You can find the latest version of MyCrypto on mycrypto.com.

This is confusing.

**Comment by Mrtenz** [comment]
`app.mycrypto.com` currently does not work offline, so for those situations we recommend using the desktop application. It is not actively maintained however, and we don't add any new features to the desktop application. It's still perfectly usable though if you have a plain private key or want to send offline.

We are working on a replacement for the desktop application, which you can check out here: https://github.com/MyCryptoHQ/quill. It's still a work in progress however, and we don't recommend using it with "real" private keys just yet.

**Comment by adrelanos** [comment]
Is there still security support for the desktop application?

Would the desktop application get security updates if vulnerabilities are reported or would any vulnerabilities reports be rejected?

**Comment by Mrtenz** [comment]
We will still update it in case of security vulnerabilities, at least until the release of the new application.
