### ISSUE TITLE
Shotota/Sa

### ISSUE THREAD

**Issue by sheakhasan926** [MyCryptoHQ/MyCrypto#4205]
Shotota/Sa

_Originally posted by @sheakhasan926 in https://github.com/MyCryptoHQ/MyCrypto/issues/4204#issuecomment-976411088_

**Comment by sheakhasan926** [comment]
> Shotota/Sa
> 
> _Originally posted by @sheakhasan926 in https://github.com/MyCryptoHQ/MyCrypto/issues/4204#issuecomment-976411088_

**Comment by FrederikBolding** [comment]
Hey! If you are having an issue with the application, please elaborate on the issue. You can also contact support@mycrypto.com.
