### ISSUE TITLE
Blank screen after adding erc20 token

### ISSUE THREAD

**Issue by jonathascarrijo** [MyCryptoHQ/MyCrypto#4220]
### Description of Issue

Dashboard blank page after I added a custom smart contract.

### What exactly were you doing when you encountered this issue?

I selected a custom path address (`m/44'/60'/1'/0`) and added a single account for the address `0xc208e32b16859884991774938839dDEc23d50492` (path `m/44'/60'/1'/0/33`).

The UI showed "No Tokens Found", so I went on to manually add an ERC20 token, supplying the contract address `0xa6fa6531acdf1f9f96eddd66a0f9481e35c2e42a`, and the UI loaded the ticker CBRL and 6 decimals places automatically.

After I clicked "Add token", the screen went blank, and the browser console shows the following error:

```
main.560d577a10564b057436.js:278612 TypeError: Cannot read properties of null (reading 'toFixed')
    at main.560d577a10564b057436.js:193442
    at Array.map (<anonymous>)
    at t.default (main.560d577a10564b057436.js:193442)
    at na (main.560d577a10564b057436.js:278612)
    at Gs (main.560d577a10564b057436.js:278612)
    at Mu (main.560d577a10564b057436.js:278612)
    at wu (main.560d577a10564b057436.js:278612)
    at vu (main.560d577a10564b057436.js:278612)
    at fu (main.560d577a10564b057436.js:278612)
    at main.560d577a10564b057436.js:278612
```

### How were you accessing your wallet?

Ledger with a custom path.

### Description of Your Machine

- Browser: Chrome
- Browser version: 96.0.4664.45 (official version) 64 bit
- Operating system: Linux Mint
- Device: Samsung notebook
- MyCrypto.com website
- MyCrypto Version Number: v.57cb3a2

---

I deleted the LocalStorage and did it all over, getting the same result.

**Comment by Mrtenz** [comment]
Can you try clearing your browser cache, and see if this issue persists?

**Comment by jonathascarrijo** [comment]
I tried clearing the cache, went through the same steps and got the same result.

**Comment by Mrtenz** [comment]
I'm able to reproduce this issue, so will look into it further. Thanks for the report!
