### ISSUE TITLE
Desktop application fail to get equivalent of gas

### ISSUE THREAD

**Issue by sguarin** [MyCryptoHQ/MyCrypto#4239]
### Description of Issue
MyCrypto Application Linux version doesn't show equivalent assets.

![image](https://user-images.githubusercontent.com/4202701/147892825-d02c437a-1534-40aa-90f8-05822cb579f8.png)

### What exactly were you doing when you encountered this issue?

Give a try.

### How were you accessing your wallet?

Keystore file

### Description of Your Machine

- Operating system: Fedora 34 64 bits
- Desktop Application
- MyCrypto Version Number: 1.7.17

### Console Logs / Screenshots
When in developer mode, I could see the following request failing to get equivalent of gas assets.

https://proxy.mycryptoapi.com/cc?fsym=ETH&tsyms=USD,EUR,GBP,CHF,RUB,JPY,KRW,INR,BTC,ETH,ETH
{"message":"Missing Authentication Token"}

**Comment by FrederikBolding** [comment]
Thanks for reporting! I'll be sure to let our infrastructure team know so we can triage and fix this issue. Will let you know when I know more.

**Comment by FrederikBolding** [comment]
@sguarin this issue should now be fixed! Thanks again for reporting it.

Feel free to open an issue if you find any other problems like this!

**Comment by sguarin** [comment]
Thanks. I confirm you that its fixed.
