### ISSUE TITLE
Still using 2021 in all your latest release dates + https://download.mycrypto.com/ not up to date 

### ISSUE THREAD

**Issue by timbeiko** [MyCryptoHQ/MyCrypto#4279]
You have a typo in your release dates, and I think it's breaking your download website :-) 

This release was cut yesterday, should be Feb **2022**, not 2021: 

<img width="1231" alt="Screen Shot 2022-02-09 at 1 30 20 PM" src="https://user-images.githubusercontent.com/9390255/153293349-338a1974-9f54-464a-a581-35aadde960f8.png">

[Your website](https://download.mycrypto.com/) then shows the latest 2021 release as the last one: 
<img width="521" alt="Screen Shot 2022-02-09 at 1 31 10 PM" src="https://user-images.githubusercontent.com/9390255/153293429-f6a1ab8f-5496-428d-a246-d74f6bc0a2f2.png">

**Comment by chrishamer91** [comment]
The team has been notified :) thanks!

**Comment by FrederikBolding** [comment]
@timbeiko Just to clarify - it is intentional for the download page to serve `1.7.17`, as we don't produce a desktop version of v2.

**Comment by timbeiko** [comment]
@FrederikBolding ah, got it! It might make sense to highlight that on the page. One thing that confused me is that the screenshots on the download pages have a `Swap` feature, but the download didn't, so I was looking for a desktop version which did have it. If you don't plan on offering that as a download version, I'd maybe just make that clearer on the page. Just my 2 gwei :-)

**Comment by Mrtenz** [comment]
@timbeiko The downloads page will be replaced very soon by the one [here](https://github.com/MyCryptoHQ/download), for our upcoming replacement of the desktop application. Thanks for the feedback though!
