### ISSUE TITLE
Not able to connect XinFin Network 

### ISSUE THREAD

**Issue by RuslanWing** [MyCryptoHQ/MyCrypto#4283]
### Description of Issue
XinFin Network is an EVM compatible network but not able to connect it to mycrypto wallet with metamask and XDC Network has been also added on Chainlist https://chainlist.org/ in the list of the EVM compatible network

### What exactly were you doing when you encountered this issue?

Not able to Connect XinFin Network to mycrypto wallet with metamask it shows error MyCrypto doesn’t support the network with chain ID '50'

### How were you accessing your wallet?

MetaMask

### Description of Your Machine

- Browser: Chrome
- Browser version: 98.0.4758.102
- Operating system: Windows
- Device:- Laptop

### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/76780500/154410121-132e48c0-3402-46c7-ba79-2c168998da6d.png)

**Comment by FrederikBolding** [comment]
We're currently reviewing a PR that adds this network 👍 

See #4250

**Comment by FrederikBolding** [comment]
Solved with #4250
