### ISSUE TITLE
Public address lower case issue

### ISSUE THREAD

**Issue by banjo-kazooie** [MyCryptoHQ/MyCrypto#4290]
Under Wallet Info -> Your Address all letters of the public address are lower case. The QR-Code is correct, though. This might be fatal if someone entered the address manually.

### How were you accessing your wallet?

Keystore File, Mnemonic Phrase

### Description of Your Machine

- Operating system: Lubuntu Linux
- Desktop Application
- MyCrypto Version Number: 1.7.17

**Comment by banjo-kazooie** [comment]
Sorry, mixed up address and public key. Nevermind. Still a bit confusing if you're unfamiliar with Ether.

**Comment by FrederikBolding** [comment]
Glad to hear you solved it yourself. Let us know if you have any other questions!
