### ISSUE TITLE
Add CAD support as fiat currency 

### ISSUE THREAD

**Issue by seblavoie** [MyCryptoHQ/MyCrypto#4301]
I think that adding support for a wider array of currencies would be helpful. The one I'd like personally is Canadian dollars (CAD). 

I can make a pull request, but your contributor guide specified to make an issue first so here it is. 

Let me know, if that makes sense on your end to add it and I'll gladly provide the pull request.

Thanks and great work by the way! :)

**Comment by FrederikBolding** [comment]
Feel free to open a PR for this @seblavoie !
