### ISSUE TITLE
Standardize Checksums and Hex Prefixes for Public/Private Addresses

### ISSUE THREAD

**Issue by eddiewang** [MyCryptoHQ/MyCrypto#437]
Currently, when we create a wallet in the production site, the filename is a combination of the date, and the unchecksummed public address without a prefix:

![image](https://user-images.githubusercontent.com/2057997/33083527-96e45808-cead-11e7-8bca-70103acf6a58.png)

The private key is displayed without a hex prefix, like this:
![image](https://user-images.githubusercontent.com/2057997/33083690-12ba7f16-ceae-11e7-85aa-2ac418b8dc97.png)

Since we've moved to the ethereumjs library to handle the wallet creation, it's added minor changes to the way addresses are handled. For example, by default the private key automatically includes a `0x` prefix for the key. 

![image](https://user-images.githubusercontent.com/2057997/33084082-05e2b140-ceaf-11e7-8dd0-5f47c06530b2.png)

To maintain compatibility, we plan to manually remove the 0x so that both the paper wallet and the private key displayed on wallet creation.

This is a discussion to see if we should standardize how we choose to display the public key and private keys to the user, and if we should be prefixing the `0x` hex identifier for the public and private keys, and if we should be checksumming the public address in the wallet filename.

**Comment by tayvano** [comment]
This is likely part of a larger discussion within Ethereum community but general unofficial consensus is **NO 0x before private keys**. Namely to reduce confusion between Addresses or TX hashes that alwlays SHOULD HAVE the proceeding 0x.

Fun fact: TX hashes and private keys are same length. 😱
