### ISSUE TITLE
Understand and standardize hex modifications

### ISSUE THREAD

**Issue by eddiewang** [MyCryptoHQ/MyCrypto#474]
We're using alot of different methods to strip hex prefixes, add hex prefixes, pad, lower, etc. We need to make sure that we're keeping things DRY, and perhaps add some of the address prefixing (or un-prefixing) functionality directly as a method on the wallet class.

**Comment by dternyak** [comment]
After changes are made, reminder to visit [here](https://github.com/MyEtherWallet/MyEtherWallet/pull/388/files#diff-1786a0c4dc7c3f0a517ec16fae0d0236R17) and [here](https://github.com/MyEtherWallet/MyEtherWallet/pull/388/files#diff-7238a35c049f186454ea2179bf752dd6R31)
