### ISSUE TITLE
(E)NS resolving support

### ISSUE THREAD

**Issue by crptm** [MyCryptoHQ/MyCrypto#62]
- [ ] 1. match all foo.tld addresses 
- [x] 2. resolve label to address on resolver

---

- [ ] We should debounce 1.
- [x] We can cache 2 bw browser refreshes.
- [x] Use ens abi to interact with contracts.

Bonus points for:
- [ ] readable errors
- [ ] extension point(s) to integrate non-ens resolving

**Comment by dternyak** [comment]
Henry says yes.
