### ISSUE TITLE
Ensure correct EXP Integration

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#627]

**Comment by tayvano** [comment]
Also reference: https://github.com/kvhnuke/etherwallet/pull/840

**Comment by chrisfranko** [comment]
K I’ll check this out soon as I can. Traveling atm. 🤗

**Comment by dternyak** [comment]
@chrisfranko Were you still interested in helping out to fully integrate RSK into V4?

**Comment by chrisfranko** [comment]
EXP, and yes absolutely. I just got back from holiday a week ago and have
been catching up.

**Comment by dternyak** [comment]
Great.

We're under audit in less than a week, so earlier than later would be better to make it in with the audit :)

**Comment by chrisfranko** [comment]
Hey @dternyak what are the best steps for me to audit. :) Which files do I need to audit?

**Comment by dternyak** [comment]
Hey @chrisfranko - sorry for the delayed response. 

1. common/config/dpaths
2. common/config/nodes/staticNodes

It would also be valuable to just confirm purely from a user perspective that the integration is correct.

**Comment by chrisfranko** [comment]
Hey Daniel, no worries man. After checking it from a user perspective, its
solid. We are going to setup some better loadbalanced exp nodes for you as
well since digital ocean keeps force restarting our servers.

**Comment by dternyak** [comment]
Sorry for the delay in response. Thanks a lot for your help @chrisfranko
