### ISSUE TITLE
Update Default Token List from V3

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#630]
- [ ] Integrate `ethereum-lists` as git sub-module

**Comment by tayvano** [comment]
Should pull from https://github.com/myetherwallet/ethereum-lists

Finishing up build system that will compile to a more limited file

Did you want to grab it from API or include with source?

**Comment by dternyak** [comment]
We could work out a git-submodule approach so that we don't have multiple sources of truth, have to make additional request, and allow that repo to managed independently.

**Comment by dternyak** [comment]
@tayvano Is it now possible load this data via API?

**Comment by wbobeirne** [comment]
Closing this out in favor of #969, update their about the API. But for now, the blocking part of this is done.
