### ISSUE TITLE
Catch error if user attempts to send to ENS name (e.g. mewtopia.eth) while in offline mode

### ISSUE THREAD

**Issue by tayvano** [MyCryptoHQ/MyCrypto#636]
Offline == cannot reach contract to resolve == cannot resolve to the 0xaddress. (This may already be complete)

Also needs to be caught on any input that allows ENS name input (e.g. #631)

Error can be something like:

`You must be online in order to send to an ENS name. Please provide the full address or go online.`

Reference: https://github.com/kvhnuke/etherwallet/issues/1389

(the lowest of low priorities. very rare occurrence, no harm done if not complete)

**Comment by wbobeirne** [comment]
@HenryNguyen5 it shows as "Resolved Address: 0x0" for any names offline, though a notification does pop up saying "Failed to fetch" and the field is marked invalid. I think all we need here is to fix it showing as resolved, and instead show the error there. Maybe get rid of the notification while we're at it.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837184)
