### ISSUE TITLE
Firefox Support for U2F (Ledger)

### ISSUE THREAD

**Issue by tayvano** [MyCryptoHQ/MyCrypto#637]
The terrible u2f packages will likely need to be updated once we figure out how to solve to make Ledger work on Firefox's implementation. This is still WIP on v3, but if there are related issues open in v4, they may end up being solved via this update. This actually has a few other notable improvements which will be nice, like promises

- v3 issue with lots of resources: https://github.com/kvhnuke/etherwallet/issues/1122

- The npm package that will most likely end up being used: https://www.npmjs.com/package/u2f-api

- Another team who recently had to update: https://github.com/nextcloud/twofactor_u2f/pull/74

**Comment by wbobeirne** [comment]
Just want to confirm this is still a problem, despite now using [Ledger's npm package](https://www.npmjs.com/package/ledgerco). Looks like this is still an issue in their queue: https://github.com/LedgerHQ/ledgerjs/issues/89.
