### ISSUE TITLE
'DAI' and 'OLD_MKR' won't show up in default tokens list in UI. 'MKR' is referencing the wrong token contract.

### ISSUE THREAD

**Issue by NiklasKunkel** [MyCryptoHQ/MyCrypto#712]
In reference to: https://github.com/MyEtherWallet/ethereum-lists/issues/318

**Comment by dternyak** [comment]
Hey @NiklasKunkel!

Thanks for opening up this issue. I don't mean to "pass the buck" so to speak, but I believe you are meaning to file this against the existing production site at https://myetherwallet.com, not our V4 implementation.

If this is true, you may want to re-file against https://github.com/kvhnuke/etherwallet. We'll be sure to update the contract address for V4 at the time it is released.

Best,
Daniel

**Comment by wbobeirne** [comment]
Closing this in favor of more holistic token updating solution (#1247 or #969)
