### ISSUE TITLE
Optimize JS bundle size

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#721]
There are a few things we could do to substantially reduce our bundle size by a sizable amount:

1. translations - 1.09mb (Ideally we can only load the locale you're currently set to use.)
2. lodash - 526kb (We should be using a subset of its functionality.)
3. Moment locales - 344kb (Ideally we can only load the locale you're currently set to use.)
4. unorm.js - 139kb (Do we need this polyfill?)
5. contracts json - 107kb (Could be an externally loaded asset on the contracts page.)
6. bip39 wordlist locales - ~90kb (Do we need these? Do we support them at the moment?)

The language stuff might be tricky, I'm thinking we'll need a third bundle in addition to vendor and client, some kind of `language.(en|fr|de|etc).js` file that has the language-specific code.

**Comment by dternyak** [comment]
https://github.com/MyCryptoHQ/MyCrypto/issues/1191 should largely take care of this. We can re-open if needed after more webpack 4 investigation
