### ISSUE TITLE
Warning or Info message somewhere if you are about to send funds to your self

### ISSUE THREAD

**Issue by tayvano** [MyCryptoHQ/MyCrypto#731]
> Can you add an alert for if the SEND from and RECIPIENT are the same address? I had a friend just send money to himself. lol! #oops

https://twitter.com/kylewarmour/status/949114445128749056

Probably a good one for a bounty? 

Probably best to add to the confirmation modal?

**Comment by wbobeirne** [comment]
#724 adds the ability to attach an error message to the to address field. Seems like an easy thing to add onto that.

**Comment by wbobeirne** [comment]
This was done a while ago.
