### ISSUE TITLE
Combat NPM Based Attacks

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#751]
The security model of relying on NPM's public registry allows for several attack vectors, especially since NPM does not enforce immutable packages.

Once a package is deleted, NPM will allow a package with an identical namespace to be published. [This](https://status.npmjs.org/incidents/41zfb8qpvrdj) incident caused significant amounts of packages to be re-published, any of which could have been malicious.

Additionally, there is (admittedly low) risk in trusting the public NPM registry to serve the correct package.

This issue is largely a request for comment on potential mitigations, however I would like to propose that at a minimum we switch over to our own mirrored / private registry.

**Comment by wparad** [comment]
Haven't validated it yet, but I assume a better solution would be something like
`yarn --freeze-lockfile` which validates that the hash of the package is the same, rather than having to commit/mirror all the packages locally.

**Comment by ConnorBryan** [comment]
Created an issue in GitHub.
