### ISSUE TITLE
Present non-generated wallets as options on Create New Wallet

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#778]
As I've been working on #557, I realize that while we may brow-beat users with other options for wallet on unlock, we'd be best off trying to guide them towards other wallets _before_ they generate one. Rather than show a bunch of (easily ignored) warnings during generate with links to other wallets, what if we presented MetaMask / Ledger / Trezor as options for creating a new wallet? Quick n dirty mockup, but the idea is there'd be much more emphasis on the more secure options, and we put the insecure generatable ones towards the bottom with warnings.

![create-multi-option](https://user-images.githubusercontent.com/649992/34791854-33beba50-f614-11e7-8f85-67b6c3d5ba29.png)

Let me know if y'all have thoughts on this.

**Comment by dternyak** [comment]
Definitely makes sense to start letting them know what wallet options we recommend earlier in the process rather than later.

👍

**Comment by dternyak** [comment]
The Parity Mobile Signer is a good candidate for this view as well.

**Comment by wbobeirne** [comment]
Closing in favor of #557, to do all together.
