### ISSUE TITLE
Auto-cycle through nodes

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#802]
Currently, we do not attempt to establish a connection with another default node when determining that the currently selected node is down. Instead, we simply notify the user that the node is down.

Through offline polling that is initiated on-load, we make a single ping to the selected node to determine it's health. Additional logic should be inserted to test the health of the non-default node and swap to the first available node. Randomness should be used here so as not to suddenly DDoS a node provider should we switch all live traffic to them in the case that our default node goes down. Instead, we should attempt to redistribute the traffic in a roughly even manner across other default nodes.

- [ ] Swap to a "live" node upon determining the the default (default meaning LS hydrated in some cases) node is down.

Long term, @wbobeirne has a proposal to handle this logic serverside in the following manner:

```
I think the ideal situation would be:
1) Default to some static url, like node.x.com
2) Have that run a balancer that splits users
3) Balancer also detects when nodes go down, and shifts users to working nodes
```

**Comment by wbobeirne** [comment]
Closing this in favor of the node balancer.
