### ISSUE TITLE
chrome password autofill removed unlocking keystore

### ISSUE THREAD

**Issue by james-prado** [MyCryptoHQ/MyCrypto#809]
Chrome autofill's the password (indicated by the yellow), and [this onLoad](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/components/WalletDecrypt/components/Keystore.tsx#L112) function seems to be removing it
<img width="444" alt="screen shot 2018-01-13 at 5 59 19 am" src="https://user-images.githubusercontent.com/13836920/34905461-02ffee7e-f827-11e7-8252-da5eaf6761e2.png">

**Comment by dternyak** [comment]
Is this an issue? I would rather not allow autofill to fill-in the password, but perhaps there's a cleaner way of doing so (e.g. `no-autofill` property).

**Comment by james-prado** [comment]
You can't actually turn off [autofill for passwords](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion). I think it would be better to just fix the issue instead of replacing the password with a blank string
