### ISSUE TITLE
Nonce reset after navigating 'send' subtabs

### ISSUE THREAD

**Issue by james-prado** [MyCryptoHQ/MyCrypto#810]
On the 'Account view & send' tab, when you go from 'Send Eth & Tokens' to 'Request payment', the Nonce is reset to null, and when you navigate back to 'Send Eth & Tokens' it remains null. If the nonce needs to be reset when in 'Request payment' it should be automatically set again when you go back to 'Send Eth & Tokens'

**Comment by HenryNguyen5** [comment]
This has been fixed by #850
