### ISSUE TITLE
Disable tx generation until account balance is loaded (when online)

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#812]
Currently, transaction generation is available even while account balance is loading. During this time, user's are able to generate transactions with any value amount. While this should not cause the user to lose funds, it does allow them to generate an invalid transaction where sent funds > account balance.

- [ ] Provide a loading indicator / otherwise notify that the user needs to wait until account balance resolves before allow transaction generation.
     - Note: When the user is sending an offline transaction, we will not have access to the account balance, and should not restrict transaction generation based on if account balance has been loaded.

<img width="985" alt="screen shot 2018-01-13 at 2 53 23 pm" src="https://user-images.githubusercontent.com/7861465/34909963-924b9426-f871-11e7-84f3-9771cb12e441.png">

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837133)
