### ISSUE TITLE
Alpha beginner impressions / usability issues

### ISSUE THREAD

**Issue by jidanni** [MyCryptoHQ/MyCrypto#828]
On https://alpha.myetherwallet.com/
```
  <ul class="ColorDropdown dropdown-menu dropdown-menu-right">
    <li class="ColorDropdown-item" style=
    "border-color: rgb(14, 151, 192);">
      <a class="active"><span>ETH
      <small>(MyEtherWallet)</small></span></a>
    </li>
    <li class="ColorDropdown-item" style=
    "border-color: rgb(14, 151, 192);">
      <a class=""><span>ETH
      <small>(Etherscan.io)</small></span></a>
    </li>
    <li class="ColorDropdown-item" style=
    "border-color: rgb(14, 151, 192);">
      <a class=""><span>ETH <small>(infura.io)</small></span></a>
    </li>
    <li class="ColorDropdown-item" style=
    "border-color: rgb(102, 144, 115);">
      <a class=""><span>ETC <small>(Epool.io)</small></span></a>
    </li>
    <li class="ColorDropdown-item" style=
    "border-color: rgb(173, 193, 1);">
      <a class=""><span>Ropsten
      <small>(MyEtherWallet)</small></span></a>
    </li>
    <li class="ColorDropdown-item" style=
    "border-color: rgb(173, 193, 1);">
      <a class=""><span>Ropsten
      <small>(infura.io)</small></span></a>
    </li>...
```
is broken up into subgroups. The first group has three items, the next one, etc.
However they are anonymous sub-groups. Each one should have a header giving them a title.

**Comment by dternyak** [comment]
@jidanni Thanks for all of these accessibility issues!

Would you mind if I asked you to collapse these into a single issue with multiple comments / bullet points? It would certainly help on our end to have a single source of accessibility issues instead of searching against all open issues. 

Let me know if this is something you're okay with doing :)

**Comment by jidanni** [comment]
@dternyak OK. Feel free to retitle this bug "Alpha beginner impressions / usability issues". I'll append the rest here. Thanks.

**Comment by dternyak** [comment]
@jidanni Great. Feel free to close the other issues yourself once they're moved over, or I can do so myself if you let me know.

**Comment by jidanni** [comment]
OK.
Here we see the user has 0.5 Ropstein in his account, but can only select sending Ether.

![nj](https://user-images.githubusercontent.com/1230959/34933471-ebbf6608-fa11-11e7-8a2b-af5132963381.jpg)

**Comment by jidanni** [comment]
Here we see more Ether/Ropstein confusion, with the addition of a new word "Nonce" that the user has not seen before. Please add a "(?)" link or mouseover at this point to where he can learn more about "Nonce."
![ndd](https://user-images.githubusercontent.com/1230959/34933571-4bd5052a-fa12-11e7-9803-c5f6c7949f0e.jpg)

**Comment by jidanni** [comment]
See also https://github.com/MyEtherWallet/knowledge-base/issues/44

**Comment by jidanni** [comment]
Regarding the 12 words
```
1. nurd
2. turd
3. herd...
```
please just do as Electrum and have them all shown the user in one textbox:
```
nurd turn herd...
```
thus:
1. Give less of an impression that they are supposed to actually be memorized.
2. Save them time: instead of unnecessary typing practice filling them
back in to proceed, just allow them to paste them back in all at once,
as the point is supposed to be that they are supposed to copy them down
on a piece of paper. And adding more speed bumps just wastes the time
that would be better spent copying them down on paper.

**Comment by dternyak** [comment]
@jidanni We intentionally make it difficult to copy+paste the word phrase by not putting them in one textbox. The goal here is not to save the user time - we want to make sure they take the time to backup their word-phrase on a physical piece of a paper.

**Comment by jidanni** [comment]
( @dternyak Then you might as well go the whole-hog and [please don't] via CSS
disable all forms of cut and paste in any 12 (or 1/12) word related
textbox... that in theory would drive users to use paper even faster.
(Or drive them to use a future electron/electrum-eth even faster :-( ))

Another issue: testnet. In electrum and derivatives using --testnet on
the command line gives an interface with the word Testnet on top.
Within it all wallet addresses are visually distinct from real-net
addresses. In fact with that word Testnet on the top of the window
(or even better https://github.com/spesmilo/electrum/issues/3728 )
the authors needn't create different currency acronyms.

But in myetherwallet it seems one could easily confuse sending realnet
money to testnet addresses etc. etc. one big mishmosh.

**Comment by jidanni** [comment]
Maybe too much freedom... on the homepage there is one (server) selector,
some of these servers are testnet, then here there is another selector (```(Default (ETH) v```) ...
![ffoffndd](https://user-images.githubusercontent.com/1230959/34965148-dcfd393a-fa8c-11e7-8183-73f6f226f62a.jpg)
In electrum both of those would be decided by the single '''--testnet'''
choice. Any further tapering by the user would be under 'expert setting'
or something.

By the way haven't the users already "unlocked" these addresses and now it is time to
simply choose which address to use? So maybe just say [Choose address]
at the top and bottom... Or 'select address' etc.

**Comment by wbobeirne** [comment]
WRT Ropsten and testnet: I agree we should add the word "Testnet" to all of those to make it clear. However, the unit is still ETH on the testnets, so I don't know if we should rename the unit to the network. Maybe we could call the unit `Testnet ETH` or something to be more clear. I think that it says Ropsten on the sidebar is a bug (It looks to be using the `network.name` key, not `network.unit`.)

The [dropdown screenshot](https://github.com/MyEtherWallet/MyEtherWallet/issues/828#issuecomment-357810536) you show in that addresses modal isn't actually for network, that's for the derivation path for non-deterministic modals. It's definitely confusing though, good catch. We should be more specific with the wording there, or add a (?) to find out what that means. But tl;dr unless you know that you want to change it, you probably don't.

**Comment by jidanni** [comment]
Moving right along, in this picture,
![ffondd](https://user-images.githubusercontent.com/1230959/34965438-fbf7a03a-fa8e-11e7-9074-bb3780536e60.jpg)
we notice,
1. What seems like an ad at the right, for turning one currency into
another. The user thinks: gee, some of the items on this page are ads,
and some are not. I had better be careful of what I am clicking.
Also why would ads be interacting on sensitive pages like this?
OK it turns out not to be an ad. But still such exchanging currency
functionality should be cleanly cordoned off to where it lives usually
in a different menu and not here distracting serious operations.

2. We see "To Address:" but no "From Address:". Ah, it turns out the
"Wallet Address," oops I mean "Account Address" here is actually the From
Address. OK, I would stack it atop the To Address, and make it
greyed-out readonly.

**Comment by jidanni** [comment]
https://alpha.myetherwallet.com/generate offers two choices,
1. Keystore File
2. Mnemonic Phrase

But later on https://alpha.myetherwallet.com/account the user sees ```<i class="fa fa-exclamation-triangle"></i>``` warnings about them being insecure.
User thinks "why didn't you tell me earlier?!"

**Comment by jidanni** [comment]
Say 'Unlock _**your wallet with**_ your mnemonic phase', or at least
say 'Unlock _**with**_ your mnemonic phase' 


![m](https://user-images.githubusercontent.com/1230959/35467075-71c6dccc-0345-11e8-9b71-a944e481c141.jpg)

**Comment by dternyak** [comment]
Regarding
```
   Create New Wallet
   Enter a password
   Do NOT forget to save this!
   Create New Wallet
```
If they mistype it then they will never be able to get in again.
Therefore have a second "confirm by typing again" field.

(Yes, it is just as easy to type the wrong password when creating a password as when using that password later.)

Copied from https://github.com/MyEtherWallet/MyEtherWallet/issues/820

**Comment by dternyak** [comment]
Tell users up front about password requirements. Don't force them to learn by trial and error,
> (error_02) Your password must be at least 9 characters. Please ensure it is a strong password.

copied from https://github.com/MyEtherWallet/MyEtherWallet/issues/819

**Comment by dternyak** [comment]
Users will notice two versions of an address. One with all lower case, and one with mixed case. As this might be the first time users have ever such a thing they will click the question mark, seeing (MyEtherWallet/common/translations/lang/en.json):
> Your Address can also be known as you Account # or your Public Key. It is what you share with people so they can send you Ether or Tokens. Find the colorful address icon. Make sure it matches your paper wallet & whenever you enter your address somewhere.

Alas the critical link to https://myetherwallet.github.io/knowledge-base/addresses/my-ethereum-address-has-uppercase-and-lowercase-letters.html which would explain what is going on is missing to that Help message. Please add it.

copied from https://github.com/MyEtherWallet/MyEtherWallet/issues/818

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837180)
