### ISSUE TITLE
Show list of past addresses on Address Only unlocker

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#855]
This is an idea I've had come up a few times, so I wanted to put it out there. I'd use the address viewer option more if I didn't have to find somewhere I'd saved my address and paste it in each time. An easy way to do this would be to save the last ~10 addresses a user has unlocked in local storage, and have those as quick select options. The only concern I'd have is us "tracking" user's wallets. However, since it's totally local, and isn't private keys or anything, that does not personally concern me.

Let me know if there are any other reasons we might not want to do this. Otherwise, I think it's a quick easy win for usability and discouraging pasting keys in just to view your balance.

**Comment by dternyak** [comment]
The global account unlock / persisted accounts we've been designing should make this issue eventually redundant.

Perhaps it's worth waiting before moving forward on this.
