### ISSUE TITLE
Please add DGX 1.0 Token Contract 

### ISSUE THREAD

**Issue by tymat** [MyCryptoHQ/MyCrypto#866]
Our **DGX 1.0** ERC-20 token contract has some additional functions and we would like the ABI to be available on the **[Interact With Contract](https://www.myetherwallet.com/#contracts)** page  

The ABI can be found [here](https://gist.githubusercontent.com/tymat/4dab28cb7769b0d32c31bbc1af6154cd/raw/aa7ab5a800855c52437ec2956e69b58dfe4c2ec7/GoldToken.json).

The contract address for DGX 1.0 is `0x55b9a11c2e8351b4ffc7b11561148bfac9977855`

This functionality would be useful for our users as we are looking to launch DGX 2.0 in the near future.  This would allow them to verify their balances on the old ledger as well as do some calculations to help them transfer their full balances to different accounts before we 'freeze' and begin the migration.

**Comment by dternyak** [comment]
Hey @tymat,

Just wanted to make sure you were aware this is the repo for the v4 re-implementation of MEW.

If this is a time-sensitive issue, you may want to re-open at https://github.com/kvhnuke/etherwallet.

**Comment by wbobeirne** [comment]
We'll be porting over the list of tokens before launch, and DGX 1.0 is in there, so I'm just going to close this.
