### ISSUE TITLE
[BLOCKED] Full ENS

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#87]
- [ ] Start Auction
- [ ] Place Bid
- [ ] Start & Place Bid
- [ ] Reveal Bid
- [ ] Finalize Auction
- [ ] Resolve using Public Resolver

Available
- [ ] ETH
- [ ] ETC (future)
- [ ] Ropsten
- [ ] Rinkeby

Future (Low Priority)

- [ ] Is there a way to know if I have already revealed my bid for a certain name?
- [ ] Allow people to reveal via a JSON from the official client

Github Ref

1. Issue: Testnet ENS addresses kvhnuke/etherwallet#509
2. Issue: non-ascii characters? kvhnuke/etherwallet#480
3. Feature: Calendar kvhnuke/etherwallet#456
4. Show Address they are sending to: kvhnuke/etherwallet#454
5. Issue: Time kvhnuke/etherwallet#453

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837145)
