### ISSUE TITLE
Support for Identity contracts (ERC-725)

### ISSUE THREAD

**Issue by adetante** [MyCryptoHQ/MyCrypto#883]
Can it be interesting to have support in MEW for Identity contracts based on [ERC-725](https://github.com/ethereum/EIPs/issues/725)?

In a basic version, I imagine a new "Identity" tab in the main MEW interface (like ENS) in which the user can input a contract address, and display the information about the identity:
* List of keys linked to this ERC-725 with their type (ECDSA / RSA) and their purpose (MANAGEMENT, ENCRYPTION, ...)
* A functionality to test if a key is linked to this identity

In a more advanced version, with support of [ERC-735](https://github.com/ethereum/EIPs/issues/735) we can display the list of claims owned by the identity, and a way to validate these claims.

As an improvement, we can add the ability to interact with this Identity (Key Management and Identity usage) using a wallet provider (metamask, ...) and a functionality to create a new Identity contract (similar to "Create new wallet" functionnality)?

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837131)
