### ISSUE TITLE
Have components that take state props be directly connected

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#887]
Files like this -
 https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/containers/Tabs/Swap/index.tsx

Are prime candidates for this refactor, this should make it easier in preventing unnecessary re-renders since each component will have `connect` implement `shouldComponentUpdate` for their specific slice of state. Goes well with #884 and #885

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837135)
