### ISSUE TITLE
MEW-01-004: Keystore Protection allows weak passwords

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#889]
- [ ] Block users from generating keystore wallets with weak passwords 
- [ ] Increase N Factor to acceptable level (Mist uses ~10000 rounds)
     - Note: We'll need to benchmark this to make sure UX doesn't completely fall off a cliff. 

Notes: 
https://github.com/dropbox/zxcvbn may be a good resource for estimating password complexity.

**Comment by wbobeirne** [comment]
> Note: We'll need to benchmark this to make sure UX doesn't completely fall off a cliff.

Now that we're cool kids with service workers, this can easily be taken off of the main thread.

**Comment by dternyak** [comment]
Taylor: 

"
Ethereum keystores have been added to hashcat. I'm not longer comfortable using a low of an n-value. Also, n values must be 2^n. In this case, 8192 is 2^13.

https://stealthsploit.com/2018/01/04/ethereum-wallet-cracking-pt-2-gpu-vs-cpu/

2^13 puts us at GPU-incompatible under 32 GB cards. 2^14 at 64GB cards. Both are sufficiently stronger than the current values and should be high enough for the foreseeable future.

Attackers can still CPU brute-force but that’s a miserable undertaking and making them miserable is enough for me.
"
