### ISSUE TITLE
Better error messages for invalid redux fields

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#901]
Currently, invalid states for transactions are computed by checking if the `value` field is null. When a invalid input checked within a saga for a field, it sets the `value` field to null. This does not allow for custom / inline error messages as the cause of the error is not known from the UI side ( as it can only tell if the field is valid or invalid, but not why ). Instead, for each field we can introduce a `error` field that is of type `string | null`. This would allow validators within sagas to put error messages for components to display to the user.

Example field:
Previously: 
```ts 
AppState['transactions']['fields']['gasLimit'] === { raw: string, value: Wei | null }
```
After: 
```ts
AppState['transactions']['fields']['gasLimit'] === { raw: string, value: Wei | null, error: string | null }
```

**Comment by wbobeirne** [comment]
I know I originally did an `error` field, but I think it'd actually be more flexible to do a `message` field. There've been a lot of discussions that involve showing positive things (ENS resolution, you've sent to this address before etc.) and warnings (You've never sent to this address before, abnormally high gas.) So it would be nice to have an `InputMessage` type that takes in a string / react element for display, and a type `error|warning|success` for how to display.

Let me know if that sounds good, or more trouble than it's worth.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837137)
