### ISSUE TITLE
Contract transaction details not cleared on subtab switch

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#918]
When switching between `Interact` and `Deploy` the previous transaction details from the panel switched from (such as wallet, value, to address, data) are not cleared

**Comment by wbobeirne** [comment]
Apparently the tx meta panel (Formerly gas slider) is now resetting on mount. It's not happening offline (Though it probably should anyway) but other than that, I think this should cover this? Please close once you confirm. https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/components/TXMetaDataPanel/TXMetaDataPanel.tsx#L71

As for wallet, I think that behavior is desired. You only lose wallet on top-level tab change, not subtab. Account works the same way.

**Comment by aitrean** [comment]
Confirmed.
