### ISSUE TITLE
To Address Component

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#93]
- [x] Resolves ENS name to address
- [x] Shows Addressicon

Validations

- [x] Validates Valid Ethereum Address w/ Checksum if Available
- [ ] Validates valid ENS name
- [x] Not sending to 0x00000
- [x] If ENS resolver is set to 0x0, don't show as resolved to an address

**Comment by HenryNguyen5** [comment]
After ENS merging this should be completed and isolated to `AddressField` component

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837161)
