### ISSUE TITLE
MEW-01-005 Web: External Links not using HTTPS

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#946]
Affected URLs:
1. https://github.com/MyEtherWallet/MyEtherWallet/blob/master/common/index.html#L55
2. https://github.com/MyEtherWallet/MyEtherWallet/blob/master/common/config/data.ts#L18
3. https://github.com/MyEtherWallet/MyEtherWallet/blob/master/common/containers/Tabs/ENS/components/Title.tsx#L7
4. https://github.com/MyEtherWallet/MyEtherWallet/blob/master/common/containers/Tabs/ENS/components/GeneralInfoPanel/index.tsx#L78
5. https://github.com/MyEtherWallet/MyEtherWallet/blob/master/common/translations/lang/en.json#L287

- [ ] Adjusting linting rules to catch ^ issues.

**Comment by wbobeirne** [comment]
Unfortunately tslint won't run over json or html files, so I don't think we can incorporate the linter for those issues. Should we develop some alternative http catcher, or should we fix these one-off and try to be more diligent in the future with reviews?

**Comment by dternyak** [comment]
@wbobeirne I'd be alright with just fixing these for now and being more diligent in the future 👍

**Comment by dternyak** [comment]
I think we still aught to add `NewTabLink` to the linter, as it seems a handful of those are getting through since the linter can't infer the DOM element will eventually be an anchor tag.
