### ISSUE TITLE
Electron Build Server

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#950]

**Comment by wbobeirne** [comment]
It looks like Travis should be able to handle this, code signing and everything. I think we could use it for all of our builds by making release tags, and having the assets be uploaded directly to the Github release from travis via https://docs.travis-ci.com/user/deployment/releases/.

The only obvious downside is that our code signing keys are going to be on a hosted server. But I don't think there's a way around that, unless we're building it ourselves.

**Comment by dternyak** [comment]
The plan as of today is to maintain our own infrastructure so that we can
more safely keep signing credentials stored.
