### ISSUE TITLE
Move config data to API, request as needed

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#969]
This is something I've been kicking around for a while. One annoying thing about the current MyEtherWallet site is that in order to do something as simple as add a gas limit for an ICO, change gas price ranges, add a new token, or change a node's URL, we need to push a whole new release. If it's something pretty critical, such as updating a token's contract address, old versions that have been downloaded are left high and dry.

I propose that we move out the following items to an API that loads the data from https://github.com/MyEtherWallet/ethereum-lists for the following things:
* Announcement banner, requested immediately
* Node list, requested immediately
* Gas defaults, requested immediately (Assuming we don't migrate to ethgasstation or something)
* Network tokens, requested on account unlock
* Contract ABIs, requested on contracts page

However, I think we should continue to ship with the data in the bundle for offline cases, or if the API is down. We can pop up a message that lets the user know that some data may be out of date, and just revert back to the old data. That way whatever version we ship will just have whatever data is in ethereum-lists at that time.

Let me know what y'all think.

**Comment by HenryNguyen5** [comment]
Definitely in favour of this. But maybe with a more decentralised solution such as IPFS + Smart contract

**Comment by wbobeirne** [comment]
While I'm down for rock-solid solutions for the critical stuff, I'd like to avoid a painful deploy process for the less critical things:

* Announcements - Definitely don't want to start pointing people towards some scam ICO, so yeah, this would be a good choice for that.
* Node list - I don't feel like a malicious node does a terrible amount of damage, and could be caught pretty fast. Perhaps we hard-code the default node, but allow the list to be loaded dynamically to mitigate any damage?
* Gas defaults - Worst it could do is make unobservant people overpay / fail to transact. Not a big deal.
* Network tokens - Since all you're sending is data, not ETH, I don't think this can be used maliciously? Someone correct me if I'm wrong.
* Contract ABIs - Definitely a danger zone here, since someone could change the contract address, and would be pretty subtle.

**Comment by dternyak** [comment]
@wbobeirne Changing the contract address for default network tokens would be a rather large attack vector.

**Comment by HenryNguyen5** [comment]
We can instead pull from parity's token registry, which also lets us display icons for the tokens to the user (horray ux!)
https://paritytech.github.io/wiki/Token-Registry

**Comment by dternyak** [comment]
For the initial MVP, we'll be exploring a multi-sig smart contract IPFS hash pointer to `ethereum-lists`'s token lists.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837077)
