### ISSUE TITLE
Warn if transaction amount > wallet balance

### ISSUE THREAD

**Issue by james-prado** [MyCryptoHQ/MyCrypto#983]
If a user tries to enter an amount greater than their account balance, the 'generate transaction' button is disabled, but provides no indication that its because of the amount. The only thing indicating this is the tiny 1px border, which turns from red to green, and tbh it's pretty hard to notice, and very easy to ignore. 

Ideally, there should be some sort of [inline validation](https://medium.com/wdstack/inline-validation-in-forms-designing-the-experience-123fb34088ce) as a user fills out the form

**Comment by wbobeirne** [comment]
Definitely agree, but I think this overlaps with #901, so I'll close this for that issue.
