### ISSUE TITLE
Have custom tokens be a dependency on network configs

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#985]
Current custom tokens are saved and have no relation to network configs, this can provide a currentNetwork -> token mismatch when the user is switching to different tokens.

We should either key tokens so that they are keyed by networkId, or store the custom tokens in the network configs themselves.

**Comment by wbobeirne** [comment]
I'd propose the following changes:
* Add a `chainId` property to custom tokens, set this to the current network when added
* Update the `getCustomTokens` selector to check the filter against current `network.chainId`
  * If no chainId, insert it anyway for backwards compatibility

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837143)
